const fs = require('fs');

// Category translations to Japanese for pure Japanese front badge
const CATEGORY_MAP_JP = {
  'Salam & Ungkapan (Aisatsu)': '挨拶・会話',
  'Kata Tanya & Kata Ganti': '疑問詞・代名詞',
  'Penunjuk Waktu & Angka': '時間・数字・お金',
  'Kata Benda - Buah & Makanan': '果物・食べ物',
  'Kata Benda - Kendaraan & Transportasi': '乗り物・交通',
  'Kata Benda - Tempat & Fasilitas': '場所・施設',
  'Kata Benda - Keluarga & Orang': '家族・人々',
  'Kata Benda - Rumah & Barang': '家・日用品',
  'Kata Benda - Sekolah & Kantor': '学校・文具',
  'Kata Benda - Tubuh & Pakaian': '身体・衣服',
  'Kata Benda - Alam & Cuaca': '自然・天気',
  'Kata Kerja Dasar': '基本動詞',
  'Kata Sifat': '形容詞',
  'Kosakata Pekerjaan & Sehari-hari': '仕事・日常生活',
  // Standard categories
  'Angka': '数字',
  'Uang': 'お金',
  'Nama Buah': '果物',
  'Kendaraan Umum': '乗り物',
  'Kosakata Sehari-hari': '日常生活',
  'Pekerjaan': '仕事',
  'Sapaan': '挨拶'
};

// =========================================================================
// DATASET KOSAKATA N5: 1.000 KOTOBA RESMI MINNA NO NIHONGO BAB 1 - 25+ & JLPT
// Format: [japanese, kana, romaji, indonesian, category, example, exampleIndonesian]
// =========================================================================

const N5_AISATSU = [
  ['おはようございます', 'おはようございます', 'ohayou gozaimasu', 'Selamat pagi (sopan)', 'Salam & Ungkapan (Aisatsu)', '先生、おはようございます。', 'Selamat pagi, Guru.'],
  ['おはよう', 'おはよう', 'ohayou', 'Selamat pagi (akrab/santai)', 'Salam & Ungkapan (Aisatsu)', '友達におはようと言います。', 'Mengucapkan selamat pagi ke teman.'],
  ['こんにちは', 'こんにちは', 'konnichiwa', 'Selamat siang / Halo', 'Salam & Ungkapan (Aisatsu)', '皆さん、こんにちは。', 'Halo semuanya.'],
  ['こんばんは', 'こんばんは', 'konbanwa', 'Selamat malam (sapaan bertemu)', 'Salam & Ungkapan (Aisatsu)', '夜、こんばんはと挨拶します。', 'Menyapa selamat malam saat bertemu di malam hari.'],
  ['おやすみなさい', 'おやすみなさい', 'oyasuminasai', 'Selamat tidur / Selamat beristirahat (sopan)', 'Salam & Ungkapan (Aisatsu)', 'お母さん、おやすみなさい。', 'Ibu, selamat tidur.'],
  ['おやすみ', 'おやすみ', 'oyasumi', 'Selamat tidur (santai)', 'Salam & Ungkapan (Aisatsu)', 'もう寝るね、おやすみ。', 'Aku mau tidur ya, selamat tidur.'],
  ['さようなら', 'さようなら', 'sayounara', 'Selamat tinggal (perpisahan lama)', 'Salam & Ungkapan (Aisatsu)', '先生、さようなら。', 'Selamat tinggal, Guru.'],
  ['じゃ、また', 'じゃ、また', 'ja, mata', 'Sampai jumpa lagi (santai)', 'Salam & Ungkapan (Aisatsu)', 'また明日会いましょう、じゃ、また。', 'Sampai ketemu besok ya, sampai jumpa.'],
  ['また明日', 'またあした', 'mata ashita', 'Sampai jumpa besok', 'Salam & Ungkapan (Aisatsu)', 'また明日学校で会いましょう。', 'Sampai jumpa besok di sekolah.'],
  ['また来週', 'またらいしゅう', 'mata raishuu', 'Sampai jumpa minggu depan', 'Salam & Ungkapan (Aisatsu)', '良い週末を、また来週。', 'Selamat berakhir pekan, sampai minggu depan.'],
  ['ありがとうございます', 'ありがとうございます', 'arigatou gozaimasu', 'Terima kasih banyak (sopan saat ini)', 'Salam & Ungkapan (Aisatsu)', '親切にありがとうございます。', 'Terima kasih banyak atas kebaikan Anda.'],
  ['ありがとうございました', 'ありがとうございました', 'arigatou gozaimashita', 'Terima kasih banyak (atas hal yang telah selesai)', 'Salam & Ungkapan (Aisatsu)', '昨日はありがとうございました。', 'Terima kasih banyak untuk yang kemarin.'],
  ['どうもありがとうございます', 'どうもありがとうございます', 'doumo arigatou gozaimasu', 'Terima kasih banyak sekali (sangat sopan)', 'Salam & Ungkapan (Aisatsu)', 'プレゼントをどうもありがとうございます。', 'Terima kasih banyak sekali atas hadiahnya.'],
  ['どういたしまして', 'どういたしまして', 'douitashimashite', 'Sama-sama / Kembali', 'Salam & Ungkapan (Aisatsu)', '「ありがとう」「どういたしまして」。', '“Terima kasih” “Sama-sama”.'],
  ['すみません', 'すみません', 'sumimasen', 'Permisi / Maaf / Tolong', 'Salam & Ungkapan (Aisatsu)', 'すみません、メニューをお願いします。', 'Permisi, tolong menunya.'],
  ['ごめんなさい', 'ごめんなさい', 'gomennasai', 'Mohon maaf (permohonan maaf personal)', 'Salam & Ungkapan (Aisatsu)', '遅れてごめんなさい。', 'Maafkan saya terlambat.'],
  ['失礼します', 'しつれいします', 'shitsureishimasu', 'Permisi (saat masuk ruangan / pamit)', 'Salam & Ungkapan (Aisatsu)', '職員室に入る時、失礼しますと言います。', 'Saat masuk ruang guru mengucapkan permisi.'],
  ['失礼しました', 'しつれいしました', 'shitsureishimashita', 'Mohon maaf atas kelancangan saya (lampau)', 'Salam & Ungkapan (Aisatsu)', 'お邪魔して失礼しました。', 'Mohon maaf telah mengganggu.'],
  ['お邪魔します', 'おじゃまします', 'ojamashimasu', 'Permisi (saat berkunjung ke rumah orang)', 'Salam & Ungkapan (Aisatsu)', 'お宅にお邪魔します。', 'Permisi masuk ke dalam rumah Anda.'],
  ['いただきます', 'いただきます', 'itadakimasu', 'Selamat makan (ungkapan rasa syukur sebelum makan)', 'Salam & Ungkapan (Aisatsu)', '食べる前にいただきますと言います。', 'Mengucapkan selamat makan sebelum mulai bersantap.'],
  ['ごちそうさまでした', 'ごちそうさまでした', 'gochisousamadeshita', 'Terima kasih atas hidangannya (setelah makan)', 'Salam & Ungkapan (Aisatsu)', '食後にごちそうさまでしたと言います。', 'Mengucapkan terima kasih atas hidangan setelah selesai makan.'],
  ['いってきます', 'いってきます', 'ittekimasu', 'Saya berangkat dulu (dari rumah/kantor)', 'Salam & Ungkapan (Aisatsu)', '学校へいってきます。', 'Saya berangkat dulu ke sekolah.'],
  ['いってらっしゃい', 'いってらっしゃい', 'itterasshai', 'Selamat jalan / Hati-hati di jalan', 'Salam & Ungkapan (Aisatsu)', '出かける人にいってらっしゃいと言います。', 'Mengucapkan selamat jalan kepada yang akan bepergian.'],
  ['ただいま', 'ただいま', 'tadaima', 'Saya pulang / Saya sudah kembali', 'Salam & Ungkapan (Aisatsu)', '家に着いて、ただいまと言います。', 'Tiba di rumah mengucapkan saya pulang.'],
  ['おかえりなさい', 'おかえりなさい', 'okaerinasai', 'Selamat datang kembali di rumah', 'Salam & Ungkapan (Aisatsu)', '家族におかえりなさいと言います。', 'Menyambut keluarga dengan selamat pulang.'],
  ['いらっしゃいませ', 'いらっしゃいませ', 'irasshaimase', 'Selamat datang (di toko / restoran)', 'Salam & Ungkapan (Aisatsu)', '店員がいらっしゃいませと迎えます。', 'Pegawai toko menyambut dengan selamat datang.'],
  ['初めまして', 'はじめまして', 'hajimemashite', 'Perkenalkan / Senang bertemu pertama kali', 'Salam & Ungkapan (Aisatsu)', '初めまして、田中です。', 'Perkenalkan, saya Tanaka.'],
  ['どうぞよろしくお願いします', 'どうぞよろしくおねがいします', 'douzo yoroshiku onegaishimasu', 'Mohon bimbingan dan kerja samanya', 'Salam & Ungkapan (Aisatsu)', 'こちらこそ、どうぞよろしくお願いします。', 'Dengan senang hati, mohon kerja samanya juga.'],
  ['こちらこそ', 'こちらこそ', 'kochirakoso', 'Sama-sama / Justru pihak saya', 'Salam & Ungkapan (Aisatsu)', 'こちらこそよろしくお願いします。', 'Saya pun mohon kerja samanya.'],
  ['お元気ですか', 'おげんきですか', 'ogenki desu ka', 'Apa kabar?', 'Salam & Ungkapan (Aisatsu)', 'お久しぶりです、お元気ですか。', 'Lama tidak berjumpa, apa kabar?'],
  ['はい、元気です', 'はい、げんきです', 'hai, genki desu', 'Ya, saya sehat / baik-baik saja', 'Salam & Ungkapan (Aisatsu)', 'はい、おかげさまで元気です。', 'Ya, berkat doa Anda saya sehat walafiat.'],
  ['お疲れ様でした', 'おつかれさまでした', 'otsukaresamadeshita', 'Terima kasih atas kerja kerasnya (selesai kerja)', 'Salam & Ungkapan (Aisatsu)', '仕事が終わってお疲れ様でしたと言います。', 'Selesai bekerja mengucapkan terima kasih atas kerja kerasnya.'],
  ['お先に失礼します', 'おさきにしつれいします', 'osaki ni shitsureishimasu', 'Saya pamit pulang duluan', 'Salam & Ungkapan (Aisatsu)', '定時になったのでお先に失礼します。', 'Karena sudah jam pulang saya pamit duluan.'],
  ['お大事に', 'おだいじに', 'odaiji ni', 'Semoga lekas sembuh (kepada orang sakit)', 'Salam & Ungkapan (Aisatsu)', '風邪ですね、お大事にどうぞ。', 'Anda kena flu ya, semoga lekas sembuh.'],
  ['気をつけて', 'きをつけて', 'ki wo tsukete', 'Hati-hati ya', 'Salam & Ungkapan (Aisatsu)', '車に気をつけて帰ってください。', 'Hati-hati dengan kendaraan saat perjalanan pulang.'],
  ['いかがですか', 'いかがですか', 'ikaga desu ka', 'Bagaimana? / Mau mencoba? (sopan)', 'Salam & Ungkapan (Aisatsu)', 'お茶はいかがですか。', 'Bagaimana kalau minum teh?'],
  ['結構です', 'けっこうです', 'kekkou desu', 'Cukup / Tidak perlu (penolakan halus)', 'Salam & Ungkapan (Aisatsu)', 'いいえ、もう結構です。', 'Tidak, sudah cukup.'],
  ['どうぞ', 'どうぞ', 'douzo', 'Silakan', 'Salam & Ungkapan (Aisatsu)', 'どうぞお入りください。', 'Silakan masuk.'],
  ['どうも', 'どうも', 'doumo', 'Terima kasih / Halo (fleksibel santai)', 'Salam & Ungkapan (Aisatsu)', 'どうも、助かりました。', 'Terima kasih, sangat membantu.'],
  ['おめでとうございます', 'おめでとうございます', 'omedetou gozaimasu', 'Selamat atas keberhasilan / perayaan', 'Salam & Ungkapan (Aisatsu)', 'お誕生日おめでとうございます。', 'Selamat ulang tahun.'],
  ['乾杯', 'かんぱい', 'kanpai', 'Bersulang!', 'Salam & Ungkapan (Aisatsu)', 'グラスを持って乾杯します。', 'Memegang gelas lalu bersulang.'],
  ['しばらくですね', 'しばらくですね', 'shibaraku desu ne', 'Lama tidak berjumpa ya', 'Salam & Ungkapan (Aisatsu)', 'お久しぶりですね、しばらくでした。', 'Sudah lama ya, lama tidak bersua.'],
  ['ご苦労様でした', 'ごくろうさまでした', 'gokurousamadeshita', 'Terima kasih atas kerja kerasnya (atasan ke bawahan)', 'Salam & Ungkapan (Aisatsu)', '部長が部下にご苦労様と言いました。', 'Manajer berterima kasih kepada bawahan.'],
  ['かしこまりました', 'かしこまりました', 'kashikomarimashita', 'Baik, saya mengerti dan siap melaksanakan (sangat sopan di restoran/toko)', 'Salam & Ungkapan (Aisatsu)', 'ご注文、かしこまりました。', 'Pesanan Anda telah saya catat dan mengerti.'],
  ['少々お待ちください', 'しょうしょうおまちください', 'shoushou omachi kudasai', 'Mohon tunggu sebentar', 'Salam & Ungkapan (Aisatsu)', '確認しますので少々お待ちください。', 'Mohon tunggu sebentar saya cek terlebih dahulu.'],
  ['もう一度お願いします', 'もういちどおねがいします', 'mou ichido onegaishimasu', 'Tolong ulangi sekali lagi', 'Salam & Ungkapan (Aisatsu)', '聞き取れなかったのでもう一度お願いします。', 'Karena belum terdengar jelas tolong ulangi sekali lagi.'],
  ['ゆっくり話してください', 'ゆっくりはなしてください', 'yukkuri hanashite kudasai', 'Tolong bicara perlahan-lahan', 'Salam & Ungkapan (Aisatsu)', '日本語をゆっくり話してください。', 'Tolong bicaralah bahasa Jepang secara perlahan.'],
  ['わかりました', 'わかりました', 'wakarimashita', 'Saya sudah mengerti / Paham', 'Salam & Ungkapan (Aisatsu)', '説明がよくわかりました。', 'Saya sudah mengerti penjelasannya.'],
  ['わかりません', 'わかりません', 'wakarimasen', 'Saya tidak mengerti / Tidak tahu', 'Salam & Ungkapan (Aisatsu)', '意味がまだわかりません。', 'Saya belum memahami maknanya.']
];

const N5_QUESTION_PRONOUNS = [
  ['私', 'わたし', 'watashi', 'Saya / Aku', 'Kata Tanya & Kata Ganti', '私は学生です。', 'Saya adalah seorang pelajar.'],
  ['私たち', 'わたしたち', 'watashitachi', 'Kami / Kita', 'Kata Tanya & Kata Ganti', '私たちは日本語を勉強します。', 'Kami belajar bahasa Jepang.'],
  ['あなた', 'あなた', 'anata', 'Anda / Kamu', 'Kata Tanya & Kata Ganti', 'あなたは先生ですか。', 'Apakah Anda seorang guru?'],
  ['あの人', 'あのひと', 'ano hito', 'Orang itu', 'Kata Tanya & Kata Ganti', 'あの人は誰ですか。', 'Siapakah orang itu?'],
  ['あの方', 'あのかた', 'ano kata', 'Beliau itu (sopan dari ano hito)', 'Kata Tanya & Kata Ganti', 'あの方は社長です。', 'Beliau itu adalah direktur utama.'],
  ['皆さん', 'みなさん', 'minasan', 'Saudara-saudari sekalian / Hadirin', 'Kata Tanya & Kata Ganti', '皆さん、聞いてください。', 'Semuanya, tolong dengarkan.'],
  ['これ', 'これ', 'kore', 'Ini (benda dekat pembicara)', 'Kata Tanya & Kata Ganti', 'これは私の本です。', 'Ini adalah buku milik saya.'],
  ['それ', 'それ', 'sore', 'Itu (benda dekat lawan bicara)', 'Kata Tanya & Kata Ganti', 'それは辞書ですか。', 'Apakah itu kamus?'],
  ['あれ', 'あれ', 'are', 'Itu (benda jauh dari keduanya)', 'Kata Tanya & Kata Ganti', 'あれは富士山です。', 'Itu adalah Gunung Fuji.'],
  ['どれ', 'どれ', 'dore', 'Yang mana? (pilihan dari 3 benda atau lebih)', 'Kata Tanya & Kata Ganti', 'あなたのかばんはどれですか。', 'Tas milikmu yang mana?'],
  ['この', 'この', 'kono', '... ini (menerangkan kata benda)', 'Kata Tanya & Kata Ganti', 'この傘は私のです。', 'Payung ini milik saya.'],
  ['その', 'その', 'sono', '... itu (dekat lawan bicara)', 'Kata Tanya & Kata Ganti', 'その時計は高いです。', 'Jam tangan itu mahal.'],
  ['あの', 'あの', 'ano', '... itu (jauh dari keduanya)', 'Kata Tanya & Kata Ganti', 'あの建物は銀行です。', 'Gedung itu adalah bank.'],
  ['どの', 'どの', 'dono', '... yang mana?', 'Kata Tanya & Kata Ganti', 'どの部屋が好きですか。', 'Kamar yang mana yang kamu sukai?'],
  ['ここ', 'ここ', 'koko', 'Di sini (tempat dekat pembicara)', 'Kata Tanya & Kata Ganti', 'ここは教室です。', 'Di sini adalah ruang kelas.'],
  ['そこ', 'そこ', 'soko', 'Di situ (tempat dekat lawan bicara)', 'Kata Tanya & Kata Ganti', 'そこは食堂です。', 'Di situ adalah kantin.'],
  ['あそこ', 'あそこ', 'asoko', 'Di sana (tempat jauh dari keduanya)', 'Kata Tanya & Kata Ganti', 'あそこは図書館です。', 'Di sana adalah perpustakaan.'],
  ['どこ', 'どこ', 'doko', 'Di mana? / Kemana?', 'Kata Tanya & Kata Ganti', 'トイレはどこですか。', 'Di manakah toilet?'],
  ['こちら', 'こちら', 'kochira', 'Sebelah sini / Arah ini (sopan)', 'Kata Tanya & Kata Ganti', '受付はこちらです。', 'Meja resepsionis di sebelah sini.'],
  ['そちら', 'そちら', 'sochira', 'Sebelah situ / Arah situ (sopan)', 'Kata Tanya & Kata Ganti', '電話はそちらにあります。', 'Telepon ada di sebelah situ.'],
  ['あちら', 'あちら', 'achira', 'Sebelah sana / Arah sana (sopan)', 'Kata Tanya & Kata Ganti', 'エレベーターはあちらです。', 'Lift ada di sebelah sana.'],
  ['どちら', 'どちら', 'dochira', 'Sebelah mana? / Yang mana? (sopan)', 'Kata Tanya & Kata Ganti', 'お国はどちらですか。', 'Negara asal Anda dari mana?'],
  ['だれ', 'だれ', 'dare', 'Siapa?', 'Kata Tanya & Kata Ganti', 'あの人はだれですか。', 'Siapakah orang itu?'],
  ['どなた', 'どなた', 'donata', 'Siapa? (bentuk sangat sopan)', 'Kata Tanya & Kata Ganti', 'あの方はどなたですか。', 'Siapakah beliau itu?'],
  ['何', 'なに / なん', 'nani / nan', 'Apa? / Berapa?', 'Kata Tanya & Kata Ganti', 'これは何ですか。', 'Ini apa?'],
  ['いつ', 'いつ', 'itsu', 'Kapan?', 'Kata Tanya & Kata Ganti', '日本へいつ行きますか。', 'Kapan akan pergi ke Jepang?'],
  ['いくら', 'いくら', 'ikura', 'Berapa harganya?', 'Kata Tanya & Kata Ganti', 'このリンゴはいくらですか。', 'Apel ini harganya berapa?'],
  ['いくつ', 'いくつ', 'ikutsu', 'Berapa buah? / Berapa usianya?', 'Kata Tanya & Kata Ganti', '卵をいくつ買いましたか。', 'Beli telur berapa butir?'],
  ['何人', 'なんにん', 'nannin', 'Berapa orang?', 'Kata Tanya & Kata Ganti', '家族は何人ですか。', 'Keluarga Anda berapa orang?'],
  ['何歳', 'なんさい', 'nansai', 'Berapa umur / usianya?', 'Kata Tanya & Kata Ganti', 'お子さんは何歳ですか。', 'Berapa usia anak Anda?'],
  ['おいくつ', 'おいくつ', 'oikutsu', 'Berapa umur Anda? (sopan)', 'Kata Tanya & Kata Ganti', '失礼ですがおいくつですか。', 'Mohon maaf, berapa umur Anda?'],
  ['何時', 'なんじ', 'nanji', 'Jam berapa?', 'Kata Tanya & Kata Ganti', '今、何時ですか。', 'Sekarang jam berapa?'],
  ['何分', 'なんぷん', 'nanpun', 'Berapa menit?', 'Kata Tanya & Kata Ganti', '駅から歩いて何分ですか。', 'Berapa menit berjalan kaki dari stasiun?'],
  ['何曜日', 'なんようび', 'nanyoubi', 'Hari apa?', 'Kata Tanya & Kata Ganti', '今日は何曜日ですか。', 'Hari ini hari apa?'],
  ['何月', 'なんがつ', 'nangatsu', 'Bulan apa?', 'Kata Tanya & Kata Ganti', '誕生日は何月ですか。', 'Ulang tahun di bulan apa?'],
  ['何日', 'なんにち', 'nannichi', 'Tanggal berapa? / Berapa hari?', 'Kata Tanya & Kata Ganti', '今日は何日ですか。', 'Hari ini tanggal berapa?'],
  ['何番', 'なんばん', 'nanban', 'Nomor berapa?', 'Kata Tanya & Kata Ganti', '部屋の番号は何番ですか。', 'Nomor kamarnya nomor berapa?'],
  ['どう', 'どう', 'dou', 'Bagaimana?', 'Kata Tanya & Kata Ganti', '日本の生活はどうですか。', 'Bagaimana kehidupan di Jepang?'],
  ['どうして', 'どうして', 'doushite', 'Mengapa? / Kenapa?', 'Kata Tanya & Kata Ganti', 'どうして昨日休みましたか。', 'Mengapa kemarin Anda tidak masuk?'],
  ['なぜ', 'なぜ', 'naze', 'Mengapa? (formal)', 'Kata Tanya & Kata Ganti', 'なぜ勉強しますか。', 'Mengapa kamu belajar?'],
  ['どんな', 'どんな', 'donna', 'Yang bagaimana? / Macam apa?', 'Kata Tanya & Kata Ganti', 'どんな音楽が好きですか。', 'Musik yang bagaimana yang kamu sukai?'],
  ['どっち', 'どっち', 'dotchi', 'Yang mana? (santai, pilihan dari 2 benda)', 'Kata Tanya & Kata Ganti', '肉と魚、どっちがいいですか。', 'Daging atau ikan, kamu pilih yang mana?']
];

console.log('Building Minna no Nihongo vocab dataset...');
