const fs = require('fs');
const path = require('path');

// =========================================================================
// JLPT N5 (103 KANJI DASAR RESMI LENGKAP - 100% STANDAR UJIAN RESMI)
// =========================================================================
const KANJI_N5 = [
  // Angka
  ['一', 'イチ, イツ / ひと-つ', 'ichi / hito-tsu', 'Satu', '一つ (hitotsu = satu buah), 一日 (tsuitachi = tanggal satu / ichinichi = satu hari)', 'Angka'],
  ['二', 'ニ / ふた-つ', 'ni / futa-tsu', 'Dua', '二つ (futatsu = dua buah), 二人 (futari = dua orang)', 'Angka'],
  ['三', 'サン / みっ-つ', 'san / mit-tsu', 'Tiga', '三日 (mikka = tanggal tiga), 三月 (sangatsu = bulan Maret)', 'Angka'],
  ['四', 'シ / よっ-つ, よん', 'shi / yot-tsu, yon', 'Empat', '四つ (yottsu = empat buah), 四月 (shigatsu = bulan April)', 'Angka'],
  ['五', 'ゴ / いつ-つ', 'go / itsu-tsu', 'Lima', '五日 (itsuka = tanggal lima), 五年 (gonen = lima tahun)', 'Angka'],
  ['六', 'ロク / むっ-つ', 'roku / mut-tsu', 'Enam', '六日 (muika = tanggal enam), 六分 (roppun = enam menit)', 'Angka'],
  ['七', 'シチ / なな-つ', 'shichi / nana-tsu', 'Tujuh', '七日 (nanoka = tanggal tujuh), 七月 (shichigatsu = bulan Juli)', 'Angka'],
  ['八', 'ハチ / やっ-つ', 'hachi / yat-tsu', 'Delapan', '八日 (youka = tanggal delapan), 八百屋 (yaoya = toko sayur buah)', 'Angka'],
  ['九', 'キュウ, ク / ここの-つ', 'kyuu, ku / kokono-tsu', 'Sembilan', '九日 (kokonoka = tanggal sembilan), 九時 (kuji = jam sembilan)', 'Angka'],
  ['十', 'ジュウ, ジッ / とお', 'juu / too', 'Sepuluh', '十日 (tooka = tanggal sepuluh), 十分 (juubun = cukup)', 'Angka'],
  ['百', 'ヒャク', 'hyaku', 'Ratus', '百円 (hyakuen = seratus yen), 三百 (sanbyaku = tiga ratus)', 'Angka'],
  ['千', 'セン / ち', 'sen / chi', 'Ribu', '千円 (sen\'en = seribu yen), 三千 (sanzen = tiga ribu)', 'Angka'],
  ['万', 'マン, バン', 'man, ban', 'Puluh Ribu (10.000)', '一万円 (ichiman\'en = sepuluh ribu yen), 万歳 (banzai = hidup mulia)', 'Angka'],

  // Orang & Keluarga
  ['人', 'ジン, ニン / ひと', 'jin, nin / hito', 'Orang / Manusia', '日本人 (nihonjin = orang Jepang), 一人 (hitori = seorang diri)', 'Orang & Keluarga'],
  ['父', 'フ / ちち, とう', 'fu / chichi, tou', 'Ayah', '父 (chichi = ayah kandung saya), お父さん (otousan = ayah / bapak)', 'Orang & Keluarga'],
  ['母', 'ボ / はは, かあ', 'bo / haha, kaa', 'Ibu', '母 (haha = ibu kandung saya), お母さん (okaasan = ibu)', 'Orang & Keluarga'],
  ['子', 'シ, ス / こ', 'shi / ko', 'Anak', '子供 (kodomo = anak-anak), 女の子 (onnanoko = anak perempuan)', 'Orang & Keluarga'],
  ['女', 'ジョ, ニョ / おんな, め', 'jo / onna', 'Wanita / Perempuan', '女の人 (onna no hito = perempuan), 彼女 (kanojo = pacar / dia perempuan)', 'Orang & Keluarga'],
  ['男', 'ダン, ナン / おとこ', 'dan / otoko', 'Pria / Laki-laki', '男の人 (otoko no hito = pria), 男の子 (otokonoko = anak laki-laki)', 'Orang & Keluarga'],
  ['兄', 'ケイ, キョウ / あに, にい', 'kei / ani', 'Kakak Laki-laki', '兄 (ani = abang saya), お兄さん (oniisan = kakak laki-laki)', 'Orang & Keluarga'],
  ['弟', 'テイ, ダイ / おとうと', 'tei / otouto', 'Adik Laki-laki', '弟 (otouto = adik laki-laki), 兄弟 (kyoudai = saudara kandung)', 'Orang & Keluarga'],
  ['姉', 'シ / あね, ねえ', 'shi / ane', 'Kakak Perempuan', '姉 (ane = kakak perempuan saya), お姉さん (oneesan = mbak/kakak)', 'Orang & Keluarga'],
  ['妹', 'マイ / いもうと', 'mai / imouto', 'Adik Perempuan', '妹 (imouto = adik perempuan), 姉妹 (shimai = saudari perempuan)', 'Orang & Keluarga'],

  // Waktu & Kalender
  ['日', 'ニチ, ジツ / ひ, か', 'nichi, jitsu / hi, ka', 'Hari / Matahari', '日曜日 (nichiyoubi = hari Minggu), 毎日 (mainichi = setiap hari)', 'Waktu'],
  ['月', 'ゲツ, ガツ / つき', 'getsu, gatsu / tsuki', 'Bulan (Kalender & Langit)', '月曜日 (getsuyoubi = hari Senin), 今月 (kongetsu = bulan ini)', 'Waktu'],
  ['年', 'ネン / とし', 'nen / toshi', 'Tahun / Usia', '今年 (kotoshi = tahun ini), 来年 (rainen = tahun depan)', 'Waktu'],
  ['時', 'ジ / とき', 'ji / toki', 'Waktu / Jam', '時間 (jikan = durasi waktu), 何時 (nanji = jam berapa)', 'Waktu'],
  ['分', 'ブン, フン / わ-ける, わ-かる', 'bun, fun / wa-karu', 'Menit / Memahami', '五分 (gofun = 5 menit), 分かる (wakaru = mengerti)', 'Waktu'],
  ['週', 'シュウ', 'shuu', 'Minggu (Pekan)', '今週 (konshuu = pekan ini), 毎週 (maishuu = tiap pekan)', 'Waktu'],
  ['朝', 'チョウ / あさ', 'chou / asa', 'Pagi Hari', '今朝 (kesa = pagi ini), 毎朝 (maiasa = setiap pagi)', 'Waktu'],
  ['昼', 'チュウ / ひる', 'chuu / hiru', 'Siang Hari', '昼休み (hiruyasumi = istirahat siang), 昼ご飯 (hirugohan = makan siang)', 'Waktu'],
  ['夜', 'ヤ / よる, よ', 'ya / yoru', 'Malam Hari', '今夜 (konya = malam ini), 夜中 (yonaka = tengah malam)', 'Waktu'],
  ['毎', 'マイ', 'mai', 'Setiap / Tiap', '毎日 (mainichi = setiap hari), 毎月 (maitsuki = setiap bulan)', 'Waktu'],
  ['午', 'ゴ', 'go', 'Tengah Hari (Siang)', '午前 (gozen = pagi a.m.), 午後 (gogo = sore p.m.)', 'Waktu'],
  ['間', 'カン, ケン / あいだ, ま', 'kan / aida', 'Antara / Ruang / Durasi', '一時間 (ichijikan = kurun satu jam), 間 (aida = di antara)', 'Waktu'],
  ['半', 'ハン / なか-ば', 'han / naka-ba', 'Setengah / Separuh', '九時半 (kujihan = jam 9 lewat 30), 半分 (hanbun = separuh)', 'Waktu'],

  // Tempat & Arah
  ['上', 'ジョウ / うえ, あ-がる', 'jou / ue, a-garu', 'Atas / Naik', '机の上 (tsukue no ue = di atas meja), 上手 (jouzu = pandai/mahir)', 'Tempat & Arah'],
  ['下', 'カ, ゲ / した, さ-がる', 'ka, ge / shita', 'Bawah / Turun', '下 (shita = bagian bawah), 下手 (heta = kurang pandai)', 'Tempat & Arah'],
  ['左', 'サ / ひだり', 'sa / hidari', 'Kiri', '左手 (hidarite = tangan kiri), 左側 (hidarigawa = sisi kiri)', 'Tempat & Arah'],
  ['右', 'ウ, ユウ / みぎ', 'u, yuu / migi', 'Kanan', '右手 (migite = tangan kanan), 右側 (migigawa = sisi kanan)', 'Tempat & Arah'],
  ['中', 'チュウ / なか', 'chuu / naka', 'Tengah / Di Dalam', '部屋の中 (heya no naka = di dalam kamar), 一日中 (ichinichijuu = sepanjang hari)', 'Tempat & Arah'],
  ['外', 'ガイ, ゲ / そと, ほか', 'gai / soto', 'Luar / Lain', '外国 (gaikoku = luar negeri), 外 (soto = luar ruangan)', 'Tempat & Arah'],
  ['前', 'ゼン / まえ', 'zen / mae', 'Depan / Sebelum', '駅の前 (eki no mae = depan stasiun), 三年前 (sannenmae = 3 tahun lalu)', 'Tempat & Arah'],
  ['後', 'ゴ, コウ / あと, うし-ろ', 'go, kou / ato, ushiro', 'Belakang / Setelah', '後ろ (ushiro = belakang), その後 (sono ato = setelah itu)', 'Tempat & Arah'],
  ['東', 'トウ / ひがし', 'tou / higashi', 'Timur', '東京 (Toukyou = Tokyo), 東口 (higashiguchi = pintu timur)', 'Tempat & Arah'],
  ['西', 'セイ, サイ / にし', 'sei, sai / nishi', 'Barat', '西口 (nishiguchi = pintu barat), 西洋 (seiyou = dunia barat)', 'Tempat & Arah'],
  ['南', 'ナン / みなみ', 'nan / minami', 'Selatan', '南口 (minamiguchi = gerbang selatan), 東南 (tounan = tenggara)', 'Tempat & Arah'],
  ['北', 'ホク / きた', 'hoku / kita', 'Utara', '北海道 (Hokkaidou = Hokkaido), 北口 (kitaguchi = gerbang utara)', 'Tempat & Arah'],
  ['国', 'コク / くに', 'koku / kuni', 'Negara / Negeri', '外国 (gaikoku = negeri asing), 国 (kuni = tanah air)', 'Tempat & Arah'],
  ['校', 'コウ', 'kou', 'Sekolah', '学校 (gakkou = sekolah), 高校 (koukou = SMA)', 'Tempat & Arah'],
  ['家', 'カ, ケ / いえ, や', 'ka / ie, ya', 'Rumah / Keluarga', '家に帰る (ie ni kaeru = pulang ke rumah), 家族 (kazoku = keluarga)', 'Tempat & Arah'],

  // Kata Kerja Dasar
  ['行', 'コウ, ギョウ / い-く, おこな-う', 'kou / i-ku', 'Pergi / Mengadakan', '学校へ行く (gakkou e iku = pergi ke sekolah), 旅行 (ryokou = melancong)', 'Kata Kerja'],
  ['来', 'ライ / く-る, き-ます', 'rai / ku-ru', 'Datang / Masa Depan', '日本へ来る (nihon e kuru = datang ke Jepang), 来週 (raishuu = pekan depan)', 'Kata Kerja'],
  ['見', 'ケン / み-る, み-せる', 'ken / mi-ru', 'Melihat / Menonton', 'テレビを見る (terebi o miru = menonton TV), 見せる (miseru = memperlihatkan)', 'Kata Kerja'],
  ['言', 'ゲン, ゴン / い-う, こと', 'gen, gon / i-u', 'Berkata / Mengucapkan', '言う (iu = berkata), 言語 (gengo = bahasa)', 'Kata Kerja'],
  ['話', 'ワ / はな-す, はなし', 'wa / hana-su', 'Berbicara / Cerita', '日本語で話す (nihongo de hanasu = bicara bahasa Jepang), 電話 (denwa = telepon)', 'Kata Kerja'],
  ['書', 'ショ / か-く', 'sho / ka-ku', 'Menulis / Dokumen', '手紙を書く (tegami o kaku = menulis surat), 辞書 (jisho = kamus)', 'Kata Kerja'],
  ['読', 'ドク / よ-む', 'doku / yo-mu', 'Membaca', '本を読む (hon o yomu = membaca buku), 読書 (dokusho = gemar membaca)', 'Kata Kerja'],
  ['食', 'ショク / た-べる', 'shoku / ta-beru', 'Makan / Makanan', '朝ご飯を食べる (asagohan o taberu = makan sarapan), 食事 (shokuji = santap makan)', 'Kata Kerja'],
  ['飲', 'イン / の-む', 'in / no-mu', 'Minum / Minuman', '水を飲む (mizu o nomu = minum air), 飲み物 (nomimono = minuman)', 'Kata Kerja'],
  ['立', 'リツ / た-つ, た-てる', 'ritsu / ta-tsu', 'Berdiri', '立つ (tatsu = berdiri tegak), 起立 (kiritsu = berdiri memberi salam)', 'Kata Kerja'],
  ['座', 'ザ / すわ-る', 'za / suwa-ru', 'Duduk / Kursi', '椅子に座る (isu ni suwaru = duduk di kursi), 座席 (zaseki = tempat duduk)', 'Kata Kerja'],
  ['走', 'ソウ / はし-る', 'sou / hashi-ru', 'Berlari', '走る (hashiru = berlari cepat), 走者 (sousha = pelari)', 'Kata Kerja'],
  ['出', 'シュツ / で-る, だ-す', 'shutsu / de-ru, da-su', 'Keluar / Mengeluarkan', '部屋を出る (heya o deru = keluar kamar), 出口 (deguchi = pintu keluar)', 'Kata Kerja'],
  ['入', 'ニュウ / はい-る, い-れる', 'nyuu / hai-ru', 'Masuk / Memasukkan', '中に入る (naka ni hairu = masuk ke dalam), 入口 (iriguchi = pintu masuk)', 'Kata Kerja'],
  ['買', 'バイ / か-う', 'bai / ka-u', 'Membeli', 'パンを買う (pan o kau = membeli roti), 買い物 (kaimono = belanja)', 'Kata Kerja'],
  ['聞', 'ブン, モン / き-く', 'bun / ki-ku', 'Mendengar / Bertanya', '音楽を聞く (ongaku o kiku = mendengarkan musik), 新聞 (shinbun = koran)', 'Kata Kerja'],

  // Alam, Benda & Sifat Dasar
  ['水', 'スイ / みず', 'sui / mizu', 'Air', '冷たい水 (tsumetai mizu = air dingin), 水曜日 (suiyoubi = hari Rabu)', 'Alam & Benda'],
  ['火', 'カ / ひ', 'ka / hi', 'Api', '火 (hi = nyala api), 火曜日 (kayoubi = hari Selasa)', 'Alam & Benda'],
  ['木', 'ボク, モク / き', 'boku, moku / ki', 'Pohon / Kayu', '大きな木 (ookina ki = pohon besar), 木曜日 (mokuyoubi = hari Kamis)', 'Alam & Benda'],
  ['金', 'キン, コン / かね', 'kin / kane', 'Emas / Uang', 'お金 (okane = uang), 金曜日 (kin\'youbi = hari Jumat)', 'Alam & Benda'],
  ['土', 'ド, ト / つち', 'do / tsuchi', 'Tanah / Bumi', '土 (tsuchi = tanah), 土曜日 (doyoubi = hari Sabtu)', 'Alam & Benda'],
  ['山', 'サン / やま', 'san / yama', 'Gunung', '富士山 (Fujisan = Gunung Fuji), 山登り (yamanobori = mendaki gunung)', 'Alam & Benda'],
  ['川', 'セン / かわ', 'sen / kawa', 'Sungai', '川で泳ぐ (kawa de oyogu = berenang di sungai), 小川 (ogawa = sungai kecil)', 'Alam & Benda'],
  ['空', 'クウ / そら, あ-く', 'kuu / sora', 'Langit / Hampa', '青い空 (aoi sora = langit biru), 空港 (kuukou = bandara)', 'Alam & Benda'],
  ['雨', 'ウ / あめ', 'u / ame', 'Hujan', '雨が降る (ame ga furu = hujan turun), 大雨 (ooame = hujan lebat)', 'Alam & Benda'],
  ['花', 'カ / はな', 'ka / hana', 'Bunga', '桜の花 (sakura no hana = bunga sakura), 花火 (hanabi = kembang api)', 'Alam & Benda'],
  ['天', 'テン', 'ten', 'Langit / Cuaca', '天気 (tenki = cuaca), 天国 (tengoku = surga)', 'Alam & Benda'],
  ['気', 'キ', 'ki', 'Udara / Semangat / Rasa', '元気 (genki = sehat bugar), 気をつける (ki o tsukeru = berhati-hati)', 'Alam & Benda'],
  ['大', 'ダイ, タイ / おお-きい', 'dai, tai / oo-kii', 'Besar', '大きい家 (ookii ie = rumah besar), 大学 (daigaku = universitas)', 'Sifat Dasar'],
  ['小', 'ショウ / ちい-さい, こ', 'shou / chii-sai', 'Kecil', '小さい猫 (chiisai neko = kucing kecil), 小学校 (shougakkou = SD)', 'Sifat Dasar'],
  ['多', 'タ / おお-い', 'ta / oo-i', 'Banyak', '人が多い (hito ga ooi = banyak orang), 多少 (tashou = sedikit banyak)', 'Sifat Dasar'],
  ['少', 'ショウ / すく-ない, すこ-し', 'shou / suku-nai, suko-shi', 'Sedikit', '少し (sukoshi = sedikit demi sedikit), 少女 (shoujo = gadis kecil)', 'Sifat Dasar'],
  ['高', 'コウ / たか-い', 'kou / taka-i', 'Tinggi / Mahal', '高い山 (takai yama = gunung tinggi), 高校生 (koukousei = murid SMA)', 'Sifat Dasar'],
  ['安', 'アン / やす-い', 'an / yasu-i', 'Murah / Tenang', '安い肉 (yasui niku = daging murah), 安心 (anshin = lega tenang)', 'Sifat Dasar'],
  ['新', 'シン / あたら-しい', 'shin / atara-shii', 'Baru', '新しい車 (atarashii kuruma = mobil baru), 新聞 (shinbun = surat kabar koran)', 'Sifat Dasar'],
  ['古', 'コ / ふる-い', 'ko / furu-i', 'Lama / Kuno', '古い本 (furui hon = buku kuno lama), 中古 (chuuko = barang bekas)', 'Sifat Dasar'],
  ['長', 'チョウ / なが-い', 'chou / naga-i', 'Panjang / Pimpinan', '長い道 (nagai michi = jalan panjang), 社長 (shachou = pimpinan direktur)', 'Sifat Dasar'],
  ['白', 'ハク / しろ, しろ-い', 'haku / shiro', 'Putih', '白い雪 (shiroi yuki = salju putih), 白鳥 (hakuchou = angsa)', 'Sifat Dasar'],
  ['黒', 'コク / くろ, くろ-い', 'koku / kuro', 'Hitam', '黒いペン (kuroi pen = pulpen hitam), 黒板 (kokuban = papan tulis hitam)', 'Sifat Dasar'],
  ['赤', 'セキ / あか, あか-い', 'seki / aka', 'Merah', '赤いリンゴ (akai ringo = apel merah), 赤ちゃん (akachan = bayi)', 'Sifat Dasar'],
  ['青', 'セイ / あお, あお-い', 'sei / ao', 'Biru', '青い空 (aoi sora = langit biru), 青年 (seinen = pemuda)', 'Sifat Dasar'],
  ['円', 'エン / まる-い', 'en / maru-i', 'Mata Uang Yen / Lingkaran', '五百円 (gohyakuen = 500 yen), 円い (marui = bundar bulat)', 'Benda & Lain'],
  ['本', 'ホン / もと', 'hon / moto', 'Buku / Asal / Dasar', '本を読む (hon o yomu = baca buku), 日本 (Nihon = negara Jepang)', 'Benda & Lain'],
  ['名', 'メイ, ミョウ / な', 'mei / na', 'Nama / Terkenal', '名前 (namae = nama lengkap), 有名 (yuumei = tersohor terkenal)', 'Benda & Lain'],
  ['何', 'カ / なに, なん', 'ka / nani, nan', 'Apa', '何ですか (nan desu ka = apa ini?), 何人 (nannin = berapa orang)', 'Benda & Lain'],
  ['友', 'ユウ / とも', 'yuu / tomo', 'Teman / Kawan', '友達 (tomodachi = sahabat kawan), 友人 (yuujin = kawan akrab)', 'Benda & Lain'],
  ['車', 'シャ / くるま', 'sha / kuruma', 'Mobil / Kendaraan', '車を運転する (kuruma o unten suru = menyetir mobil), 電車 (densha = kereta listrik)', 'Benda & Lain'],
  ['道', 'ドウ / みち', 'dou / michi', 'Jalan / Jalur', '広い道 (hiroi michi = jalan lebar), 水道 (suidou = saluran air)', 'Benda & Lain'],
  ['電', 'デン', 'den', 'Listrik', '電気 (denki = listrik/lampu), 電話 (denwa = telepon)', 'Benda & Lain'],
  ['語', 'ゴ / かた-る', 'go / kata-ru', 'Bahasa / Kata', '日本語 (nihongo = bahasa Jepang), 英語 (eigo = bahasa Inggris)', 'Benda & Lain'],
  ['魚', 'ギョ / さかな, うお', 'gyo / sakana', 'Ikan', '魚を食べる (sakana o taberu = menyantap ikan), 金魚 (kingyo = ikan mas koki)', 'Alam & Benda'],
  ['肉', 'ニク', 'niku', 'Daging', '牛肉 (gyuuniku = daging sapi), 豚肉 (butaniku = daging babi)', 'Benda & Lain'],
  ['犬', 'ケン / いぬ', 'ken / inu', 'Anjing', '白い犬 (shiroi inu = anjing putih), 子犬 (koinu = anak anjing)', 'Alam & Benda'],
];

// =========================================================================
// JLPT N4 (150+ KANJI TAMBAHAN RESMI - NO OVERLAP WITH N5)
// =========================================================================
const KANJI_N4 = [
  // Waktu & Kalender
  ['曜', 'ヨウ', 'you', 'Hari dalam Pekan', '月曜日 (getsuyoubi = hari Senin), 何曜日 (nanyoubi = hari apa)', 'Waktu'],
  ['今', 'コン, キン / いま', 'kon, kin / ima', 'Sekarang / Kini', '今 (ima = saat ini), 今日 (kyou = hari ini)', 'Waktu'],
  ['昨', 'サク', 'saku', 'Kemarin / Lalu', '昨日 (kinou = kemarin), 昨年 (sakunen = tahun lalu)', 'Waktu'],
  ['明', 'メイ, ミョウ / あか-るい, あ-ける', 'mei / aka-rui', 'Terang / Jelas / Esok', '明日 (ashita = besok), 明るい部屋 (akarui heya = kamar terang)', 'Waktu & Keadaan'],
  ['終', 'シュウ / お-わる, お-える', 'shuu / o-waru', 'Selesai / Akhir', '授業が終わる (jugyou ga owaru = kelas usai), 終電 (shuuden = kereta terakhir)', 'Waktu'],
  ['祭', 'サイ / まつ-り', 'sai / matsu-ri', 'Festival / Pesta Rakyat', 'お祭り (omatsuri = festival rakyat), 文化祭 (bunkasai = pekan seni budaya)', 'Budaya & Acara'],
  ['春', 'シュン / はる', 'shun / haru', 'Musim Semi', '春休み (haruyasumi = libur musim semi), 青春 (seishun = masa muda)', 'Waktu & Musim'],
  ['夏', 'カ, ゲ / なつ', 'ka / natsu', 'Musim Panas', '夏休み (natsuyasumi = liburan musim panas), 夏祭り (natsumatsuri = festival musim panas)', 'Waktu & Musim'],
  ['秋', 'シュウ / あき', 'shuu / aki', 'Musim Gugur', '秋風 (akikaze = angin musim gugur), 読書の秋 (dokusho no aki = musim gugur membaca)', 'Waktu & Musim'],
  ['冬', 'トウ / ふゆ', 'tou / fuyu', 'Musim Dingin', '冬休み (fuyuyasumi = libur musim dingin), 真冬 (mafuyu = puncak musim dingin)', 'Waktu & Musim'],
  ['夕', 'セキ / ゆう', 'seki / yuu', 'Senja / Petang', '夕方 (yuugata = waktu senja), 夕飯 (yuuhan = makan malam santai)', 'Waktu'],
  ['晩', 'バン', 'ban', 'Malam Hari', '今晩 (konban = malam ini), 毎晩 (maiban = tiap malam)', 'Waktu'],

  // Hubungan & Orang
  ['先', 'セン / さき', 'sen / saki', 'Dahulu / Ujung', '先生 (sensei = guru pengajar), 先週 (senshuu = minggu lalu)', 'Hubungan'],
  ['生', 'セイ, ショウ / い-きる, う-まれる', 'sei / i-kiru, u-mareru', 'Hidup / Lahir / Murid', '学生 (gakusei = murid pelajar), 生まれる (umareru = terlahir)', 'Hubungan'],
  ['同', 'ドウ / おな-じ', 'dou / ona-ji', 'Sama / Serupa', '同じ (onaji = sama persis), 同僚 (douryou = rekan kerja)', 'Hubungan'],
  ['他', 'タ / ほか', 'ta / hoka', 'Lain / Yang Lain', '他の人 (hoka no hito = orang lain), 他人 (tanin = orang asing)', 'Hubungan'],
  ['彼', 'ヒ / かれ, かの', 'hi / kare, kano', 'Dia Laki-laki / Kekasih', '彼 (kare = dia pria / pacar pria), 彼ら (karera = mereka)', 'Hubungan'],
  ['私', 'シ / わたし, わたくし', 'shi / watashi', 'Saya / Pribadi', '私の本 (watashi no hon = buku saya), 私立 (shiritsu = swasta)', 'Hubungan'],
  ['族', 'ゾク', 'zoku', 'Keluarga / Suku', '家族 (kazoku = sanak keluarga), 親族 (shinzoku = kerabat)', 'Hubungan'],
  ['達', 'タツ / たち', 'tatsu / tachi', 'Mencapai / Jamak (Para)', '友達 (tomodachi = teman-teman), 私達 (watashitachi = kami / kita)', 'Hubungan'],
  ['親', 'シン / おや, した-しい', 'shin / oya, shita-shii', 'Orang Tua / Akrab', '両親 (ryoushin = kedua orang tua), 親しい友人 (shitashii yuujin = sahabat karib akrab)', 'Hubungan'],
  ['切', 'セツ, サイ / き-る, き-れる', 'setsu / ki-ru', 'Memotong / Penting', '切手を貼る (kitte o haru = menempel perangko), 大切 (taisetsu = amat penting berharga)', 'Hubungan & Sifat'],
  ['者', 'シャ / もの', 'sha / mono', 'Orang (Pelaku / Profesi)', '医者 (isha = dokter), 若者 (wakamono = kaum muda)', 'Hubungan'],
  ['体', 'タイ, テイ / からだ', 'tai / karada', 'Tubuh / Fisik', '体が健康 (karada ga kenkou = tubuh sehat walafiat), 体重 (taijuu = berat badan)', 'Tubuh & Kesehatan'],
  ['首', 'シュ / くび', 'shu / kubi', 'Leher / Pimpinan', '首 (kubi = leher), 首都 (shuto = ibu kota negara)', 'Tubuh & Kesehatan'],
  ['手', 'シュ / て', 'shu / te', 'Tangan', '手を洗う (te o arau = mencuci tangan), 上手 (jouzu = mahir terampil)', 'Tubuh & Kesehatan'],
  ['足', 'ソク / あし, た-りる', 'soku / ashi, ta-riru', 'Kaki / Cukup', '足が痛い (ashi ga itai = kaki terasa pegal sakit), 足りる (tariru = mencukupi)', 'Tubuh & Kesehatan'],
  ['目', 'モク / め', 'moku / me', 'Mata / Butir Poin', '目がいい (me ga ii = mata tajam sehat), 目的 (mokuteki = tujuan sasaran)', 'Tubuh & Kesehatan'],
  ['耳', 'ジ / みみ', 'ji / mimi', 'Telinga', '耳を傾ける (mimi o katamukeru = menyimak saksama), 耳鼻科 (jibika = poli THT)', 'Tubuh & Kesehatan'],
  ['口', 'コウ, ク / くち', 'kou, ku / kuchi', 'Mulut / Pintu Masuk', '入口 (iriguchi = pintu masuk), 出口 (deguchi = pintu keluar)', 'Tubuh & Tempat'],

  // Pekerjaan, Tempat & Benda
  ['仕', 'シ, ジ / つか-える', 'shi / tsuka-eru', 'Bekerja / Melayani', '仕事 (shigoto = pekerjaan), 仕方 (shikata = cara metode)', 'Pekerjaan'],
  ['事', 'ジ / こと', 'ji / koto', 'Hal / Urusan / Kejadian', '大事 (daiji = penting krusial), 事故 (jiko = kecelakaan)', 'Pekerjaan'],
  ['会', 'カイ / あ-う', 'kai / a-u', 'Pertemuan / Bertemu', '会社 (kaisha = perusahaan), 会議 (kaigi = rapat komite)', 'Pekerjaan'],
  ['社', 'シャ / やしろ', 'sha / yashiro', 'Perusahaan / Masyarakat', '会社員 (kaishain = karyawan kantor), 社会 (shakai = masyarakat)', 'Pekerjaan'],
  ['店', 'テン / みせ', 'ten / mise', 'Toko / Warung', '喫茶店 (kissaten = kafe kedai kopi), 店員 (ten\'in = pramuniaga pelayan)', 'Tempat & Benda'],
  ['員', 'イン', 'in', 'Pegawai / Anggota', '駅員 (ekiin = petugas stasiun), 銀行員 (ginkouin = pegawai bank)', 'Pekerjaan'],
  ['教', 'キョウ / おし-える, おそ-わる', 'kyou / oshi-eru', 'Mengajar / Ajaran', '教室 (kyoushitsu = ruang kelas), 教える (oshieru = mengajari)', 'Pendidikan'],
  ['室', 'シツ / むろ', 'shitsu / muro', 'Ruangan / Kamar', '研究室 (kenkyuushitsu = laboratorium riset), 室内 (shitsunai = dalam ruangan)', 'Tempat & Benda'],
  ['師', 'シ', 'shi', 'Ahli / Guru / Pakar', '医師 (ishi = dokter spesialis), 教師 (kyoushi = pendidik guru)', 'Pekerjaan'],
  ['医', 'イ', 'i', 'Medis / Pengobatan', '医者 (isha = dokter), 医学 (igaku = ilmu kedokteran medis)', 'Pekerjaan'],
  ['病', 'ビョウ, ヘイ / やま-い', 'byou / yama-i', 'Penyakit / Sakit', '病院 (byouin = rumah sakit), 病気 (byouki = sedang sakit)', 'Kesehatan'],
  ['院', 'イン', 'in', 'Institusi / Balai', '大学院 (daigakuin = pascasarjana S2/S3), 入院 (nyuuin = rawat inap RS)', 'Kesehatan'],
  ['館', 'カン / やかた', 'kan', 'Gedung Publik / Balai', '図書館 (toshokan = perpustakaan), 映画館 (eigakan = bioskop)', 'Tempat & Benda'],
  ['図', 'ズ, ト / はか-る', 'zu, to / haka-ru', 'Gambar / Denah', '地図 (chizu = peta petunjuk jalan), 図書 (tosho = kepustakaan buku)', 'Tempat & Benda'],
  ['堂', 'ドウ', 'dou', 'Aula / Balai Megah', '食堂 (shokudou = kantin ruang makan), 本堂 (hondou = aula kuil utama)', 'Tempat & Benda'],
  ['屋', 'オク / や', 'oku / ya', 'Toko / Atap / Kamar', '本屋 (hon\'ya = toko buku), 部屋 (heya = kamar)', 'Tempat & Benda'],
  ['場', 'ジョウ / ば', 'jou / ba', 'Tempat / Lapangan', '場所 (basho = letak lokasi), 工場 (koujou = pabrik industri)', 'Tempat & Benda'],
  ['所', 'ショ / ところ', 'sho / tokoro', 'Tempat / Bagian', '住所 (juusho = alamat tinggal), 台所 (daidokoro = dapur masak)', 'Tempat & Benda'],
  ['町', 'チョウ / まち', 'chou / machi', 'Kota Kecil / Lingkungan', '町 (machi = pemukiman kota kecil), 下町 (shitamachi = kota tua tradisional)', 'Tempat & Benda'],
  ['村', 'ソン / むら', 'son / mura', 'Desa / Dusun', '村人 (murabito = warga desa), 農村 (nouson = pedesaan agraris)', 'Tempat & Benda'],
  ['市', 'シ / いち', 'shi / ichi', 'Kota Administratif / Pasar', '京都市 (Kyouto-shi = Kota Kyoto), 市場 (ichiba = pasar transaksi)', 'Tempat & Benda'],
  ['京', 'キョウ, ケイ', 'kyou, kei', 'Ibu Kota', '京都 (Kyouto = Kyoto), 上京 (joukyou = merantau ke Tokyo)', 'Tempat & Benda'],
  ['駅', 'エキ', 'eki', 'Stasiun Kereta', '駅前 (ekimae = depan stasiun), 新宿駅 (Shinjuku-eki = Stasiun Shinjuku)', 'Tempat & Benda'],
  ['線', 'セン', 'sen', 'Rel / Garis / Jalur', '山手線 (yamanotesen = jalur Yamanote), 新幹線 (shinkansen = kereta cepat)', 'Tempat & Benda'],
  ['地', 'チ, ジ', 'chi, ji', 'Tanah / Bumi / Wilayah', '地下鉄 (chikatetsu = kereta bawah tanah MRT), 地震 (jishin = gempa bumi tektonik)', 'Tempat & Benda'],
  ['港', 'コウ / みなと', 'kou / minato', 'Pelabuhan Dermaga', '空港 (kuukou = bandar udara), 横浜港 (Yokohamakou = Pelabuhan Yokohama)', 'Tempat & Benda'],
  ['園', 'エン / その', 'en / sono', 'Taman / Kebun Rekreasi', '公園 (kouen = taman umum), 動物園 (doubutsuen = kebun binatang)', 'Tempat & Benda'],
  ['公', 'コウ / おおやけ', 'kou / ooyake', 'Publik / Umum Terbuka', '公園 (kouen = taman terbuka publik), 公務員 (koumuin = aparatur sipil ASN)', 'Tempat & Benda'],
  ['銀', 'ギン', 'gin', 'Perak / Perbankan', '銀行 (ginkou = kantor bank), 銀座 (Ginza = kawasan Ginza)', 'Tempat & Benda'],
  ['池', 'チ / いけ', 'chi / ike', 'Kolam Air Tenang', '公園の池 (kouen no ike = kolam taman), 電池 (denchi = batu baterai daya)', 'Alam & Benda'],
  ['界', 'カイ', 'kai', 'Batas Dunia / Ranah', '世界 (sekai = dunia jagat raya), 限界 (genkai = ambang batas)', 'Konsep & Benda'],

  // Kata Kerja N4
  ['知', 'チ / し-る', 'chi / shi-ru', 'Mengetahui / Mengerti', '道を知る (michi o shiru = tahu jalan), 知識 (chishiki = pengetahuan wawasan)', 'Kata Kerja'],
  ['思', 'シ / おも-う', 'shi / omo-u', 'Berpikir / Merasa', 'そう思う (sou omou = saya kira begitu), 思い出 (omoide = memori kenangan manis)', 'Kata Kerja'],
  ['考', 'コウ / かんが-える', 'kou / kanga-eru', 'Menimbang / Merenungkan', '深く考える (fukaku kangaeru = berpikir matang), 考案 (kouan = ide rancangan)', 'Kata Kerja'],
  ['学', 'ガク / まな-ぶ', 'gaku / mana-bu', 'Belajar / Menuntut Ilmu', '大学 (daigaku = universitas), 学ぶ (manabu = mendalami ilmu)', 'Pendidikan'],
  ['習', 'シュウ / なら-う', 'shuu / nara-u', 'Berlatih / Kursus', '日本語を習う (nihongo o narau = kursus bahasa Jepang), 練習 (renshuu = latihan soal)', 'Pendidikan'],
  ['研', 'ケン / と-ぐ', 'ken / to-gu', 'Mengasah / Riset', '研究 (kenkyuu = penelitian riset), 研修 (kenshuu = diklat pelatihan magang)', 'Pendidikan'],
  ['究', 'キュウ / きわ-める', 'kyuu / kiwa-meru', 'Meneliti Tuntas', '研究所 (kenkyuujo = laboratorium riset), 究明 (kyuumei = investigasi tuntas)', 'Pendidikan'],
  ['届', 'カイ / とど-く, とど-ける', 'kai / todo-ku, todo-keru', 'Menyampaikan / Sampai', '荷物が届く (nimotsu ga todoku = paket kiriman tiba), 届出 (todokede = pelaporan resmi)', 'Kata Kerja'],
  ['返', 'ヘン / かえ-す, かえ-る', 'hen / kae-su', 'Mengembalikan / Menjawab', '本を返す (hon o kaesu = memulangkan buku), 返事 (henji = jawaban balasan)', 'Kata Kerja'],
  ['送', 'ソウ / おく-る', 'sou / oku-ru', 'Mengirim / Mengantar', '手紙を送る (tegami o okuru = mengirim surat), 送金 (soukin = transfer dana uang)', 'Kata Kerja'],
  ['貸', 'タイ / か-す', 'tai / ka-su', 'Meminjamkan', 'お金を貸す (okane o kasu = meminjamkan uang), 賃貸 (chintai = sewa kontrak hunian)', 'Kata Kerja'],
  ['借', 'シャク / か-りる', 'shaku / ka-riru', 'Meminjam', '本を借りる (hon o kariru = meminjam buku), 借金 (shakkin = utang pinjaman piutang)', 'Kata Kerja'],
  ['始', 'シ / はじ-まる, はじ-める', 'shi / haji-maru, haji-meru', 'Memulai / Mengawali', '試合が始まる (shiai ga hajimaru = tanding dimulai), 開始 (kaishi = awal mula start)', 'Kata Kerja'],
  ['住', 'ジュウ / す-む', 'juu / su-mu', 'Tinggal / Menetap', '東京に住む (Toukyou ni sumu = berdomisili di Tokyo), 住民 (juumin = warga penghuni)', 'Kata Kerja'],
  ['売', 'バイ / う-る, う-れる', 'bai / u-ru, u-reru', 'Menjual', '切符を売る (kippu o uru = menjual karcis), 売店 (baiten = kios pedagang)', 'Kata Kerja'],
  ['待', 'タイ / ま-つ', 'tai / ma-tsu', 'Menunggu / Menanti', 'ここで待つ (koko de matsu = menanti di sini), 期待 (kitai = harapan asa tinggi)', 'Kata Kerja'],
  ['急', 'キュウ / いそ-ぐ', 'kyuu / iso-gu', 'Bergegas / Cepat Mendesak', '急いで歩く (isoide aruku = melangkah bergegas), 急行 (kyuukou = kereta ekspres)', 'Kata Kerja'],
  ['持', 'ジ / も-つ', 'ji / mo-tsu', 'Membawa / Memiliki', '荷物を持つ (nimotsu o motsu = menjinjing koper), 気持ち (kimochi = perasaan sukma)', 'Kata Kerja'],
  ['開', 'カイ / あ-く, ひら-く', 'kai / a-ku, hira-ku', 'Membuka', 'ドアが開く (doa ga aku = pintu terbuka), 開会 (kaikai = upacara pembukaan)', 'Kata Kerja'],
  ['閉', 'ヘイ / し-まる, と-じる', 'hei / shi-maru, to-jiru', 'Menutup', '窓を閉める (mado o shimeru = menutup jendela), 閉店 (heiten = toko tutup kasir)', 'Kata Kerja'],
  ['止', 'シ / と-まる, と-める', 'shi / to-maru, to-meru', 'Berhenti / Menghentikan', '車が止まる (kuruma ga tomaru = mobil berhenti), 中止 (chuushi = pembatalan acara)', 'Kata Kerja'],
  ['乗', 'ジョウ / の-る, の-せる', 'jou / no-ru', 'Naik Kendaraan', '電車に乗る (densha ni noru = naik gerbong kereta), 乗客 (joukyaku = penumpang)', 'Kata Kerja'],
  ['降', 'コウ / お-りる, ふ-る', 'kou / o-riru, fu-ru', 'Turun Kendaraan / Hujan', 'バスを降りる (basu o oriru = turun dari bus), 雨が降る (ame ga furu = hujan turun)', 'Kata Kerja'],
  ['運', 'ウン / はこ-ぶ', 'un / hako-bu', 'Mengangkut / Nasib', '荷物を運ぶ (nimotsu o hakobu = memindahkan barang), 運動 (undou = olahraga jasmani)', 'Kata Kerja'],
  ['動', 'ドウ / うご-く, うご-かす', 'dou / ugo-ku', 'Bergerak / Beroperasi', '機械が動く (kikai ga ugoku = mesin beroperasi), 自動車 (jidousha = mobil)', 'Kata Kerja'],
  ['働', 'ドウ / はたら-く', 'dou / hatara-ku', 'Bekerja Mencari Nafkah', '会社で働く (kaisha de hataraku = bekerja di korporasi), 労働 (roudou = tenaga kerja buruh)', 'Kata Kerja'],
  ['洗', 'セン / あら-う', 'sen / ara-u', 'Mencuci', '手を洗う (te o arau = membasuh tangan), 洗濯 (sentaku = mencuci pakaian jemuran)', 'Kata Kerja'],
  ['歌', 'カ / うた, うた-う', 'ka / uta, uta-u', 'Menyanyi / Lagu', '歌を歌う (uta o utau = menyanyikan lagu), 歌手 (kashu = penyanyi vokalis)', 'Kata Kerja'],
  ['試', 'シ / こころ-みる, ため-す', 'shi / tame-su', 'Mencoba / Menguji', '試験 (shiken = ujian penilaian), 試食 (shishoku = mencicipi makanan uji rasa)', 'Pendidikan'],
  ['験', 'ケン', 'ken', 'Menguji / Asam Garam Pengalaman', '受験 (juken = menempuh ujian seleksi), 経験 (keiken = asam garam pengalaman)', 'Pendidikan'],
  ['題', 'ダイ', 'dai', 'Soal Ujian / Topik / Judul', '問題 (mondai = soal ujian / permasalahan), 宿題 (shukudai = tugas PR)', 'Pendidikan'],
  ['答', 'トウ / こた-える, こた-え', 'tou / kota-eru', 'Menjawab / Jawaban', '質問に答える (shitsumon ni kotaeru = menjawab tanya), 回答 (kaitou = lembar respon)', 'Pendidikan'],
  ['引', 'イン / ひ-く, ひ-ける', 'in / hi-ku', 'Menarik / Mengurangi', 'ドアを引く (doa o hiku = menarik gagang pintu), 割引 (waribiki = diskon potongan harga)', 'Kata Kerja'],
  ['押', 'オウ / お-す, お-さえる', 'ou / o-su', 'Menekan / Mendorong', 'ボタンを押す (botan o osu = menekan tombol picu), 押入れ (oshiire = lemari dinding geser)', 'Kata Kerja'],
  ['作', 'サク, サ / つく-る', 'saku, sa / tsuku-ru', 'Membuat / Memproduksi', '料理を作る (ryouri o tsukuru = memasak hidangan), 作文 (sakubun = karangan esei)', 'Kata Kerja'],
  ['使', 'シ / つか-う', 'shi / tsuka-u', 'Menggunakan / Memakai', '辞書を使う (jisho o tsukau = memakai kamus), 大使館 (taishikan = kantor kedutaan besar)', 'Kata Kerja'],
  ['歩', 'ホ, ブ / ある-く', 'ho / aru-ku', 'Berjalan Kaki', '散歩する (sanpo suru = jalan-jalan santai), 歩道 (hodou = trotoar pejalan kaki)', 'Kata Kerja'],
  ['通', 'ツウ / とお-る, かよ-う', 'tsuu / too-ru, kayo-u', 'Melintas / Bolak-balik Komuter', '学校に通う (gakkou ni kayou = bersekolah komuter), 通行 (tsuukou = lalu lintas jalan)', 'Kata Kerja'],

  // Sifat & Keadaan N4
  ['嬉', 'キ / うれ-しい', 'ki / ure-shii', 'Gembira / Bahagia', '合格して嬉しい (goukaku shite ureshii = gembira lulus seleksi)', 'Sifat & Perasaan'],
  ['悲', 'ヒ / かな-しい', 'hi / kana-shii', 'Sedih / Pilu Haru', '悲しい物語 (kanashii monogatari = kisah sedih pilu), 悲劇 (higeki = drama tragedi)', 'Sifat & Perasaan'],
  ['怒', 'ド / おこ-る, いか-る', 'do / oko-ru', 'Marah / Murka Geram', '怒りの声 (ikari no koe = luapan amarah), 怒る (okoru = marah meluap)', 'Sifat & Perasaan'],
  ['楽', 'ラク, ガク / たの-しい', 'raku, gaku / tano-shii', 'Menyenangkan / Musik', '楽しい時間 (tanoshii jikan = waktu berharga seru), 音楽 (ongaku = seni musik alunan)', 'Sifat & Perasaan'],
  ['苦', 'ク / くる-しい, にが-い', 'ku / kuru-shii, niga-i', 'Pahit / Susah Payah', '苦い薬 (nigai kusuri = pil obat pahit), 苦労 (kurou = kerja keras banting tulang)', 'Sifat & Perasaan'],
  ['甘', 'カン / あま-い', 'kan / ama-i', 'Manis / Manja', '甘いお菓子 (amai okashi = penganan manis legit), 甘酒 (amazake = minuman beras manis)', 'Sifat & Perasaan'],
  ['辛', 'シン / から-い', 'shin / kara-i', 'Pedas / Berat Pedih', '辛いカレー (karai karee = kari berkuah pedas), 辛抱 (shinbou = ketabahan tekad)', 'Sifat & Perasaan'],
  ['強', 'キョウ, ゴウ / つよ-い', 'kyou / tsuyo-i', 'Kuat / Perkasa', '強い風 (tsuyoi kaze = terpaan angin kencang), 勉強 (benkyou = belajar giat tekun)', 'Sifat & Keadaan'],
  ['弱', 'ジャク / よわ-い', 'jaku / yowa-i', 'Lemah / Rapuh', '体が弱い (karada ga yowai = kondisi badan ringkih), 弱者 (jakusha = pihak yang lemah)', 'Sifat & Keadaan'],
  ['速', 'ソク / はや-い', 'soku / haya-i', 'Cepat (Laju Kecepatan)', '足が速い (ashi ga hayai = lari secepat kilat), 速度 (sokudo = laju kecepatan km/jam)', 'Sifat & Keadaan'],
  ['遅', 'チ / おそ-い, おく-れる', 'chi / oso-i, oku-reru', 'Lambat / Terlambat', '歩くのが遅い (aruku no ga osoi = langkah lamban), 遅刻 (chikoku = terlambat hadir)', 'Sifat & Keadaan'],
  ['暑', 'ショ / あつ-い', 'sho / atsu-i', 'Panas (Cuaca Suhu)', '暑い夏 (atsui natsu = musim panas menyengat), 残暑 (zansho = hawa panas akhir musim)', 'Sifat & Keadaan'],
  ['寒', 'カン / さむ-い', 'kan / samu-i', 'Dingin (Suhu Cuaca)', '寒い朝 (samui asa = pagi dingin menggigil), 寒中 (kanchuu = di tengah musim dingin)', 'Sifat & Keadaan'],
  ['重', 'ジュウ, チョウ / おも-い, かさ-ねる', 'juu / omo-i', 'Berat / Berbobot Nilai', '荷物が重い (nimotsu ga omoi = tas bawaan berbobot berat), 重要 (juuyou = amat krusial)', 'Sifat & Keadaan'],
  ['軽', 'ケイ / かる-い', 'kei / karu-i', 'Ringan / Santai', '軽い服 (karui fuku = busana ringan semilir), 手軽 (tegaru = praktis mudah dijangkau)', 'Sifat & Keadaan'],
  ['広', 'コウ / ひろ-い', 'kou / hiro-i', 'Luas / Lapang Lega', '広い部屋 (hiroi heya = kamar luas lapang), 広告 (koukoku = iklan promosi publik)', 'Sifat & Keadaan'],
  ['狭', 'キョウ / せま-い', 'kyou / sema-i', 'Sempit / Berhimpitan', '狭い道 (semai michi = gang sempit pemukiman), 狭苦しい (semakurushii = sesak sempit)', 'Sifat & Keadaan'],
  ['暗', 'アン / くら-い', 'an / kura-i', 'Gelap / Muram', '暗い夜道 (kurai yomichi = jalan malam remang), 暗証番号 (anshoubangou = nomor PIN sandi rahasia)', 'Sifat & Keadaan'],
  ['痛', 'ツウ / いた-い, いた-む', 'tsuu / ita-i', 'Sakit / Nyeri Perih', 'お腹が痛い (onaka ga itai = perut terasa nyeri melilit), 頭痛 (zutsuu = sakit kepala pening)', 'Kesehatan'],
  ['静', 'セイ, ジョウ / しず-か', 'sei / shizu-ka', 'Sunyi / Hening Asri', '静かな夜 (shizukana yoru = malam sunyi hening), 安静 (ansei = istirahat pemulihan bedrest)', 'Sifat & Keadaan'],

  // Benda Sehari-hari, Alam & Hewan N4
  ['紙', 'シ / かみ', 'shi / kami', 'Kertas', '手紙 (tegami = surat tulisan tangan pos), 和紙 (washi = kertas tradisional Jepang)', 'Benda & Tempat'],
  ['帳', 'チョウ', 'chou', 'Buku Catatan Agenda', '手帳 (techou = buku saku agenda), 銀行通帳 (ginkou tsuuchou = buku tabungan rekening)', 'Benda & Tempat'],
  ['筆', 'ヒツ / ふで', 'hitsu / fude', 'Kuas Tulis / Pena', '鉛筆 (enpitsu = pensil karbon tulis), 万年筆 (mannenhitsu = pena tinta bolpoin klasik)', 'Benda & Tempat'],
  ['茶', 'チャ, サ', 'cha, sa', 'Teh Hijau / Jamuan', 'お茶を飲む (ocha o nomu = minum teh hangat), 茶道 (sadou = seni upacara tradisi teh)', 'Benda & Tempat'],
  ['飯', 'ハン / めし', 'han / meshi', 'Nasi / Hidangan Makanan', '朝ご飯 (asagohan = santapan sarapan), 昼飯 (hirumeshi = makan siang)', 'Benda & Tempat'],
  ['鳥', 'チョウ / とり', 'chou / tori', 'Burung / Unggas', '小鳥がさえずる (kotori ga saezuru = burung kecil bernyanyi), 焼き鳥 (yakitori = sate ayam Jepang)', 'Alam & Benda'],
  ['牛', 'ギュウ / うし', 'gyuu / ushi', 'Sapi Lembu', '牛肉 (gyuuniku = daging sapi segar), 牛乳 (gyuunyuu = susu sapi murni kemasan)', 'Alam & Benda'],
  ['馬', 'バ / うま', 'ba / uma', 'Kuda', '馬に乗る (uma ni noru = mengendarai kuda gagah), 競馬 (keiba = pacuan balapan kuda)', 'Alam & Benda'],
  ['風', 'フウ, フ / かぜ', 'fuu / kaze', 'Angin / Hembusan / Flu', '涼しい風 (suzushii kaze = hembusan angin sejuk), 台風 (taifuu = badai topan tropis)', 'Alam & Benda'],
  ['門', 'モン / かど', 'mon / kado', 'Gerbang Pintu Pagar', '学校の正門 (gakkou no seimon = gerbang pintu depan kampus), 専門 (senmon = bidang spesialisasi)', 'Tempat & Benda'],
  ['服', 'フク', 'fuku', 'Pakaian / Busana', '洋服 (youfuku = pakaian gaya modern barat), 和服 (wafuku = kimono tradisional Jepang)', 'Benda & Tempat'],
  ['物', 'ブツ, モツ / もの', 'butsu, motsu / mono', 'Benda / Barang / Sesuatu', '買い物 (kaimono = belanja kebutuhan), 動物 (doubutsu = hewan satwa liar)', 'Benda & Tempat'],
  ['色', 'ショク, シキ / いろ', 'shoku, shiki / iro', 'Warna Corak', '好きな色 (suki na iro = corak warna kesukaan), 景色 (keshiki = pemandangan panorama alam)', 'Benda & Tempat'],
  ['音', 'オン, イン / おと, ね', 'on / oto', 'Suara Bunyi / Musik', '足音 (ashioto = derap langkah kaki), 発音 (hatsuon = lafal artikulasi pengucapan)', 'Benda & Tempat'],
  ['声', 'セイ, ショウ / こえ', 'sei / koe', 'Suara Makhluk Hidup', '大きな声 (ookina koe = suara lantang bergema), 歌声 (utagoe = alunan suara merdu menyanyi)', 'Tubuh & Kesehatan'],
  ['光', 'コウ / ひかり, ひか-る', 'kou / hikari, hika-ru', 'Cahaya / Sinar Kemilau', '朝の光 (asa no hikari = hangat pancaran sinar fajar), 観光 (kankou = plesir pariwisata tamasya)', 'Alam & Benda'],
  ['旅', 'リョ / たび', 'ryo / tabi', 'Perjalanan Melancong / Musafir', '旅行 (ryokou = bepergian tamasya wisata), 旅人 (tabibito = pengelana musafir melangkah)', 'Budaya & Acara'],
  ['映', 'エイ / うつ-る, うつ-す', 'ei / utsu-su', 'Memantulkan / Menayangkan', '映画 (eiga = sinema film layar perak), 映像 (eizou = rekaman video visualisasi)', 'Budaya & Acara'],
  ['画', 'ガ, カク', 'ga, kaku', 'Gambar Lukisan / Goresan', '画家 (gaka = perupa pelukis kanvas), 計画 (keikaku = perancangan strategi rancangan)', 'Budaya & Acara'],
  ['漢', 'カン', 'kan', 'Dinasti Han / Aksara Kanji', '漢字 (kanji = aksara kanji berkarakter), 漢方薬 (kanpouyaku = ramuan herbal tradisional timur)', 'Pendidikan'],
  ['字', 'ジ / あざ', 'ji', 'Huruf / Karakter Tulisan', 'ローマ字 (roomaji = abjad romawi latin), 名字 (myouji = nama keluarga marga trah)', 'Pendidikan'],
  ['具', 'グ', 'gu', 'Alat Perkakas / Kelengkapan', '家具 (kagu = perabotan interior furnitur), 道具 (dougu = perkakas piranti kerja)', 'Benda & Tempat'],
  ['台', 'ダイ, タイ', 'dai, tai', 'Meja Podium / Kata Bantu Mesin', '一台の車 (ichidai no kuruma = seunit mobil), 台所 (daidokoro = ruangan dapur memasak)', 'Benda & Tempat'],
  ['度', 'ド, ト / たび', 'do / tabi', 'Derajat Suhu / Kali Pengulangan', '温度 (ondo = takaran derajat suhu), 今度 (kondo = kesempatan kali lain mendatang)', 'Konsep & Benda'],
  ['回', 'カイ / まわ-る, まわ-す', 'kai / mawa-ru', 'Memutar / Frekuensi Kali', '一回 (ikkai = satu kali kesempatan), 回す (mawasu = memutar tuas sakelar)', 'Konsep & Benda'],
  ['番', 'バン', 'ban', 'Nomor Urut / Giliran Tugas', '一番 (ichiban = nomor satu paling utama), 電話番号 (denwabangou = digit deretan nomor kontak telepon)', 'Konsep & Benda'],
  ['号', 'ゴウ', 'gou', 'Nomor Identitas / Gelar', '一号室 (ichigoushitsu = kamar unit nomor satu), 信号 (shingou = lampu lalu lintas rambu jalan)', 'Konsep & Benda'],
  ['意', 'イ', 'i', 'Maksud Pikiran / Kehendak', '意味 (imi = kandungan arti makna hakiki), 意見 (iken = buah pemikiran pendapat pandangan)', 'Konsep & Benda'],
  ['味', 'ミ / あじ, あじ-わう', 'mi / aji', 'Cita Rasa Kelezatan', '美味しい味 (oishii aji = kelezatan rasa cita rasa), 興味 (kyoumi = ketertarikan minat rasa ingin tahu)', 'Benda & Tempat'],
];

// =========================================================================
// JLPT N3 (180+ KANJI MENENGAH RESMI - NO OVERLAP WITH N5 OR N4)
// =========================================================================
const KANJI_N3 = [
  ["命","メイ, ミョウ / いのち","mei, myou / inochi","Nyawa / Kehidupan / Takdir","命を大切にする (inochi o taisetsu ni suru = menghargai nyawa hidup), 生命 (seimei = kehidupan raga)","Kualitas"],
  ["然","ゼン, ネン","zen, nen","Alami / Demikian","自然 (shizen = alam semesta raya), 当然 (touzen = sudah sewajarnya demikian)","Kualitas"],
  ["偶","グウ","guu","Kebetulan / Berpasangan","偶然会う (guuzen au = kebetulan berpapasan temu), 偶数 (guusuu = bilangan angka genap)","Konsep"],
  ["容","ヨウ","you","Wadah / Muatan Isi / Bentuk","内容 (naiyou = muatan isi kandungan), 容易 (youi = mudah tanpa kesukaran)","Konsep"],
  ["易","エキ, イ / やさ-しい","eki, i / yasa-shii","Mudah Gampang / Berniaga","貿易 (boueki = perdagangan ekspor impor antarnegara), 容易 (youi = mudah dikerjakan)","Konsep"],
  ["複","フク","fuku","Ganda / Majemuk Jamak","複雑 (fukuzatsu = rumit berbelit kompleks), 複写 (fukusha = fotokopi salinan)","Konsep"],
  ["雑","ザツ, ゾウ / ま-じる","zatsu / ma-jiru","Bercampur / Macam-macam","雑誌 (zasshi = majalah periodik), 混雑 (konzatsu = kesemrawutan padat sesak)","Konsep"],
  ["規","キ","ki","Standar Kaidah / Regulasi","規則 (kisoku = aturan norma disiplin), 規定 (kitei = ketentuan regulasi baku)","Konsep"],
  ["則","ソク","soku","Kaidah Hukum / Mengikuti","規則正しい生活 (kisokutadashii seikatsu = pola hidup berdisiplin tertib), 法則 (housoku = hukum kepastian alam)","Konsep"],
  ["効","コウ / き-く","kou / ki-ku","Khasiat Efek / Berfaedah","効果がある (kouka ga aru = ada khasiat mujarab), 有効 (yuukou = sah berlaku efektif)","Konsep"],
  ["課","カ","ka","Seksi Bagian / Beban Bab","第一課 (daiikka = bab kesatu pelajaran), 課長 (kachou = kepala seksi manajer)","Pekerjaan"],
  ["査","サ","sa","Meneliti / Memeriksa Seksama","調査 (chousa = survei penyelidikan komprehensif), 検査 (kensa = pemeriksaan tes uji lab)","Pendidikan"],
  ["探","タン / さが-す, さぐ-る","tan / saga-su","Mencari / Menjelajah","仕事を探す (shigoto o sagasu = berikhtiar mencari kerja), 探検 (tanken = ekspedisi penjelajahan rimba)","Kata Kerja"],
  ["捜","ソウ / さが-す","sou / saga-su","Melacak / Menggeledah","犯人を捜す (hannin o sagasu = memburu melacak jejak pelaku), 捜査 (sousa = investigasi penyidikan aparat)","Kata Kerja"],
  ["拾","シュウ, ジュウ / ひろ-う","shuu / hiro-u","Memungut / Menemukan","ゴミを拾う (gomi o hirou = memungut sampah jalan), 拾得物 (shuutokubutsu = barang temuan)","Kata Kerja"],
  ["捨","シャ / す-てる","sha / su-teru","Membuang / Mengabaikan","ゴミを捨てる (gomi o suteru = membuang sampah pada tempatnya), 四捨五入 (shishagonyuu = pembulatan angka desimal)","Kata Kerja"],
  ["壊","カイ / こわ-す, こわ-れる","kai / kowa-su, kowa-reru","Rusak / Menghancurkan","時計が壊れる (tokei ga kowareru = arloji jam rusak macet), 破壊 (hakai = destruksi kehancuran)","Kata Kerja"],
  ["直","チョク, ジキ / なお-す, ただ-ちに","choku / nao-su","Lurus / Memperbaiki Segera","間違いを直す (machigai o naosu = membenahi kekeliruan salah), 直線 (chokusen = garis lurus lencang)","Kata Kerja"],
  ["断","ダン / ことわ-る, た-つ","dan / kotowa-ru","Menolak Halus / Memutuskan","誘いを断る (sasoi o kotowaru = menolak ajakan sopan), 判断 (handan = pertimbangan keputusan)","Kata Kerja"],
  ["招","ショウ / まね-く","shou / mane-ku","Mengundang Tamu / Memanggil","友人を招く (yuujin o maneku = mengundang kawan jamuan), 招待状 (shoutaijou = surat undangan pesta)","Kata Kerja"],
  ["迎","ゲイ / むか-える","gei / muka-eru","Menyambut / Menjemput","駅で客を迎える (eki de kyaku o mukaeru = menjemput tamu di stasiun), 歓迎 (kangei = sambutan hangat)","Kata Kerja"],
  ["逃","トウ / に-げる, に-がす","tou / ni-geru","Melarikan Diri / Lepas","犯人が逃げる (hannin ga nigeru = tersangka meloloskan diri kabur), 逃走 (tousou = pelarian buronan)","Kata Kerja"],
  ["迷","メイ / まよ-う","mei / mayo-u","Tersesat / Ragu-ragu Bimbang","道に迷う (michi ni mayou = tersesat hilang arah jalan), 迷惑 (meiwaku = merepotkan mengganggu)","Kata Kerja"],
  ["倒","トウ / たお-れる, たお-す","tou / tao-reru","Tumbang / Bangkrut Rubuh","木が倒れる (ki ga taoreru = pohon tumbang terhempas), 倒産 (tousan = pailit bangkrut usaha)","Kata Kerja"],
  ["起","キ / お-きる, お-こす","ki / o-kiru","Bangun Tidur / Terjadi Musibah","早起き (hayaoki = bangun fajar pagi), 事故が起きる (jiko ga okiru = terjadi insiden kecelakaan)","Kata Kerja"],
  ["助","ジョ / たす-かる, たす-ける","jo / tasu-karu, tasu-keru","Menolong / Tertolong Selamat","人を助ける (hito o tasukeru = menolong sesama insan), 救助 (kyuujo = evakuasi pertolongan tim SAR)","Kata Kerja"],
  ["救","キュウ / すく-う","kyuu / suku-u","Menyelamatkan Jiwa Raga","命を救う (inochi o sukuu = menyelamatkan nyawa insan), 救急車 (kyuukyuusha = mobil ambulans darurat)","Kata Kerja"],
  ["守","シュ, ス / まも-る","shu / mamo-ru","Melindungi / Menepati Janji","約束を守る (yakusoku o mamoru = menepati komitmen janji), 留守 (rusu = bepergian tidak di rumah)","Kata Kerja"],
  ["争","ソウ / あらそ-う","sou / arasou","Berselisih / Berkompetisi","争いを避ける (arasoi o sakeru = menghindari friksi pertengkaran), 戦争 (sensou = peperangan sengit)","Kata Kerja"],
  ["競","キョウ, ケイ / きそ-う","kyou / kiso-u","Bersaing Gigih / Balapan","技を競う (waza o kisou = mengadu keterampilan bersaing), 競争 (kyousou = rivalitas kompetisi pasar)","Kata Kerja"],
  ["勝","ショウ / か-つ, まさ-る","shou / ka-tsu","Menang / Mengungguli","試合に勝つ (shiai ni katsu = memenangkan turnamen laga), 勝利 (shouri = kemenangan gemilang)","Kata Kerja"],
  ["負","フ / ま-ける, お-う","fu / ma-keru","Kalah / Memikul Beban","勝負 (shoubu = pertarungan duel), 負ける (makeru = menelan kekalahan)","Kata Kerja"],
  ["費","ヒ / つい-やす","hi / tsui-yasu","Biaya Pengeluaran / Konsumsi","学費を払う (gakuhi o harau = menyetor biaya kuliah SPP), 費用 (hiyou = ongkos pengeluaran)","Ekonomi"],
  ["額","ガク / ひたい","gaku / hitai","Jumlah Nominal Uang / Dahi","多額の寄付 (tagaku no kifu = donasi dana bernominal besar), 額 (hitai = dahi kening)","Ekonomi"],
  ["預","ヨ / あず-ける, あず-かる","yo / azu-keru","Menitipkan / Menyimpan Tabungan","銀行にお金を預ける (ginkou ni okane o azukeru = menabung dana di bank), 預金 (yokin = simpanan deposito)","Ekonomi"],
  ["貯","チョ","cho","Menimbun / Menabung Dana","貯金箱 (chokinbako = celengan uang koin), 貯水池 (chosuichi = waduk penampungan air)","Ekonomi"],
  ["収","シュウ / おさ-める","shuu / osa-meru","Memperoleh / Pemasukan Kas","収入が増える (shuunyuu ga fueru = pendapatan pemasukan bertambah), 収穫 (shuukaku = panen raya)","Ekonomi"],
  ["得","トク / え-る, う-る","toku / e-ru","Mendapatkan Laba / Untung","経験を得る (keiken o eru = memetik hikmah pengalaman), 得意 (tokui = mahir andalan)","Ekonomi"],
  ["営","エイ / いとな-む","ei / itona-mu","Menjalankan Usaha / Bisnis","会社を経営する (kaisha o keiei suru = menakhodai manajemen korporasi), 営業 (eigyou = kegiatan niaga komersial)","Ekonomi"],
  ["景","ケイ","kei","Pemandangan Panorama / Iklim Bisnis","美しい景色 (utsukushii keshiki = panorama lanskap molek), 景気回復 (keiki kaifuku = pemulihan geliat ekonomi)","Alam & Ekonomi"],
  ["季","キ","ki","Musim Periode Waktu","四季の移ろい (shiki no utsuroi = pergantian siklus 4 musim), 季節 (kisetsu = musim cuaca)","Alam & Waktu"],
  ["節","セツ, セチ / ふし","setsu / fushi","Musim Cuaca / Sendi / Hemat","季節の変わり目 (kisetsu no kawarime = pergantian musim), 節約 (setsuyaku = pola hidup hemat efisien)","Alam & Waktu"],
  ["乾","カン / かわ-く, かわ-かす","kan / kawa-ku","Kering Gersang / Mengeringkan","洗濯物が乾く (sentakumono ga kawaku = cucian pakaian mengering), 乾杯 (kanpai = bersulang gelas pesta)","Alam & Keadaan"],
  ["燥","ソウ","sou","Kering Hampa Udara","空気が乾燥する (kuuki ga kansou suru = udara terasa kering kemarau), 乾燥機 (kansouki = mesin pengering pakaian)","Alam & Keadaan"],
  ["温","オン / あたた-かい","on / atata-kai","Hangat Suhu / Lemah Lembut","温かいスープ (atatakai suupu = kuah sup hangat), 温度計 (ondokei = alat termometer pengukur suhu)","Alam & Keadaan"],
  ["泉","セン / いずみ","sen / izumi","Mata Air / Pemandian Air Hangat","天然温泉 (tennen onsen = pemandian mata air hangat alami), 泉 (izumi = mata air jernih)","Alam"],
  ["湖","コ / みずうみ","ko / mizuumi","Danau Telaga Luas","琵琶湖 (Biwako = Danau Biwa terluas), 湖畔 (kohan = tepian sempadan danau)","Alam"],
  ["石","セキ / いし","seki / ishi","Batu Kerikil / Padat","重い石 (omoi ishi = bongkahan batu berbobot), 磁石 (jishaku = batang kompas magnet)","Alam"],
  ["砂","サ, シャ / すな","sa / suna","Pasir Pantai Butiran","砂浜を歩く (sunahama o aruku = menyusuri pasir pesisir pantai), 砂漠 (sabaku = hamparan gurun pasir)","Alam"],
  ["坂","ハン / さか","han / saka","Tanjakan Tebing Lereng","急な坂道 (kyuu na sakamichi = jalan tanjakan terjal berliku), 登り坂 (noborisaka = lereng perbukitan menanjak)","Alam & Tempat"],
  ["岸","ガン / きし","gan / kishi","Tepi Pesisir Pantai Sempadan","海岸を散歩する (kaigan o sanpo suru = santai menyusuri tepian pantai), 対岸 (taigan = daratan seberang tepi)","Alam & Tempat"],
  ["礼","レイ, ライ","rei, rai","Tata Krama Sopan Santun / Terima Kasih","お礼を述べる (orei o noberu = menghaturkan terima kasih tulus), 礼儀正しく (reigitadashiku = bersopan santun luhur)","Sikap"],
  ["儀","ギ","gi","Upacara Sakral / Protokoler Etiket","儀式を執り行う (gishiki o toriokonau = memimpin prosesi upacara sakral), マナーと礼儀 (manaa to reigi = adab tata krama)","Sikap"],
  ["敬","ケイ / うやま-う","kei / uyama-u","Menghormati Takzim Santun","敬語を使う (keigo o tsukau = berbicara dengan ragam bahasa keigo sopan), 敬意を表する (keii o hyousuru = menaruh takzim luhur)","Sikap"],
  ["勤","キン, ゴン / つと-める","kin / tsuto-meru","Bekerja Dinas / Rajin Tekun","通勤ラッシュ (tsuukin rasshu = jam sibuk mobilitas pekerja dinas), 勤勉 (kinben = dedikasi tekun ulet)","Sikap"],
  ["勉","ベン / つと-める","ben / tsuto-meru","Berusaha Keras / Tekun","勉学に励む (bengaku ni hagemu = bersungguh-sungguh mendalami studi), 勉強 (benkyou = belajar mengasah ilmu)","Sikap"],
  ["望","ボウ, モウ / のぞ-む","bou / nozo-mu","Mengharapkan Cita / Memandang Jauh","希望の光 (kibou no hikari = lentera pelita harapan asa), 望み (nozomi = impian cita-cita luhur)","Sikap"],
  ["志","シ / こころざ-す, こころざし","shi / kokorozashi","Tekad Batin Cita Mulia","高い志を抱く (takai kokorozashi o idaku = menyematkan tekad cita luhur nan mulia), 志望動機 (shibou douki = motivasi melamar jurusan)","Sikap"],
  // Lingkungan, Wilayah & Kemasyarakatan
  ['都', 'ト, ツ / みやこ', 'to, tsu / miyako', 'Metropolis / Ibu Kota', '東京都 (Toukyou-to = Metropolis Tokyo), 都会 (tokai = kawasan perkotaan metropolitan modern)', 'Lingkungan'],
  ['府', 'フ', 'fu', 'Prefektur Urban Istimewa', '大阪府 (Oosaka-fu = Prefektur Osaka), 京都府 (Kyouto-fu = Prefektur Kyoto)', 'Lingkungan'],
  ['県', 'ケン', 'ken', 'Prefektur / Provinsi Daerah', '県庁 (kenchou = kantor gubernur pusat prefektur), 県知事 (kenchiji = gubernur kepala daerah)', 'Lingkungan'],
  ['区', 'ク', 'ku', 'Kecamatan / Distrik Kota', '区役所 (kuyakusho = kantor camat distrik pemda), 区分 (kubun = pemilahan kategorisasi)', 'Lingkungan'],
  ['民', 'ミン / たみ', 'min / tami', 'Rakyat / Warga Penduduk', '市民 (shimin = warga kota madya), 民主主義 (minshushugi = asas demokrasi kedaulatan)', 'Sosial'],
  ['建', 'ケン / た-てる, た-つ', 'ken / ta-teru', 'Mendirikan / Gedung Struktur', '建物を建てる (tatemono o tateru = mendirikan bangunan kokoh), 建設 (kensetsu = konstruksi rancang bangun)', 'Lingkungan'],
  ['築', 'チク / きず-く', 'chiku / kizu-ku', 'Membangun / Konstruksi Arsitektur', '建築家 (kenchikuka = arsitek perancang), 信頼関係を築く (shinraikankei o kizuku = membangun relasi saling percaya)', 'Lingkungan'],
  ['宅', 'タク', 'taku', 'Rumah Tinggal / Kediaman', '住宅 (juutaku = kawasan kompleks hunian perumahan), 自宅 (jitaku = rumah tempat tinggal pribadi)', 'Lingkungan'],
  ['居', 'キョ / い-る', 'kyo / i-ru', 'Berdiam / Menghuni Ruang', '居間 (ima = ruang santai keluarga), 居眠り (inemuri = tertidur pulas sejenak)', 'Lingkungan'],
  ['宿', 'シュク / やど, やど-る', 'shuku / yado', 'Penginapan / Menginap Malam', '宿泊する (shukuhaku suru = menginap di hotel), 宿題 (shukudai = tugas pekerjaan rumah PR)', 'Lingkungan'],
  ['街', 'ガイ, カイ / まち', 'gai / machi', 'Jalan Raya / Pusat Kota Pertokoan', '商店街 (shoutengai = deretan pertokoan niaga), 街頭 (gaitou = tepi jalan raya umum)', 'Lingkungan'],
  ['郊', 'コウ', 'kou', 'Pinggiran Kota / Suburb', '郊外 (kougai = kawasan asri suburban luar kota), 近郊 (kinkou = daerah penyangga kota)', 'Lingkungan'],
  ['域', 'イキ', 'iki', 'Zona / Wilayah Teritorial', '地域 (chiiki = komunitas regional lokal), 区域 (kuiki = tapal batas zona wilayah)', 'Lingkungan'],
  ['境', 'キョウ, ケイ / さかい', 'kyou / sakai', 'Perbatasan / Batas Wilayah', '国境 (kokkyou = garis perbatasan negara), 環境 (kankyou = kondisi lingkungan hidup)', 'Lingkungan'],
  ['環', 'カン / わ', 'kan / wa', 'Lingkaran / Melingkari Dunia', '環境保護 (kankyou hogo = pelestarian lingkungan hidup), 環状線 (kanjousen = jalur kereta melingkar)', 'Lingkungan'],

  // Pendidikan, Sains, Kebudayaan & Pemikiran
  ['文', 'ブン, モン / ふみ', 'bun / fumi', 'Sastra / Alinea / Kebudayaan', '文学 (bungaku = ilmu kesusastraan), 文章 (bunshou = teks bacaan alinea paragraf)', 'Pendidikan'],
  ['化', 'カ, ケ / ば-ける', 'ka / ba-keru', 'Mengubah / Berubah / -isasi', '文化 (bunka = kebudayaan kearifan), 変化 (henka = evolusi pergeseran perubahan)', 'Pendidikan'],
  ['科', 'カ', 'ka', 'Disiplin Ilmu / Cabang Bidang', '科学 (kagaku = sains keilmuan alam), 教科書 (kyoukasho = buku pegangan kurikulum resmi)', 'Pendidikan'],
  ['技', 'ギ / わざ', 'gi / waza', 'Teknik / Keterampilan Piawai', '技術 (gijutsu = kehandalan rekayasa teknologi), 特技 (tokugi = kemahiran bakat istimewa)', 'Pendidikan'],
  ['術', 'ジュツ', 'jutsu', 'Keahlian Olah Seni / Trik', '手術 (shujutsu = tindakan bedah operasi medis), 美術館 (bijutsukan = gedung museum karya seni)', 'Pendidikan'],
  ['表', 'ヒョウ / あらわ-す, おもて', 'hyou / arawa-su, omote', 'Mengekspresikan / Tabel Bagan', '研究発表 (kenkyuuhappyou = pemaparan riset tesis), 表 (omote = permukaan sisi depan)', 'Pendidikan'],
  ['解', 'カイ, ゲ / と-く, と-ける', 'kai / to-ku', 'Memecahkan Solusi / Mengurai', '解説 (kaisetsu = kupasan ulasan mendalam), 理解 (rikai = pemahaman menyerap konsep)', 'Pendidikan'],
  ['釈', 'シャク', 'shaku', 'Menjelaskan / Tafsir Makna Teks', '解釈 (kaishaku = interpretasi penafsiran ayat makna), 注釈 (chuushaku = penjelasan catatan kaki)', 'Pendidikan'],
  ['講', 'コウ', 'kou', 'Kuliah / Menjabarkan Ceramah', '講義 (kougi = kuliah tatap muka dosen), 講演会 (kouenkai = seminar simposium orasi)', 'Pendidikan'],
  ['義', 'ギ', 'gi', 'Keadilan / Kebajikan Luhur / Makna', '義務 (gimu = beban tanggung jawab kewajiban), 正義 (seigi = keadilan hakiki merata)', 'Sikap'],
  ['授', 'ジュ / さず-ける', 'ju / sazu-keru', 'Menganugerahi / Memberi Pelajaran', '授業 (jugyou = proses belajar mengajar kelas), 教授 (kyouju = guru besar profesor)', 'Pendidikan'],
  ['業', 'ギョウ, ゴウ / わざ', 'gyou / waza', 'Usaha Industri / Karya Pekerjaan', '卒業 (sotsugyou = kelulusan wisuda sarjana), 工業 (kougyou = sektor industri manufaktur)', 'Pendidikan & Bisnis'],
  ['論', 'ロン', 'ron', 'Teori Argumentasi / Risalah Tesis', '論文 (ronbun = naskah skripsi tesis ilmiah), 結論 (ketsuron = konklusi intisari akhir)', 'Pendidikan'],
  ['訳', 'ヤク / わけ', 'yaku / wake', 'Terjemahan Alih Bahasa / Alasan', '翻訳 (hon\'yaku = terjemahan teks literatur), 通訳 (tsuuyaku = juru alih bahasa lisan interpreter)', 'Pendidikan'],
  ['専', 'セン / もっぱ-ら', 'sen / moppa-ra', 'Khusus / Spesialis Mendalam', '専門家 (senmonka = pakar ahli spesialis), 専攻 (senkou = program studi jurusan)', 'Pendidikan'],
  ['歴', 'レキ', 'reki', 'Jejak Masa Silam / Melintasi Zaman', '歴史 (rekishi = lembaran sejarah peradaban), 経歴 (keireki = rekam jejak portofolio karir)', 'Pendidikan'],
  ['史', 'シ', 'shi', 'Catatan Sejarah / Kronik Berita', '世界史 (sekaishi = sejarah peradaban dunia), 史学 (shigaku = disiplin ilmu historiografi)', 'Pendidikan'],

  // Sikap, Moral, Integritas & Emosi N3
  ['信', 'シン', 'shin', 'Kepercayaan / Sinyal Telekomunikasi', '信頼 (shinrai = amanah kepercayaan teguh), 信用 (shinyou = reputasi kredibilitas bonafide)', 'Sikap'],
  ['頼', 'ライ / たの-む, たよ-る', 'rai / tano-mu, tayo-ru', 'Mengandalkan / Memohon Bantuan', '頼もしい仲間 (tanomoshii nakama = sahabat handal tangguh), 頼む (tanomu = memesan/meminta tolong)', 'Sikap'],
  ['尊', 'ソン / とうと-ぶ', 'son / touto-bu', 'Menghormati Takzim / Mulia Luhur', '尊敬する (sonkei suru = menaruh hormat kagum), 自尊心 (jisonshin = martabat harga diri)', 'Sikap'],
  ['厳', 'ゲン, ゴン / きび-しい', 'gen / kibi-shii', 'Disiplin Ketat / Tegas Bersahaja', '厳しい訓練 (kibishii kunren = tempaan latihan disiplin ketat), 厳格 (genkaku = aturan baku kaku)', 'Sikap'],
  ['誠', 'セイ / まこと', 'sei / makoto', 'Ketulusan Kalbu / Kejujuran Hakiki', '誠実な人柄 (seijitsu na hitogara = pribadi tulus jujur bersahaja), 誠意 (seii = itikad baik tulus)', 'Sikap'],
  ['実', 'ジツ / み, みの-る', 'jitsu / mi', 'Kenyataan Riil / Buah Hasil', '実験 (jikken = riset uji coba empiris), 実現 (jitsugen = cita-cita mewujud nyata)', 'Kualitas'],
  ['勇', 'ユウ / いさ-む', 'yuu / isa-mu', 'Keberanian Gagah Perwira', '勇気 (yuuki = keteguhan nyali keberanian), 勇者 (yuusha = ksatria pahlawan perkasa)', 'Sikap'],
  ['責', 'セキ / せ-める', 'seki / se-meru', 'Tanggung Jawab Beban / Menyalahkan', '責任感 (sekininkan = rasa tanggung jawab amanah), 責める (semeru = mencerca menyalahkan pihak)', 'Sikap'],
  ['任', 'ニン / まか-せる', 'nin / maka-seru', 'Menyerahkan / Mandat Amanah Tugas', '任務を果たす (ninmu o hatasu = menuntaskan mandat amanah), 担任 (tannin = wali kelas asuh)', 'Sikap'],
  ['務', 'ム / つと-める', 'mu / tsuto-meru', 'Tugas Pekerjaan Dinas / Berusaha', '公務 (koumu = dinas pelayanan kedinasan negara), 勤務先 (kinmusaki = alamat tempat kantor dinas)', 'Pekerjaan'],
  ['優', 'ユウ / やさ-しい, すぐ-れる', 'yuu / yasa-shii, sugu-reru', 'Unggul Prestasi / Lembut Ramah', '優しい笑顔 (yasashii egao = senyum ramah menenteramkan), 優秀 (yuushuu = luar biasa gemilang)', 'Kualitas'],
  ['秀', 'シュウ / ひい-でる', 'shuu / hii-deru', 'Menonjol Prestasi / Cemerlang Elit', '秀才 (shuusai = sosok intelektual berbakat), 優秀賞 (yuushoushou = anugerah gelar terbaik)', 'Kualitas'],
  ['良', 'リョウ / よ-い', 'ryou / yo-i', 'Bagus Prima / Mutu Terbaik', '良好な健康 (ryoukou na kenkou = kondisi raga sangat prima), 改良 (kairyou = inovasi perbaikan mutu)', 'Kualitas'],
  ['悪', 'アク, オ / わる-い', 'aku / waru-i', 'Buruk Rusak / Jahat Buruk', '最悪の事態 (saiaku no jitai = skenario terburuk krisis), 悪口 (warukuchi = caci maki gunjingan)', 'Kualitas'],
  ['完', 'カン', 'kan', 'Sempurna / Tuntas Tergarap', '完成品 (kanseihin = produk jadi tuntas terakit), 完全無欠 (kanzen muketsu = sempurna tanpa cela sedikitpun)', 'Kualitas'],
  ['全', 'ゼン / すべ-て', 'zen / sube-te', 'Seluruh Jagat / Utuh Segenap', '全員集合 (zen\'in shuugou = segenap hadirin berkumpul lengkap), 安全確認 (anzen kakunin = kroscek proteksi keselamatan)', 'Kualitas'],
  ['非', 'ヒ', 'hi', 'Bukan / Ekstrim / Keliru Cela', '非常口 (hijouguchi = pintu darurat tangga evakuasi), 非難 (hinan = kecaman teguran tajam)', 'Kualitas'],
  ['常', 'ジョウ / つね', 'jou / tsune', 'Biasa Lazim / Rutin Lestari', '日常会話 (nichijou kaiwa = percakapan santai sehari-hari), 正常運転 (seijou unten = perjalanan armada beroperasi normal)', 'Kualitas'],
  ['要', 'ヨウ / い-る', 'you / i-ru', 'Memerlukan / Pokok Esensial Krusial', '必要不可欠 (hitsuyou fukaketsu = keniscayaan mutlak esensial), 重要事項 (juuyou jikou = klausul butir penting)', 'Kualitas'],

  // Transaksi, Manajemen & Ekonomi N3
  ['続', 'ゾク / つづ-く, つづ-ける', 'zoku / tsuzu-ku, tsuzu-keru', 'Berlanjut Menyambung / Kontinu', '継続は力なり (keizoku wa chikara nari = konsistensi berkesinambungan adalah kunci ketangguhan)', 'Kata Kerja'],
  ['承', 'ショウ / うけたまわ-る', 'shou / uketamawa-ru', 'Menerima Menyetujui Taat', '承認を受ける (shounin o ukeru = mengantongi persetujuan izin resmi), 承知 (shouchi = siap paham mengerti)', 'Kata Kerja'],
  ['認', 'ニン / みと-める', 'nin / mito-meru', 'Mengakui Sah / Menilai Layak', '確認する (kakunin suru = memeriksa kroscek kepastian), 認可 (ninka = lisensi otorisasi sah)', 'Kata Kerja'],
  ['許', 'キョ / ゆる-す', 'kyo / yuru-su', 'Mengizinkan / Mengampuni Maaf', '許可証 (kyokashou = lembar surat izin edar resmi), 許す (yurusu = memaafkan kekeliruan)', 'Kata Kerja'],
  ['可', 'カ', 'ka', 'Boleh Layak / Memungkinkan', '可能性が高い (kanousei ga takai = potensi terwujud sangat tinggi), 不可解 (fukakai = sukar dimengerti ganjil)', 'Konsep'],
  ['支', 'シ / ささ-える', 'shi / sasa-eru', 'Menopang Dukung / Membayar / Cabang', '支払いを済ませる (shiharai o sumaseru = melunasi pembayaran belanja), 支店 (shiten = kantor cabang bank)', 'Ekonomi'],
  ['払', 'フツ / はら-う', 'futsu / hara-u', 'Membayar Lunas / Mengibaskan', '代金を支払う (daikin o shiharau = menyetor tagihan total biaya), 払戻金 (haraimodoshikin = uang pengembalian dana refund)', 'Ekonomi'],
  ['受', 'ジュ / う-ける', 'ju / u-keru', 'Menerima Sambut / Menghadapi Ujian', '試験を受ける (shiken o ukeru = menempuh ujian kelulusan), 受付窓口 (uketsuke madoguchi = loket bagian pendaftaran resepsionis)', 'Kata Kerja'],
  ['取', 'シュ / と-る', 'shu / to-ru', 'Mengambil Peroleh / Merengkuh', '予約を取る (yoyaku o toru = memesan reservasi tempat), 取引先 (torihikisaki = mitra relasi bisnis niaga)', 'Kata Kerja'],
  ['販', 'ハン', 'han', 'Memasarkan / Menjual Niaga', '販売促進 (hanbai sokushin = promosi akselerasi penjualan omset), 自動販売機 (jidouhanbaiki = mesin penjaja otomatis)', 'Ekonomi'],
  ['購', 'コウ', 'kou', 'Membeli Aset Transaksi Resmi', '商品を購入する (shouhin o kounyuu suru = membeli produk komoditas), 購買部 (koubaibu = divisi pengadaan barang inventaris)', 'Ekonomi'],

  // Alam Semesta, Lanskap & Maritim N3
  ['海', 'カイ / うみ', 'kai / umi', 'Laut Samudra Samudera', '日本海 (Nihonkai = Laut Jepang membentang), 海岸線 (kaigan sen = garis pesisir pantai nan molek)', 'Alam'],
  ['森', 'シン / もり', 'shin / mori', 'Hutan Rimbun Lebat Kanopi', '深い森 (fukai mori = belantara rimba lebat rimbun), 森林浴 (shinrinyoku = terapi menyegarkan jiwa di kanopi hutan)', 'Alam'],
  ['林', 'リン / はやし', 'rin / hayashi', 'Hutan Muda / Rimba Bambu', '雑木林 (zoubayashi = hutan pepohonan muda), 林業 (ringyou = industri tata kelola perkayuan kehutanan)', 'Alam'],
  ['太', 'タイ, タ / ふと-い', 'tai / futo-i', 'Tebal / Agung Perkasa', '太陽の恵み (taiyou no megumi = berkah anugerah surya matahari), 太平洋 (taiheiyou = Samudra Pasifik terbentang)', 'Alam'],
  ['陽', 'ヨウ', 'you', 'Sinar Surya Hangat Terang', '陽光を浴びる (youkou o abiru = bermandikan hangat sinar mentari fajar), 陽気 (youki = keceriaan hati semringah)', 'Alam'],
  ['星', 'セイ, ショウ / ほし', 'sei / hoshi', 'Bintang Gemerlap Antariksa', '夜空の満天の星 (yozora no manten no hoshi = taburan bintang gemerlap langit malam), 惑星探索 (wakusei tansaku = ekspedisi planet angkasa)', 'Alam'],
  ['雲', 'ウン / くも', 'un / kumo', 'Awan Berarak Angkasa', '白い雨雲 (shiroi amagumo = gumpalan awan mendung menggelantung), 青空に浮かぶ雲 (aozora ni ukabu kumo = awan berarak di langit biru)', 'Alam'],
  ['波', 'ハ / なみ', 'ha / nami', 'Gelombang Ombak / Frekuensi Riak', '穏やかな波 (odayaka na nami = deburan ombak laut tenang membelai), 電波状況 (denpa joukyou = penerimaan sinyal frekuensi)', 'Alam'],
  ['潮', 'チョウ / しお', 'chou / shio', 'Pasang Surut Air Samudra', '潮の流れ (shio no nagare = arus sirkulasi pasang air laut), 満潮の時刻 (manchou no jikoku = jadwal puncak pasang air laut)', 'Alam'],
  ['流', 'リュウ, ル / なが-れる, なが-す', 'ryuu / naga-reru, naga-su', 'Mengalir Arus / Aliran Mazhab', '大河が流れる (taiga ga nagareru = sungai besar mengalir megah), 流行の最先端 (ryuukou no saisentan = garis terdepan tren viral populer)', 'Alam'],
];

// =========================================================================
// JLPT N2 (200+ KANJI LANJUTAN RESMI - NO OVERLAP WITH N5, N4, OR N3)
// =========================================================================
const KANJI_N2 = [
  ["識","シキ","shiki","Wawasan Intelektual / Kesadaran","専門知識 (senmon chishiki = penguasaan wawasan spesialis), 意識 (ishiki = alam kesadaran nurani)","Konsep"],
  ["態","タイ","tai","Sikap Bahasa Tubuh / Situasi Dinamika","事態の推移 (jitai no suii = dinamika bergulirnya situasi perkara), 態度 (taido = tata krama sikap perangai)","Sosial"],
  ["察","サツ","satsu","Menelaah Menduga / Mengamati Cermat","警察官 (keisatsukan = aparat penegak kepolisian), 観察 (kansatsu = observasi pengamatan seksama)","Sosial"],
  ["拡","カク / ひろ-がる, ひろ-げる","kaku / hiro-geru","Memperluas Ekspansi / Melebar","事業規模の拡大 (jigyou kibo no kakudai = ekspansi perluasan skala bisnis), 拡散 (kakusan = penyebaran gaung viral)","Ekonomi"],
  ["批","ヒ","hi","Mengkritisi / Menguji Telaah Tajam","鋭い批判 (surudoi hinan = kritik telaah tajam objektif), 批評家 (hihyouka = pakar kritikus karya seni)","Konsep"],
  ["裁","サイ / さば-く, た-つ","sai / saba-ku","Mengadili Perkara / Memutuskan Vonis","裁判所 (saibansho = gedung pengadilan meja hijau), 判定を下す裁量 (hantei o kudasu sairyou = wewenang diskresi putusan)","Sosial"],
  ["判","ハン, バン","han, ban","Menilai Menimbang / Cap Stempel Sah","客観的判断 (kyakkanteki handan = penilaian pertimbangan objektif), 判決 (hanketsu = ketetapan amar vonis hakim)","Sosial"],
  ["拠","キョ, コ / よ-る","kyo / yo-ru","Berpijak / Bukti Otentik Basis","明確な証拠 (meikaku na shouko = alat bukti otentik tak terbantahkan), 根拠 (konkyo = dasar pijakan dalil nalar)","Konsep"],
  ["貿","ボウ","bou","Perdagangan Transnasional Ekspor Impor","自由貿易体制 (jiyuu boueki taisei = rezim perdagangan pasar bebas global), 貿易黒字 (boueki kuroji = surplus neraca dagang ekspor)","Ekonomi"],
  ["障","ショウ / さわ-る","shou / sawa-ru","Rintangan Halangan / Hambatan Kendala","障害物を乗り越える (shougaibutsu o norikoeru = melompati rintangan aral melintang), 保障 (hoshou = jaminan proteksi)","Sosial"],
  ["害","ガイ","gai","Kerusakan / Dampak Cidera Mudharat","環境破壊の公害 (kankyou hakai no kougai = polusi pencemaran lingkungan), 損害 (songai = kerugian materiil)","Sosial"],
  ["衛","エイ","ei","Menjaga Pertahanan / Sanitasi Higienis","衛生管理 (eisei kanri = manajemen tata kelola sanitasi kebersihan), 衛星放送 (eisei housou = siaran televisi parabola satelit)","Sosial"],
  ["憲","ケン","ken","Konstitusi Negara / Hukum Dasar Tertinggi","日本国憲法 (Nihonkoku Kenpou = Undang-Undang Dasar Konstitusi Jepang), 立憲主義 (rikkenshugi = paham konstitusionalisme bernegara)","Sosial"],
  ["章","ショウ","shou","Pasal Klausul / Lencana Bintang Kehormatan","序章の幕開け (joshou no makuake = pembuka babak pendahuluan bab), 勲章 (kunshou = lencana bintang tanda jasa kehormatan)","Sosial"],
  ["訴","ソ / うった-える","so / utta-eru","Menggugat Perkara / Mengadukan Keluh","裁判所に訴える (saibansho ni uttaeru = melayangkan gugatan perdata ke pengadilan), 訴訟 (soshou = perkara persidangan meja hijau)","Sosial"],
  ["審","シン / つまび-らか","shin","Pemeriksaan Sidang / Telaah Meneliti","厳正な審査 (gensei na shinsa = tahapan audit verifikasi seleksi ketat), 審議 (shingi = musyawarah telaah mendalam)","Sosial"],
  ["罰","バツ, バチ","batsu","Hukuman Sanksi Pidana / Ganjar Cela","処罰の対象 (shobatsu no taishou = subjek target sanksi hukuman pidana), 罰金を納付する (bakkin o noufu suru = melunasi denda hukum administratif)","Sosial"],
  ["財","ザイ, サイ","zai","Harta Kekayaan / Anggaran Keuangan Fiskal","国家財政 (kokka zaisei = struktur perbendaharaan fiskal kas negara), 財産 (zaisan = aset kekayaan perbendaharaan)","Ekonomi"],
  ["融","ユウ / と-ける","yuu","Melebur / Kucuran Likuiditas Dana","金融機関 (kin'yuu kikan = lembaga institusi perbankan finansial), 融資を募る (yuushi o tsunoru = menggalang kucuran pinjaman investasi modal)","Ekonomi"],
  ["債","サイ","sai","Surat Utang Obligasi / Liabilitas Pinjaman","国債の発行 (kokusai no hakkou = penerbitan obligasi surat utang negara), 負債 (fusai = beban liabilitas neraca hutang)","Ekonomi"],
  ["株","シュ / かぶ","shu / kabu","Saham Kepemilikan / Tunggul Pangkal","株式会社 (kabushiki gaisha = perseroan terbatas PT terbuka), 株主総会 (kabunushi soukai = rapat umum pemegang saham RUPS)","Ekonomi"],
  ["替","タイ / か-える, か-わる","tai / ka-eru","Menukar Kurs / Berganti Ganti","外国為替相場 (gaikoku kawase souba = dinamika kurs valuta asing pasar uang), 両替 (ryougae = penukaran valas mata uang)","Ekonomi"],
  ["雇","コ / やと-う","ko / yato-u","Mempekerjakan Karyawan / Rekrutmen","優秀な人材を雇用する (yuushuu na jinzai o koyou suru = merekrut talenta tenaga kerja berprestasi), 解雇 (kaiko = pemutusan hubungan kerja PHK)","Ekonomi"],
  ["労","ロウ","rou","Banting Tulang Jerih Payah / Ketenagakerjaan","労働条件の改善 (roudou jouken no kaizen = perbaikan taraf kesejahteraan iklim kerja), 苦労 (kurou = jerih payah perjuangan hidup)","Ekonomi"],
  ["賃","チン","chin","Upah Gaji / Biaya Sewa Kontrak","賃金の上昇 (chingin no joushou = kenaikan indeks upah penghasilan), 家賃 (yachin = biaya iuran sewa hunian rumah)","Ekonomi"],
  ["織","ショク, シキ / お-る","shoku / o-ru","Menenun Merajut / Struktur Organisasi","組織の結束を固める (soshiki no kessoku o katameru = memperkokoh soliditas struktur organisasi), 織物 (orimono = kain tenun rajutan)","Hubungan"],
  ["企","キ / くわだ-てる","ki / kuwada-teru","Merancang Gagasan / Entitas Perusahaan","革新的な企画 (kakushinteki na kikaku = proposal terobosan inovatif), 企業 (kigyou = entitas dunia usaha korporasi)","Ekonomi"],
  ["統","トウ / す-べる","tou","Menyatukan Kendali / Memimpin Sistematis","統率力を発揮する (tousotsuryoku o hakki suru = unjuk taring kepemimpinan komando), 統一 (touitsu = penyatuan persatuan utuh)","Sosial"],
  ["括","カツ / くく-る","katsu / kuku-ru","Merangkum / Mengikat Satu Kesatuan","全体を総括する (zentai o soukatsu suru = merangkum telaah evaluasi komprehensif), 一括 (ikkatsu = pembayaran tunai sekaligus)","Sosial"],
  ["指","シ / ゆび, さ-す","shi / yubi, sa-su","Jari Tangan / Menunjuk Arah Membimbing","指導教員 (shidou kyouin = dosen pembimbing skripsi akademik), 指摘 (shiteki = penunjukan koreksi evaluasi)","Hubungan"],
  ["揮","キ / ふ-る","ki / fu-ru","Mengayunkan Komando / Memancarkan Aura","指揮官 (shikikan = jenderal panglima komando lapangan), 発揮 (hakki = mengeluarkan unjuk potensi terbaik)","Hubungan"],
  ["監","カン","kan","Mengawasi Menginspeksi / Supervisi Audit","監査役 (kansayaku = dewan komisaris pengawas audit), 監督 (kantoku = sutradara / pelatih kepala regu)","Pekerjaan"],
  ["督","トク","toku","Memerintahkan / Mendorong Tegas","監督不行き届き (kantoku fuyukitodoki = kelalaian pengawasan komando), 督促 (tokusoku = peringatan penagihan tegas)","Pekerjaan"],
  ["評","ヒョウ","hyou","Menilai Mengulas / Komentar Review","高い評価を得る (takai hyouka o eru = panen apresiasi penilaian prestisius), 評判 (hyouban = buah bibir reputasi harum)","Konsep"],
  ["念","ネン","nen","Perhatian Kalbu / Doa Keinginan Batin","理念 (rinen = prinsip asas falsafah ideologi luhur), 念願が叶う (nengan ga kanau = hajat doa batin terkabul)","Konsep"],
  ["傾","ケイ / かたむ-く, かたむ-ける","kei / katamu-ku","Condong Miring / Menumpahkan Fokus","耳を傾ける (mimi o katamukeru = menyimak dengan segenap perhatian kalbu), 傾向 (keikou = tren kecenderungan arah)","Konsep"],
  ["向","コウ / む-く, む-かう","kou / mu-kau","Menghadap Menuju / Arah Haluan","前を向いて進む (mae o muite susumu = melangkah maju menatap cakrawala esok), 方向 (houkou = arah kompas haluan)","Konsep"],
  ["縮","シュク / ちぢ-む, ちぢ-める","shuku / chiji-mu","Menyusut Ramping / Memperpendek Jarak","距離を縮める (kyori o chijimeru = merapatkan jarak jurang silaturahmi), 縮小 (shukushou = pemangkasan ramping)","Konsep"],
  ["促","ソク / うなが-す","soku / unaga-su","Mendorong Mengimbau / Mempercepat Laju","注意を促す (chuui o unagasu = mengimbau himbauan waspada), 促進 (sokushin = akselerasi promosi stimulus)","Konsep"],
  ["抑","ヨク / おさ-える","yoku / osa-eru","Menekan Meredam / Mengendalikan Emosi","費用を抑制する (hiyou o yokusei suru = meredam lonjakan beban pembengkakan anggaran), 感情を抑える (kanjou o osaeru = menahan emosi amarah)","Konsep"],
  ["撤","テツ","tetsu","Menarik Mundur / Menghapus Ketetapan","方針を撤回する (houshin o tekkai suru = mencabut membatalkan garis haluan kebijakan), 撤退 (tettai = penarikan mundur armada pasukan)","Sosial"],
  ["退","タイ / しりぞ-く, のぞ-く","tai / shirizo-ku","Mundur / Pensiun Meletakkan Jabatan","定年退職 (teinen taishoku = purnatugas pensiun masa pengabdian), 後退 (koutai = langkah mundur perlambatan)","Sosial"],
  ["採","サイ / と-る","sai / to-ru","Memilih Memetik / Mengadopsi Strategi","新たな手法を採用する (arata na shuhou o saiyou suru = mengadopsi pendekatan metode mutakhir), 採点 (saiten = penilaian skor nilai)","Pekerjaan"],
  ["択","タク","taku","Memilih Menyeleksi Di Antara Pilihan","選択肢 (sentakushi = butir opsi alternatif pilihan nalar), 二者択一 (nishatakuitsu = memilih satu di antara dua opsi sulit)","Konsep"],
  ["緩","カン / ゆる-い, ゆる-む","kan / yuru-mu","Melonggarkan Relaksasi / Reda Kendur","金融緩和政策 (kin'yuu kanwa seisaku = kebijakan stimulus pelonggaran moneter likuiditas), 緩やか (yuruyaka = landai lembut perlahan)","Ekonomi"],
  ["提","テイ / さ-げる","tei / sa-geru","Mengajukan Usulan / Menjinjing Mengangkat","業務提携 (gyoumu teikei = aliansi kemitraan strategis antarperusahaan), 提案 (teian = usulan inisiatif gagasan)","Hubungan"],
  ["携","ケイ / たずさ-える","kei / tazusa-eru","Bergandengan Tangan / Terlibat Terpadu","携帯電話 (keitaidenwa = telepon seluler genggam portabel), 連携 (renkei = jalinan kolaborasi sinergi)","Hubungan"],
  ["破","ハ / やぶ-る, やぶ-れる","ha / yabu-reru","Runtuh Robek / Memecahkan Rekor","世界新記録を破る (sekai shin kiroku o yaburu = memecahkan rekor torehan dunia), 破産 (hasan = kebangkrutan kepailitan total)","Ekonomi"],
  ["産","サン / う-む, う-まれる","san / u-mu","Melahirkan Menghasilkan / Produk Industri","特産品 (tokusanhin = komoditas unggulan lokal khas daerah), 産業 (sangyou = denyut nadi sektor perindustrian)","Ekonomi"],
  ["範","ハン","han","Cakupan Batas / Teladan Baku Panutan","適用範囲 (tekiyou han'i = spektrum cakupan ruang lingkup penerapan), 模範 (mohan = keteladanan suri tauladan luhur)","Konsep"],
  ["囲","イ / かこ-む, かこ-う","i / kako-mu","Mengepung Mengelilingi / Lingkaran Pagar","自然に囲まれた環境 (shizen ni kakomareta kankyou = lingkungan asri terpagari panorama alam raya), 周囲 (shuui = sekeliling lingkar)","Konsep"],
  ["倫","リン","rin","Etika Akhlak / Kepatutan Kemanusiaan","職業倫理の遵守 (shokugyou rinri no junshu = ketaatan menjunjung kode etik profesionalisme), 倫理観 (rinrikan = kompas moralitas nurani)","Sosial"],
  ["遵","ジュン","jun","Tunduk Patuh Taat Garis Aturan","法令遵守 (hourei junshu = kepatuhan ketaatan hukum korporasi compliance)","Sosial"],
  ["契","ケイ / ちぎ-る","kei / chigi-ru","Akad Perjanjian Ikatan / Meneken Janji","正式な契約を締結する (seishiki na keiyaku o teiketsu suru = meneken penandatanganan akad kontrak resmi), 契機 (keiki = momentum titik tolak balik)","Sosial"],
  ["約","ヤク","yaku","Janji Ikrar / Sekitar Kurang Lebih","約束を果たす (yakusoku o hatasu = menuntaskan ikrar janji suci), 予約 (yoyaku = pemesanan registrasi tempat reservasi)","Sosial"],
  ["処","ショ","sho","Mengambil Tindakan / Mengelola Menangani","適切な処理 (tekisetsu na shori = penanganan pemrosesan prosedur yang tepat), 処置 (shochi = tindakan penanganan medis pertolongan)","Konsep"],
  ["応","オウ / こた-える","ou / kota-eru","Merespons Cepat / Memenuhi Permintaan","要請に応じる (yousei ni oujiru = memenuhi gayung sambut permohonan amanah), 応援 (ouen = sorak dukungan semangat)","Hubungan"],
  ["募","ボ / つの-る","bo / tsuno-ru","Merekrut Menggalang / Berkobar Emosi","ボランティアを募集する (borantia o boshuu suru = membuka rekrutmen pendaftaran sukarelawan kemanusiaan), 応募 (oubo = pengajuan lamaran karir)","Pekerjaan"],
  ["履","リ / は-く","ri / ha-ku","Melangkah Mengenakan / Rekam Jejak","履歴書を提出する (rirekisho o teishutsu suru = mengirimkan berkas riwayat hidup CV), 履修 (rishuu = pengambilan satuan kredit semester)","Pekerjaan"],
  ["昇","ショウ / のぼ-る","shou / nobo-ru","Naik Pangkat Terbit / Menanjak Karir","管理職に昇進する (kanrishoku ni shoushin suru = promosi naik jenjang pimpinan manajerial), 昇給 (shoukyuu = kenaikan tangga upah tunjangan)","Pekerjaan"],
  ["進","シン / すす-む, すす-める","shin / susu-mu","Maju Melangkah / Mengembangkan Akselerasi","前進あるのみ (zenshin aru nomi = pantang surut melangkah maju ke depan), 進歩 (shinpo = lompatan kemajuan peradaban)","Konsep"],
  ["転","テン / ころ-がる, ころ-ぶ","ten / koro-bu","Berputar Berpindah / Jatuh Terguling","自転車 (jitensha = sepeda kayuh kayuhan), 転勤 (tenkin = rotasi mutasi dinas tugas ke cabang lain)","Pekerjaan"],
  ["派","ハイ","hai","Mengutus Delegasi / Mazhab Golongan Kubu","専門家を派遣する (senmonka o haken suru = mengutus penugasan pakar delegasi khusus), 派閥 (habatsu = faksi kubu kelompok internal)","Sosial"],
  ["遣","ケン / つか-う, つか-わす","ken / tsuka-u","Mengirimkan Utusan / Menggunakan Batin","派遣社員 (hakenshain = staf tenaga kerja alih daya outsourcing), 気遣い (kizukai = perhatian tenggang rasa empati santun)","Pekerjaan"],
  ["修","シュウ / おさ-める","shuu / osa-meru","Menuntut Ilmu Tempaan / Reparasi Benahi","研修を修了する (kenshuu o shuuryou suru = tuntas lulus menempuh diklat pembekalan), 修理 (shuuri = reparasi servis perbaikan)","Pendidikan"],
  ["了","リョウ","ryou","Selesai Tuntas Paripurna / Memahami","全行程が完了する (zen koutei ga kanryou suru = segenap tahapan selesai tuntas paripurna), 了解 (ryoukai = siap paham dimengerti)","Konsep"],
  // Sosial, Politik, Tata Kelola & Kebijakan
  ['政', 'セイ, ショウ / まつりごと', 'sei, shou', 'Pemerintahan / Urusan Kenegaraan', '政治体制 (seiji taisei = sistem perpolitikan tata negara), 政策提言 (seisaku teigen = usulan rekomendasi kebijakan)', 'Sosial'],
  ['治', 'ジ, チ / おさ-める, なお-る', 'ji, chi / osa-meru, nao-ru', 'Memerintah Tata / Pulih Sembuh', '治安維持 (chian iji = pemeliharaan stabilitas keamanan wilayah), 治療法 (chiryouhou = protokol terapi penyembuhan)', 'Sosial'],
  ['法', 'ホウ, ハッ', 'hou', 'Hukum / Undang-Undang Norma', '法律を遵守する (houritsu o junshu suru = tunduk patuh norma hukum), 方法論 (houhouron = pendekatan metodologi)', 'Sosial'],
  ['律', 'リツ', 'ritsu', 'Aturan Baku / Tata Tertib Disiplin', '規律正しく行動する (kiritsu tadashiku koudou suru = berdisiplin tertib), 法律顧問 (houritsu komon = konsultan ahli hukum)', 'Sosial'],
  ['権', 'ケン, ゴン', 'ken', 'Hak Yurisdiksi / Otoritas Kekuasaan', '基本的人権の尊重 (kihonteki jinken no sonchou = menjunjung martabat hak asasi), 権力集中 (kenryoku shuuchuu = sentralisasi kekuasaan)', 'Sosial'],
  ['利', 'リ / き-く', 'ri / ki-ku', 'Keuntungan Laba / Maslahat Manfaat', '利潤を追求する (rijun o tsuikyuu suru = memburu perolehan laba profit), 利益還元 (rieki kangen = pembagian dividen laba ke masyarakat)', 'Ekonomi'],
  ['平', 'ヘイ, ビョウ / たい-ら, ひら', 'hei, byou / tai-ra', 'Perdamaian Jagat / Keadilan Rata', '平和共存 (heiwa kyouzon = koeksistensi damai berdampingan), 平等待遇 (byoudou taiguu = perlakuan setara tanpa diskriminasi)', 'Sosial'],
  ['和', 'ワ / やわ-らぐ', 'wa', 'Harmoni Rukun / Nilai Adat Jepang', '協調と調和 (kyouchou to chouwa = semangat kolaborasi dan keselarasan harmoni), 和解 (wakai = mufakat perdamaian rekonsiliasi)', 'Budaya & Nilai'],
  ['定', 'テイ, ジョウ / さだ-める', 'tei / sada-meru', 'Menetapkan Garis / Mapan Stabil', '安定した成長基盤 (antei shita seichou kiban = pondasi pertumbuhan mapan stabil), 規則を定める (kisoku o sadameru = merumuskan regulasi)', 'Sosial'],

  // Ekonomi Makro, Pasar Modal & Korporasi N2
  ['経', 'ケイ, キョウ / へ-る', 'kei / he-ru', 'Mengelola Urusan / Melintasi Zaman', '経済連携協定 (keizai renkei kyoutei = pakta kesepakatan kemitraan ekonomi), 経営方針 (keiei houshin = garis haluan manajerial korporasi)', 'Ekonomi'],
  ['済', 'サイ, ザイ / す-む, す-ます', 'sai, zai / su-mu', 'Selesai Tuntas / Penyelamatan Finansial', '返済計画を立てる (hensai keikaku o tateru = menyusun jadwal skema pelunasan utang), 経済指標 (keizai shihyou = indikator barometer ekonomi)', 'Ekonomi'],
  ['価', 'カ / あたい', 'ka / atai', 'Nilai Mutu / Taksiran Harga Valuasi', '価値観の相違 (kachikan no soui = divergensi asas sudut pandang nilai kehidupan), 価格競争 (kakaku kyousou = perang harga pasar bebas)', 'Ekonomi'],
  ['格', 'カク', 'kaku', 'Kedudukan Kasta / Standar Kualifikasi', '資格認定試験 (shikaku nintei shiken = uji sertifikasi kompetensi lisensi), 格差社会 (kakusa shakai = fenomena kesenjangan sosial ekonomi)', 'Ekonomi'],
  ['益', 'エキ, ヤク', 'eki', 'Laba Bersih / Manfaat Maslahat Faedah', '純利益を計上する (junrieki o keijou suru = membukukan laba bersih audit), 収益構造の改革 (shuueki kouzou no kaikaku = reformasi struktur pundi omset)', 'Ekonomi'],
  ['損', 'ソン / そこ-なう', 'son / soko-nau', 'Kerugian Neraca / Cidera Kerusakan', '損失補填の手続き (sonshitsu hoten no tetsuzuki = prosedur kompensasi talangan rugi), 損害賠償 (songai baishou = ganti rugi restitusi perdata)', 'Ekonomi'],
  ['失', 'シツ / うしな-う', 'shitsu / ushina-u', 'Kehilangan Aset / Pupus Kegagalan', '信用を失う (shinyou o ushinau = kehilangan muka reputasi kredibilitas), 失敗を糧にする (shippai o kate ni suru = petik hikmah dari kegagalan)', 'Ekonomi'],
  ['投', 'トウ / な-げる', 'tou / na-geru', 'Menanam Modal Investasi / Menyalurkan Suara', '設備投資の拡大 (setsubi toushi no kakudai = ekspansi kucuran investasi pabrik aset), 投票率 (touhyouritsu = persentase partisipasi bilik pemilu)', 'Ekonomi'],
  ['資', 'シ', 'shi', 'Modal Pokok / Sumber Daya Vital', '資金調達に成功する (shikin choutatsu ni seikou suru = sukses meraup kucuran modal ventura), 天然資源 (tennen shigen = kekayaan sumber daya alam tambang)', 'Ekonomi'],

  // Kerja Sama, Sinergi & Komunikasi N2
  ['協', 'キョウ', 'kyou', 'Kerja Sama Gotong Royong / Padu', '多国間協力協定 (takokukan kyouryoku kyoutei = pakta kolaborasi kemitraan multilateral), 協会設立 (kyoukai setsuritsu = pendirian wadah asosiasi)', 'Hubungan'],
  ['力', 'リョク, リキ / ちから', 'ryoku / chikara', 'Daya Upaya / Kapabilitas Tenaga', '潜在能力を開花させる (senzai nouryoku o kaika saseru = memekarkan potensi bakat terpendam), 競争力 (kyousouryoku = daya saing kompetitif)', 'Hubungan'],
  ['団', 'ダン, トン', 'dan', 'Paguyuban Kolektif / Guyub Terpadu', '団結して困難を乗り越える (danketsu shite konnan o norikoeru = bersatu padu kompak arungi rintangan), 経済団体 (keizai dantai = wadah asosiasi konglomerasi)', 'Hubungan'],
  ['結', 'ケツ / むす-ぶ, ゆ-わえる', 'ketsu / musu-bu', 'Mengikat Akad / Menuai Buah Hasil', '業務提携を結ぶ (gyoumu teikei o musubu = meneken jalinan ikatan aliansi kerja sama), 結論を急ぐ (ketsuron o isogu = jangan tergesa ambil konklusi)', 'Hubungan'],
  ['対', 'タイ, ツイ', 'tai', 'Menghadapi Respons / Bertolak Belakang', '緊急対策本部を設置する (kinkyuu taisaku honbu o setchi suru = mendirikan posko tanggap darurat antisipasi), 対話 (taiwa = dialog diplomasi meja bundar)', 'Hubungan'],
  ['調', 'チョウ / しら-べる, ととの-う', 'chou / shira-beru, totono-u', 'Meneliti Survei / Menyelaraskan Harmoni', '市場調査を実施する (shijou chousa o jisshi suru = melancarkan riset survei pasar konsumen), 利害関係を調整する (rigai kankei o chousei suru = menyelaraskan gesekan friksi kepentingan)', 'Hubungan'],
  ['理', 'リ', 'ri', 'Nalar Logika Berpikir / Asas Hakikat', '合理的根拠を示す (gouriteki konkyo o shimesu = memaparkan landasan nalar pembuktian rasional), 理想郷 (risoukyou = firdaus peradaban idaman utopia)', 'Konsep'],
  ['意', 'イ', 'i', 'Kehendak Batin / Makna Komitmen Niat', '明確な意図を伝える (meikaku na ito o tsutaeru = menyampaikan ketegasan niat intensi komitmen), 同意書 (douishou = lembar akta persetujuan mufakat)', 'Konsep'],

  // Evaluasi, Sistem, Regulasi & Konsep Analitis N2
  ['能', 'ノウ', 'nou', 'Potensi Bakat / Fungsi Kapabilitas', '職務遂行能力 (shokumu suikou nouryoku = kapabilitas kompetensi penuntasan tugas), 可能性 (kanousei = peluang probabilitas)', 'Konsep'],
  ['必', 'ヒツ / かなら-ず', 'hitsu / kanara-zu', 'Pasti Niscaya / Mutlak Wajib', '必勝を誓う (hisshou o chikau = mengikrarkan tekad janji kemenangan mutlak), 必需品 (hitsujuuhin = komoditas pangan kebutuhan pokok sandang)', 'Konsep'],
  ['基', 'キ / もと, もとい', 'ki / moto', 'Fondasi Asas / Landasan Fundamental', '基本的方針を策定する (kihonteki houshin o sakutei suru = memformulasi asas garis pedoman pokok), 基地 (kichi = pangkalan posko induk)', 'Konsep'],
  ['的', 'テキ / まと', 'teki / mato', 'Bersifat Menyerupai / Target Bidikan', '具体的な改善策 (gutaiteki na kaizensaku = cetak biru solusi konkret berwujud), 目的意識 (mokuteki ishiki = kesadaran arah kompas tujuan)', 'Konsep'],
  ['質', 'シツ, シチ / たち', 'shitsu / tachi', 'Mutu Kualitas Kualitas / Karakter Hakikat', '品質保証基準を満たす (hinshitsu hoshou kijun o mitasu = penuhi standar kaidah jaminan mutu), 本質を見抜く (honshitsu o minuku = menembus pandang hakikat sejati)', 'Konsep'],
  ['規', 'キ', 'ki', 'Standar Kaidah / Regulasi Acuan Norma', '社内規則を順守する (shanai kisoku o junshu suru = taat patuh pedoman tata tertib korporasi), 事業規模 (jigyou kibo = dimensi skala cakupan portofolio bisnis)', 'Konsep'],
  ['模', 'モ, ボ', 'mo', 'Pola Model Rancangan / Mencontoh Tiruan', '大規模な社会インフラ整備 (daikibo na shakai infura seibi = revitalisasi infrastruktur sipil berskala masif), 模範解答 (mohan kaitou = contoh kunci jawaban teladan)', 'Konsep'],
  ['制', 'セイ', 'sei', 'Pranata Aturan / Mengontrol Batas Sistem', '新体制を発足させる (shin taisei o hossoku saseru = meluncurkan formasi tatanan sistem kepengurusan baru), 規制緩和 (kisei kanwa = deregulasi pemangkasan birokrasi)', 'Sosial'],
  ['状', 'ジョウ', 'jou', 'Keadaan Lanskap / Lembar Piagam Resmi', '現状の課題を分析する (genjou no kadai o bunseki suru = membedah peta problematika status quo saat ini), 招待状 (shoutaijou = lembaran warkat kartu undangan jamuan)', 'Sosial'],
  ['況', 'キョウ', 'kyou', 'Kondisi Nyata / Situasi Mutakhir Terkini', '刻一刻と変化する状況 (kokuikkoku to henka suru joukyou = dinamika konstelasi situasi yang bergulir cepat), 不況 (fukyou = lesunya krisis resesi)', 'Sosial'],
  ['過', 'カ / す-ぎる, あやま-ち', 'ka / su-giru', 'Melampaui Batas / Kekhilafan Khilaf', '試行錯誤の過程を経る (shikousakugo no katei o heru = melalui dinamika proses jatuh bangun asam garam), 過去 (kako = lembaran tirai masa lampau silam)', 'Konsep'],
  ['程', 'テイ / ほど', 'tei / hodo', 'Derajat Takaran / Proses Rangkaian Jadwal', '全日程を無事に終了する (zen nittei o buji ni shuuryou suru = menuntaskan seluruh agenda jadwal tanpa kendala rintangan), 程度 (teido = takaran derajat ambang mutu)', 'Konsep'],
  ['果', 'カ / は-たす, は-てる', 'ka / ha-tasu', 'Buah Hasil Manis / Menuntaskan Janji', '輝かしい研究成果を収める (kagayakashii kenkyuuseika o osameru = menuai panen hasil riset ilmiah gemilang), 因果関係 (inga kankei = relasi benang merah kausalitas sebab akibat)', 'Konsep'],
];

// Sequential assignment with absolute Zero-Duplicate check across all levels
let currentId = 1;
const allKanji = [];
const seenKanji = new Set();
const duplicateReports = [];

function registerLevel(list, level) {
  list.forEach(([kanji, onKun, romaji, arti, contoh, category]) => {
    if (seenKanji.has(kanji)) {
      duplicateReports.push({ kanji, level });
      return;
    }
    seenKanji.add(kanji);

    allKanji.push({
      id: currentId++,
      level,
      kanji,
      onKun,
      romaji,
      arti,
      contoh,
      category,
    });
  });
}

registerLevel(KANJI_N5, 'N5');
registerLevel(KANJI_N4, 'N4');
registerLevel(KANJI_N3, 'N3');
registerLevel(KANJI_N2, 'N2');

console.log('=== KANJI DATABASE GENERATION SUMMARY ===');
console.log('Total Kanji generated:', allKanji.length);
console.log('Duplicates detected:', duplicateReports.length, duplicateReports);

const levelCounts = {
  N5: allKanji.filter(k => k.level === 'N5').length,
  N4: allKanji.filter(k => k.level === 'N4').length,
  N3: allKanji.filter(k => k.level === 'N3').length,
  N2: allKanji.filter(k => k.level === 'N2').length,
};
console.log('Total per level:', levelCounts);

// Generate src/data/kanjiData.ts
const fileHeader = `import { KanjiCard, JLPTLevel } from '../types';

/**
 * =========================================================================
 * DATABASE RESMI KANJI JLPT N5–N2 (STANDAR RESMI & BEBAS DUPLIKAT)
 * - Tampilan Depan: Hanya Kanji Utama (Murni kaligrafi kanji tanpa bocoran)
 * - Tampilan Balik: On/Kun, Romaji, Arti Indonesia, Contoh Kata & Kalimat
 * - Audio: Pengucapan autentik bahasa Jepang
 * =========================================================================
 */
export const KANJI_DATABASE: KanjiCard[] = [
`;

const fileBody = allKanji.map(k => {
  return `  { id: ${k.id}, level: '${k.level}', kanji: '${k.kanji}', onKun: ${JSON.stringify(k.onKun)}, romaji: ${JSON.stringify(k.romaji)}, arti: ${JSON.stringify(k.arti)}, contoh: ${JSON.stringify(k.contoh)}, category: ${JSON.stringify(k.category)} },`;
}).join('\n');

const fileFooter = `\n];\n`;

fs.writeFileSync(path.join(__dirname, '../src/data/kanjiData.ts'), fileHeader + fileBody + fileFooter, 'utf-8');
console.log('Successfully wrote src/data/kanjiData.ts with pristine formatting!');
