# -*- coding: utf-8 -*-
# Angka Lengkap (1 - 1 Triliun), Satuan Bantu Hitung, Waktu, Tanggal, Kalender & Musim-Musim di Dunia

DICT_NUMBERS_TIME_SEASONS = [
    # Angka Dasar 1 - 20, Puluhan, Ratusan, Ribuan, Jutaan, Triliunan
    ("一", "いち", "ichi", "Angka Satu (1)", "Penunjuk Waktu & Angka", "一からやり直します。", "Mengulang kembali dari angka satu."),
    ("二", "に", "ni", "Angka Dua (2)", "Penunjuk Waktu & Angka", "二人で協力します。", "Bekerja sama berdua."),
    ("三", "さん", "san", "Angka Tiga (3)", "Penunjuk Waktu & Angka", "三日間の旅行です。", "Perjalanan liburan selama tiga hari."),
    ("四", "よん / し", "yon / shi", "Angka Empat (4)", "Penunjuk Waktu & Angka", "四角いテーブルです。", "Meja berbentuk segi empat."),
    ("五", "ご", "go", "Angka Lima (5)", "Penunjuk Waktu & Angka", "五時に集合します。", "Berkumpul pada pukul lima."),
    ("六", "ろく", "roku", "Angka Enam (6)", "Penunjuk Waktu & Angka", "六角形の鉛筆です。", "Pensil berbentuk segi enam."),
    ("七", "なな / しち", "nana / shichi", "Angka Tujuh (7)", "Penunjuk Waktu & Angka", "七階へ上がります。", "Naik ke lantai tujuh."),
    ("八", "はち", "hachi", "Angka Delapan (8)", "Penunjuk Waktu & Angka", "八月は真夏です。", "Bulan Agustus adalah puncak musim panas."),
    ("九", "きゅう / く", "kyuu / ku", "Angka Sembilan (9)", "Penunjuk Waktu & Angka", "九時五分前に着きます。", "Tiba lima menit sebelum jam sembilan."),
    ("十", "じゅう", "juu", "Angka Sepuluh (10)", "Penunjuk Waktu & Angka", "十分間休憩します。", "Istirahat selama sepuluh menit."),
    ("十一", "じゅういち", "juuichi", "Angka Sebelas (11)", "Penunjuk Waktu & Angka", "十一月に紅葉を見ます。", "Melihat daun merah di bulan November."),
    ("十二", "じゅうに", "juuni", "Angka Dua Belas (12)", "Penunjuk Waktu & Angka", "十二月は師走です。", "Bulan Desember adalah akhir tahun."),
    ("十三", "じゅうさん", "juusan", "Angka Tiga Belas (13)", "Penunjuk Waktu & Angka", "十三番目の席です。", "Kursi nomor tiga belas."),
    ("十四", "じゅうよん / じゅうし", "juuyon / juushi", "Angka Empat Belas (14)", "Penunjuk Waktu & Angka", "十四日間滞在します。", "Tinggal selama empat belas hari."),
    ("十五", "じゅうご", "juugo", "Angka Lima Belas (15)", "Penunjuk Waktu & Angka", "十五分歩きます。", "Berjalan kaki selama lima belas menit."),
    ("十六", "じゅうろく", "juuroku", "Angka Enam Belas (16)", "Penunjuk Waktu & Angka", "十六歳で高校に入学します。", "Masuk SMA di usia enam belas tahun."),
    ("十七", "じゅうなな / じゅうしち", "juunana / juushichi", "Angka Tujuh Belas (17)", "Penunjuk Waktu & Angka", "十七条の憲法です。", "Konstitusi tujuh belas pasal."),
    ("十八", "じゅうはち", "juuhachi", "Angka Delapan Belas (18)", "Penunjuk Waktu & Angka", "十八歳で成人となります。", "Menjadi dewasa di usia delapan belas tahun."),
    ("十九", "じゅうきゅう / じゅうく", "juukyuu / juuku", "Angka Sembilan Belas (19)", "Penunjuk Waktu & Angka", "十九世紀の絵画です。", "Lukisan abad kesembilan belas."),
    ("二十", "にじゅう", "nijuu", "Angka Dua Puluh (20)", "Penunjuk Waktu & Angka", "二十ページを開きます。", "Membuka halaman dua puluh."),
    ("三十", "さんじゅう", "sanjuu", "Angka Tiga Puluh (30)", "Penunjuk Waktu & Angka", "三十分で着きます。", "Tiba dalam tiga puluh menit."),
    ("四十", "よんじゅう", "yonjuu", "Angka Empat Puluh (40)", "Penunjuk Waktu & Angka", "四十代の社員です。", "Karyawan berusia empat puluhan tahun."),
    ("五十", "ごじゅう", "gojuu", "Angka Lima Puluh (50)", "Penunjuk Waktu & Angka", "五十音順に並べます。", "Menata sesuai urutan 50 bunyi kana."),
    ("六十", "ろくじゅう", "rokujuu", "Angka Enam Puluh (60)", "Penunjuk Waktu & Angka", "六十歳で還暦を迎えます。", "Merayakan usia 60 tahun (Kanreki)."),
    ("七十", "ななじゅう", "nanajuu", "Angka Tujuh Puluh (70)", "Penunjuk Waktu & Angka", "七十パーセントの確率です。", "Peluang sebesar tujuh puluh persen."),
    ("八十", "はちじゅう", "hachijuu", "Angka Delapan Puluh (80)", "Penunjuk Waktu & Angka", "八十キロのスピードです。", "Kecepatan delapan puluh kilometer per jam."),
    ("九十", "きゅうじゅう", "kyuujuu", "Angka Sembilan Puluh (90)", "Penunjuk Waktu & Angka", "九十度回転させます。", "Memutar rotasi sebesar sembilan puluh derajat."),
    ("百", "ひゃく", "hyaku", "Angka Seratus (100)", "Penunjuk Waktu & Angka", "テストで百点を取ります。", "Meraih nilai seratus dalam ujian."),
    ("千", "せん", "sen", "Angka Seribu (1.000)", "Penunjuk Waktu & Angka", "千羽鶴を折ります。", "Melipat seribu burung bangau kertas."),
    ("一万", "いちまん", "ichiman", "Angka Sepuluh Ribu (10.000)", "Penunjuk Waktu & Angka", "一万円札で支払います。", "Membayar dengan uang sepuluh ribu yen."),
    ("十万", "じゅうまん", "juuman", "Angka Seratus Ribu (100.000)", "Penunjuk Waktu & Angka", "十万部突破のベストセラーです。", "Buku laris terjual melampaui seratus ribu eksemplar."),
    ("百万", "ひゃくまん", "hyakuman", "Angka Satu Juta (1.000.000)", "Penunjuk Waktu & Angka", "百万ドルの夜景です。", "Pemandangan malam bernilai sejuta dolar."),
    ("一千万", "いっせんまん", "issenman", "Angka Sepuluh Juta (10.000.000)", "Penunjuk Waktu & Angka", "一千万円の保険に加入します。", "Mendaftar asuransi senilai sepuluh juta yen."),
    ("一億", "いちおく", "ichioku", "Angka Seratus Juta (100.000.000)", "Penunjuk Waktu & Angka", "一億総活躍社会を目指します。", "Membidik masyarakat dengan 100 juta penduduk aktif."),
    ("十億", "じゅうおく", "juuoku", "Angka Satu Miliar (1.000.000.000)", "Penunjuk Waktu & Angka", "世界の人口は八十億人を超えました。", "Populasi dunia melampaui delapan miliar jiwa."),
    ("百億", "ひゃくおく", "hyakuoku", "Angka Sepuluh Miliar (10.000.000.000)", "Penunjuk Waktu & Angka", "百億円の大型投資計画です。", "Rencana investasi besar senilai sepuluh miliar yen."),
    ("一兆", "いっちょう", "icchou", "Angka Satu Triliun (1.000.000.000.000)", "Penunjuk Waktu & Angka", "国家予算は百兆円規模です。", "Skala anggaran negara mencapai seratus triliun yen."),

    # Angka Ordinal (Ke-1, Ke-2, dst.) & Pecahan / Persen
    ("第一", "だいいち", "daiichi", "Pertama-tama / Nomor satu", "Penunjuk Waktu & Angka", "健康が第一です。", "Kesehatan adalah yang nomor satu paling utama."),
    ("第二", "だいに", "daini", "Yang kedua (Kedua)", "Penunjuk Waktu & Angka", "第二外国語として日本語を学びます。", "Belajar bahasa Jepang sebagai bahasa asing kedua."),
    ("第三", "だいさん", "daisan", "Yang ketiga (Ketiga)", "Penunjuk Waktu & Angka", "第三者委員会を設置します。", "Membentuk komite pihak ketiga."),
    ("二分の一", "にぶんのいち", "nibun no ichi", "Setengah (1/2)", "Penunjuk Waktu & Angka", "リンゴを二分の一に切ります。", "Memotong apel menjadi setengah bagian."),
    ("三分の一", "さんぶんのいち", "sanbun no ichi", "Sepertiga (1/3)", "Penunjuk Waktu & Angka", "敷地の三分の一を緑地にします。", "Menjadikan sepertiga area tanah sebagai ruang hijau."),
    ("四分の一", "よんぶんのいち", "yonbun no ichi", "Seperempat (1/4)", "Penunjuk Waktu & Angka", "ピザを四分の一食べました。", "Memakan seperempat loyang pizza."),
    ("パーセント", "ぱーせんと", "paasento", "Persen (%)", "Penunjuk Waktu & Angka", "消費税は十パーセントです。", "Pajak konsumsi adalah sepuluh persen."),

    # Satuan Bantu Hitung Lengkap (Counters)
    ("一個", "いっこ", "ikko", "Satu buah (satuan butir/buah bulat)", "Penunjuk Waktu & Angka", "リンゴを一個食べます。", "Memakan satu buah apel."),
    ("二個", "にこ", "niko", "Dua buah (satuan butir/benda kecil)", "Penunjuk Waktu & Angka", "消しゴムを二個買いました。", "Membeli dua buah penghapus."),
    ("三個", "さんこ", "sanko", "Tiga buah", "Penunjuk Waktu & Angka", "みかんを三個皮を剥きます。", "Mengupas tiga buah jeruk."),
    ("一匹", "いっぴき", "ippiki", "Satu ekor (hewan kecil: kucing/ikan/serangga)", "Penunjuk Waktu & Angka", "池に金魚が一匹泳いでいます。", "Ada seekor ikan mas koki berenang di kolam."),
    ("二匹", "にひき", "nihiki", "Dua ekor", "Penunjuk Waktu & Angka", "猫を二匹飼っています。", "Memelihara dua ekor kucing."),
    ("三匹", "さんびき", "sanbiki", "Tiga ekor", "Penunjuk Waktu & Angka", "三匹のこぶたの童話です。", "Dongeng tiga ekor anak babi."),
    ("一頭", "いっとう", "ittou", "Satu ekor (hewan besar: sapi/kuda/gajah)", "Penunjuk Waktu & Angka", "牧場で牛を一頭見ました。", "Melihat seekor sapi di peternakan."),
    ("二頭", "にごう / にとう", "nitou", "Dua ekor hewan besar", "Penunjuk Waktu & Angka", "馬が二頭走っています。", "Dua ekor kuda sedang berlari."),
    ("一羽", "いちわ", "ichiwa", "Satu ekor (burung / unggas / kelinci)", "Penunjuk Waktu & Angka", "小鳥が一羽とまっています。", "Seekor burung kecil bertengger."),
    ("二羽", "にわ", "niwa", "Dua ekor burung", "Penunjuk Waktu & Angka", "白鳥が二羽飛んでいます。", "Dua ekor angsa putih sedang terbang."),
    ("一軒", "いっけん", "ikken", "Satu unit rumah hunian", "Penunjuk Waktu & Angka", "静かな住宅街に家を一軒建てました。", "Membangun satu unit rumah di perumahan tenang."),
    ("二軒", "にけん", "niken", "Dua unit rumah", "Penunjuk Waktu & Angka", "隣の二軒に挨拶します。", "Menyapa dua rumah tetangga sebelah."),
    ("一足", "いっそく", "issoku", "Satu pasang (sepatu / kaus kaki)", "Penunjuk Waktu & Angka", "新しいスニーカーを一足買いました。", "Membeli sepasang sepatu kets baru."),
    ("二足", "にそく", "nisoku", "Dua pasang sepatu", "Penunjuk Waktu & Angka", "革靴を二足揃えます。", "Menyiapkan dua pasang sepatu kulit."),
    ("一着", "いっちゃく", "icchaku", "Satu setel (jas / pakaian)", "Penunjuk Waktu & Angka", "スーツを一着新調します。", "Membuat baru satu setel jas formal."),
    ("二着", "にちゃく", "nichaku", "Dua setel pakaian", "Penunjuk Waktu & Angka", "ワンピースを二着買いました。", "Membeli dua potong baju terusan dress."),
    ("一皿", "ひとさら", "hitosara", "Satu piring hidangan", "Penunjuk Waktu & Angka", "カレーを一皿注文します。", "Memesan sepiring nasi kari."),
    ("二皿", "ふたさら", "futasara", "Dua piring makanan", "Penunjuk Waktu & Angka", "餃子を二皿焼いてもらいます。", "Meminta memanggangkan dua piring gyoza."),
    ("一箱", "ひとはこ", "hitohako", "Satu kotak / Satu kardus", "Penunjuk Waktu & Angka", "お菓子を一箱プレゼントします。", "Memberikan sekotak kue sebagai hadiah."),
    ("一袋", "ひとふくろ", "hitofukuro", "Satu bungkus / Satu kantong", "Penunjuk Waktu & Angka", "小麦粉を一袋買います。", "Membeli sebungkus tepung terigu."),
    ("一巻", "いっかん", "ikkan", "Jilid pertama (komik/buku)", "Penunjuk Waktu & Angka", "漫画の第一巻を読みます。", "Membaca komik jilid pertama."),
    ("秒", "びょう", "byou", "Detik (satuan waktu)", "Penunjuk Waktu & Angka", "十秒数えてから目を開けます。", "Menghitung sepuluh detik lalu membuka mata."),
    ("一秒", "いちびょう", "ichibyou", "Satu detik", "Penunjuk Waktu & Angka", "一秒を争う救急救命です。", "Pertolongan darurat medis yang berpacu dengan tiap detik."),
    ("瞬間", "しゅんかん", "shunkan", "Detik saat / Momen sekejap", "Penunjuk Waktu & Angka", "決定的瞬間を写真に収めます。", "Mengabadikan momen penentu dalam foto."),
    ("期間", "きかん", "kikan", "Jangka waktu periode", "Penunjuk Waktu & Angka", "契約期間は一年間です。", "Masa berlaku periode kontrak adalah satu tahun."),

    # Musim-Musim di Jepang & Seluruh Dunia (世界の季節と気候)
    ("春夏秋冬", "しゅんかしゅうとう", "shunkashuutou", "Empat Musim (Semi, Panas, Gugur, Dingin)", "Penunjuk Waktu & Angka", "日本の春夏秋冬の美しさを味わいます。", "Menikmati keindahan empat musim di Jepang."),
    ("四季", "しき", "shiki", "Empat musim pergantian tahun", "Penunjuk Waktu & Angka", "四季折々の風景を楽しみます。", "Menikmati aneka panorama pemandangan empat musim."),
    ("初春", "しょしゅん", "shoshun", "Awal musim semi", "Penunjuk Waktu & Angka", "初春の風がまだ少し冷たいです。", "Angin awal musim semi masih terasa agak dingin."),
    ("晩春", "ばんしゅん", "banshun", "Penghujung musim semi", "Penunjuk Waktu & Angka", "晩春に新緑が芽吹きます。", "Daun hijau segar bertunas di penghujung musim semi."),
    ("初夏", "しょか", "shoka", "Awal musim panas", "Penunjuk Waktu & Angka", "初夏の爽やかな日差しを浴びます。", "Menikmati sinar matahari yang hangat di awal musim panas."),
    ("真夏", "まなつ", "manatsu", "Puncak musim panas terik", "Penunjuk Waktu & Angka", "真夏の浜辺で海水浴をします。", "Bermain air laut di tepi pantai saat puncak musim panas."),
    ("晩夏", "ばんか", "banka", "Penghujung musim panas", "Penunjuk Waktu & Angka", "晩夏の夕暮れに赤とんぼが飛びます。", "Capung merah terbang di senja penghujung musim panas."),
    ("初秋", "しょしゅう", "shoshuu", "Awal musim gugur", "Penunjuk Waktu & Angka", "初秋の夜風が心地よいです。", "Semilir angin malam awal musim gugur sangat nyaman."),
    ("晩秋", "ばんしゅう", "banshuu", "Penghujung musim gugur", "Penunjuk Waktu & Angka", "晩秋の落ち葉を踏みしめて歩きます。", "Berjalan menginjak daun gugur di akhir musim gugur."),
    ("初冬", "しょとう", "shotou", "Awal musim dingin", "Penunjuk Waktu & Angka", "初冬の朝に霜が降りました。", "Embun beku turun di pagi hari awal musim dingin."),
    ("真冬", "まふゆ", "mafuyu", "Puncak musim dingin membeku", "Penunjuk Waktu & Angka", "真冬の雪景色が銀世界に広がります。", "Pemandangan salju putih membentang saat puncak musim dingin."),
    ("梅雨", "つゆ / ばいう", "tsuyu / baiu", "Musim hujan awal panas Jepang (Tsuyu)", "Penunjuk Waktu & Angka", "六月は梅雨で雨が続きます。", "Bulan Juni adalah musim hujan Tsuyu yang basah."),
    ("梅雨明け", "つゆあけ", "tsuyuake", "Berakhirnya musim hujan Tsuyu", "Penunjuk Waktu & Angka", "梅雨明けとともに本格的な夏が来ます。", "Musim panas sejati tiba seiring berakhirnya musim Tsuyu."),
    ("雨季", "うき", "uki", "Musim hujan tropis (Monsoon)", "Penunjuk Waktu & Angka", "東南アジアの雨季にはスコールが降ります。", "Hujan lebat squall turun saat musim hujan di Asia Tenggara."),
    ("乾季", "かんき", "kanki", "Musim kemarau tropis", "Penunjuk Waktu & Angka", "乾季はカラッとして観光に最適です。", "Musim kemarau kering dan sangat ideal untuk berwisata."),
    ("台風シーズン", "たいふうしーずん", "taifuu shiizun", "Musim badai taifun", "Penunjuk Waktu & Angka", "秋の台風シーズンに備えて防災用品を確認します。", "Memeriksa perlengkapan darurat siaga menghadapi musim taifun."),
    ("花粉症の季節", "かふんしょうのきせつ", "kafunshou no kisetsu", "Musim alergi serbuk sari bunga (Kafunsho)", "Penunjuk Waktu & Angka", "春は花粉症の季節なのでマスクをつけます。", "Mengenakan masker saat musim semi karena musim serbuk sari."),
    ("衣替え", "ころもがえ", "koromogae", "Tradisi pergantian busana sesuai musim", "Penunjuk Waktu & Angka", "六月一日に夏服へ衣替えします。", "Mengganti seragam ke pakaian musim panas pada tanggal 1 Juni."),
    ("節分", "せつぶん", "setsubun", "Festival Setsubun penyambutan musim semi", "Penunjuk Waktu & Angka", "節分に豆まきをして福を呼びます。", "Melempar kacang kedelai saat Setsubun untuk membawa keberuntungan."),
    ("立春", "りっしゅん", "risshun", "Hari pertama awal musim semi kalender lunar", "Penunjuk Waktu & Angka", "立春を迎えて暦の上では春になります。", "Musim semi dimulai berdasarkan kalender lunar pada hari Risshun.")
]

print(f"Loaded {len(DICT_NUMBERS_TIME_SEASONS)} complete Numbers, Time & Seasons items.")
