# -*- coding: utf-8 -*-
import json
import os

CATEGORY_MAP_JP = {
    'Kata Kerja Dasar': '動詞',
    'Kata Sifat': '形容詞',
    'Penunjuk Waktu dan Angka': '時間・数字',
    'Kata Benda Umum': '名詞',
    'Kata Tanya dan Kata Ganti': '疑問詞・代名詞',
    'Salam dan Percakapan': '挨拶・表現',
    'Angka': '数字',
    'Uang': 'お金',
    'Kosakata Sehari-hari': '日常生活',
    'Pekerjaan': '仕事',
    'Nama Buah': '果物',
    'Kendaraan Umum': '乗り物',
    'Sapaan': '挨拶'
}

# 1. KATA KERJA DASAR (動詞 - Minna no Nihongo I Bab 1-25)
N5_VERBS = [
    ("会います", "あいます", "aimasu", "Bertemu (teman)", "Kata Kerja Dasar", "駅で友達に会います。", "Bertemu teman di stasiun."),
    ("開きます", "あきます", "akimasu", "Terbuka (pintu terbuka)", "Kata Kerja Dasar", "ドアが開きます。", "Pintu terbuka."),
    ("開けます", "あけます", "akemasu", "Membuka (pintu/jendela)", "Kata Kerja Dasar", "窓を開けます。", "Membuka jendela."),
    ("あげます", "あげます", "agemasu", "Memberikan (kepada orang lain)", "Kata Kerja Dasar", "プレゼントをあげます。", "Memberikan hadiah."),
    ("遊びます", "あそびます", "asobimasu", "Bermain / Bersenang-senang", "Kata Kerja Dasar", "友達と遊びます。", "Bermain bersama kawan."),
    ("浴びます", "あびます", "abimasu", "Mandi guyur (shower)", "Kata Kerja Dasar", "毎朝シャワーを浴びます。", "Setiap pagi mandi shower."),
    ("洗います", "あらいます", "araimasu", "Mencuci (tangan/pakaian)", "Kata Kerja Dasar", "手をきれいに洗います。", "Mencuci tangan sampai bersih."),
    ("案内します", "あんないします", "annaishimasu", "Memandu / Menunjukkan jalan", "Kata Kerja Dasar", "東京の町を案内します。", "Memandu keliling kota Tokyo."),
    ("あります", "あります", "arimasu", "Ada (benda mati/tanaman)", "Kata Kerja Dasar", "机の上に本があります。", "Ada buku di atas meja."),
    ("歩きます", "あるきます", "arukimasu", "Berjalan kaki", "Kata Kerja Dasar", "駅まで歩いて行きます。", "Pergi ke stasiun dengan jalan kaki."),
    ("言います", "いいます", "iimasu", "Berkata / Mengatakan", "Kata Kerja Dasar", "日本語で何と言いますか。", "Mengatakannya bagaimana dalam bahasa Jepang?"),
    ("行きます", "いきます", "ikimasu", "Pergi ke tempat tujuan", "Kata Kerja Dasar", "学校へ行きます。", "Pergi ke sekolah."),
    ("急ぎます", "いそぎます", "isogimasu", "Terburu-buru / Bergegas", "Kata Kerja Dasar", "急いで駅へ向かいます。", "Bergegas menuju stasiun."),
    ("要ります", "いります", "irimasu", "Memerlukan / Butuh", "Kata Kerja Dasar", "ビザが要ります。", "Memerlukan visa."),
    ("入れます", "いれます", "iremasu", "Memasukkan", "Kata Kerja Dasar", "財布にお金を入れます。", "Memasukkan uang ke dalam dompet."),
    ("歌います", "うたいます", "utaimasu", "Menyanyikan lagu", "Kata Kerja Dasar", "日本の歌を歌います。", "Menyanyikan lagu Jepang."),
    ("生まれます", "うまれます", "umaremasu", "Lahir ke dunia", "Kata Kerja Dasar", "東京で生まれました。", "Lahir di Tokyo."),
    ("売ります", "うります", "urimasu", "Menjual barang dagangan", "Kata Kerja Dasar", "野菜を安く売ります。", "Menjual sayuran dengan murah."),
    ("置きます", "おきます", "okimasu", "Menaruh / Meletakkan", "Kata Kerja Dasar", "ここに荷物を置きます。", "Menaruh barang di sini."),
    ("起きます", "おきます", "okimasu", "Bangun dari tidur", "Kata Kerja Dasar", "毎朝六時に起きます。", "Bangun jam enam setiap pagi."),
    ("送ります", "おくります", "okurimasu", "Mengirimkan (paket/surat)", "Kata Kerja Dasar", "家族に手紙を送ります。", "Mengirimkan surat kepada keluarga."),
    ("教えます", "おしえます", "oshiemasu", "Mengajar / Memberitahu", "Kata Kerja Dasar", "日本語を教えます。", "Mengajar bahasa Jepang."),
    ("押します", "おします", "oshimasu", "Menekan / Mendorong (tombol)", "Kata Kerja Dasar", "ボタンを押します。", "Menekan tombol."),
    ("落とします", "おとします", "otoshimasu", "Menjatuhkan barang", "Kata Kerja Dasar", "鍵を落としました。", "Menjatuhkan kunci."),
    ("思い出します", "おもいだします", "omoidashimasu", "Teringat kembali ingatan", "Kata Kerja Dasar", "昔のことを思い出します。", "Teringat masa lalu."),
    ("思います", "おもいます", "omoimasu", "Berpikir / Mengira", "Kata Kerja Dasar", "とてもいいと思います。", "Saya kira sangat bagus."),
    ("泳ぎます", "およぎます", "oyogimasu", "Berenang di air", "Kata Kerja Dasar", "海で泳ぎます。", "Berenang di laut."),
    ("降ります", "おります", "orimasu", "Turun dari kendaraan", "Kata Kerja Dasar", "バスを降ります。", "Turun dari bus."),
    ("終わります", "おわります", "owarimasu", "Selesai / Berakhir", "Kata Kerja Dasar", "授業が終わりました。", "Pelajaran telah selesai."),
    ("買います", "かいます", "kaimasu", "Membeli barang", "Kata Kerja Dasar", "新しい靴を買います。", "Membeli sepatu baru."),
    ("買い物します", "かいものします", "kaimonoshimasu", "Berbelanja kebutuhan", "Kata Kerja Dasar", "スーパーで買い物します。", "Berbelanja di supermarket."),
    ("返します", "かえします", "kaeshimasu", "Mengembalikan pinjaman", "Kata Kerja Dasar", "図書館に本を返します。", "Mengembalikan buku ke perpustakaan."),
    ("帰ります", "かえります", "kaerimasu", "Pulang ke rumah", "Kata Kerja Dasar", "うちへ帰ります。", "Pulang ke rumah."),
    ("かかります", "かかります", "kakarimasu", "Memerlukan (waktu/biaya)", "Kata Kerja Dasar", "二時間かかります。", "Memerlukan waktu dua jam."),
    ("書きます", "かきます", "kakimasu", "Menulis huruf/catatan", "Kata Kerja Dasar", "ノートに名前を書きます。", "Menulis nama di buku catatan."),
    ("かけます", "かけます", "kakemasu", "Menelepon (denwa o kakemasu)", "Kata Kerja Dasar", "友達に電話をかけます。", "Menelepon kawan."),
    ("貸します", "かします", "kashimasu", "Meminjamkan kepada orang", "Kata Kerja Dasar", "傘を貸します。", "Meminjamkan payung."),
    ("勝ちます", "かちます", "kachimasu", "Menang dalam pertandingan", "Kata Kerja Dasar", "試合に勝ちました。", "Menang dalam pertandingan."),
    ("被ります", "かぶります", "kaburimasu", "Memakai topi di kepala", "Kata Kerja Dasar", "帽子を被ります。", "Memakai topi."),
    ("借ります", "かります", "karimasu", "Meminjam dari orang", "Kata Kerja Dasar", "辞書を借ります。", "Meminjam kamus."),
    ("考えます", "かんがえます", "kangaemasu", "Memikirkan / Merenungkan", "Kata Kerja Dasar", "将来のことを考えます。", "Memikirkan masa depan."),
    ("頑張ります", "がんばります", "ganbarimasu", "Berusaha keras / Berjuang", "Kata Kerja Dasar", "試験を頑張ります。", "Berjuang dalam ujian."),
    ("消えます", "きえます", "kiemasu", "Padam / Mati aliran", "Kata Kerja Dasar", "電気が消えました。", "Lampu padam."),
    ("聞きます", "ききます", "kikimasu", "Mendengar suara / Bertanya", "Kata Kerja Dasar", "先生に質問を聞きます。", "Bertanya kepada guru."),
    ("切ります", "きります", "kirimasu", "Memotong dengan pisau/gunting", "Kata Kerja Dasar", "ハサミで紙を切ります。", "Memotong kertas dengan gunting."),
    ("着ます", "きます", "kimasu", "Memakai baju atasan", "Kata Kerja Dasar", "シャツを着ます。", "Memakai kemeja."),
    ("来ます", "きます", "kimasu", "Datang kemari", "Kata Kerja Dasar", "先生が教室に来ました。", "Guru datang ke kelas."),
    ("消します", "けします", "keshimasu", "Mematikan lampu / Api", "Kata Kerja Dasar", "エアコンを消します。", "Mematikan AC."),
    ("結婚します", "けっこんします", "kekkonshimasu", "Menikah membina rumah tangga", "Kata Kerja Dasar", "来年結婚します。", "Akan menikah tahun depan."),
    ("研究します", "けんきゅうします", "kenkyuushimasu", "Meneliti / Mengadakan riset", "Kata Kerja Dasar", "日本文化を研究します。", "Meneliti kebudayaan Jepang."),
    ("答えます", "こたえます", "kotaemasu", "Menjawab pertanyaan", "Kata Kerja Dasar", "質問に答えます。", "Menjawab pertanyaan."),
    ("コピーします", "こぴーします", "kopiishimasu", "Memfotokopi dokumen", "Kata Kerja Dasar", "書類をコピーします。", "Memfotokopi dokumen."),
    ("困ります", "こまります", "komarimasu", "Mengalami kesulitan / Bingung", "Kata Kerja Dasar", "道に迷って困りました。", "Bingung karena tersesat jalan."),
    ("咲きます", "さきます", "sakimasu", "Mekar (bunga bersemi)", "Kata Kerja Dasar", "庭に花が咲きました。", "Bunga bermekaran di halaman."),
    ("差します", "さします", "sashimasu", "Memayungi (kasa o)", "Kata Kerja Dasar", "傘を差して歩きます。", "Berjalan sambil memakai payung."),
    ("触ります", "さわります", "sawarimasu", "Menyentuh / Meraba", "Kata Kerja Dasar", "展示品に触らないでください。", "Jangan menyentuh barang pameran."),
    ("散歩します", "さんぽします", "sanposhimasu", "Jalan-jalan santai", "Kata Kerja Dasar", "公園を散歩します。", "Jalan santai di taman."),
    ("死にます", "しにます", "shinimasu", "Mati / Meninggal", "Kata Kerja Dasar", "金魚が死にました。", "Ikan mas koki mati."),
    ("閉まります", "しまります", "shimarimasu", "Tertutup (pintu tertutup)", "Kata Kerja Dasar", "自動ドアが閉まります。", "Pintu otomatis tertutup."),
    ("締めます", "しめます", "shimemasu", "Mengencangkan sabuk / Dasi", "Kata Kerja Dasar", "ネクタイを締めます。", "Memakai dasi."),
    ("閉めます", "しめます", "shimemasu", "Menutup (pintu/jendela)", "Kata Kerja Dasar", "窓を閉めます。", "Menutup jendela."),
    ("修理します", "しゅうりします", "shuurishimasu", "Mereparasi / Menservis", "Kata Kerja Dasar", "壊れた時計を修理します。", "Mereparasi jam yang rusak."),
    ("出張します", "しゅっちょうします", "shucchoushimasu", "Dinas tugas ke luar kota", "Kata Kerja Dasar", "大阪へ出張します。", "Dinas ke luar kota ke Osaka."),
    ("紹介します", "しょうかいします", "shoukaishimasu", "Memperkenalkan orang/tempat", "Kata Kerja Dasar", "友達を紹介します。", "Memperkenalkan teman."),
    ("食事します", "しょくじします", "shokujishimasu", "Makan bersama / Bersantap", "Kata Kerja Dasar", "レストランで食事します。", "Bersantap di restoran."),
    ("知ります", "しります", "shirimasu", "Tahu / Mengetahui", "Kata Kerja Dasar", "そのニュースを知っています。", "Mengetahui berita itu."),
    ("調べます", "しらべます", "shirabemasu", "Memeriksa / Mencari di kamus", "Kata Kerja Dasar", "単語の意味を調べます。", "Mencari arti kosakata."),
    ("吸います", "すいます", "suimasu", "Menghisap nafas / Merokok", "Kata Kerja Dasar", "たばこを吸いません。", "Tidak merokok."),
    ("住みます", "すみます", "sumimasu", "Tinggal / Menetap", "Kata Kerja Dasar", "京都に住んでいます。", "Tinggal di Kyoto."),
    ("します", "します", "shimasu", "Melakukan / Mengerjakan", "Kata Kerja Dasar", "テニスをします。", "Bermain tenis."),
    ("座ります", "すわります", "suwarimasu", "Duduk di kursi", "Kata Kerja Dasar", "椅子に座ってください。", "Silakan duduk di kursi."),
    ("捨てます", "すてます", "sutemasu", "Membuang ke tempat sampah", "Kata Kerja Dasar", "ここにゴミを捨てないでください。", "Jangan membuang sampah di sini."),
    ("説明します", "せつめいします", "setsumeishimasu", "Menerangkan / Menjelaskan", "Kata Kerja Dasar", "文法を分かりやすく説明します。", "Menjelaskan tata bahasa dengan mudah dipahami."),
    ("洗濯します", "せんたくします", "sentakushimasu", "Mencuci pakaian kotor", "Kata Kerja Dasar", "天気がいいので洗濯します。", "Karena cuaca cerah, mencuci pakaian."),
    ("掃除します", "そうじします", "soujishimasu", "Membersihkan ruangan/rumah", "Kata Kerja Dasar", "部屋をきれいに掃除します。", "Membersihkan kamar sampai rapi."),
    ("相談します", "そうだんします", "soudanshimasu", "Berkonsultasi meminta saran", "Kata Kerja Dasar", "先生に相談します。", "Berkonsultasi dengan guru."),
    ("出します", "だします", "dashimasu", "Mengeluarkan / Menyerahkan", "Kata Kerja Dasar", "宿題を出します。", "Menyerahkan PR."),
    ("立ちます", "たちます", "tachimasu", "Berdiri tegak", "Kata Kerja Dasar", "黒板の前に立ちます。", "Berdiri di depan papan tulis."),
    ("頼みます", "たのみます", "tanomimasu", "Memohon / Meminta tolong", "Kata Kerja Dasar", "水を頼みます。", "Memesan air minum."),
    ("食べます", "たべます", "tabemasu", "Makan makanan", "Kata Kerja Dasar", "美味しい寿司を食べます。", "Makan sushi yang lezat."),
    ("違います", "ちがいます", "chigaimasu", "Berbeda / Keliru", "Kata Kerja Dasar", "答えが違います。", "Jawabannya keliru."),
    ("使います", "つかいます", "tsukaimasu", "Menggunakan / Memakai", "Kata Kerja Dasar", "辞書を使います。", "Menggunakan kamus."),
    ("疲れます", "つかれます", "tsukaremasu", "Lelah / Letih fisik", "Kata Kerja Dasar", "歩いて疲れました。", "Lelah karena banyak berjalan."),
    ("着きます", "つきます", "tsukimasu", "Tiba / Sampai tujuan", "Kata Kerja Dasar", "駅に着きました。", "Tiba di stasiun."),
    ("つけます", "つけます", "tsukemasu", "Nyalakan lampu / AC", "Kata Kerja Dasar", "部屋の電気をつけます。", "Menyalakan lampu kamar."),
    ("作ります", "つくります", "tsukurimasu", "Membuat / Memasak", "Kata Kerja Dasar", "日本料理を作ります。", "Membuat masakan Jepang."),
    ("連れて行きます", "つれていきます", "tsurete ikimasu", "Mengajak pergi orang", "Kata Kerja Dasar", "子供を病院へ連れて行きます。", "Membawa anak ke rumah sakit."),
    ("連れて来ます", "つれてきます", "tsurete kimasu", "Mengajak datang orang", "Kata Kerja Dasar", "友達を連れて来ました。", "Membawa kawan kemari."),
    ("出かけます", "でかけます", "dekakemasu", "Pergi keluar rumah", "Kata Kerja Dasar", "休みの日に出かけます。", "Keluar jalan-jalan di hari libur."),
    ("できます", "できます", "dekimasu", "Bisa / Mampu melakukan", "Kata Kerja Dasar", "スキーができます。", "Bisa bermain ski."),
    ("出ます", "でます", "demasu", "Keluar dari ruangan", "Kata Kerja Dasar", "家を出ます。", "Keluar dari rumah."),
    ("手伝います", "てつだいます", "tetsudaimasu", "Membantu orang lain", "Kata Kerja Dasar", "母を手伝います。", "Membantu ibu."),
    ("電話します", "でんわします", "denwashimasu", "Menelepon", "Kata Kerja Dasar", "家族に電話します。", "Menelepon keluarga."),
    ("通ります", "とおります", "toorimasu", "Melewati / Melintasi", "Kata Kerja Dasar", "橋を通ります。", "Melewati jembatan."),
    ("止まります", "とまります", "tomarimasu", "Berhenti (kendaraan)", "Kata Kerja Dasar", "タクシーが止まりました。", "Taksi berhenti."),
    ("泊まります", "とまります", "tomarimasu", "Menginap di hotel/rumah", "Kata Kerja Dasar", "旅館に泊まります。", "Menginap di penginapan ryokan."),
    ("取ります", "とります", "torimasu", "Mengambil barang", "Kata Kerja Dasar", "塩を取ってください。", "Tolong ambilkan garam."),
    ("撮ります", "とります", "torimasu", "Memotret foto", "Kata Kerja Dasar", "写真を撮ります。", "Memotret foto."),
    ("直します", "なおします", "naoshimasu", "Membetulkan kesalahan", "Kata Kerja Dasar", "作文を直します。", "Membetulkan karangan."),
    ("治ります", "なおります", "naorimasu", "Sembuh dari penyakit", "Kata Kerja Dasar", "病気が治りました。", "Penyakitnya sudah sembuh."),
    ("亡くなります", "なくなります", "nakunarimasu", "Meninggal dunia (sopan)", "Kata Kerja Dasar", "おじいさんが亡くなりました。", "Kakek telah meninggal dunia."),
    ("なくします", "なくします", "nakushimasu", "Kehilangan barang", "Kata Kerja Dasar", "財布をなくしました。", "Kehilangan dompet."),
    ("並びます", "ならびます", "narabimasu", "Mengantre berbaris", "Kata Kerja Dasar", "切符売り場に並びます。", "Mengantre di loket karcis."),
    ("並べます", "ならべます", "narabemasu", "Menata berjejer", "Kata Kerja Dasar", "本をきれいに並べます。", "Menata buku berjejer rapi."),
    ("習います", "ならいます", "naraimasu", "Belajar dari guru", "Kata Kerja Dasar", "茶道を習います。", "Belajar upacara minum teh."),
    ("鳴ります", "なります", "narimasu", "Berbunyi (bel/telepon)", "Kata Kerja Dasar", "チャイムが鳴りました。", "Bel telah berbunyi."),
    ("なります", "なります", "narimasu", "Menjadi / Berubah jadi", "Kata Kerja Dasar", "医者になりたいです。", "Ingin menjadi dokter."),
    ("脱ぎます", "ぬぎます", "nugimasu", "Membuka pakaian/sepatu", "Kata Kerja Dasar", "上着を脱ぎます。", "Membuka jaket."),
    ("寝ます", "ねます", "nemasu", "Tidur terlelap", "Kata Kerja Dasar", "十一時に寝ます。", "Tidur jam sebelas."),
    ("登ります", "のぼります", "noborimasu", "Mendaki gunung", "Kata Kerja Dasar", "山に登ります。", "Mendaki gunung."),
    ("飲みます", "のみます", "nomimasu", "Meminum cairan", "Kata Kerja Dasar", "冷たいジュースを飲みます。", "Minum jus dingin."),
    ("乗ります", "のります", "norimasu", "Menaiki armada kendaraan", "Kata Kerja Dasar", "電車に乗ります。", "Naik kereta listrik."),
    ("乗り換えます", "のりかえます", "norikaemasu", "Transit ganti kendaraan", "Kata Kerja Dasar", "地下鉄に乗り換えます。", "Transit ke kereta bawah tanah."),
    ("入ります", "はいります", "hairimasu", "Masuk ke dalam ruangan", "Kata Kerja Dasar", "お風呂に入ります。", "Masuk mandi berendam."),
    ("履きます", "はきます", "hakimasu", "Memakai celana/sepatu", "Kata Kerja Dasar", "靴を履きます。", "Memakai sepatu."),
    ("走ります", "はしります", "hashirimasu", "Berlari kencang", "Kata Kerja Dasar", "グラウンドを走ります。", "Berlari di lapangan."),
    ("始まります", "はじまります", "hajimarimasu", "Dimulai (acara)", "Kata Kerja Dasar", "試合が始まります。", "Pertandingan dimulai."),
    ("始めます", "はじめます", "hajimemasu", "Memulai kegiatan", "Kata Kerja Dasar", "勉強を始めます。", "Memulai belajar."),
    ("働きます", "はたらきます", "hatarakimasu", "Bekerja mencari nafkah", "Kata Kerja Dasar", "銀行で働きます。", "Bekerja di bank."),
    ("話します", "はなします", "hanashimasu", "Berbicara dengan orang", "Kata Kerja Dasar", "日本語で話します。", "Berbicara dalam bahasa Jepang."),
    ("払います", "はらいます", "haraimasu", "Membayar uang kasir", "Kata Kerja Dasar", "レジでお金を払います。", "Membayar uang di kasir."),
    ("晴れます", "はれます", "haremasu", "Langit menjadi cerah", "Kata Kerja Dasar", "空が晴れました。", "Langit telah cerah."),
    ("引きます", "ひきます", "hikimasu", "Menarik pintu/laci", "Kata Kerja Dasar", "ドアを引いて開けます。", "Menarik pintu untuk membuka."),
    ("弾きます", "ひきます", "hikimasu", "Memainkan instrumen piano", "Kata Kerja Dasar", "ピアノを弾きます。", "Memainkan piano."),
    ("吹きます", "ふきます", "fukimasu", "Bertiup (angin)", "Kata Kerja Dasar", "強い風が吹きます。", "Angin kencang bertiup."),
    ("降ります", "ふります", "furimasu", "Turun (hujan/salju)", "Kata Kerja Dasar", "雨が降ります。", "Hujan turun."),
    ("曲がります", "まがります", "magarimasu", "Belok arah rute", "Kata Kerja Dasar", "右へ曲がります。", "Belok ke kanan."),
    ("負けます", "まけます", "makemasu", "Kalah pertandingan", "Kata Kerja Dasar", "ゲームに負けました。", "Kalah dalam permainan."),
    ("待ちます", "まちます", "machimasu", "Menunggu seseorang", "Kata Kerja Dasar", "友達を待ちます。", "Menunggu teman."),
    ("回します", "まわします", "mawashimasu", "Memutar kenop/keran", "Kata Kerja Dasar", "水道の蛇口を回します。", "Memutar keran air."),
    ("見せます", "みせます", "misemasu", "Memperlihatkan barang", "Kata Kerja Dasar", "写真を見せてください。", "Tolong perlihatkan fotonya."),
    ("見ます", "みます", "mimasu", "Melihat / Menonton", "Kata Kerja Dasar", "テレビを見ます。", "Menonton televisi."),
    ("迎えます", "むかえます", "mukaemasu", "Menjemput / Menyambut", "Kata Kerja Dasar", "空港で友達を迎えます。", "Menjemput teman di bandara."),
    ("持ちます", "もちます", "mochimasu", "Membawa / Memegang", "Kata Kerja Dasar", "荷物を持ちます。", "Membawa barang bawaan."),
    ("持って行きます", "もっていきます", "motte ikimasu", "Membawa pergi barang", "Kata Kerja Dasar", "傘を持って行きます。", "Membawa payung pergi."),
    ("持って来ます", "もってきます", "motte kimasu", "Membawa kemari barang", "Kata Kerja Dasar", "本を持って来てください。", "Tolong bawa buku kemari."),
    ("もらいます", "もらいます", "moraimasu", "Menerima pemberian", "Kata Kerja Dasar", "お土産をもらいました。", "Mendapatkan oleh-oleh."),
    ("休みます", "やすみます", "yasumimasu", "Beristirahat / Izin libur", "Kata Kerja Dasar", "少し休みましょう。", "Mari beristirahat sebentar."),
    ("やめます", "やめます", "yamemasu", "Berhenti melakukan sesuatu", "Kata Kerja Dasar", "会社をやめます。", "Berhenti dari perusahaan."),
    ("呼びます", "よびます", "yobimasu", "Memanggil taksi/nama", "Kata Kerja Dasar", "タクシーを呼びます。", "Memanggil taksi."),
    ("読みます", "よみます", "yomimasu", "Membaca buku", "Kata Kerja Dasar", "本を読みます。", "Membaca buku."),
    ("予約します", "よやくします", "yoyakushimasu", "Memesan / Reservasi", "Kata Kerja Dasar", "新幹線を予約します。", "Memesan tiket Shinkansen."),
    ("練習します", "れんしゅうします", "renshuushimasu", "Berlatih / Latihan", "Kata Kerja Dasar", "漢字を練習します。", "Berlatih menulis kanji."),
    ("連絡します", "れんらくします", "renrakushimasu", "Menghubungi / Mengabari", "Kata Kerja Dasar", "メールで連絡します。", "Mengabari melalui email."),
    ("分かります", "わかります", "wakarimasu", "Mengerti / Paham arti", "Kata Kerja Dasar", "日本語が分かります。", "Mengerti bahasa Jepang."),
    ("忘れます", "わすれます", "wasuremasu", "Lupa ingatan", "Kata Kerja Dasar", "約束を忘れました。", "Lupa janji."),
    ("渡します", "わたします", "watashimasu", "Menyerahkan barang", "Kata Kerja Dasar", "プレゼントを渡します。", "Menyerahkan hadiah."),
    ("渡ります", "わたります", "watarimasu", "Menyeberang jalan/jembatan", "Kata Kerja Dasar", "道を渡ります。", "Menyeberangi jalan.")
]

# 2. KATA SIFAT (形容詞 - Minna no Nihongo 1-25)
N5_ADJECTIVES = [
    ("大きい", "おおきい", "ookii", "Besar", "Kata Sifat", "大きな家に住んでいます。", "Tinggal di rumah yang besar."),
    ("小さい", "ちいさい", "chiisai", "Kecil", "Kata Sifat", "小さい犬がいます。", "Ada anjing kecil."),
    ("新しい", "あたらしい", "atarashii", "Baru", "Kata Sifat", "新しい靴を買いました。", "Membeli sepatu baru."),
    ("古い", "ふるい", "furui", "Lama / Kuno / Tua", "Kata Sifat", "古い本を読みます。", "Membaca buku lama."),
    ("いい", "いい", "ii", "Bagus / Baik", "Kata Sifat", "今日はいい天気です。", "Hari ini cuaca bagus."),
    ("悪い", "わるい", "warui", "Buruk / Jelek", "Kata Sifat", "気分が悪いです。", "Merasa tidak enak badan."),
    ("暑い", "あつい", "atsui", "Panas (suhu cuaca)", "Kata Sifat", "夏はとても暑いです。", "Musim panas sangat panas."),
    ("熱い", "あつい", "atsui", "Panas (benda/minuman)", "Kata Sifat", "熱いお茶を飲みます。", "Minum teh panas."),
    ("寒い", "さむい", "samui", "Dingin (suhu cuaca)", "Kata Sifat", "冬はとても寒いです。", "Musim dingin sangat dingin."),
    ("冷たい", "つめたい", "tsumetai", "Dingin (benda/minuman)", "Kata Sifat", "冷たい水をください。", "Minta air dingin."),
    ("難しい", "むずかしい", "muzukashii", "Sukar / Sulit", "Kata Sifat", "漢字は難しいです。", "Kanji itu sulit."),
    ("易しい", "やさしい", "yasashii", "Mudah / Gampang", "Kata Sifat", "テストは易しかったです。", "Ujiannya mudah."),
    ("優しい", "やさしい", "yasashii", "Baik hati / Lemah lembut", "Kata Sifat", "優しい先生です。", "Guru yang baik hati."),
    ("高い", "たかい", "takai", "Tinggi / Mahal harganya", "Kata Sifat", "富士山は高い山です。", "Gunung Fuji adalah gunung yang tinggi."),
    ("安い", "やすい", "yasui", "Murah harganya", "Kata Sifat", "この店は安いです。", "Toko ini murah."),
    ("低い", "ひくい", "hikui", "Rendah kedudukan/suara", "Kata Sifat", "低い山に登ります。", "Mendaki gunung yang rendah."),
    ("面白い", "おもしろい", "omoshiroi", "Menarik / Lucu", "Kata Sifat", "面白い映画を見ました。", "Menonton film yang menarik."),
    ("美味しい", "おいしい", "oishii", "Enak / Lezat rasanya", "Kata Sifat", "この料理は美味しいです。", "Masakan ini lezat."),
    ("不味い", "まずい", "mazui", "Tidak enak rasanya", "Kata Sifat", "このスープは不味いです。", "Sup ini tidak enak."),
    ("忙しい", "いそがしい", "isogashii", "Sibuk banyak urusan", "Kata Sifat", "今日は仕事で忙しいです。", "Hari ini sibuk dengan pekerjaan."),
    ("楽しい", "たのしい", "tanoshii", "Menyenangkan / Gembira", "Kata Sifat", "パーティーは楽しかったです。", "Pestanya menyenangkan."),
    ("白い", "しろい", "shiroi", "Putih warnanya", "Kata Sifat", "白いシャツを着ます。", "Memakai kemeja putih."),
    ("黒い", "くろい", "kuroi", "Hitam warnanya", "Kata Sifat", "黒い靴を履きます。", "Memakai sepatu hitam."),
    ("赤い", "あかい", "akai", "Merah warnanya", "Kata Sifat", "赤いリンゴを食べます。", "Makan apel merah."),
    ("青い", "あおい", "aoi", "Biru warnanya", "Kata Sifat", "青い海がきれいです。", "Laut biru sangat indah."),
    ("黄色い", "きいろい", "kiiroi", "Kuning warnanya", "Kata Sifat", "黄色い傘を持っています。", "Membawa payung kuning."),
    ("茶色い", "ちゃいろい", "chairoi", "Cokelat warnanya", "Kata Sifat", "茶色い鞄を買いました。", "Membeli tas cokelat."),
    ("好き", "すき", "suki", "Suka / Gemar", "Kata Sifat", "日本料理が好きです。", "Saya suka masakan Jepang."),
    ("嫌い", "きらい", "kirai", "Benci / Tidak suka", "Kata Sifat", "納豆が嫌いです。", "Saya tidak suka natto."),
    ("上手", "じょうず", "jouzu", "Pandai / Mahir", "Kata Sifat", "歌が上手ですね。", "Pandai menyanyi ya."),
    ("下手", "へた", "heta", "Kurang pandai / Tidak mahir", "Kata Sifat", "絵が下手です。", "Kurang pandai menggambar."),
    ("綺麗", "きれい", "kirei", "Cantik / Bersih rapi", "Kata Sifat", "花が綺麗です。", "Bunganya indah."),
    ("静か", "しずか", "shizuka", "Tenang / Senyap", "Kata Sifat", "図書館は静かです。", "Perpustakaan itu tenang."),
    ("賑やか", "にぎやか", "nigiyaka", "Ramai meriah", "Kata Sifat", "東京は賑やかです。", "Tokyo sangat ramai."),
    ("有名", "ゆうめい", "yuumei", "Terkenal / Populer", "Kata Sifat", "有名な神社へ行きます。", "Pergi ke kuil terkenal."),
    ("親切", "しんせつ", "shinsetsu", "Ramah / Baik hati", "Kata Sifat", "親切な人に助けられました。", "Ditolong oleh orang yang ramah."),
    ("元気", "げんき", "genki", "Sehat bugar / Bersemangat", "Kata Sifat", "毎日元気です。", "Setiap hari sehat bersemangat."),
    ("暇", "ひま", "hima", "Senggang / Banyak waktu", "Kata Sifat", "明日は暇です。", "Besok saya senggang."),
    ("便利", "べんり", "benri", "Praktis / Memudahkan", "Kata Sifat", "コンビニは便利です。", "Minimarket sangat praktis."),
    ("不便", "ふべん", "fuben", "Tidak praktis / Merepotkan", "Kata Sifat", "駅から遠くて不便です。", "Jauh dari stasiun sehingga tidak praktis."),
    ("簡単", "かんたん", "kantan", "Sederhana / Mudah", "Kata Sifat", "簡単な問題です。", "Pertanyaan yang mudah."),
    ("近い", "ちかい", "chikai", "Dekat jaraknya", "Kata Sifat", "駅から近いです。", "Dekat dari stasiun."),
    ("遠い", "とおい", "tooi", "Jauh jaraknya", "Kata Sifat", "家から学校まで遠いです。", "Jauh dari rumah ke sekolah."),
    ("速い", "はやい", "hayai", "Cepat lajunya", "Kata Sifat", "新幹線は速いです。", "Shinkansen sangat cepat."),
    ("早い", "はやい", "hayai", "Awal pagi hari", "Kata Sifat", "朝早く起きます。", "Bangun pagi-pagi."),
    ("遅い", "おそい", "osoi", "Lambat / Terlambat", "Kata Sifat", "足が遅いです。", "Langkahnya lambat."),
    ("多い", "おおい", "ooi", "Banyak (kuantitas)", "Kata Sifat", "人が多いです。", "Banyak orang."),
    ("少ない", "すくない", "sukunai", "Sedikit (kuantitas)", "Kata Sifat", "雨が少ないです。", "Curah hujan sedikit."),
    ("暖かい", "あたたかい", "atatakai", "Hangat (cuaca udara)", "Kata Sifat", "春は暖かいです。", "Musim semi itu hangat."),
    ("温かい", "あたたかい", "atatakai", "Hangat (makanan/minuman)", "Kata Sifat", "温かいスープを飲みます。", "Minum sup hangat."),
    ("涼しい", "すずしい", "suzushii", "Sejuk semilir", "Kata Sifat", "秋は涼しいです。", "Musim gugur itu sejuk."),
    ("甘い", "あまい", "amai", "Manis rasanya", "Kata Sifat", "ケーキは甘いです。", "Kue ini manis."),
    ("辛い", "からい", "karai", "Pedas / Asin menusuk", "Kata Sifat", "辛いカレーが好きです。", "Suka kari pedas."),
    ("酸っぱい", "すっぱい", "suppai", "Asam rasanya", "Kata Sifat", "レモンは酸っぱいです。", "Lemon itu asam."),
    ("苦い", "にがい", "nigai", "Pahit rasanya", "Kata Sifat", "良薬は口に苦いです。", "Obat manjur terasa pahit di mulut."),
    ("塩辛い", "しおからい", "shiokarai", "Asin rasanya", "Kata Sifat", "塩辛いスープです。", "Sup yang asin."),
    ("重い", "おもい", "omoi", "Berat bobotnya", "Kata Sifat", "この荷物は重いです。", "Barang bawaan ini berat."),
    ("軽い", "かるい", "karui", "Ringan bobotnya", "Kata Sifat", "この鞄は軽いです。", "Tas ini ringan."),
    ("広い", "ひろい", "hiroi", "Luas / Lapang", "Kata Sifat", "部屋が広いです。", "Kamarnya luas."),
    ("狭い", "せまい", "semai", "Sempit ruangannya", "Kata Sifat", "部屋が狭いです。", "Kamarnya sempit."),
    ("若い", "わかい", "wakai", "Muda usianya", "Kata Sifat", "彼はまだ若いです。", "Dia masih muda."),
    ("長い", "ながい", "nagai", "Panjang ukurannya", "Kata Sifat", "髪が長いです。", "Rambutnya panjang."),
    ("短い", "みじかい", "mijikai", "Pendek ukurannya", "Kata Sifat", "スカートが短いです。", "Roknya pendek."),
    ("明るい", "あかるい", "akarui", "Terang / Ceria", "Kata Sifat", "明るい部屋です。", "Ruangan yang terang."),
    ("暗い", "くらい", "kurai", "Gelap / Muram", "Kata Sifat", "夜道は暗いです。", "Jalan malam itu gelap."),
    ("大切", "たいせつ", "taisetsu", "Penting / Berharga", "Kata Sifat", "時間は大切です。", "Waktu sangat berharga."),
    ("大丈夫", "だいじょうぶ", "daijoubu", "Tidak apa-apa / Aman", "Kata Sifat", "もう大丈夫です。", "Sudah tidak apa-apa."),
    ("危ない", "あぶない", "abunai", "Berbahaya risikonya", "Kata Sifat", "車道は危ないです。", "Badan jalan itu berbahaya."),
    ("欲しい", "ほしい", "hoshii", "Ingin / Mau punya", "Kata Sifat", "新しい時計が欲しいです。", "Saya ingin jam tangan baru."),
    ("寂しい", "さびしい", "sabishii", "Kesepian / Sepi", "Kata Sifat", "一人で寂しいです。", "Merasa kesepian sendirian."),
    ("眠い", "ねむい", "nemui", "Mengantuk", "Kata Sifat", "とても眠いです。", "Sangat mengantuk."),
    ("強い", "つよい", "tsuyoi", "Kuat / Tangguh", "Kata Sifat", "風が強いです。", "Angin bertiup kencang."),
    ("弱い", "よわい", "yowai", "Lemah tenaganya", "Kata Sifat", "力不足で弱いです。", "Tenaganya lemah."),
    ("素敵", "すてき", "suteki", "Bagus sekali / Menawan", "Kata Sifat", "素敵な服ですね。", "Pakaian yang sangat bagus ya."),
    ("痛い", "いたい", "itai", "Sakit / Nyeri", "Kata Sifat", "頭が痛いです。", "Kepala saya sakit."),
    ("太い", "ふとい", "futoi", "Tebal / Gemuk", "Kata Sifat", "太いペンで書きます。", "Menulis dengan pulpen tebal."),
    ("細い", "ほそい", "hosoi", "Ramping / Tipis halus", "Kata Sifat", "細い道を通ります。", "Melewati jalan sempit."),
    ("厚い", "あつい", "atsui", "Tebal (buku/kain)", "Kata Sifat", "厚い本を読みます。", "Membaca buku tebal."),
    ("薄い", "うすい", "usui", "Tipis (kertas/baju)", "Kata Sifat", "薄い紙に書きます。", "Menulis di kertas tipis."),
    ("丸い", "まるい", "marui", "Bulat bentuknya", "Kata Sifat", "丸いボールです。", "Bola yang bulat."),
    ("硬い", "かたい", "katai", "Keras teksturnya", "Kata Sifat", "硬いパンを食べます。", "Makan roti keras."),
    ("柔らかい", "やわらかい", "yawarakai", "Lembut / Empuk", "Kata Sifat", "柔らかいベッドで寝ます。", "Tidur di kasur yang empuk."),
    ("汚い", "きたない", "kitanai", "Kotor tidak rapi", "Kata Sifat", "部屋が汚いです。", "Kamarnya kotor."),
    ("同じ", "おなじ", "onaji", "Sama persis", "Kata Sifat", "同じ本を持っています。", "Memiliki buku yang sama."),
    ("違う", "ちがう", "chigau", "Berbeda sifatnya", "Kata Sifat", "意見が違います。", "Pendapatnya berbeda.")
]

# 3. PENUNJUK WAKTU DAN ANGKA (時間・数字 - Minna no Nihongo 1-25)
N5_TIME_NUMBERS = [
    ("一", "いち", "ichi", "Satu (1)", "Penunjuk Waktu dan Angka", "一円", "Satu yen."),
    ("二", "に", "ni", "Dua (2)", "Penunjuk Waktu dan Angka", "二月", "Bulan Februari."),
    ("三", "さん", "san", "Tiga (3)", "Penunjuk Waktu dan Angka", "三日", "Tanggal tiga."),
    ("四", "よん", "yon", "Empat (4)", "Penunjuk Waktu dan Angka", "四時", "Pukul empat."),
    ("五", "ご", "go", "Lima (5)", "Penunjuk Waktu dan Angka", "五人", "Lima orang."),
    ("六", "ろく", "roku", "Enam (6)", "Penunjuk Waktu dan Angka", "六階", "Lantai enam."),
    ("七", "なな", "nana", "Tujuh (7)", "Penunjuk Waktu dan Angka", "七時", "Pukul tujuh."),
    ("八", "はち", "hachi", "Delapan (8)", "Penunjuk Waktu dan Angka", "八月", "Bulan Agustus."),
    ("九", "きゅう", "kyuu", "Sembilan (9)", "Penunjuk Waktu dan Angka", "九時", "Pukul sembilan."),
    ("十", "じゅう", "juu", "Sepuluh (10)", "Penunjuk Waktu dan Angka", "十歳", "Usia sepuluh tahun."),
    ("十一", "じゅういち", "juuichi", "Sebelas (11)", "Penunjuk Waktu dan Angka", "十一月", "Bulan November."),
    ("十二", "じゅうに", "juuni", "Dua belas (12)", "Penunjuk Waktu dan Angka", "十二月", "Bulan Desember."),
    ("二十", "にじゅう", "nijuu", "Dua puluh (20)", "Penunjuk Waktu dan Angka", "二十歳", "Usia 20 tahun."),
    ("三十", "さんじゅう", "sanjuu", "Tiga puluh (30)", "Penunjuk Waktu dan Angka", "三十日", "Tanggal 30."),
    ("四十", "よんじゅう", "yonjuu", "Empat puluh (40)", "Penunjuk Waktu dan Angka", "四十人", "Empat puluh orang."),
    ("五十", "ごじゅう", "gojuu", "Lima puluh (50)", "Penunjuk Waktu dan Angka", "五十ページ", "Halaman 50."),
    ("百", "ひゃく", "hyaku", "Seratus (100)", "Penunjuk Waktu dan Angka", "百円", "Seratus yen."),
    ("二百", "にひゃく", "nihyaku", "Dua ratus (200)", "Penunjuk Waktu dan Angka", "二百メートル", "Dua ratus meter."),
    ("三百", "さんびゃく", "sanbyaku", "Tiga ratus (300)", "Penunjuk Waktu dan Angka", "三百円", "Tiga ratus yen."),
    ("六百", "ろっぴゃく", "roppyaku", "Enam ratus (600)", "Penunjuk Waktu dan Angka", "六百人", "Enam ratus orang."),
    ("八百", "はっぴゃく", "happyaku", "Delapan ratus (800)", "Penunjuk Waktu dan Angka", "八百円", "Delapan ratus yen."),
    ("千", "せん", "sen", "Seribu (1.000)", "Penunjuk Waktu dan Angka", "千円", "Seribu yen."),
    ("二千", "にせん", "nisen", "Dua ribu (2.000)", "Penunjuk Waktu dan Angka", "二千メートル", "Dua ribu meter."),
    ("三千", "さんぜん", "sanzen", "Tiga ribu (3.000)", "Penunjuk Waktu dan Angka", "三千人", "Tiga ribu orang."),
    ("八千", "はっせん", "hassen", "Delapan ribu (8.000)", "Penunjuk Waktu dan Angka", "八千円", "Delapan ribu yen."),
    ("万", "まん", "man", "Sepuluh ribu (10.000)", "Penunjuk Waktu dan Angka", "一万円", "Sepuluh ribu yen."),
    ("十万", "じゅうまん", "juuman", "Seratus ribu (100.000)", "Penunjuk Waktu dan Angka", "十万人", "Seratus ribu orang."),
    ("一つ", "ひとつ", "hitotsu", "Satu buah", "Penunjuk Waktu dan Angka", "リンゴを一つください。", "Minta satu buah apel."),
    ("二つ", "ふたつ", "futatsu", "Dua buah", "Penunjuk Waktu dan Angka", "パンを二つ買いました。", "Membeli dua buah roti."),
    ("三つ", "みっつ", "mittsu", "Tiga buah", "Penunjuk Waktu dan Angka", "箱が三つあります。", "Ada tiga buah kotak."),
    ("四つ", "よっつ", "yottsu", "Empat buah", "Penunjuk Waktu dan Angka", "みかんを四つ食べました。", "Makan empat buah jeruk."),
    ("五つ", "いつつ", "itsutsu", "Lima buah", "Penunjuk Waktu dan Angka", "卵が五つあります。", "Ada lima butir telur."),
    ("六つ", "むっつ", "muttsu", "Enam buah", "Penunjuk Waktu dan Angka", "椅子が六つあります。", "Ada enam buah kursi."),
    ("七つ", "ななつ", "nanatsu", "Tujuh buah", "Penunjuk Waktu dan Angka", "机が七つあります。", "Ada tujuh buah meja."),
    ("八つ", "やっつ", "yattsu", "Delapan buah", "Penunjuk Waktu dan Angka", "ノートが八つあります。", "Ada delapan buah buku catatan."),
    ("九つ", "ここのつ", "kokonotsu", "Sembilan buah", "Penunjuk Waktu dan Angka", "鞄が九つあります。", "Ada sembilan buah tas."),
    ("十", "とお", "too", "Sepuluh buah", "Penunjuk Waktu dan Angka", "お菓子を十個買いました。", "Membeli sepuluh buah kue."),
    ("一人", "ひとり", "hitori", "Satu orang / Sendirian", "Penunjuk Waktu dan Angka", "一人で行きます。", "Pergi sendirian."),
    ("二人", "ふたり", "futari", "Dua orang", "Penunjuk Waktu dan Angka", "二人で食べます。", "Makan berdua."),
    ("三人", "さんにん", "sannin", "Tiga orang", "Penunjuk Waktu dan Angka", "学生が三人います。", "Ada tiga orang murid."),
    ("四人", "よにん", "yonin", "Empat orang", "Penunjuk Waktu dan Angka", "家族は四人です。", "Keluarga saya empat orang."),
    ("五人", "ごにん", "gonin", "Lima orang", "Penunjuk Waktu dan Angka", "五人で旅行します。", "Berwisata lima orang."),
    ("一枚", "いちまい", "ichimai", "Satu lembar (kertas/baju)", "Penunjuk Waktu dan Angka", "シャツを一枚買います。", "Membeli selembar kemeja."),
    ("一本", "いっぽん", "ippon", "Satu batang/botol", "Penunjuk Waktu dan Angka", "ペンを一本貸してください。", "Tolong pinjamkan sebatang pulpen."),
    ("二本", "にほん", "nihon", "Dua batang/botol", "Penunjuk Waktu dan Angka", "ビールを二本飲みました。", "Minum dua botol bir."),
    ("三本", "さんぼん", "sanbon", "Tiga batang/botol", "Penunjuk Waktu dan Angka", "木が三本あります。", "Ada tiga batang pohon."),
    ("一冊", "いっさつ", "issatsu", "Satu jilid buku", "Penunjuk Waktu dan Angka", "本を一冊買いました。", "Membeli satu jilid buku."),
    ("一台", "いちだい", "ichidai", "Satu unit mesin/mobil", "Penunjuk Waktu dan Angka", "車が一台あります。", "Ada satu unit mobil."),
    ("一階", "いっかい", "ikkai", "Lantai satu", "Penunjuk Waktu dan Angka", "一階に受付があります。", "Di lantai satu ada resepsionis."),
    ("一回", "いっかい", "ikkai", "Satu kali", "Penunjuk Waktu dan Angka", "一回行きました。", "Pernah pergi satu kali."),
    ("今", "いま", "ima", "Sekarang / Saat ini", "Penunjuk Waktu dan Angka", "今何時ですか。", "Sekarang jam berapa?"),
    ("一時", "いちじ", "ichiji", "Pukul satu (01.00)", "Penunjuk Waktu dan Angka", "一時に始まります。", "Dimulai pukul 01.00."),
    ("二時", "にじ", "niji", "Pukul dua (02.00)", "Penunjuk Waktu dan Angka", "二時に集合します。", "Berkumpul pukul 02.00."),
    ("三時", "さんじ", "sanji", "Pukul tiga (03.00)", "Penunjuk Waktu dan Angka", "三時のおやつです。", "Kudapan pukul 03.00."),
    ("四時", "よじ", "yoji", "Pukul empat (04.00)", "Penunjuk Waktu dan Angka", "四時に終わります。", "Selesai pukul 04.00."),
    ("五時", "ごじ", "goji", "Pukul lima (05.00)", "Penunjuk Waktu dan Angka", "五時に起きます。", "Bangun pukul 05.00."),
    ("六時", "ろくじ", "rokuji", "Pukul enam (06.00)", "Penunjuk Waktu dan Angka", "六時に帰ります。", "Pulang pukul 06.00."),
    ("七時", "しちじ", "shichiji", "Pukul tujuh (07.00)", "Penunjuk Waktu dan Angka", "七時に食べます。", "Makan pukul 07.00."),
    ("八時", "はちじ", "hachiji", "Pukul delapan (08.00)", "Penunjuk Waktu dan Angka", "八時に出勤します。", "Berangkat kerja pukul 08.00."),
    ("九時", "くじ", "kuji", "Pukul sembilan (09.00)", "Penunjuk Waktu dan Angka", "九時に授業が始まります。", "Pelajaran dimulai pukul 09.00."),
    ("十時", "じゅうじ", "juuji", "Pukul sepuluh (10.00)", "Penunjuk Waktu dan Angka", "十時に寝ます。", "Tidur pukul 10.00."),
    ("十一時", "じゅういちじ", "juuichiji", "Pukul sebelas (11.00)", "Penunjuk Waktu dan Angka", "十一時です。", "Pukul 11.00."),
    ("十二時", "じゅうにじ", "juuniji", "Pukul dua belas (12.00)", "Penunjuk Waktu dan Angka", "十二時にお昼ご飯を食べます。", "Makan siang pukul 12.00."),
    ("一分", "いっぷん", "ippun", "Satu menit", "Penunjuk Waktu dan Angka", "一分待ってください。", "Tolong tunggu satu menit."),
    ("五分", "ごふん", "gofun", "Lima menit", "Penunjuk Waktu dan Angka", "五分休憩します。", "Istirahat lima menit."),
    ("十分", "じゅっぷん", "juppun", "Sepuluh menit", "Penunjuk Waktu dan Angka", "十分かかります。", "Memakan waktu sepuluh menit."),
    ("十五分", "じゅうごふん", "juugofun", "Lima belas menit", "Penunjuk Waktu dan Angka", "十五分歩きます。", "Berjalan kaki lima belas menit."),
    ("三十分", "さんじゅっぷん", "sanjuppun", "Tiga puluh menit", "Penunjuk Waktu dan Angka", "三十分休みます。", "Istirahat tiga puluh menit."),
    ("半", "はん", "han", "Setengah (30 menit)", "Penunjuk Waktu dan Angka", "二時半です。", "Pukul dua lewat tiga puluh menit."),
    ("午前", "ごぜん", "gozen", "Pagi hari (a.m.)", "Penunjuk Waktu dan Angka", "午前九時です。", "Pukul 09.00 pagi."),
    ("午後", "ごご", "gogo", "Sore/Malam (p.m.)", "Penunjuk Waktu dan Angka", "午後三時です。", "Pukul 03.00 sore."),
    ("朝", "あさ", "asa", "Pagi hari", "Penunjuk Waktu dan Angka", "毎朝ジョギングします。", "Setiap pagi joging."),
    ("昼", "ひる", "hiru", "Siang hari", "Penunjuk Waktu dan Angka", "お昼休みです。", "Istirahat siang."),
    ("晩", "ばん", "ban", "Malam hari", "Penunjuk Waktu dan Angka", "晩ご飯を食べます。", "Makan malam."),
    ("夜", "よる", "yoru", "Malam hari (larut)", "Penunjuk Waktu dan Angka", "夜寝ます。", "Tidur di malam hari."),
    ("一昨日", "おととい", "ototoi", "Kemarin lusa", "Penunjuk Waktu dan Angka", "一昨日日本に着きました。", "Tiba di Jepang kemarin lusa."),
    ("昨日", "きのう", "kinou", "Kemarin", "Penunjuk Waktu dan Angka", "昨日は雨でした。", "Kemarin turun hujan."),
    ("今日", "きょう", "kyou", "Hari ini", "Penunjuk Waktu dan Angka", "今日はいい天気です。", "Hari ini cuaca cerah."),
    ("明日", "あした", "ashita", "Besok", "Penunjuk Waktu dan Angka", "明日テストがあります。", "Besok ada ujian."),
    ("明後日", "あさって", "asatte", "Lusa", "Penunjuk Waktu dan Angka", "明後日会いましょう。", "Mari bertemu lusa."),
    ("今朝", "けさ", "kesa", "Tadi pagi", "Penunjuk Waktu dan Angka", "今朝パンを食べました。", "Tadi pagi makan roti."),
    ("今晩", "こんばん", "konban", "Malam ini", "Penunjuk Waktu dan Angka", "今晩映画を見ます。", "Malam ini menonton film."),
    ("毎朝", "まいあさ", "maiasa", "Setiap pagi", "Penunjuk Waktu dan Angka", "毎朝新聞を読みます。", "Setiap pagi membaca koran."),
    ("毎晩", "まいばん", "maiban", "Setiap malam", "Penunjuk Waktu dan Angka", "毎晩勉強します。", "Setiap malam belajar."),
    ("毎日", "まいにち", "mainichi", "Setiap hari", "Penunjuk Waktu dan Angka", "毎日運動します。", "Setiap hari berolahraga."),
    ("月曜日", "げつようび", "getsuyoubi", "Hari Senin", "Penunjuk Waktu dan Angka", "月曜日に始まります。", "Dimulai pada hari Senin."),
    ("火曜日", "かようび", "kayoubi", "Hari Selasa", "Penunjuk Waktu dan Angka", "火曜日は休みです。", "Hari Selasa libur."),
    ("水曜日", "すいようび", "suiyoubi", "Hari Rabu", "Penunjuk Waktu dan Angka", "水曜日に買い物します。", "Berbelanja pada hari Rabu."),
    ("木曜日", "もくようび", "mokuyoubi", "Hari Kamis", "Penunjuk Waktu dan Angka", "木曜日に会議があります。", "Ada rapat pada hari Kamis."),
    ("金曜日", "きんようび", "kinyoubi", "Hari Jumat", "Penunjuk Waktu dan Angka", "金曜日の夜に出かけます。", "Bepergian pada Jumat malam."),
    ("土曜日", "どようび", "doyoubi", "Hari Sabtu", "Penunjuk Waktu dan Angka", "土曜日はパーティーです。", "Hari Sabtu ada pesta."),
    ("日曜日", "にちようび", "nichiyoubi", "Hari Minggu", "Penunjuk Waktu dan Angka", "日曜日に休みます。", "Beristirahat hari Minggu."),
    ("先週", "せんしゅう", "senshuu", "Minggu lalu", "Penunjuk Waktu dan Angka", "先週旅行しました。", "Berwisata minggu lalu."),
    ("今週", "こんしゅう", "konshuu", "Minggu ini", "Penunjuk Waktu dan Angka", "今週は忙しいです。", "Minggu ini sangat sibuk."),
    ("来週", "らいしゅう", "raishuu", "Minggu depan", "Penunjuk Waktu dan Angka", "来週日本へ行きます。", "Pergi ke Jepang minggu depan."),
    ("先月", "せんげつ", "sengetsu", "Bulan lalu", "Penunjuk Waktu dan Angka", "先月車を買いました。", "Membeli mobil bulan lalu."),
    ("今月", "こんげつ", "kongetsu", "Bulan ini", "Penunjuk Waktu dan Angka", "今月の給料です。", "Gaji bulan ini."),
    ("来月", "らいげつ", "raigetsu", "Bulan depan", "Penunjuk Waktu dan Angka", "来月引っ越します。", "Pindah rumah bulan depan."),
    ("去年", "きょねん", "kyonen", "Tahun lalu", "Penunjuk Waktu dan Angka", "去年大学を卒業しました。", "Lulus kuliah tahun lalu."),
    ("今年", "ことし", "kotoshi", "Tahun ini", "Penunjuk Waktu dan Angka", "今年二十歳になります。", "Tahun ini berusia 20 tahun."),
    ("来年", "らいねん", "rainen", "Tahun depan", "Penunjuk Waktu dan Angka", "来年留学します。", "Studi ke luar negeri tahun depan."),
    ("一日", "ついたち", "tsuitachi", "Tanggal 1", "Penunjuk Waktu dan Angka", "一月一日", "Tanggal satu Januari."),
    ("二日", "ふつか", "futsuka", "Tanggal 2 / 2 hari", "Penunjuk Waktu dan Angka", "二日間休みます。", "Libur dua hari."),
    ("三日", "みっか", "mikka", "Tanggal 3 / 3 hari", "Penunjuk Waktu dan Angka", "三日後に会います。", "Bertemu tiga hari lagi."),
    ("四日", "よっか", "yokka", "Tanggal 4 / 4 hari", "Penunjuk Waktu dan Angka", "四月四日", "Tanggal empat April."),
    ("五日", "いつか", "itsuka", "Tanggal 5 / 5 hari", "Penunjuk Waktu dan Angka", "五月五日", "Tanggal lima Mei."),
    ("六日", "むいか", "muika", "Tanggal 6 / 6 hari", "Penunjuk Waktu dan Angka", "六月六日", "Tanggal enam Juni."),
    ("七日", "なのか", "nanoka", "Tanggal 7 / 7 hari", "Penunjuk Waktu dan Angka", "七月七日", "Tanggal tujuh Juli."),
    ("八日", "ようか", "youka", "Tanggal 8 / 8 hari", "Penunjuk Waktu dan Angka", "八月八日", "Tanggal delapan Agustus."),
    ("九日", "ここのか", "kokonoka", "Tanggal 9 / 9 hari", "Penunjuk Waktu dan Angka", "九月九日", "Tanggal sembilan September."),
    ("十日", "とおか", "tooka", "Tanggal 10 / 10 hari", "Penunjuk Waktu dan Angka", "十日間滞在します。", "Tinggal selama sepuluh hari."),
    ("十四日", "じゅうよっか", "juuyokka", "Tanggal 14", "Penunjuk Waktu dan Angka", "二月十四日", "Tanggal 14 Februari."),
    ("二十日", "はつか", "hatsuka", "Tanggal 20", "Penunjuk Waktu dan Angka", "毎月二十日", "Setiap tanggal 20."),
    ("二十四日", "にじゅうよっか", "nijuuyokka", "Tanggal 24", "Penunjuk Waktu dan Angka", "十二月二十四日", "Tanggal 24 Desember."),
    ("一週間", "いっしゅうかん", "isshuukan", "Satu minggu (durasi)", "Penunjuk Waktu dan Angka", "一週間旅行します。", "Berwisata selama satu minggu."),
    ("一か月", "いっかげつ", "ikkagetsu", "Satu bulan (durasi)", "Penunjuk Waktu dan Angka", "一か月勉強しました。", "Belajar selama satu bulan."),
    ("一年", "いちねん", "ichinen", "Satu tahun (durasi)", "Penunjuk Waktu dan Angka", "日本に一年います。", "Ada di Jepang selama satu tahun.")
]

# 4. KATA TANYA DAN KATA GANTI (疑問詞・代名詞 - Minna no Nihongo 1-25)
N5_INTERROGATIVES_PRONOUNS = [
    ("私", "わたし", "watashi", "Saya / Aku", "Kata Tanya dan Kata Ganti", "私は学生です。", "Saya adalah seorang pelajar."),
    ("あなた", "あなた", "anata", "Anda / Kamu", "Kata Tanya dan Kata Ganti", "あなたは先生ですか。", "Apakah Anda seorang guru?"),
    ("あの人", "あのひと", "ano hito", "Orang itu (netral)", "Kata Tanya dan Kata Ganti", "あの人は誰ですか。", "Siapakah orang itu?"),
    ("あの方", "あのかた", "ano kata", "Orang itu (sopan)", "Kata Tanya dan Kata Ganti", "あの方はどなたですか。", "Siapakah beliau itu?"),
    ("誰", "だれ", "dare", "Siapa", "Kata Tanya dan Kata Ganti", "誰と行きますか。", "Pergi dengan siapa?"),
    ("どなた", "どなた", "donata", "Siapa (bentuk sopan)", "Kata Tanya dan Kata Ganti", "どなたですか。", "Dengan siapa ya?"),
    ("何", "なに", "nani", "Apa", "Kata Tanya dan Kata Ganti", "これは何ですか。", "Ini apa?"),
    ("何時", "なんじ", "nanji", "Jam berapa", "Kata Tanya dan Kata Ganti", "今何時ですか。", "Sekarang jam berapa?"),
    ("何分", "なんぷん", "nanpun", "Berapa menit", "Kata Tanya dan Kata Ganti", "あと何分ですか。", "Tinggal berapa menit lagi?"),
    ("何歳", "なんさい", "nansai", "Berapa umurnya", "Kata Tanya dan Kata Ganti", "おいくつですか。", "Berapa usia Anda?"),
    ("何人", "なんにん", "nannin", "Berapa orang", "Kata Tanya dan Kata Ganti", "何人いますか。", "Ada berapa orang?"),
    ("何月", "なんがつ", "nangatsu", "Bulan apa", "Kata Tanya dan Kata Ganti", "誕生日は何月ですか。", "Ulang tahun di bulan apa?"),
    ("何日", "なんにち", "nannichi", "Tanggal berapa / Berapa hari", "Kata Tanya dan Kata Ganti", "今日は何日ですか。", "Hari ini tanggal berapa?"),
    ("何曜日", "なんようび", "nanyoubi", "Hari apa", "Kata Tanya dan Kata Ganti", "明日は何曜日ですか。", "Besok hari apa?"),
    ("何番", "なんばん", "nanban", "Nomor berapa", "Kata Tanya dan Kata Ganti", "電話番号は何番ですか。", "Nomor teleponnya berapa?"),
    ("どこ", "どこ", "doko", "Di mana / Ke mana", "Kata Tanya dan Kata Ganti", "トイレはどこですか。", "Toilet ada di mana?"),
    ("どちら", "どちら", "dochira", "Sebelah mana / Yang mana (sopan)", "Kata Tanya dan Kata Ganti", "お国はどちらですか。", "Negara asal Anda dari mana?"),
    ("どっち", "どっち", "dotchi", "Sebelah mana (informal)", "Kata Tanya dan Kata Ganti", "どっちがいいですか。", "Sebelah mana yang bagus?"),
    ("いつ", "いつ", "itsu", "Kapan", "Kata Tanya dan Kata Ganti", "いつ日本へ来ましたか。", "Kapan Anda datang ke Jepang?"),
    ("どうして", "どうして", "doushite", "Mengapa / Kenapa", "Kata Tanya dan Kata Ganti", "どうして遅れましたか。", "Mengapa Anda terlambat?"),
    ("なぜ", "なぜ", "naze", "Mengapa (formal)", "Kata Tanya dan Kata Ganti", "なぜですか。", "Mengapa begitu?"),
    ("どう", "どう", "dou", "Bagaimana", "Kata Tanya dan Kata Ganti", "日本の生活はどうですか。", "Bagaimana kehidupan di Jepang?"),
    ("いかが", "いかが", "ikaga", "Bagaimana (sopan)", "Kata Tanya dan Kata Ganti", "お茶はいかがですか。", "Bagaimana dengan secangkir teh?"),
    ("どんな", "どんな", "donna", "Yang bagaimana / Seperti apa", "Kata Tanya dan Kata Ganti", "どんな映画が好きですか。", "Film seperti apa yang Anda sukai?"),
    ("どれ", "どれ", "dore", "Yang mana (pilihan benda)", "Kata Tanya dan Kata Ganti", "あなたの傘はどれですか。", "Payungmu yang mana?"),
    ("どの", "どの", "dono", "Yang mana (+ kata benda)", "Kata Tanya dan Kata Ganti", "どの本ですか。", "Buku yang mana?"),
    ("いくら", "いくら", "ikura", "Berapa harganya", "Kata Tanya dan Kata Ganti", "これはいくらですか。", "Ini berapa harganya?"),
    ("いくつ", "いくつ", "ikutsu", "Berapa buah / Berapa usia", "Kata Tanya dan Kata Ganti", "ミカンはいくつありますか。", "Ada berapa buah jeruk?"),
    ("どのくらい", "どのくらい", "donokurai", "Berapa lama / Berapa jauh", "Kata Tanya dan Kata Ganti", "どのくらいかかりますか。", "Memakan waktu berapa lama?"),
    ("これ", "これ", "kore", "Ini (dekat pembicara)", "Kata Tanya dan Kata Ganti", "これは私のペンです。", "Ini adalah pulpen saya."),
    ("それ", "それ", "sore", "Itu (dekat lawan bicara)", "Kata Tanya dan Kata Ganti", "それは何ですか。", "Itu apa?"),
    ("あれ", "あれ", "are", "Itu (jauh dari keduanya)", "Kata Tanya dan Kata Ganti", "あれは富士山です。", "Itu adalah Gunung Fuji."),
    ("この", "この", "kono", "Ini (+ kata benda)", "Kata Tanya dan Kata Ganti", "この本は面白いです。", "Buku ini menarik."),
    ("その", "その", "sono", "Itu (+ kata benda)", "Kata Tanya dan Kata Ganti", "その辞書をください。", "Tolong beri kamus itu."),
    ("あの", "あの", "ano", "Itu (+ kata benda, jauh)", "Kata Tanya dan Kata Ganti", "あの建物は病院です。", "Bangunan itu adalah rumah sakit."),
    ("ここ", "ここ", "koko", "Di sini (dekat pembicara)", "Kata Tanya dan Kata Ganti", "ここは教室です。", "Di sini adalah ruang kelas."),
    ("そこ", "そこ", "soko", "Di situ (dekat lawan bicara)", "Kata Tanya dan Kata Ganti", "そこに置いてください。", "Tolong taruh di situ."),
    ("あそこ", "あそこ", "asoko", "Di sana (jauh)", "Kata Tanya dan Kata Ganti", "あそこに駅があります。", "Di sana ada stasiun."),
    ("こちら", "こちら", "kochira", "Sebelah sini / Pihak kami (sopan)", "Kata Tanya dan Kata Ganti", "こちらへどうぞ。", "Silakan lewat sebelah sini."),
    ("そちら", "そちら", "sochira", "Sebelah situ / Pihak Anda (sopan)", "Kata Tanya dan Kata Ganti", "そちらはいかがですか。", "Bagaimana dengan pihak Anda?"),
    ("あちら", "あちら", "achira", "Sebelah sana (sopan)", "Kata Tanya dan Kata Ganti", "あちらは受付です。", "Sebelah sana adalah meja resepsionis."),
    ("こっち", "こっち", "kotchi", "Sini (informal)", "Kata Tanya dan Kata Ganti", "こっちにおいで。", "Kemarilah ke sini."),
    ("そっち", "そっち", "sotchi", "Situ (informal)", "Kata Tanya dan Kata Ganti", "そっちを見て。", "Lihatlah ke situ."),
    ("あっち", "あっち", "atchi", "Sana (informal)", "Kata Tanya dan Kata Ganti", "あっちへ行こう。", "Ayo pergi ke sana."),
    ("彼", "かれ", "kare", "Dia (laki-laki) / Pacar", "Kata Tanya dan Kata Ganti", "彼は私の先生です。", "Dia adalah guru saya."),
    ("彼女", "かのじょ", "kanojo", "Dia (perempuan) / Pacar", "Kata Tanya dan Kata Ganti", "彼女は親切です。", "Dia sangat ramah."),
    ("私たち", "わたしたち", "watashitachi", "Kami / Kita", "Kata Tanya dan Kata Ganti", "私たちは学生です。", "Kami adalah pelajar."),
    ("皆さん", "みなさん", "minasan", "Semuanya / Hadirin sekalian", "Kata Tanya dan Kata Ganti", "皆さん、おはようございます。", "Selamat pagi semuanya."),
    ("僕", "ぼく", "boku", "Aku (pria informal)", "Kata Tanya dan Kata Ganti", "僕も行きます。", "Aku juga ikut pergi."),
    ("君", "きみ", "kimi", "Kamu (akrab)", "Kata Tanya dan Kata Ganti", "君の名前は何？", "Siapa namamu?"),
    ("自分", "じぶん", "jibun", "Diri sendiri", "Kata Tanya dan Kata Ganti", "自分で作りました。", "Membuatnya sendiri.")
]

# 5. SALAM DAN UNGKAPAN PERCAKAPAN (挨拶・表現 - Minna no Nihongo 1-25)
N5_GREETINGS = [
    ("おはようございます", "おはようございます", "ohayou gozaimasu", "Selamat pagi (sopan)", "Salam dan Percakapan", "先生、おはようございます。", "Selamat pagi, Pak/Bu Guru."),
    ("おはよう", "おはよう", "ohayou", "Selamat pagi (akrab)", "Salam dan Percakapan", "おはよう、元気？", "Pagi, apa kabar?"),
    ("こんにちは", "こんにちは", "konnichiwa", "Selamat siang / Halo", "Salam dan Percakapan", "皆さん、こんにちは。", "Halo semuanya, selamat siang."),
    ("こんばんは", "こんばんは", "konbanwa", "Selamat malam santai", "Salam dan Percakapan", "こんばんは、お元気ですか。", "Selamat malam, apa kabar?"),
    ("おやすみなさい", "おやすみなさい", "oyasuminasai", "Selamat tidur / Selamat beristirahat", "Salam dan Percakapan", "おやすみなさい、また明日。", "Selamat malam beristirahat, sampai besok."),
    ("さようなら", "さようなら", "sayounara", "Selamat tinggal perpisahan", "Salam dan Percakapan", "先生、さようなら。", "Selamat tinggal, Guru."),
    ("ありがとうございます", "ありがとうございます", "arigatou gozaimasu", "Terima kasih banyak (sopan)", "Salam dan Percakapan", "親切にありがとうございます。", "Terima kasih banyak atas kebaikannya."),
    ("どうもありがとうございます", "どうもありがとうございます", "doumo arigatou gozaimasu", "Terima kasih banyak tak terhingga", "Salam dan Percakapan", "本当にどうもありがとうございます。", "Benar-benar terima kasih banyak."),
    ("どうも", "どうも", "doumo", "Terima kasih / Halo singkat", "Salam dan Percakapan", "どうもすみません。", "Terima kasih banyak / Mohon maaf."),
    ("すみません", "すみません", "sumimasen", "Permisi / Maaf memohon", "Salam dan Percakapan", "すみません、駅はどこですか。", "Permisi, stasiun di mana?"),
    ("ごめんなさい", "ごめんなさい", "gomen nasai", "Mohon maaf santun", "Salam dan Percakapan", "遅れてごめんなさい。", "Mohon maaf saya terlambat."),
    ("失礼ですが", "しつれいですが", "shitsurei desu ga", "Permisi maaf sebelumnya...", "Salam dan Percakapan", "失礼ですが、お名前は？", "Permisi maaf, siapa nama Anda?"),
    ("失礼します", "しつれいします", "shitsurei shimasu", "Permisi masuk / Pamit pulang", "Salam dan Percakapan", "先生、失礼します。", "Permisi Guru, saya pamit."),
    ("はじめまして", "はじめまして", "hajimemashite", "Senang berkenalan (pertemuan awal)", "Salam dan Percakapan", "はじめまして、アリです。", "Senang berkenalan, saya Ari."),
    ("どうぞよろしくお願いします", "どうぞよろしくおねがいします", "douzo yoroshiku onegaishimasu", "Mohon bimbingan dan kerja samanya", "Salam dan Percakapan", "これからどうぞよろしくお願いします。", "Mulai sekarang mohon bantuannya."),
    ("どうぞよろしく", "どうぞよろしく", "douzo yoroshiku", "Mohon kerja samanya (singkat)", "Salam dan Percakapan", "どうぞよろしく。", "Mohon bantuannya ya."),
    ("お願いします", "おねがいします", "onegaishimasu", "Tolong / Mohon bantuannya", "Salam dan Percakapan", "お水を一杯お願いします。", "Tolong segelas air."),
    ("いただきます", "いただきます", "itadakimasu", "Selamat makan (ungkapan syukur)", "Salam dan Percakapan", "手を合わせていただきますと言います。", "Menangkupkan tangan dan mengucap selamat makan."),
    ("ごちそうさまでした", "ごちそうさまでした", "gochisousama deshita", "Terima kasih atas hidangannya", "Salam dan Percakapan", "美味しかったです。ごちそうさまでした。", "Sangat enak. Terima kasih atas hidangannya."),
    ("行ってきます", "いってきます", "itte kimasu", "Saya berangkat dulu (dari rumah)", "Salam dan Percakapan", "学校へ行ってきます。", "Saya berangkat ke sekolah dulu ya."),
    ("行ってらっしゃい", "いってらっしゃい", "itterasshai", "Hati-hati di jalan (melepas)", "Salam dan Percakapan", "車に気をつけて行ってらっしゃい。", "Hati-hati di jalan ya."),
    ("ただいま", "ただいま", "tadaima", "Saya pulang (sampai di rumah)", "Salam dan Percakapan", "ただいま帰りました。", "Saya sudah pulang ke rumah."),
    ("お帰りなさい", "おかえりなさい", "okaerinasai", "Selamat datang kembali di rumah", "Salam dan Percakapan", "お帰りなさい、お疲れ様。", "Selamat datang kembali, terima kasih atas lelahmu."),
    ("お疲れ様でした", "おつかれさまでした", "otsukaresama deshita", "Terima kasih atas kerja kerasnya", "Salam dan Percakapan", "今日の仕事はお疲れ様でした。", "Terima kasih atas kerja keras hari ini."),
    ("お大事に", "おだいじに", "odaiji ni", "Semoga lekas sembuh (kepada orang sakit)", "Salam dan Percakapan", "風邪ですね。お大事に。", "Masuk angin ya. Semoga lekas sembuh."),
    ("乾杯", "かんぱい", "kanpai", "Bersulang minuman (cheers)", "Salam dan Percakapan", "グラスを持って乾杯します。", "Mengangkat gelas dan bersulang."),
    ("じゃ、また", "じゃ、また", "ja, mata", "Sampai jumpa lagi (akrab)", "Salam dan Percakapan", "じゃ、また明日会いましょう。", "Sampai jumpa besok ya."),
    ("また会いましょう", "またあいましょう", "mata aimashou", "Sampai berjumpa kembali", "Salam dan Percakapan", "来週また会いましょう。", "Sampai jumpa lagi minggu depan."),
    ("どういたしまして", "どういたしまして", "dou itashimashite", "Sama-sama / Kembali", "Salam dan Percakapan", "いいえ、どういたしまして。", "Tidak apa-apa, sama-sama."),
    ("おめでとうございます", "おめでとうございます", "omedetou gozaimasu", "Selamat atas keberhasilan / Ulang tahun", "Salam dan Percakapan", "お誕生日おめでとうございます。", "Selamat ulang tahun."),
    ("いらっしゃいませ", "いらっしゃいませ", "irasshaimase", "Selamat datang di toko/restoran", "Salam dan Percakapan", "いらっしゃいませ、何名様ですか。", "Selamat datang, untuk berapa orang?"),
    ("かしこまりました", "かしこまりました", "kashikomarimashita", "Dimengerti / Siap laksanakan", "Salam dan Percakapan", "かしこまりました、すぐお持ちします。", "Dimengerti, segera saya bawakan."),
    ("少々お待ちください", "しょうしょうおまちください", "shoushou omachi kudasai", "Mohon tunggu sebentar (sopan)", "Salam dan Percakapan", "少々お待ちくださいませ。", "Mohon tunggu sebentar ya."),
    ("いいですね", "いいですね", "ii desu ne", "Ide yang bagus ya", "Salam dan Percakapan", "そうしましょう、いいですね。", "Ayo lakukan begitu, ide bagus ya."),
    ("残念ですね", "ざんねんですね", "zannen desu ne", "Sayang sekali ya", "Salam dan Percakapan", "行けなくて残念ですね。", "Sayang sekali tidak bisa pergi ya."),
    ("お世話になりました", "おせわになりました", "osewa ni narimashita", "Terima kasih atas bantuan selama ini", "Salam dan Percakapan", "大変お世話になりました。", "Terima kasih banyak atas segala bantuannya."),
    ("どうぞお入りください", "どうぞおはいりください", "douzo ohairi kudasai", "Silakan masuk ke dalam", "Salam dan Percakapan", "どうぞお入りください。", "Silakan masuk ke dalam."),
    ("どうぞお上がりください", "どうぞおあがりください", "douzo oagari kudasai", "Silakan naik masuk rumah", "Salam dan Percakapan", "靴を脱いでお上がりください。", "Silakan lepas sepatu dan masuk ke rumah.")
]

# 6. KATA BENDA UMUM (普通名詞 - Minna no Nihongo Bab 1-25)
N5_NOUNS = [
    # Sekolah & Pendidikan
    ("学校", "がっこう", "gakkou", "Sekolah", "Kata Benda Umum", "学校へ通います。", "Pergi ke sekolah."),
    ("小学校", "しょうがっこう", "shougakkou", "Sekolah Dasar (SD)", "Kata Benda Umum", "小学校の先生です。", "Guru Sekolah Dasar."),
    ("中学校", "ちゅうがっこう", "chuugakkou", "Sekolah Menengah Pertama (SMP)", "Kata Benda Umum", "中学校に入学します。", "Masuk ke SMP."),
    ("高校", "こうこう", "koukou", "Sekolah Menengah Atas (SMA)", "Kata Benda Umum", "高校生です。", "Murid SMA."),
    ("大学", "だいがく", "daigaku", "Universitas / Perguruan tinggi", "Kata Benda Umum", "大学で勉強します。", "Belajar di universitas."),
    ("大学院", "だいがくいん", "daigakuin", "Pascasarjana (S2/S3)", "Kata Benda Umum", "大学院に進学します。", "Melanjutkan ke pascasarjana."),
    ("教室", "きょうしつ", "kyoushitsu", "Ruang kelas", "Kata Benda Umum", "教室に入ります。", "Masuk ke ruang kelas."),
    ("図書館", "としょかん", "toshokan", "Perpustakaan", "Kata Benda Umum", "図書館で本を借ります。", "Meminjam buku di perpustakaan."),
    ("学生", "がくせい", "gakusei", "Murid / Mahasiswa", "Kata Benda Umum", "留学生です。", "Mahasiswa asing."),
    ("留学生", "りゅうがくせい", "ryuugakusei", "Pelajar asing di luar negeri", "Kata Benda Umum", "日本への留学生です。", "Pelajar asing di Jepang."),
    ("先生", "せんせい", "sensei", "Guru / Dokter pengajar", "Kata Benda Umum", "先生に質問します。", "Bertanya kepada guru."),
    ("本", "ほん", "hon", "Buku bacaan", "Kata Benda Umum", "本を読みます。", "Membaca buku."),
    ("辞書", "じしょ", "jisho", "Kamus bahasa", "Kata Benda Umum", "電子辞書を使います。", "Menggunakan kamus elektronik."),
    ("雑誌", "ざっし", "zasshi", "Majalah berkala", "Kata Benda Umum", "ファッション雑誌を買いました。", "Membeli majalah mode."),
    ("新聞", "しんぶん", "shinbun", "Surat kabar / Koran", "Kata Benda Umum", "毎朝新聞を読みます。", "Membaca koran setiap pagi."),
    ("ノート", "のーと", "nooto", "Buku catatan / Notebook", "Kata Benda Umum", "ノートにメモします。", "Mencatat di buku catatan."),
    ("手帳", "てちょう", "techou", "Buku agenda saku", "Kata Benda Umum", "手帳に予定を書きます。", "Menulis jadwal di agenda."),
    ("名刺", "めいし", "meishi", "Kartu nama bisnis", "Kata Benda Umum", "名刺を交換します。", "Bertukar kartu nama."),
    ("鉛筆", "えんぴつ", "enpitsu", "Pensil kayu", "Kata Benda Umum", "鉛筆で書きます。", "Menulis dengan pensil."),
    ("ボールペン", "ぼーるぺん", "boorupen", "Pulpen tinta", "Kata Benda Umum", "黒のボールペンです。", "Pulpen hitam."),
    ("消しゴム", "けしごむ", "keshigomu", "Penghapus karet", "Kata Benda Umum", "消しゴムで消します。", "Menghapus dengan karet penghapus."),
    ("紙", "かみ", "kami", "Kertas lembaran", "Kata Benda Umum", "紙に名前を書きます。", "Menulis nama di kertas."),
    ("はさみ", "はさみ", "hasami", "Gunting pemotong", "Kata Benda Umum", "はさみで切ります。", "Memotong dengan gunting."),
    ("宿題", "しゅくだい", "shukudai", "Pekerjaan rumah (PR)", "Kata Benda Umum", "宿題を出します。", "Mengumpulkan PR."),
    ("試験", "しけん", "shiken", "Ujian / Tes kelulusan", "Kata Benda Umum", "明日は試験です。", "Besok ada ujian."),
    ("テスト", "てすと", "tesuto", "Tes ujian kecil", "Kata Benda Umum", "漢字のテストがあります。", "Ada tes kanji."),
    ("質問", "しつもん", "shitsumon", "Pertanyaan", "Kata Benda Umum", "質問があります。", "Saya ada pertanyaan."),
    ("答え", "こたえ", "kotae", "Jawaban", "Kata Benda Umum", "正しい答えを選びます。", "Memilih jawaban yang benar."),
    ("意味", "いみ", "imi", "Arti / Makna kata", "Kata Benda Umum", "言葉の意味を調べます。", "Mencari arti kata."),
    ("日本語", "にほんご", "nihongo", "Bahasa Jepang", "Kata Benda Umum", "日本語を勉強します。", "Belajar bahasa Jepang."),
    ("英語", "えいご", "eigo", "Bahasa Inggris", "Kata Benda Umum", "英語を話します。", "Berbicara bahasa Inggris."),
    ("漢字", "かんじ", "kanji", "Huruf Kanji", "Kata Benda Umum", "漢字を書きます。", "Menulis huruf kanji."),
    ("ひらがな", "ひらがな", "hiragana", "Huruf Hiragana", "Kata Benda Umum", "ひらがなを覚えます。", "Menghafal hiragana."),
    ("かたかな", "かたかな", "katakana", "Huruf Katakana", "Kata Benda Umum", "かたかなで書きます。", "Menulis dengan katakana."),

    # Benda Rumah Tangga & Perabotan
    ("机", "つくえ", "tsukue", "Meja belajar / Meja kantor", "Kata Benda Umum", "机の上に置きます。", "Menaruh di atas meja."),
    ("椅子", "いす", "isu", "Kursi tempat duduk", "Kata Benda Umum", "椅子に座ってください。", "Silakan duduk di kursi."),
    ("時計", "とけい", "tokei", "Jam dinding / Jam tangan", "Kata Benda Umum", "時計を見ます。", "Melihat jam."),
    ("鍵", "かぎ", "kagi", "Kunci pintu", "Kata Benda Umum", "鍵をかけます。", "Mengunci pintu."),
    ("傘", "かさ", "kasa", "Payung hujan", "Kata Benda Umum", "傘を差します。", "Memakai payung."),
    ("鞄", "かばん", "kaban", "Tas ransel / Tas jinjing", "Kata Benda Umum", "鞄を持ちます。", "Membawa tas."),
    ("テレビ", "てれび", "terebi", "Televisi / TV", "Kata Benda Umum", "テレビを見ます。", "Menonton TV."),
    ("ラジオ", "らじお", "rajio", "Radio audio", "Kata Benda Umum", "ラジオを聞きます。", "Mendengarkan radio."),
    ("カメラ", "かめら", "kamera", "Kamera foto", "Kata Benda Umum", "カメラで撮ります。", "Memotret dengan kamera."),
    ("パソコン", "ぱそこん", "pasokon", "Komputer PC / Laptop", "Kata Benda Umum", "パソコンでメールを送ります。", "Mengirim email dengan laptop."),
    ("電話", "でんわ", "denwa", "Telepon / Ponsel", "Kata Benda Umum", "電話をかけます。", "Menelepon."),
    ("携帯電話", "けいたいでんわ", "keitaidenwa", "Telepon genggam / Handphone", "Kata Benda Umum", "携帯電話を持っています。", "Membawa handphone."),
    ("冷蔵庫", "れいぞうこ", "reizouko", "Kulkas pendingin makanan", "Kata Benda Umum", "冷蔵庫に牛乳を入れます。", "Memasukkan susu ke kulkas."),
    ("窓", "まど", "mado", "Jendela ruangan", "Kata Benda Umum", "窓を開けます。", "Membuka jendela."),
    ("ドア", "どあ", "doa", "Pintu masuk", "Kata Benda Umum", "ドアを閉めます。", "Menutup pintu."),
    ("エアコン", "えあこん", "eakon", "Pendingin ruangan (AC)", "Kata Benda Umum", "エアコンをつけます。", "Menyalakan AC."),
    ("眼鏡", "めがね", "megane", "Kacamata baca", "Kata Benda Umum", "眼鏡をかけます。", "Memakai kacamata."),
    ("服", "ふく", "fuku", "Pakaian / Baju", "Kata Benda Umum", "新しい服を着ます。", "Memakai baju baru."),
    ("シャツ", "しゃつ", "shatsu", "Kemeja baju", "Kata Benda Umum", "白いシャツです。", "Kemeja putih."),
    ("ズボン", "ずぼん", "zubon", "Celana panjang", "Kata Benda Umum", "黒いズボンを履きます。", "Memakai celana panjang hitam."),
    ("靴", "くつ", "kutsu", "Sepatu alas kaki", "Kata Benda Umum", "靴を履きます。", "Memakai sepatu."),
    ("靴下", "くつした", "kutsushita", "Kaus kaki", "Kata Benda Umum", "暖かい靴下を履きます。", "Memakai kaus kaki hangat."),
    ("帽子", "ぼうし", "boushi", "Topi kepala", "Kata Benda Umum", "帽子をかぶります。", "Memakai topi."),
    ("財布", "さいふ", "saifu", "Dompet tempat uang", "Kata Benda Umum", "財布を忘れました。", "Ketinggalan dompet."),
    ("ベッド", "べっど", "beddo", "Tempat tidur / Ranjang", "Kata Benda Umum", "ベッドで寝ます。", "Tidur di ranjang."),
    ("布団", "ふとん", "futon", "Kasur lipat tradisional Jepang", "Kata Benda Umum", "布団を敷きます。", "Menggelar kasur futon."),
    ("毛布", "もうふ", "moufu", "Selimut tebal hangat", "Kata Benda Umum", "毛布を掛けます。", "Memakai selimut."),
    ("枕", "まくら", "makura", "Bantal tidur", "Kata Benda Umum", "高い枕が好きです。", "Suka bantal yang tinggi."),
    ("石鹸", "せっけん", "sekken", "Sabun mandi batangan", "Kata Benda Umum", "石鹸で手を洗います。", "Mencuci tangan dengan sabun."),
    ("タオル", "たおる", "taoru", "Handuk pengering", "Kata Benda Umum", "タオルで顔を拭きます。", "Mengeringkan wajah dengan handuk."),
    ("お風呂", "おふろ", "ofuro", "Bak mandi rendam air hangat", "Kata Benda Umum", "お風呂に入ります。", "Masuk berendam air hangat."),
    ("シャワー", "しゃわー", "shawaa", "Pancuran air shower", "Kata Benda Umum", "シャワーを浴びます。", "Mandi pancuran shower."),
    ("鏡", "かがみ", "kagami", "Cermin rias", "Kata Benda Umum", "鏡を見ます。", "Melihat cermin."),

    # Makanan, Minuman, Masakan & Bumbu
    ("ご飯", "ごはん", "gohan", "Nasi putih / Makanan pokok", "Kata Benda Umum", "ご飯を食べます。", "Makan nasi."),
    ("朝ご飯", "あさごはん", "asagohan", "Sarapan pagi", "Kata Benda Umum", "毎朝朝ご飯を食べます。", "Setiap pagi sarapan."),
    ("昼ご飯", "ひるごはん", "hirugohan", "Makan siang", "Kata Benda Umum", "十二時に昼ご飯を食べます。", "Makan siang jam 12."),
    ("晩ご飯", "ばんごはん", "bangohan", "Makan malam", "Kata Benda Umum", "家族と晩ご飯を食べます。", "Makan malam bersama keluarga."),
    ("パン", "ぱん", "pan", "Roti gandum", "Kata Benda Umum", "パンを食べます。", "Makan roti."),
    ("肉", "にく", "niku", "Daging", "Kata Benda Umum", "肉料理が好きです。", "Suka hidangan daging."),
    ("牛肉", "ぎゅうにく", "gyuuniku", "Daging sapi", "Kata Benda Umum", "牛肉を買います。", "Membeli daging sapi."),
    ("豚肉", "ぶたにく", "butaniku", "Daging babi", "Kata Benda Umum", "豚肉を炒めます。", "Menumis daging babi."),
    ("鶏肉", "とりにく", "toriniku", "Daging ayam", "Kata Benda Umum", "鶏肉の唐揚げです。", "Ayam goreng tepung."),
    ("魚", "さかな", "sakana", "Ikan segar", "Kata Benda Umum", "魚を焼きます。", "Memanggang ikan."),
    ("野菜", "やさい", "yasai", "Sayur-mayur segar", "Kata Benda Umum", "野菜を食べます。", "Makan sayuran."),
    ("卵", "たまご", "tamago", "Telur ayam", "Kata Benda Umum", "卵焼きを作ります。", "Membuat telur gulung."),
    ("水", "みず", "mizu", "Air putih dingin", "Kata Benda Umum", "水を一杯飲みます。", "Minum segelas air."),
    ("お湯", "おゆ", "oyu", "Air panas mendidih", "Kata Benda Umum", "お湯を沸かします。", "Memasak air panas."),
    ("お茶", "おちゃ", "ocha", "Teh hijau khas Jepang", "Kata Benda Umum", "温かいお茶をどうぞ。", "Silakan teh hangat."),
    ("紅茶", "こうちゃ", "koucha", "Teh hitam manis", "Kata Benda Umum", "紅茶を飲みます。", "Minum teh hitam."),
    ("牛乳", "ぎゅうにゅう", "gyuunyuu", "Susu sapi murni", "Kata Benda Umum", "朝牛乳を飲みます。", "Minum susu di pagi hari."),
    ("ミルク", "みるく", "miruku", "Susu kemasan", "Kata Benda Umum", "ミルクを入れます。", "Memasukkan susu."),
    ("コーヒー", "こーひー", "koohii", "Kopi seduh", "Kata Benda Umum", "コーヒーを飲みます。", "Minum kopi."),
    ("ジュース", "じゅーす", "juusu", "Jus buah segar", "Kata Benda Umum", "ジュースを買いました。", "Membeli jus."),
    ("ビール", "びーる", "biiru", "Bir minuman", "Kata Benda Umum", "冷たいビールを飲みます。", "Minum bir dingin."),
    ("お酒", "おさけ", "osake", "Sake beras Jepang", "Kata Benda Umum", "日本のお酒です。", "Sake Jepang."),
    ("砂糖", "さとう", "satou", "Gula pasir manis", "Kata Benda Umum", "砂糖を入れます。", "Memasukkan gula."),
    ("塩", "しお", "shio", "Garam dapur", "Kata Benda Umum", "塩を振ります。", "Menaburkan garam."),
    ("醤油", "しょうゆ", "shouyu", "Kecap asin shoyu", "Kata Benda Umum", "醤油をつけます。", "Mencocol kecap asin."),
    ("カレー", "かれー", "karee", "Nasi kari Jepang", "Kata Benda Umum", "カレーライスを作ります。", "Membuat nasi kari."),
    ("ラーメン", "らーめん", "raamen", "Mie ramen kuah", "Kata Benda Umum", "ラーメンを食べます。", "Makan mie ramen."),
    ("うどん", "うどん", "udon", "Mie tebal udon", "Kata Benda Umum", "温かいうどんを食べます。", "Makan udon hangat."),
    ("そば", "そば", "soba", "Mie soba gandum hitam", "Kata Benda Umum", "そばを食べます。", "Makan mie soba."),
    ("寿司", "すし", "sushi", "Nasi kepal ikan sushi", "Kata Benda Umum", "寿司屋へ行きます。", "Pergi ke kedai sushi."),
    ("天ぷら", "てんぷら", "tenpura", "Gorengan renyah tempura", "Kata Benda Umum", "エビの天ぷらです。", "Tempura udang."),
    ("刺身", "さしみ", "sashimi", "Irisan ikan mentah sashimi", "Kata Benda Umum", "マグロの刺身を食べます。", "Makan sashimi tuna."),
    ("弁当", "べんとう", "bentou", "Kotak bekal makan siang", "Kata Benda Umum", "お弁当を作りました。", "Membuat bekal makan."),
    ("お菓子", "おかし", "okashi", "Camilan kue / Makanan ringan", "Kata Benda Umum", "お菓子を食べます。", "Makan camilan kue."),
    ("ケーキ", "けーき", "keeki", "Kue tart manis", "Kata Benda Umum", "誕生日ケーキです。", "Kue ulang tahun."),
    ("アイスクリーム", "あいすくりーむ", "aisukuriimu", "Es krim dingin", "Kata Benda Umum", "バニラのアイスクリームです。", "Es krim rasa vanila."),

    # Nama Buah & Hasil Kebun
    ("果物", "くだもの", "kudamono", "Buah-buahan segar", "Kata Benda Umum", "果物が大好きです。", "Sangat suka buah-buahan."),
    ("林檎", "りんご", "ringo", "Apel merah manis", "Kata Benda Umum", "林檎を食べます。", "Makan apel."),
    ("蜜柑", "みかん", "mikan", "Jeruk keprok manis", "Kata Benda Umum", "冬に蜜柑を食べます。", "Makan jeruk di musim dingin."),
    ("バナナ", "ばなな", "banana", "Pisang", "Kata Benda Umum", "バナナを食べます。", "Makan pisang."),
    ("西瓜", "すいか", "suika", "Semangka segar", "Kata Benda Umum", "夏に西瓜を食べます。", "Makan semangka di musim panas."),
    ("苺", "いちご", "ichigo", "Stroberi merah", "Kata Benda Umum", "甘い苺です。", "Stroberi manis."),
    ("葡萄", "ぶどう", "budou", "Anggur ungu", "Kata Benda Umum", "葡萄を買いました。", "Membeli buah anggur."),
    ("桃", "もも", "momo", "Persik / Peach lembut", "Kata Benda Umum", "桃が実りました。", "Buah persik telah berbuah."),
    ("レモン", "れもん", "remon", "Lemon asam segar", "Kata Benda Umum", "酸っぱいレモンです。", "Lemon yang asam."),
    ("メロン", "めろん", "meron", "Melon manis", "Kata Benda Umum", "高級なメロンです。", "Melon kualitas tinggi."),

    # Kendaraan & Transportasi Umum
    ("電車", "でんしゃ", "densha", "Kereta api listrik", "Kata Benda Umum", "電車で通います。", "Berangkat naik kereta."),
    ("地下鉄", "ちかてつ", "chikatetsu", "Kereta bawah tanah (MRT)", "Kata Benda Umum", "地下鉄に乗ります。", "Naik kereta bawah tanah."),
    ("新幹線", "しんかんせん", "shinkansen", "Kereta peluru Shinkansen", "Kata Benda Umum", "新幹線は速いです。", "Shinkansen sangat cepat."),
    ("バス", "ばす", "basu", "Bus umum", "Kata Benda Umum", "バスに乗ります。", "Naik bus umum."),
    ("タクシー", "たくしー", "takushii", "Taksi penumpang", "Kata Benda Umum", "タクシーを呼びます。", "Memanggil taksi."),
    ("飛行機", "ひこうき", "hikouki", "Pesawat terbang", "Kata Benda Umum", "飛行機で行きます。", "Pergi naik pesawat."),
    ("船", "ふね", "fune", "Kapal laut", "Kata Benda Umum", "船に乗ります。", "Naik kapal laut."),
    ("自動車", "じどうしゃ", "jidousha", "Mobil bermotor", "Kata Benda Umum", "自動車を運転します。", "Mengemudikan mobil."),
    ("車", "くるま", "kuruma", "Mobil roda empat", "Kata Benda Umum", "父の車です。", "Mobil milik ayah."),
    ("自転車", "じてんしゃ", "jitensha", "Sepeda gowes", "Kata Benda Umum", "自転車で駅へ行きます。", "Pergi ke stasiun naik sepeda."),
    ("バイク", "ばいく", "baiku", "Sepeda motor", "Kata Benda Umum", "バイクに乗ります。", "Mengendarai sepeda motor."),
    ("駅", "えき", "eki", "Stasiun kereta api", "Kata Benda Umum", "駅の前で待ちます。", "Menunggu di depan stasiun."),
    ("バス停", "ばすてい", "basutei", "Halte pemberhentian bus", "Kata Benda Umum", "バス停で並びます。", "Mengantre di halte bus."),
    ("切符", "きっぷ", "kippu", "Tiket karcis perjalanan", "Kata Benda Umum", "切符を買います。", "Membeli tiket."),
    ("定期券", "ていきけん", "teikiken", "Tiket komuter bulanan", "Kata Benda Umum", "定期券を更新します。", "Memperpanjang tiket komuter."),
    ("空港", "くうこう", "kuukou", "Bandara udara internasional", "Kata Benda Umum", "成田空港に着きました。", "Tiba di Bandara Narita."),

    # Tempat Umum & Fasilitas Kota
    ("家", "いえ", "ie", "Rumah tempat tinggal", "Kata Benda Umum", "うちへ帰ります。", "Pulang ke rumah."),
    ("部屋", "へや", "heya", "Kamar tidur / Ruangan", "Kata Benda Umum", "自分の部屋です。", "Kamar saya sendiri."),
    ("台所", "だいどころ", "daidokoro", "Dapur memasak", "Kata Benda Umum", "台所で料理します。", "Memasak di dapur."),
    ("庭", "にわ", "niwa", "Halaman taman rumah", "Kata Benda Umum", "庭で遊びます。", "Bermain di halaman."),
    ("病院", "びょういん", "byouin", "Rumah sakit", "Kata Benda Umum", "病院へ行きます。", "Pergi ke rumah sakit."),
    ("銀行", "ぎんこう", "ginkou", "Bank simpan pinjam", "Kata Benda Umum", "銀行でお金を下ろします。", "Menarik uang di bank."),
    ("郵便局", "ゆうびんきょく", "yuubinkyoku", "Kantor pos pengiriman", "Kata Benda Umum", "郵便局で切手を買います。", "Membeli perangko di kantor pos."),
    ("交番", "こうばん", "kouban", "Pos polisi jalan", "Kata Benda Umum", "交番で道を聞きます。", "Bertanya arah di pos polisi."),
    ("スーパー", "すーぱー", "suupaa", "Supermarket belanja", "Kata Benda Umum", "スーパーで買い物をします。", "Berbelanja di supermarket."),
    ("デパート", "でぱーと", "depaato", "Departement store mal", "Kata Benda Umum", "デパートへ行きます。", "Pergi ke departement store."),
    ("コンビニ", "こんびに", "konbini", "Minimarket 24 jam", "Kata Benda Umum", "コンビニでおにぎりを買います。", "Membeli onigiri di minimarket."),
    ("公園", "こうえん", "kouen", "Taman kota", "Kata Benda Umum", "公園を散歩します。", "Jalan santai di taman."),
    ("喫茶店", "きっさてん", "kissaten", "Kedai kafe kopi", "Kata Benda Umum", "喫茶店で休みます。", "Beristirahat di kedai kopi."),
    ("レストラン", "れすとらん", "resutoran", "Restoran makan", "Kata Benda Umum", "レストランで食事します。", "Makan di restoran."),
    ("ホテル", "ほてる", "hoteru", "Hotel penginapan", "Kata Benda Umum", "ホテルに泊まります。", "Menginap di hotel."),
    ("映画館", "えいがかん", "eigakan", "Bioskop teater film", "Kata Benda Umum", "映画館で映画を見ます。", "Menonton film di bioskop."),
    ("美術館", "びじゅつかん", "bijutsukan", "Museum seni rupa", "Kata Benda Umum", "美術館へ行きます。", "Pergi ke museum seni."),
    ("会社", "かいしゃ", "kaisha", "Perusahaan / Kantor", "Kata Benda Umum", "会社で働きます。", "Bekerja di kantor perusahaan."),
    ("事務所", "じむしょ", "jimusho", "Ruang kantor kerja", "Kata Benda Umum", "事務所に入ります。", "Masuk ke ruang kantor."),
    ("会議室", "かいぎしつ", "kaigishitsu", "Ruang rapat musyawarah", "Kata Benda Umum", "会議室で話し合います。", "Berdiskusi di ruang rapat."),
    ("食堂", "しょくどう", "shokudou", "Kantin makan / Ruang makan", "Kata Benda Umum", "社員食堂で食べます。", "Makan di kantin karyawan."),
    ("トイレ", "といれ", "toire", "Toilet / Kamar kecil", "Kata Benda Umum", "トイレはあそこです。", "Toilet ada di sebelah sana."),
    ("お手洗い", "おてあらい", "otearai", "Kamar kecil (sopan)", "Kata Benda Umum", "お手洗いをお借りします。", "Izin meminjam kamar kecil."),
    ("受付", "うけつけ", "uketsuke", "Meja resepsionis", "Kata Benda Umum", "受付で名前を書きます。", "Menulis nama di meja resepsionis."),
    ("エレベーター", "えれべーたー", "erebeetaa", "Lift gedung", "Kata Benda Umum", "エレベーターに乗ります。", "Naik lift gedung."),
    ("エスカレーター", "えすかれーたー", "esukareetaa", "Eskalator tangga berjalan", "Kata Benda Umum", "エスカレーターで二階へ上がります。", "Naik ke lantai dua lewat eskalator."),
    ("階段", "かいだん", "kaidan", "Tangga gedung biasa", "Kata Benda Umum", "階段を使います。", "Menggunakan tangga."),
    ("ビル", "びる", "biru", "Gedung bertingkat tinggi", "Kata Benda Umum", "高いビルが見えます。", "Terlihat gedung tinggi."),
    ("町", "まち", "machi", "Kota tempat tinggal", "Kata Benda Umum", "静かな町です。", "Kota yang tenang."),
    ("道", "みち", "michi", "Jalan raya / Lorong", "Kata Benda Umum", "この道をまっすぐ行きます。", "Jalan lurus di jalan ini."),
    ("橋", "はし", "hashi", "Jembatan penyeberangan", "Kata Benda Umum", "橋を渡ります。", "Menyeberangi jembatan."),
    ("信号", "しんごう", "shingou", "Lampu lalu lintas", "Kata Benda Umum", "信号が赤になりました。", "Lampu lalu lintas menjadi merah."),
    ("交差点", "こうさてん", "kousaten", "Persimpangan perempatan jalan", "Kata Benda Umum", "交差点を左に曲がります。", "Belok kiri di persimpangan jalan."),
    ("角", "かど", "kado", "Pojokan tikungan jalan", "Kata Benda Umum", "次の角を曲がります。", "Belok di tikungan berikutnya."),
    ("国", "くに", "kuni", "Negara tanah air", "Kata Benda Umum", "外国から来ました。", "Datang dari luar negeri."),
    ("日本", "にほん", "nihon", "Negara Jepang", "Kata Benda Umum", "日本が大好きです。", "Sangat suka negara Jepang."),
    ("インドネシア", "いんどねしあ", "indoneshia", "Negara Indonesia", "Kata Benda Umum", "インドネシアから来ました。", "Datang dari Indonesia."),

    # Anggota Tubuh & Kesehatan
    ("体", "からだ", "karada", "Tubuh / Fisik jasmani", "Kata Benda Umum", "体に気をつけてください。", "Tolong jaga kesehatan fisik Anda."),
    ("頭", "あたま", "atama", "Kepala", "Kata Benda Umum", "頭が痛いです。", "Kepala saya sakit."),
    ("顔", "かお", "kao", "Wajah muka", "Kata Benda Umum", "顔を洗います。", "Mencuci muka."),
    ("目", "め", "me", "Mata penglihatan", "Kata Benda Umum", "目が悪いです。", "Penglihatan saya kurang baik."),
    ("耳", "みみ", "mimi", "Telinga pendengaran", "Kata Benda Umum", "耳を澄ませます。", "Memasang telinga mendengarkan."),
    ("鼻", "はな", "hana", "Hidung", "Kata Benda Umum", "鼻水が出ます。", "Hidung saya meler."),
    ("口", "くち", "kuchi", "Mulut", "Kata Benda Umum", "口を開けます。", "Membuka mulut."),
    ("歯", "は", "ha", "Gigi", "Kata Benda Umum", "歯を磨きます。", "Menggosok gigi."),
    ("喉", "のど", "nodo", "Tenggorokan", "Kata Benda Umum", "喉が痛いです。", "Tenggorokan saya sakit."),
    ("手", "て", "te", "Tangan telapak", "Kata Benda Umum", "手を洗います。", "Mencuci tangan."),
    ("足", "あし", "ashi", "Kaki / Tungkai kaki", "Kata Benda Umum", "足が痛いです。", "Kaki saya sakit."),
    ("お腹", "おなか", "onaka", "Perut lambung", "Kata Benda Umum", "お腹が空きました。", "Perut saya lapar."),
    ("病気", "びょうき", "byouki", "Penyakit / Sakit", "Kata Benda Umum", "病気で休みます。", "Izin libur karena sakit."),
    ("風邪", "かぜ", "kaze", "Masuk angin / Flu batuk", "Kata Benda Umum", "風邪を引きました。", "Terkena flu masuk angin."),
    ("熱", "ねつ", "netsu", "Demam suhu badan panas", "Kata Benda Umum", "熱があります。", "Mengalami demam panas."),
    ("薬", "くすり", "kusuri", "Obat medis penyembuh", "Kata Benda Umum", "薬を飲みます。", "Minum obat medis."),

    # Anggota Keluarga
    ("家族", "かぞく", "kazoku", "Keluarga inti", "Kata Benda Umum", "家族と住んでいます。", "Tinggal bersama keluarga."),
    ("両親", "りょうしん", "ryoushin", "Kedua orang tua", "Kata Benda Umum", "両親に手紙を書きます。", "Menulis surat untuk orang tua."),
    ("父", "ちち", "chichi", "Ayah saya", "Kata Benda Umum", "父は会社員です。", "Ayah saya karyawan."),
    ("母", "はは", "haha", "Ibu saya", "Kata Benda Umum", "母は優しいです。", "Ibu saya sangat ramah."),
    ("お父さん", "おとうさん", "otousan", "Ayah (orang lain)", "Kata Benda Umum", "お父さんはお元気ですか。", "Apakah ayah Anda sehat?"),
    ("お母さん", "おかあさん", "okaasan", "Ibu (orang lain)", "Kata Benda Umum", "お母さんは料理が上手です。", "Ibu Anda pandai memasak."),
    ("兄", "あに", "ani", "Kakak laki-laki saya", "Kata Benda Umum", "兄は医者です。", "Kakak laki-laki saya dokter."),
    ("お兄さん", "おにいさん", "oniisan", "Kakak laki-laki (orang lain)", "Kata Benda Umum", "お兄さんは学生ですか。", "Apakah kakak laki-lakimu mahasiswa?"),
    ("姉", "あね", "ane", "Kakak perempuan saya", "Kata Benda Umum", "姉は東京にいます。", "Kakak perempuan saya ada di Tokyo."),
    ("お姉さん", "おねえさん", "oneesan", "Kakak perempuan (orang lain)", "Kata Benda Umum", "お姉さんは綺麗ですね。", "Kakak perempuanmu cantik ya."),
    ("弟", "おとうと", "otouto", "Adik laki-laki saya", "Kata Benda Umum", "弟と遊びます。", "Bermain bersama adik laki-laki."),
    ("弟さん", "おとうとさん", "otoutosan", "Adik laki-laki (orang lain)", "Kata Benda Umum", "弟さんは何歳ですか。", "Adik laki-lakimu berapa usianya?"),
    ("妹", "いもうと", "imouto", "Adik perempuan saya", "Kata Benda Umum", "妹は高校生です。", "Adik perempuan saya murid SMA."),
    ("妹さん", "いもうとさん", "imoutosan", "Adik perempuan (orang lain)", "Kata Benda Umum", "妹さんは可愛いですね。", "Adik perempuanmu lucu ya."),
    ("夫", "おっと", "otto", "Suami saya", "Kata Benda Umum", "夫と買い物します。", "Berbelanja bersama suami."),
    ("主人", "しゅじん", "shujin", "Suami saya (panggilan santun)", "Kata Benda Umum", "主人は働いています。", "Suami saya sedang bekerja."),
    ("ご主人", "ごしゅじん", "goshujin", "Suami (orang lain)", "Kata Benda Umum", "ご主人はお元気ですか。", "Apakah suami Anda sehat?"),
    ("妻", "つま", "tsuma", "Istri saya", "Kata Benda Umum", "妻と一緒に旅行します。", "Berwisata bersama istri."),
    ("家内", "かない", "kanai", "Istri saya (santun)", "Kata Benda Umum", "家内が料理を作ります。", "Istri saya membuat masakan."),
    ("奥さん", "おくさん", "okusan", "Istri (orang lain)", "Kata Benda Umum", "奥さんはお元気ですか。", "Apakah istri Anda sehat?"),
    ("子供", "こども", "kodomo", "Anak / Anak-anak", "Kata Benda Umum", "子供が遊んでいます。", "Anak-anak sedang bermain."),
    ("お子さん", "おこさん", "okosan", "Anak (orang lain)", "Kata Benda Umum", "お子さんは何歳ですか。", "Berapa umur anak Anda?"),
    ("祖父", "そふ", "sofu", "Kakek saya", "Kata Benda Umum", "祖父は元気です。", "Kakek saya sehat."),
    ("おじいさん", "おじいさん", "ojiisan", "Kakek / Pria lansia", "Kata Benda Umum", "おじいさんと散歩します。", "Jalan-jalan bersama kakek."),
    ("祖母", "そぼ", "sobo", "Nenek saya", "Kata Benda Umum", "祖母と話します。", "Berbicara dengan nenek."),
    ("おばあさん", "おばあさん", "obaasan", "Nenek / Wanita lansia", "Kata Benda Umum", "おばあさんの昔話です。", "Cerita masa lalu nenek."),
    ("友達", "ともだち", "tomodachi", "Teman kawan akrab", "Kata Benda Umum", "友達と遊びます。", "Bermain bersama kawan."),

    # Alam, Cuaca & Hewan
    ("山", "やま", "yama", "Gunung", "Kata Benda Umum", "山に登ります。", "Mendaki gunung."),
    ("川", "かわ", "kawa", "Sungai mengalir", "Kata Benda Umum", "川で魚を釣ります。", "Memancing ikan di sungai."),
    ("海", "うみ", "umi", "Laut samudra", "Kata Benda Umum", "海で泳ぎます。", "Berenang di laut."),
    ("空", "そら", "sora", "Langit angkasa", "Kata Benda Umum", "青い空がきれいです。", "Langit biru sangat indah."),
    ("雨", "あめ", "ame", "Hujan rintik/lebat", "Kata Benda Umum", "雨が降っています。", "Hujan sedang turun."),
    ("雪", "ゆき", "yuki", "Salju putih", "Kata Benda Umum", "冬に雪が降ります。", "Salju turun di musim dingin."),
    ("風", "かぜ", "kaze", "Angin sepoi/kencang", "Kata Benda Umum", "心地よい風が吹きます。", "Bertiup angin yang nyaman."),
    ("雲", "くも", "kumo", "Awan di langit", "Kata Benda Umum", "白い雲が浮かんでいます。", "Awan putih mengapung."),
    ("天気", "てんき", "tenki", "Cuaca hari ini", "Kata Benda Umum", "明日の天気はどうですか。", "Bagaimana cuaca besok?"),
    ("木", "き", "ki", "Pohon kayu / Kayu", "Kata Benda Umum", "大きな木があります。", "Ada pohon besar."),
    ("花", "はな", "hana", "Bunga mekar", "Kata Benda Umum", "綺麗な花が咲きました。", "Bunga indah bermekaran."),
    ("桜", "さくら", "sakura", "Bunga Sakura khas Jepang", "Kata Benda Umum", "春に桜を見ます。", "Melihat sakura di musim semi."),
    ("犬", "いぬ", "inu", "Anjing peliharaan", "Kata Benda Umum", "犬と散歩します。", "Jalan santai bersama anjing."),
    ("猫", "ねこ", "neko", "Kucing", "Kata Benda Umum", "猫が寝ています。", "Kucing sedang tidur."),
    ("鳥", "とり", "tori", "Burung", "Kata Benda Umum", "鳥が飛んでいます。", "Burung sedang terbang."),
    ("魚", "さかな", "sakana", "Ikan hidup", "Kata Benda Umum", "川で魚が泳ぎます。", "Ikan berenang di sungai.")
]

# Assemble N5 list in orderly categorical groups as instructed:
N5_TOTAL = [
    *N5_VERBS,
    *N5_ADJECTIVES,
    *N5_TIME_NUMBERS,
    *N5_NOUNS,
    *N5_INTERROGATIVES_PRONOUNS,
    *N5_GREETINGS
]

# Deduplicate N5 while preserving exact sequence
seen = set()
deck_n5 = []
current_id = 1

for item in N5_TOTAL:
    jp, kana, romaji, indo, cat, ex_jp, ex_id = item
    if jp in seen:
        continue
    seen.add(jp)
    deck_n5.append({
        "id": current_id,
        "level": "N5",
        "japanese": jp,
        "kana": kana,
        "romaji": romaji,
        "reading": romaji,
        "indonesian": indo,
        "category": cat,
        "categoryJp": CATEGORY_MAP_JP.get(cat, "単語"),
        "example": ex_jp,
        "exampleIndonesian": ex_id
    })
    current_id += 1

print(f"Total Unique N5 Minna no Nihongo Cards Generated: {len(deck_n5)}")

# Read existing N4, N3, N2
with open("src/data/vocabData.ts", "r", encoding="utf-8") as f:
    existing_code = f.read()

import re
match_n4 = re.search(r"export const VOCAB_N4: VocabCard\[\] = (\[[\s\S]*?\]);\s*export const VOCAB_N3", existing_code)
match_n3 = re.search(r"export const VOCAB_N3: VocabCard\[\] = (\[[\s\S]*?\]);\s*export const VOCAB_N2", existing_code)
match_n2 = re.search(r"export const VOCAB_N2: VocabCard\[\] = (\[[\s\S]*?\]);\s*export const ALL_VOCAB", existing_code)

deck_n4 = json.loads(match_n4.group(1)) if match_n4 else []
deck_n3 = json.loads(match_n3.group(1)) if match_n3 else []
deck_n2 = json.loads(match_n2.group(1)) if match_n2 else []

print(f"Preserved N4={len(deck_n4)}, N3={len(deck_n3)}, N2={len(deck_n2)}")

file_header = """import { VocabCard, JLPTLevel } from '../types';

/**
 * =======================================================================
 * DATA KOSAKATA / KOTOBA RESMI STANDAR JLPT (N5 - N2)
 * Kurikulum Lengkap Minna no Nihongo I (Bab 1 - 25) untuk Level N5
 * Disusun terurut dan terkelompok berdasarkan:
 * 1. Kata Kerja Dasar (動詞)
 * 2. Kata Sifat (形容詞)
 * 3. Penunjuk Waktu dan Angka (時間・数字)
 * 4. Kata Benda Umum (名詞)
 * 5. Kata Tanya dan Kata Ganti (疑問詞・代名詞)
 * 6. Salam dan Ungkapan Percakapan (挨拶・表現)
 * =======================================================================
 */

"""

file_content = file_header + \
    f"export const VOCAB_N5: VocabCard[] = {json.dumps(deck_n5, ensure_ascii=False, indent=2)};\n\n" + \
    f"export const VOCAB_N4: VocabCard[] = {json.dumps(deck_n4, ensure_ascii=False, indent=2)};\n\n" + \
    f"export const VOCAB_N3: VocabCard[] = {json.dumps(deck_n3, ensure_ascii=False, indent=2)};\n\n" + \
    f"export const VOCAB_N2: VocabCard[] = {json.dumps(deck_n2, ensure_ascii=False, indent=2)};\n\n" + \
    "export const ALL_VOCAB: Record<JLPTLevel, VocabCard[]> = {\n" + \
    "  N5: VOCAB_N5,\n" + \
    "  N4: VOCAB_N4,\n" + \
    "  N3: VOCAB_N3,\n" + \
    "  N2: VOCAB_N2,\n" + \
    "};\n"

with open("src/data/vocabData.ts", "w", encoding="utf-8") as f:
    f.write(file_content)

print("Successfully wrote src/data/vocabData.ts with complete Minna no Nihongo N5 dataset!")
