# -*- coding: utf-8 -*-
# Data Kata Sifat (形容詞) & Kosakata Pekerjaan / Sehari-hari Minna no Nihongo N5

N5_ADJECTIVES = [
    # Kata Sifat -i (い形容詞)
    ("大きい", "おおきい", "ookii", "Besar ukurannya", "Kata Sifat", "大きな家に住んでいます。", "Tinggal di sebuah rumah yang besar."),
    ("小さい", "ちいさい", "chiisai", "Kecil ukurannya", "Kata Sifat", "小さくて可愛い犬です。", "Anjing kecil yang lucu."),
    ("新しい", "あたらしい", "atarashii", "Baru keadaannya", "Kata Sifat", "新しい靴を買いました。", "Membeli sepatu baru."),
    ("古い", "ふるい", "furui", "Lama / Kuno / Tua", "Kata Sifat", "京都の古いお寺を訪ねます。", "Mengunjungi kuil kuno di Kyoto."),
    ("いい", "いい / よい", "ii / yoi", "Bagus / Baik sifatnya", "Kata Sifat", "今日はとてもいい天気です。", "Hari ini cuacanya sangat bagus."),
    ("悪い", "わるい", "warui", "Buruk / Jelek kondisinya", "Kata Sifat", "気分が悪いので休みます。", "Beristirahat karena merasa kurang enak badan."),
    ("暑い", "あつい", "atsui", "Panas (suhu cuaca)", "Kata Sifat", "日本の夏はとても暑いです。", "Musim panas di Jepang sangat terik."),
    ("熱い", "あつい", "atsui", "Panas (suhu benda / minuman)", "Kata Sifat", "熱いお茶を飲みます。", "Meminum teh yang panas."),
    ("寒い", "さむい", "samui", "Dingin (suhu cuaca)", "Kata Sifat", "冬は風が吹いて寒いです。", "Musim dingin terasa dingin karena angin bertiup."),
    ("冷たい", "つめたい", "tsumetai", "Dingin (suhu benda / minuman)", "Kata Sifat", "冷たいジュースを飲みます。", "Meminum jus buah dingin."),
    ("難しい", "むずかしい", "muzukashii", "Sulit / Sukar dipahami", "Kata Sifat", "この漢字は書くのが難しいです。", "Kanji ini sulit ditulis."),
    ("易しい", "やさしい", "yasashii", "Mudah / Gampang dipelajari", "Kata Sifat", "今日のテストは易しかったです。", "Ujian hari ini cukup mudah."),
    ("高い", "たかい", "takai", "Tinggi (ukuran) / Mahal (harga)", "Kata Sifat", "富士山は日本で一番高い山です。", "Gunung Fuji adalah gunung tertinggi di Jepang."),
    ("安い", "やすい", "yasui", "Murah harganya", "Kata Sifat", "このスーパーの卵は安いです。", "Telur di supermarket ini harganya murah."),
    ("低い", "ひくい", "hikui", "Rendah ukurannya", "Kata Sifat", "天井が低い部屋です。", "Kamar dengan langit-langit yang rendah."),
    ("面白い", "おもしろい", "omoshiroi", "Menarik / Menghibur", "Kata Sifat", "この小説はとても面白いです。", "Novel ini sangat menarik untuk dibaca."),
    ("美味い", "おいしい", "oishii", "Lezat / Enak rasanya", "Kata Sifat", "日本のラーメンは美味しいです。", "Ramen khas Jepang rasanya sangat enak."),
    ("不味い", "まずい", "mazui", "Tidak enak rasanya", "Kata Sifat", "薬は苦くて不味いです。", "Obat rasanya pahit dan tidak enak."),
    ("忙しい", "いそがしい", "isogashii", "Sibuk banyak pekerjaan", "Kata Sifat", "今週は仕事で忙しいです。", "Minggu ini sangat sibuk dengan pekerjaan."),
    ("楽しい", "たのしい", "tanoshii", "Menyenangkan / Gembira", "Kata Sifat", "みんなで旅行して楽しかったです。", "Sangat menyenangkan berlibur bersama semuanya."),
    ("白い", "しろい", "shiroi", "Putih warnanya", "Kata Sifat", "白いシャツを着ます。", "Mengenakan kemeja berwarna putih."),
    ("黒い", "くろい", "kuroi", "Hitam warnanya", "Kata Sifat", "黒い靴を履きます。", "Mengenakan sepatu berwarna hitam."),
    ("赤い", "あかい", "akai", "Merah warnanya", "Kata Sifat", "赤いリンゴを食べます。", "Memakan buah apel yang merah."),
    ("青い", "あおい", "aoi", "Biru warnanya", "Kata Sifat", "青い空が広がっています。", "Langit biru membentang luas."),
    ("近い", "ちかい", "chikai", "Dekat jaraknya", "Kata Sifat", "駅から家まで近いです。", "Jarak dari stasiun ke rumah dekat."),
    ("遠い", "とおい", "tooi", "Jauh jaraknya", "Kata Sifat", "学校まで遠いので電車で行きます。", "Karena jauh ke sekolah saya naik kereta."),
    ("早い", "はやい", "hayai", "Pagi sekali / Cepat (waktu)", "Kata Sifat", "朝早く起きて散歩します。", "Bangun pagi-pagi sekali dan jalan-jalan."),
    ("速い", "はやい", "hayai", "Cepat (kecepatan gerak)", "Kata Sifat", "新幹線はとても速いです。", "Kereta Shinkansen sangat cepat."),
    ("遅い", "おそい", "osoi", "Lambat / Terlambat", "Kata Sifat", "足が遅いですが頑張ります。", "Lari saya lambat namun tetap berusaha keras."),
    ("多い", "おおい", "ooi", "Banyak jumlahnya", "Kata Sifat", "東京は人が多いです。", "Tokyo banyak penduduknya."),
    ("少ない", "すくない", "sukunai", "Sedikit jumlahnya", "Kata Sifat", "雨の日は客が少ないです。", "Pelanggan sedikit saat hari hujan."),
    ("暖かい", "あたたかい", "atatakai", "Hangat (suhu cuaca musim semi)", "Kata Sifat", "春は暖かくて気持ちがいいです。", "Musim semi terasa hangat dan menyenangkan."),
    ("涼しい", "すずしい", "suzushii", "Sejuk (suhu cuaca musim gugur)", "Kata Sifat", "秋は風が涼しいです。", "Musim gugur anginnya terasa sejuk."),
    ("甘い", "あまい", "amai", "Manis rasanya", "Kata Sifat", "このケーキは甘くて美味しいです。", "Kue ini manis dan enak."),
    ("辛い", "からい", "karai", "Pedas rasanya", "Kata Sifat", "辛いカレーが好きです。", "Suka masakan kari pedas."),
    ("重い", "おもい", "omoi", "Berat bobotnya", "Kata Sifat", "荷物が重いのでタクシーに乗ります。", "Naik taksi karena barang bawaannya berat."),
    ("軽い", "かるい", "karui", "Ringan bobotnya", "Kata Sifat", "軽くて持ち運びに便利です。", "Ringan dan praktis dibawa kemana-mana."),
    ("広い", "ひろい", "hiroi", "Luas / Lapang", "Kata Sifat", "明るくて広い部屋です。", "Kamar yang terang dan lapang."),
    ("狭い", "せまい", "semai", "Sempit ruangannya", "Kata Sifat", "部屋が狭いですが快適です。", "Kamarnya sempit tapi terasa nyaman."),
    ("若い", "わかい", "wakai", "Muda usianya", "Kata Sifat", "若いうちにたくさん挑戦します。", "Mencoba banyak hal selagi masih muda."),
    ("長い", "ながい", "nagai", "Panjang ukurannya", "Kata Sifat", "長い髪をまとめて結びます。", "Mengikat rambut yang panjang."),
    ("短い", "みじかい", "mijikai", "Pendek ukurannya", "Kata Sifat", "夏休みの期間は短いです。", "Masa libur musim panas terbilang singkat."),
    ("明るい", "あかるい", "akarui", "Terang pencahayaannya / Ceria", "Kata Sifat", "窓が大きくて明るい教室です。", "Ruang kelas terang karena jendelanya besar."),
    ("暗い", "くらい", "kurai", "Gelap gulita", "Kata Sifat", "夜道が暗いので気をつけます。", "Hati-hati karena jalanan malam gelap."),
    ("可愛い", "かわいい", "kawaii", "Lucu / Manis / Imut", "Kata Sifat", "小さくて可愛い子猫です。", "Anak kucing kecil yang sangat lucu."),

    # Kata Sifat -na (な形容詞)
    ("静か", "しずか", "shizuka", "Tenang / Hening", "Kata Sifat", "図書館はとても静かです。", "Perpustakaan suasananya sangat tenang."),
    ("賑やか", "にぎやか", "nigiyaka", "Ramai meriah", "Kata Sifat", "祭りの日は町が賑やかです。", "Kota menjadi ramai saat hari festival."),
    ("有名", "ゆうめい", "yuumei", "Terkenal / Populer", "Kata Sifat", "富士山は世界で有名です。", "Gunung Fuji terkenal di seluruh dunia."),
    ("親切", "しんせつ", "shinsetsu", "Ramah / Baik hati", "Kata Sifat", "近所の人はみんな親切です。", "Warga sekitar semuanya ramah dan baik hati."),
    ("元気", "げんき", "genki", "Sehat bugar / Bersemangat", "Kata Sifat", "毎日元気に働きます。", "Bekerja dengan penuh semangat setiap hari."),
    ("暇", "ひま", "hima", "Senggang / Tidak sibuk", "Kata Sifat", "明日は暇なので遊びに行きます。", "Besok ada waktu senggang jadi pergi main."),
    ("便利", "べんり", "benri", "Praktis / Memudahkan", "Kata Sifat", "スマホはとても便利です。", "Smartphone sangatlah praktis."),
    ("不便", "ふべん", "fuben", "Tidak praktis / Merepotkan", "Kata Sifat", "駅から遠くて不便です。", "Tidak praktis karena jauh dari stasiun."),
    ("素敵", "すてき", "suteki", "Bagus sekali / Menawan", "Kata Sifat", "素敵なプレゼントをもらいました。", "Mendapatkan hadiah yang sangat indah."),
    ("好き", "すき", "suki", "Suka / Gemar", "Kata Sifat", "日本の音楽が好きです。", "Suka mendengarkan musik Jepang."),
    ("嫌い", "きらい", "kirai", "Benci / Tidak suka", "Kata Sifat", "納豆が嫌いではありません。", "Saya tidak membenci natto."),
    ("上手", "じょうず", "jouzu", "Mahir / Pandai (pujian ke orang)", "Kata Sifat", "日本語の発音が上手ですね。", "Pelafalan bahasa Jepang Anda sangat mahir ya."),
    ("下手", "へた", "heta", "Kurang mahir / Belum pandai", "Kata Sifat", "絵を描くのが下手です。", "Saya kurang mahir dalam melukis."),
    ("簡単", "かんたん", "kantan", "Sederhana / Mudah dikerjakan", "Kata Sifat", "簡単な料理を作ります。", "Membuat hidangan yang mudah dan sederhana."),
    ("大変", "たいへん", "taihen", "Berat / Melelahkan / Sangat", "Kata Sifat", "毎日の仕事が大変です。", "Pekerjaan sehari-hari cukup berat."),
    ("大切", "たいせつ", "taisetsu", "Penting / Berharga dijaga", "Kata Sifat", "家族との時間を大切にします。", "Menghargai waktu berharga bersama keluarga."),
    ("大丈夫", "だいじょうぶ", "daijoubu", "Tidak apa-apa / Aman terkendali", "Kata Sifat", "「怪我はないですか」「大丈夫です」。", "“Apakah terluka?” “Tidak apa-apa”."),
    ("綺麗", "きれい", "kirei", "Cantik / Bersih / Indah", "Kata Sifat", "部屋を綺麗に片付けます。", "Merapikan kamar hingga bersih rapi."),
    ("熱心", "ねっしん", "nesshin", "Tekun / Antusias belajar", "Kata Sifat", "熱心に日本語を勉強します。", "Belajar bahasa Jepang dengan tekun."),
    ("真面目", "まじめ", "majime", "Jujur / Rajin / Bersungguh-sungguh", "Kata Sifat", "真面目に仕事に取り組みます。", "Mengerjakan pekerjaan dengan bersungguh-sungguh."),
    ("必要", "ひつよう", "hitsuyou", "Perlu / Dibutuhkan", "Kata Sifat", "パスポートの更新が必要です。", "Perlu perpanjangan masa berlaku paspor."),
    ("安全", "あんぜん", "anzen", "Aman terjamin", "Kata Sifat", "日本の夜道は安全です。", "Jalanan malam di Jepang aman dilalui."),
    ("危険", "きけん", "kiken", "Berbahaya / Berisiko", "Kata Sifat", "工事現場は危険ですから注意してください。", "Area konstruksi berbahaya jadi harap berhati-hati."),
    ("楽", "らく", "raku", "Santai / Nyaman tanpa beban", "Kata Sifat", "新幹線に乗ると移動が楽です。", "Perjalanan terasa nyaman jika naik Shinkansen.")
]

N5_WORK_DAILY = [
    ("仕事", "しごと", "shigoto", "Pekerjaan / Tugas kantor", "Kosakata Pekerjaan & Sehari-hari", "明日朝から仕事があります。", "Ada pekerjaan mulai besok pagi."),
    ("会社", "かいしゃ", "kaisha", "Perusahaan tempat kerja", "Kata Benda - Tempat & Fasilitas", "駅の近くの会社に勤めています。", "Bekerja di perusahaan dekat stasiun."),
    ("事務所", "じむしょ", "jimusho", "Kantor ruang administrasi", "Kata Benda - Tempat & Fasilitas", "事務所で報告書を作成します。", "Membuat laporan di kantor."),
    ("会議", "かいぎ", "kaigi", "Rapat koordinasi kerja", "Kosakata Pekerjaan & Sehari-hari", "午後二時から重要な会議があります。", "Ada rapat penting mulai pukul dua siang."),
    ("工場", "こうじょう", "koujou", "Pabrik industri produksi", "Kata Benda - Tempat & Fasilitas", "自動車の工場で組み立てを行います。", "Melakukan perakitan di pabrik mobil."),
    ("部長", "ぶちょう", "buchou", "Kepala bagian / Manajer divisi", "Kata Benda - Keluarga & Orang", "部長に書類を提出します。", "Menyerahkan dokumen kepada kepala bagian."),
    ("課長", "かちょう", "kachou", "Kepala seksi / Supervisor", "Kata Benda - Keluarga & Orang", "課長から指示を受けます。", "Menerima instruksi dari kepala seksi."),
    ("社長", "しゃちょう", "shachou", "Direktur utama perusahaan", "Kata Benda - Keluarga & Orang", "社長が新年の挨拶を述べました。", "Direktur utama menyampaikan pidato tahun baru."),
    ("名刺", "めいし", "meishi", "Kartu nama bisnis", "Kosakata Pekerjaan & Sehari-hari", "両手で名刺をお渡しします。", "Menyerahkan kartu nama bisnis dengan kedua belah tangan."),
    ("給料", "きゅうりょう", "kyuuryou", "Gaji bulanan karyawan", "Penunjuk Waktu & Angka", "毎月二十五日に給料が入ります。", "Gaji masuk setiap tanggal dua puluh lima."),
    ("休み", "やすみ", "yasumi", "Libur / Hari istirahat", "Kosakata Pekerjaan & Sehari-hari", "明日は会社の休みです。", "Besok adalah hari libur kantor."),
    ("休暇", "きゅうか", "kyuuka", "Cuti istirahat kerja", "Kosakata Pekerjaan & Sehari-hari", "有給休暇を取って旅行します。", "Mengambil cuti tahunan untuk berlibur."),
    ("計画", "けいかく", "keikaku", "Rencana kegiatan / Program", "Kosakata Pekerjaan & Sehari-hari", "旅行の計画を立てます。", "Menyusun rencana perjalanan liburan."),
    ("資料", "しりょう", "shiryou", "Bahan materi berkas dokumen", "Kosakata Pekerjaan & Sehari-hari", "会議用の資料を準備します。", "Menyiapkan berkas materi untuk rapat."),
    ("報告", "ほうこく", "houkoku", "Laporan hasil kerja", "Kosakata Pekerjaan & Sehari-hari", "上司に進捗を報告します。", "Melaporkan perkembangan kepada atasan."),
    ("連絡", "れんらく", "renraku", "Komunikasi / Menghubungi pihak terkait", "Kosakata Pekerjaan & Sehari-hari", "変更があったら連絡してください。", "Tolong hubungi kami jika ada perubahan."),
    ("相談", "そうだん", "soudan", "Konsultasi / Musyawarah bersama", "Kosakata Pekerjaan & Sehari-hari", "困ったときは先輩に相談します。", "Berkonsultasi dengan senior saat menemui kesulitan."),
    ("約束", "やくそく", "yakusoku", "Janji komitmen / Perjanjian waktu", "Kosakata Pekerjaan & Sehari-hari", "友達との約束を守ります。", "Menepati janji bersama teman."),
    ("生活", "せいかつ", "seikatsu", "Kehidupan sehari-hari", "Kosakata Pekerjaan & Sehari-hari", "日本での生活に慣れました。", "Sudah terbiasa dengan kehidupan di Jepang."),
    ("趣味", "しゅみ", "shumi", "Hobi kegemaran", "Kosakata Pekerjaan & Sehari-hari", "私の趣味は写真を撮ることです。", "Hobi saya adalah mengambil foto."),
    ("旅行", "りょこう", "ryokou", "Perjalanan wisata liburan", "Kosakata Pekerjaan & Sehari-hari", "夏休みに北海道へ旅行します。", "Berwisata ke Hokkaido pada libur musim panas."),
    ("音楽", "おんがく", "ongaku", "Musik alunan lagu", "Kosakata Pekerjaan & Sehari-hari", "部屋で静かな音楽を聴きます。", "Mendengarkan musik yang tenang di kamar."),
    ("映画", "えいが", "eiga", "Film layar lebar bioskop", "Kosakata Pekerjaan & Sehari-hari", "週末に映画を見に行きます。", "Pergi menonton film saat akhir pekan."),
    ("スポーツ", "すぽーつ", "supootsu", "Olahraga kebugaran fisik", "Kosakata Pekerjaan & Sehari-hari", "健康のためにスポーツをします。", "Berolahraga demi menjaga kesehatan."),
    ("祭り", "まつり", "matsuri", "Festival pesta rakyat", "Kosakata Pekerjaan & Sehari-hari", "夏の祭りで花火を見ます。", "Menonton kembang api di festival musim panas.")
]

print("Loaded N5 Adjectives and Work/Daily vocabulary.")
