# -*- coding: utf-8 -*-
# Data Kosakata N5: 1.000 Kotoba Resmi Minna no Nihongo Bab 1 - 25+ & Standar JLPT N5
# Format tiap item: (japanese, kana, romaji, indonesian, category, example, exampleIndonesian)

N5_AISATSU = [
    ("おはようございます", "おはようございます", "ohayou gozaimasu", "Selamat pagi (sopan)", "Salam & Ungkapan (Aisatsu)", "先生、おはようございます。", "Selamat pagi, Guru."),
    ("おはよう", "おはよう", "ohayou", "Selamat pagi (santai)", "Salam & Ungkapan (Aisatsu)", "友達におはようと言います。", "Menyapa selamat pagi kepada teman."),
    ("こんにちは", "こんにちは", "konnichiwa", "Selamat siang / Halo", "Salam & Ungkapan (Aisatsu)", "皆さん、こんにちは。", "Halo semuanya."),
    ("こんばんは", "こんばんは", "konbanwa", "Selamat malam", "Salam & Ungkapan (Aisatsu)", "夜、こんばんはと挨拶します。", "Menyapa selamat malam saat berpapasan."),
    ("おやすみなさい", "おやすみなさい", "oyasuminasai", "Selamat tidur / istirahat (sopan)", "Salam & Ungkapan (Aisatsu)", "お母さん、おやすみなさい。", "Ibu, selamat tidur."),
    ("おやすみ", "おやすみ", "oyasumi", "Selamat tidur (santai)", "Salam & Ungkapan (Aisatsu)", "また明日ね、おやすみ。", "Sampai besok ya, selamat tidur."),
    ("さようなら", "さようなら", "sayounara", "Selamat tinggal", "Salam & Ungkapan (Aisatsu)", "先生、さようなら。", "Selamat tinggal, Guru."),
    ("じゃ、また", "じゃ、また", "ja, mata", "Sampai jumpa lagi", "Salam & Ungkapan (Aisatsu)", "また明日会いましょう、じゃ、また。", "Sampai ketemu besok, sampai jumpa."),
    ("また明日", "またあした", "mata ashita", "Sampai jumpa besok", "Salam & Ungkapan (Aisatsu)", "また明日学校で会いましょう。", "Sampai jumpa besok di sekolah."),
    ("また来週", "またらいしゅう", "mata raishuu", "Sampai jumpa minggu depan", "Salam & Ungkapan (Aisatsu)", "良い週末を、また来週。", "Selamat berakhir pekan, sampai jumpa minggu depan."),
    ("ありがとうございます", "ありがとうございます", "arigatou gozaimasu", "Terima kasih banyak (sopan)", "Salam & Ungkapan (Aisatsu)", "親切にありがとうございます。", "Terima kasih banyak atas kebaikan Anda."),
    ("ありがとうございました", "ありがとうございました", "arigatou gozaimashita", "Terima kasih atas bantuan yang telah lampau", "Salam & Ungkapan (Aisatsu)", "昨日はありがとうございました。", "Terima kasih banyak atas bantuan kemarin."),
    ("どうもありがとうございます", "どうもありがとうございます", "doumo arigatou gozaimasu", "Terima kasih banyak sekali", "Salam & Ungkapan (Aisatsu)", "プレゼントをどうもありがとうございます。", "Terima kasih banyak sekali atas hadiahnya."),
    ("どういたしまして", "どういたしまして", "douitashimashite", "Sama-sama / Kembali", "Salam & Ungkapan (Aisatsu)", "「ありがとう」「どういたしまして」。", "“Terima kasih” “Sama-sama”."),
    ("すみません", "すみません", "sumimasen", "Permisi / Maaf / Tolong", "Salam & Ungkapan (Aisatsu)", "すみません、メニューをお願いします。", "Permisi, tolong berikan menunya."),
    ("ごめんなさい", "ごめんなさい", "gomennasai", "Mohon maaf", "Salam & Ungkapan (Aisatsu)", "遅れてごめんなさい。", "Mohon maaf saya datang terlambat."),
    ("失礼します", "しつれいします", "shitsureishimasu", "Permisi (masuk ruangan/pamit)", "Salam & Ungkapan (Aisatsu)", "職員室に入るとき失礼しますと言います。", "Ucapkan permisi saat memasuki ruang guru."),
    ("失礼しました", "しつれいしました", "shitsureishimashita", "Mohon maaf atas kelancangan saya (lampau)", "Salam & Ungkapan (Aisatsu)", "お邪魔して失礼しました。", "Mohon maaf atas kelancangan saya."),
    ("お邪魔します", "おじゃまします", "ojamashimasu", "Permisi bertamu ke rumah orang", "Salam & Ungkapan (Aisatsu)", "先生のお宅にお邪魔します。", "Permisi bertamu ke kediaman guru."),
    ("いただきます", "いただきます", "itadakimasu", "Selamat makan (doa sebelum makan)", "Salam & Ungkapan (Aisatsu)", "食べる前にいただきますと言います。", "Ucapkan selamat makan sebelum menyantap hidangan."),
    ("ごちそうさまでした", "ごちそうさまでした", "gochisousamadeshita", "Terima kasih atas hidangannya (setelah makan)", "Salam & Ungkapan (Aisatsu)", "食後にごちそうさまでしたと言います。", "Ucapkan terima kasih atas hidangan setelah selesai makan."),
    ("いってきます", "いってきます", "ittekimasu", "Saya berangkat dulu", "Salam & Ungkapan (Aisatsu)", "学校へいってきます。", "Saya berangkat dulu ke sekolah."),
    ("いってらっしゃい", "いってらっしゃい", "itterasshai", "Selamat jalan / Hati-hati di jalan", "Salam & Ungkapan (Aisatsu)", "出かける人にいってらっしゃいと言います。", "Ucapkan selamat jalan kepada orang yang berangkat."),
    ("ただいま", "ただいま", "tadaima", "Saya pulang / Sudah kembali", "Salam & Ungkapan (Aisatsu)", "家に着いてただいまと言います。", "Ucapkan saya pulang saat tiba di rumah."),
    ("おかえりなさい", "おかえりなさい", "okaerinasai", "Selamat datang kembali", "Salam & Ungkapan (Aisatsu)", "帰宅した家族におかえりなさいと言います。", "Sambut keluarga yang pulang dengan selamat datang kembali."),
    ("いらっしゃいませ", "いらっしゃいませ", "irasshaimase", "Selamat datang (pelanggan toko)", "Salam & Ungkapan (Aisatsu)", "店員がいらっしゃいませと迎えます。", "Pegawai toko menyambut dengan selamat datang."),
    ("初めまして", "はじめまして", "hajimemashite", "Perkenalkan / Senang bertemu pertama kali", "Salam & Ungkapan (Aisatsu)", "初めまして、田中です。", "Perkenalkan, saya Tanaka."),
    ("どうぞよろしくお願いします", "どうぞよろしくおねがいします", "douzo yoroshiku onegaishimasu", "Mohon bimbingan dan kerja samanya", "Salam & Ungkapan (Aisatsu)", "こちらこそ、どうぞよろしくお願いします。", "Saya pun mohon kerja samanya."),
    ("こちらこそ", "こちらこそ", "kochirakoso", "Sama-sama / Justru dari pihak saya", "Salam & Ungkapan (Aisatsu)", "こちらこそよろしくお願いします。", "Saya pun sangat mengharapkan kerja sama Anda."),
    ("お元気ですか", "おげんきですか", "ogenki desu ka", "Apa kabar?", "Salam & Ungkapan (Aisatsu)", "お久しぶりです、お元気ですか。", "Sudah lama tidak berjumpa, apa kabar?"),
    ("はい、元気です", "はい、げんきです", "hai, genki desu", "Ya, saya sehat walafiat", "Salam & Ungkapan (Aisatsu)", "おかげさまで元気です。", "Berkat doa Anda saya sehat walafiat."),
    ("お疲れ様でした", "おつかれさまでした", "otsukaresamadeshita", "Terima kasih atas kerja kerasnya", "Salam & Ungkapan (Aisatsu)", "今日の仕事はお疲れ様でした。", "Terima kasih atas kerja keras Anda hari ini."),
    ("お先に失礼します", "おさきにしつれいします", "osaki ni shitsureishimasu", "Saya mohon pamit pulang duluan", "Salam & Ungkapan (Aisatsu)", "定時ですのでお先に失礼します。", "Karena sudah jam pulang saya pamit duluan."),
    ("お大事に", "おだいじに", "odaiji ni", "Semoga lekas sembuh", "Salam & Ungkapan (Aisatsu)", "風邪ですね、どうぞお大事に。", "Anda sedang flu, semoga lekas sembuh."),
    ("気をつけて", "きをつけて", "ki wo tsukete", "Hati-hati ya", "Salam & Ungkapan (Aisatsu)", "夜道に気をつけて帰ってください。", "Hati-hati di jalan pulang waktu malam."),
    ("いかがですか", "いかがですか", "ikaga desu ka", "Bagaimana kalau...? (tawaran sopan)", "Salam & Ungkapan (Aisatsu)", "温かいお茶はいかがですか。", "Bagaimana kalau minum teh hangat?"),
    ("結構です", "けっこうです", "kekkou desu", "Sudah cukup / Tidak perlu (halus)", "Salam & Ungkapan (Aisatsu)", "いいえ、もう結構です。", "Tidak, sudah cukup terima kasih."),
    ("どうぞ", "どうぞ", "douzo", "Silakan", "Salam & Ungkapan (Aisatsu)", "どうぞお掛けください。", "Silakan duduk."),
    ("どうも", "どうも", "doumo", "Terima kasih / Halo (santai)", "Salam & Ungkapan (Aisatsu)", "どうも手伝ってくれてありがとう。", "Terima kasih banyak sudah membantu."),
    ("おめでとうございます", "おめでとうございます", "omedetou gozaimasu", "Selamat atas keberhasilan / momen bahagia", "Salam & Ungkapan (Aisatsu)", "合格おめでとうございます。", "Selamat atas kelulusan Anda."),
    ("乾杯", "かんぱい", "kanpai", "Bersulang!", "Salam & Ungkapan (Aisatsu)", "みんなで乾杯しましょう。", "Mari kita bersulang bersama."),
    ("かしこまりました", "かしこまりました", "kashikomarimashita", "Baik, saya mengerti dan laksanakan", "Salam & Ungkapan (Aisatsu)", "ご注文、かしこまりました。", "Pesanan Anda sudah saya pahami dan segera disiapkan."),
    ("少々お待ちください", "しょうしょうおまちください", "shoushou omachi kudasai", "Mohon tunggu sebentar", "Salam & Ungkapan (Aisatsu)", "確認しますので少々お待ちください。", "Mohon tunggu sebentar untuk pengecekan."),
    ("もう一度お願いします", "もういちどおねがいします", "mou ichido onegaishimasu", "Tolong ulangi sekali lagi", "Salam & Ungkapan (Aisatsu)", "聞き取れなかったのでもう一度お願いします。", "Karena belum terdengar tolong ulangi sekali lagi."),
    ("ゆっくり話してください", "ゆっくりはなしてください", "yukkuri hanashite kudasai", "Tolong bicara secara perlahan", "Salam & Ungkapan (Aisatsu)", "日本語をゆっくり話してください。", "Tolong bicaralah bahasa Jepang perlahan-lahan."),
    ("わかりました", "わかりました", "wakarimashita", "Saya sudah mengerti", "Salam & Ungkapan (Aisatsu)", "先生の説明がわかりました。", "Saya sudah memahami penjelasan guru."),
    ("わかりません", "わかりません", "wakarimasen", "Saya tidak mengerti", "Salam & Ungkapan (Aisatsu)", "この漢字の意味がわかりません。", "Saya tidak mengerti arti kanji ini."),
    ("いいですよ", "いいですよ", "ii desu yo", "Boleh saja / Tentu saja", "Salam & Ungkapan (Aisatsu)", "「写真をとってもいいですか」「いいですよ」。", "“Bolehkah mengambil foto?” “Boleh saja”."),
    ("だめです", "だめです", "dame desu", "Tidak boleh / Jangan", "Salam & Ungkapan (Aisatsu)", "ここでタバコを吸ってはだめです。", "Tidak boleh merokok di sini.")
]

N5_PRONOUNS_QUESTIONS = [
    ("私", "わたし", "watashi", "Saya / Aku", "Kata Tanya & Kata Ganti", "私は日本語の学生です。", "Saya adalah mahasiswa bahasa Jepang."),
    ("私たち", "わたしたち", "watashitachi", "Kami / Kita", "Kata Tanya & Kata Ganti", "私たちは毎日勉強します。", "Kami belajar setiap hari."),
    ("あなた", "あなた", "anata", "Anda / Kamu", "Kata Tanya & Kata Ganti", "あなたは日本人ですか。", "Apakah Anda orang Jepang?"),
    ("あの人", "あのひと", "ano hito", "Orang itu", "Kata Tanya & Kata Ganti", "あの人は誰ですか。", "Siapakah orang itu?"),
    ("あの方", "あのかた", "ano kata", "Beliau itu (sopan)", "Kata Tanya & Kata Ganti", "あの方は病院の先生です。", "Beliau adalah dokter rumah sakit."),
    ("皆さん", "みなさん", "minasan", "Semua hadirin / Saudara sekalian", "Kata Tanya & Kata Ganti", "皆さん、聞いてください。", "Hadirin sekalian, tolong dengarkan."),
    ("だれ", "だれ", "dare", "Siapa?", "Kata Tanya & Kata Ganti", "教室にいるのはだれですか。", "Siapa yang ada di ruang kelas?"),
    ("どなた", "どなた", "donata", "Siapakah beliau? (sopan)", "Kata Tanya & Kata Ganti", "あちらに立つ方はどなたですか。", "Siapakah beliau yang berdiri di sana?"),
    ("これ", "これ", "kore", "Ini (benda dekat pembicara)", "Kata Tanya & Kata Ganti", "これは私の教科書です。", "Ini adalah buku pelajaran saya."),
    ("それ", "それ", "sore", "Itu (benda dekat lawan bicara)", "Kata Tanya & Kata Ganti", "それは辞書ですか。", "Apakah itu kamus?"),
    ("あれ", "あれ", "are", "Itu (benda jauh)", "Kata Tanya & Kata Ganti", "あれは東京タワーです。", "Itu adalah Menara Tokyo."),
    ("どれ", "どれ", "dore", "Yang mana? (3 pilihan atau lebih)", "Kata Tanya & Kata Ganti", "あなたのかばんはどれですか。", "Tas milikmu yang mana?"),
    ("この", "この", "kono", "... ini (menerangkan benda)", "Kata Tanya & Kata Ganti", "この傘は誰のですか。", "Payung ini milik siapa?"),
    ("その", "その", "sono", "... itu (dekat lawan bicara)", "Kata Tanya & Kata Ganti", "その時計は綺麗ですね。", "Jam tangan itu bagus sekali ya."),
    ("あの", "あの", "ano", "... itu (jauh)", "Kata Tanya & Kata Ganti", "あの山はとても高いです。", "Gunung itu sangat tinggi."),
    ("どの", "どの", "dono", "... yang mana?", "Kata Tanya & Kata Ganti", "どの靴を買いますか。", "Sepatu yang mana yang akan dibeli?"),
    ("ここ", "ここ", "koko", "Di sini", "Kata Tanya & Kata Ganti", "ここは教室です。", "Di sini adalah ruang kelas."),
    ("そこ", "そこ", "soko", "Di situ", "Kata Tanya & Kata Ganti", "そこは食堂です。", "Di situ adalah kantin."),
    ("あそこ", "あそこ", "asoko", "Di sana", "Kata Tanya & Kata Ganti", "あそこは図書館です。", "Di sana adalah perpustakaan."),
    ("どこ", "どこ", "doko", "Di mana? / Kemana?", "Kata Tanya & Kata Ganti", "トイレはどこですか。", "Di manakah toilet?"),
    ("こちら", "こちら", "kochira", "Sebelah sini (sopan)", "Kata Tanya & Kata Ganti", "受付はこちらです。", "Resepsionis ada di sebelah sini."),
    ("そちら", "そちら", "sochira", "Sebelah situ (sopan)", "Kata Tanya & Kata Ganti", "電話はそちらにあります。", "Telepon ada di sebelah situ."),
    ("あちら", "あちら", "achira", "Sebelah sana (sopan)", "Kata Tanya & Kata Ganti", "階段はあちらです。", "Tangga ada di sebelah sana."),
    ("どちら", "どちら", "dochira", "Sebelah mana? / Yang mana? (sopan)", "Kata Tanya & Kata Ganti", "お国はどちらですか。", "Negara asal Anda dari mana?"),
    ("何", "なに / なん", "nani / nan", "Apa?", "Kata Tanya & Kata Ganti", "これは何ですか。", "Ini apa?"),
    ("いつ", "いつ", "itsu", "Kapan?", "Kata Tanya & Kata Ganti", "日本へいつ行きますか。", "Kapan akan pergi ke Jepang?"),
    ("いくら", "いくら", "ikura", "Berapa harganya?", "Kata Tanya & Kata Ganti", "この本はいくらですか。", "Buku ini harganya berapa?"),
    ("いくつ", "いくつ", "ikutsu", "Berapa buah? / Berapa umur?", "Kata Tanya & Kata Ganti", "リンゴをいくつ買いましたか。", "Membeli berapa buah apel?"),
    ("何人", "なんにん", "nannin", "Berapa orang?", "Kata Tanya & Kata Ganti", "家族は何人ですか。", "Keluarga Anda berapa orang?"),
    ("何歳", "なんさい", "nansai", "Berapa umur?", "Kata Tanya & Kata Ganti", "田中さんは何歳ですか。", "Saudara Tanaka berapa umurnya?"),
    ("おいくつ", "おいくつ", "oikutsu", "Berapa usia Anda? (sopan)", "Kata Tanya & Kata Ganti", "失礼ですが、おいくつですか。", "Mohon maaf, berapa usia Anda?"),
    ("何時", "なんじ", "nanji", "Jam berapa?", "Kata Tanya & Kata Ganti", "今、何時ですか。", "Sekarang jam berapa?"),
    ("何分", "なんぷん", "nanpun", "Berapa menit?", "Kata Tanya & Kata Ganti", "駅から歩いて何分ですか。", "Berapa menit berjalan kaki dari stasiun?"),
    ("何曜日", "なんようび", "nanyoubi", "Hari apa?", "Kata Tanya & Kata Ganti", "明日は何曜日ですか。", "Besok hari apa?"),
    ("何月", "なんがつ", "nangatsu", "Bulan apa?", "Kata Tanya & Kata Ganti", "誕生日は何月ですか。", "Ulang tahun di bulan apa?"),
    ("何日", "なんにち", "nannichi", "Tanggal berapa? / Berapa hari?", "Kata Tanya & Kata Ganti", "今日は何日ですか。", "Hari ini tanggal berapa?"),
    ("何番", "なんばん", "nanban", "Nomor berapa?", "Kata Tanya & Kata Ganti", "電話番号は何番ですか。", "Nomor teleponnya berapa?"),
    ("どう", "どう", "dou", "Bagaimana?", "Kata Tanya & Kata Ganti", "日本の料理はどうですか。", "Bagaimana masakan Jepang?"),
    ("どうして", "どうして", "doushite", "Mengapa? / Kenapa?", "Kata Tanya & Kata Ganti", "どうして遅れましたか。", "Mengapa Anda terlambat?"),
    ("なぜ", "なぜ", "naze", "Mengapa? (formal)", "Kata Tanya & Kata Ganti", "なぜ勉強しますか。", "Mengapa Anda belajar?"),
    ("どんな", "どんな", "donna", "Yang seperti apa? / Macam apa?", "Kata Tanya & Kata Ganti", "どんな音楽が好きですか。", "Musik seperti apa yang kamu sukai?"),
    ("どっち", "どっち", "dotchi", "Yang mana? (pilihan dari 2 hal)", "Kata Tanya & Kata Ganti", "肉と魚、どっちが好きですか。", "Daging atau ikan, kamu suka yang mana?"),
    ("どれくらい", "どれくらい", "dorekurai", "Berapa lama? / Berapa banyak?", "Kata Tanya & Kata Ganti", "東京までどれくらいかかりますか。", "Berapa lama memakan waktu sampai Tokyo?"),
    ("どのくらい", "どのくらい", "donokurai", "Berapa banyak / seberapa lama?", "Kata Tanya & Kata Ganti", "日本語をどのくらい勉強しましたか。", "Sudah berapa lama belajar bahasa Jepang?"),
    ("自己紹介", "じこしょうかい", "jikoshoukai", "Perkenalan diri sendiri", "Kata Tanya & Kata Ganti", "面接で自己紹介をします。", "Melakukan perkenalan diri saat wawancara.")
]

print(f"Loaded {len(N5_AISATSU)} Aisatsu and {len(N5_PRONOUNS_QUESTIONS)} Question/Pronouns.")
