# -*- coding: utf-8 -*-
# Kosakata Pelengkap Minna no Nihongo Bab 1 - 25+ (Partikel, Konjungsi, Keterangan Waktu & Frekuensi, Kata Bantu Bilangan, Kata Kerja & Kata Sifat Tambahan)

N5_MNN_ADDITIONS_2 = [
    # Kata Keterangan Frekuensi & Derajat (副詞)
    ("いつも", "いつも", "itsumo", "Selalu (100% frekuensi)", "Kosakata Pekerjaan & Sehari-hari", "いつも朝六時に起きます。", "Selalu bangun jam enam pagi."),
    ("大抵", "たいてい", "taitei", "Biasanya / Pada umumnya", "Kosakata Pekerjaan & Sehari-hari", "休日は大抵家にいます。", "Hari libur biasanya ada di rumah."),
    ("よく", "よく", "yoku", "Sering / Dengan baik", "Kosakata Pekerjaan & Sehari-hari", "よく友達と旅行します。", "Sering berlibur bersama teman."),
    ("時々", "ときどき", "tokidoki", "Kadang-kadang", "Kosakata Pekerjaan & Sehari-hari", "時々日本料理を作ります。", "Kadang-kadang memasak masakan Jepang."),
    ("たまに", "たまに", "tamani", "Sesekali / Jarang-jarang", "Kosakata Pekerjaan & Sehari-hari", "たまに外食します。", "Sesekali makan di luar."),
    ("あまり", "あまり", "amari", "Tidak begitu / Tidak terlalu (dengan bentuk negatif)", "Kosakata Pekerjaan & Sehari-hari", "肉はあまり食べません。", "Tidak terlalu sering makan daging."),
    ("全然", "ぜんぜん", "zenzen", "Sama sekali tidak (dengan bentuk negatif)", "Kosakata Pekerjaan & Sehari-hari", "お酒は全然飲みません。", "Sama sekali tidak minum alkohol."),
    ("とても", "とても", "totemo", "Sangat / Amat", "Kosakata Pekerjaan & Sehari-hari", "今日はとても寒いです。", "Hari ini sangat dingin."),
    ("大変", "たいへん", "taihen", "Sangat / Luar biasa", "Kosakata Pekerjaan & Sehari-hari", "大変お世話になりました。", "Terima kasih atas bantuan yang luar biasa."),
    ("少し", "すこし", "sukoshi", "Sedikit / Agak", "Kosakata Pekerjaan & Sehari-hari", "少し日本語が話せます。", "Bisa berbicara sedikit bahasa Jepang."),
    ("ちょっと", "ちょっと", "chotto", "Sebentar / Sedikit", "Kosakata Pekerjaan & Sehari-hari", "ちょっと待ってください。", "Tolong tunggu sebentar."),
    ("もっと", "もっと", "motto", "Lebih lagi", "Kosakata Pekerjaan & Sehari-hari", "もっとゆっくり話してください。", "Tolong bicara lebih perlahan lagi."),
    ("ずっと", "ずっと", "zutto", "Jauh lebih / Terus-menerus", "Kosakata Pekerjaan & Sehari-hari", "新幹線はずっと速いです。", "Shinkansen jauh lebih cepat."),
    ("一番", "いちばん", "ichiban", "Paling / Nomor satu", "Kosakata Pekerjaan & Sehari-hari", "日本で一番高い山は富士山です。", "Gunung tertinggi di Jepang adalah Gunung Fuji."),
    ("大体", "だいたい", "daitai", "Kira-kira / Garis besarnya", "Kosakata Pekerjaan & Sehari-hari", "宿題は大体終わりました。", "PR garis besarnya sudah selesai."),
    ("全部", "ぜんぶ", "zenbu", "Semuanya / Seluruhnya", "Kosakata Pekerjaan & Sehari-hari", "荷物を全部運びました。", "Memindahkan seluruh barang bawaan."),
    ("みんな", "みんな", "minna", "Semua orang / Semuanya", "Kosakata Pekerjaan & Sehari-hari", "みんなで歌を歌いましょう。", "Mari menyanyi bersama semuanya."),
    ("一緒に", "いっしょに", "isshoni", "Bersama-sama", "Kosakata Pekerjaan & Sehari-hari", "一緒に昼ご飯を食べませんか。", "Maukah makan siang bersama-sama?"),
    ("一人で", "ひとりで", "hitoride", "Sendiri / Seorang diri", "Kosakata Pekerjaan & Sehari-hari", "一人で映画を見に行きます。", "Pergi menonton film sendirian."),
    ("自分で", "じぶんで", "jibunde", "Oleh diri sendiri", "Kosakata Pekerjaan & Sehari-hari", "自分で部屋を掃除します。", "Membersihkan kamar oleh diri sendiri."),
    ("本当に", "ほんとうに", "hontouni", "Sungguh-sungguh / Benar-benar", "Kosakata Pekerjaan & Sehari-hari", "本当にありがとうございました。", "Benar-benar terima kasih banyak."),
    ("特に", "とくに", "tokuni", "Khususnya / Terutama", "Kosakata Pekerjaan & Sehari-hari", "特に刺身が好きです。", "Khususnya sangat menyukai sashimi."),

    # Kata Sambung & Konjungsi (接続詞)
    ("そして", "そして", "soshite", "Dan kemudian / Lalu", "Salam & Ungkapan (Aisatsu)", "顔を洗いました。そして朝ご飯を食べました。", "Mencuci muka, kemudian menyantap sarapan pagi."),
    ("それから", "それから", "sorekara", "Setelah itu / Kemudian", "Salam & Ungkapan (Aisatsu)", "宿題をします。それから寝ます。", "Mengerjakan PR, setelah itu tidur."),
    ("でも", "でも", "demo", "Tetapi / Namun (santai)", "Salam & Ungkapan (Aisatsu)", "日本語は難しいです。でも面白いです。", "Bahasa Jepang sulit, namun menarik."),
    ("しかし", "しかし", "shikashi", "Tetapi / Namun (formal)", "Salam & Ungkapan (Aisatsu)", "雨が降りました。しかし試合は続きました。", "Hujan turun, tetapi pertandingan berlanjut."),
    ("だから", "だから", "dakara", "Oleh karena itu / Jadi", "Salam & Ungkapan (Aisatsu)", "明日は休みです。だから出かけます。", "Besok libur, oleh karena itu saya bepergian."),
    ("ですから", "ですから", "desukara", "Oleh karena itu (sopan)", "Salam & Ungkapan (Aisatsu)", "時間がありません。ですから急ぎましょう。", "Tidak ada waktu, oleh karena itu mari bergegas."),
    ("また", "また", "mata", "Lagi / Serta", "Salam & Ungkapan (Aisatsu)", "また明日会いましょう。", "Mari bertemu lagi besok."),
    ("じゃあ", "じゃあ", "jaa", "Kalau begitu / Baiklah", "Salam & Ungkapan (Aisatsu)", "じゃあ、五時に会いましょう。", "Kalau begitu mari bertemu jam lima."),
    ("では", "では", "dewa", "Kalau begitu (formal)", "Salam & Ungkapan (Aisatsu)", "では、授業を始めます。", "Kalau begitu mari kita mulai kelas."),

    # Keterangan Waktu & Urutan (時間表現)
    ("朝早く", "あさはやく", "asahayaku", "Pagi-pagi buta", "Penunjuk Waktu & Angka", "朝早く起きて散歩します。", "Bangun pagi-pagi buta lalu jalan santai."),
    ("夜遅く", "よるおそく", "yoruosoku", "Larut malam", "Penunjuk Waktu & Angka", "夜遅くまで勉強しました。", "Belajar sampai larut malam."),
    ("昼休み", "ひるやすみ", "hiruyasumi", "Istirahat siang", "Penunjuk Waktu & Angka", "昼休みに公園へ行きます。", "Pergi ke taman saat istirahat siang."),
    ("平日", "へいじつ", "heijitsu", "Hari kerja biasa (Senin-Jumat)", "Penunjuk Waktu & Angka", "平日は会社で働きます。", "Bekerja di kantor pada hari kerja biasa."),
    ("祝日", "しゅくじつ", "shukujitsu", "Hari libur nasional", "Penunjuk Waktu & Angka", "祝日は博物館が無料です。", "Museum gratis pada hari libur nasional."),
    ("先月", "せんげつ", "sengetsu", "Bulan lalu", "Penunjuk Waktu & Angka", "先月日本へ来ました。", "Datang ke Jepang pada bulan lalu."),
    ("今月", "こんげつ", "kongetsu", "Bulan ini", "Penunjuk Waktu & Angka", "今月は忙しいです。", "Bulan ini sangat sibuk."),
    ("来月", "らいげつ", "raigetsu", "Bulan depan", "Penunjuk Waktu & Angka", "来月新しいアパートへ引っ越します。", "Pindah ke apartemen baru bulan depan."),
    ("毎月", "まいつき / まいげつ", "maitsuki / maigetsu", "Setiap bulan", "Penunjuk Waktu & Angka", "毎月貯金をします。", "Menabung setiap bulan."),
    ("一昨年", "おととし", "ototoshi", "Dua tahun lalu", "Penunjuk Waktu & Angka", "一昨年大学を卒業しました。", "Lulus universitas dua tahun lalu."),
    ("再来年", "さらいねん", "sarainen", "Dua tahun lagi", "Penunjuk Waktu & Angka", "再来年帰国する予定です。", "Berencana pulang ke tanah air dua tahun lagi."),
    ("再来週", "さらいしゅう", "saraishuu", "Dua minggu lagi", "Penunjuk Waktu & Angka", "再来週試験があります。", "Ada ujian dua minggu lagi."),
    ("再来月", "さらいげつ", "saraigetsu", "Dua bulan lagi", "Penunjuk Waktu & Angka", "再来月旅行に行きます。", "Pergi liburan dua bulan lagi."),

    # Kosakata Tempat & Geografi Jepang
    ("アジア", "あじあ", "ajia", "Benua Asia", "Kata Benda - Tempat & Fasilitas", "アジアの国々を巡ります。", "Berkeliling negara-negara di benua Asia."),
    ("東京", "とうきょう", "toukyou", "Tokyo (Ibukota Jepang)", "Kata Benda - Tempat & Fasilitas", "東京は活気がある大都市です。", "Tokyo adalah kota metropolitan yang semarak."),
    ("京都", "きょうと", "kyouto", "Kyoto (Kota bersejarah)", "Kata Benda - Tempat & Fasilitas", "京都の神社を見学します。", "Mengunjungi kuil Shinto di Kyoto."),
    ("大阪", "おおさか", "oosaka", "Osaka", "Kata Benda - Tempat & Fasilitas", "大阪で美味しい料理を食べます。", "Menyantap masakan lezat di Osaka."),
    ("富士山", "ふじさん", "fujisan", "Gunung Fuji", "Kata Benda - Alam & Cuaca", "富士山の頂上から朝日を見ます。", "Melihat matahari terbit dari puncak Gunung Fuji."),
    ("神社", "じんじゃ", "jinja", "Kuil Shinto", "Kata Benda - Tempat & Fasilitas", "神社でお祈りをします。", "Berdoa di kuil Shinto."),
    ("寺", "てら", "tera", "Kuil Buddha (Otera)", "Kata Benda - Tempat & Fasilitas", "お寺で鐘を鳴らします。", "Membunyikan lonceng di kuil Buddha."),
    ("城", "しろ", "shiro", "Kastil / Istana bersejarah", "Kata Benda - Tempat & Fasilitas", "大阪城の天守閣に登ります。", "Menaiki menara utama Istana Osaka."),
    ("温泉", "おんせん", "onsen", "Pemandian air panas alami", "Kata Benda - Tempat & Fasilitas", "温泉に入ってリラックスします。", "Berendam di onsen dan bersantai ria."),
    ("旅館", "りょかん", "ryokan", "Penginapan tradisional Jepang", "Kata Benda - Tempat & Fasilitas", "旅館で畳の部屋に泊まります。", "Menginap di kamar beralaskan tatami di ryokan."),

    # Kosakata Makanan, Minuman, Rasa & Bumbu Masakan
    ("胡椒", "こしょう", "koshou", "Lada / Merica bubuk", "Kata Benda - Buah & Makanan", "スープに胡椒をかけます。", "Menaburkan merica pada sup."),
    ("油", "あぶら", "abura", "Minyak goreng", "Kata Benda - Buah & Makanan", "フライパンに油をひきます。", "Menuangkan minyak ke wajan penggorengan."),
    ("酢", "す", "su", "Cuka masam", "Kata Benda - Buah & Makanan", "酢の物を作ります。", "Membuat hidangan acar dengan cuka."),
    ("味噌", "みそ", "miso", "Pasta kedelai Miso", "Kata Benda - Buah & Makanan", "毎朝温かい味噌汁を飲みます。", "Minum sup miso hangat setiap pagi."),
    ("豆腐", "とうふ", "toufu", "Tahu kedelai", "Kata Benda - Buah & Makanan", "冷奴の豆腐を食べます。", "Menyantap tahu dingin hiyayakko."),
    ("納豆", "なっとう", "nattou", "Natto (fermentasi kedelai)", "Kata Benda - Buah & Makanan", "ご飯に納豆をのせて食べます。", "Makan natto di atas nasi putih."),
    ("海苔", "のり", "nori", "Rumput laut kering", "Kata Benda - Buah & Makanan", "おにぎりに海苔を巻きます。", "Membalut onigiri dengan rumput laut nori."),
    ("梅干し", "うめぼし", "umeboshi", "Asinan buah plum Jepang", "Kata Benda - Buah & Makanan", "すっぱい梅干しを食べます。", "Makan asinan umeboshi yang masam."),
    ("わさび", "わさび", "wasabi", "Wasabi hijau pedas", "Kata Benda - Buah & Makanan", "お寿司にわさびをつけます。", "Membubuhi sushi dengan wasabi."),
    ("生姜", "しょうが", "shouga", "Jahe rempah", "Kata Benda - Buah & Makanan", "豚の生姜焼きを作ります。", "Memasak daging tumis jahe shogayaki."),
    ("おにぎり", "おにぎり", "onigiri", "Nasi kepal segitiga", "Kata Benda - Buah & Makanan", "鮭のおにぎりを買いました。", "Membeli onigiri isi salmon."),
    ("サンドイッチ", "さんどいっち", "sandoicchi", "Roti lapis (Sandwich)", "Kata Benda - Buah & Makanan", "たまごサンドイッチを食べます。", "Memakan roti lapis telur."),
    ("サラダ", "さらだ", "sarada", "Salad sayuran", "Kata Benda - Buah & Makanan", "新鮮な野菜サラダです。", "Salad sayuran segar."),
    ("スープ", "すーぷ", "suupu", "Sup kuah hangat", "Kata Benda - Buah & Makanan", "コーンスープを温めます。", "Menghangatkan sup jagung manis."),
    ("ハンバーグ", "はんばーぐ", "hanbaagu", "Steak daging cincang (Hamburg)", "Kata Benda - Buah & Makanan", "デミグラスソースのハンバーグです。", "Hamburg dengan saus demiglace."),
    ("ピザ", "ぴざ", "piza", "Pizza", "Kata Benda - Buah & Makanan", "熱々のチーズピザを注文します。", "Memesan pizza keju panas."),
    ("パスタ", "ぱすた", "pasuta", "Pasta / Spaghetti", "Kata Benda - Buah & Makanan", "トマトソースのパスタを作ります。", "Membuat pasta saus tomat."),

    # Kosakata Benda Rumah & Elektronik Tambahan
    ("電子レンジ", "でんしれんじ", "denshirenji", "Microwave penghangat", "Kata Benda - Rumah & Barang", "電子レンジでお弁当を温めます。", "Menghangatkan bekal dengan microwave."),
    ("炊飯器", "すいはんき", "suihanki", "Rice cooker penanak nasi", "Kata Benda - Rumah & Barang", "炊飯器でお米を炊きます。", "Menanak beras di rice cooker."),
    ("掃除機", "そうじき", "soujiki", "Penghisap debu (Vacuum Cleaner)", "Kata Benda - Rumah & Barang", "掃除機で部屋を綺麗にします。", "Membersihkan ruangan dengan vacuum cleaner."),
    ("ドライヤー", "どらいやー", "doraiyaa", "Pengering rambut (Hair Dryer)", "Kata Benda - Rumah & Barang", "ドライヤーで髪を乾かします。", "Mengeringkan rambut dengan hair dryer."),
    ("扇風機", "せんぷうき", "senpuuki", "Kipas angin baling-baling", "Kata Benda - Rumah & Barang", "夏に扇風機を回します。", "Menyalakan kipas angin di musim panas."),
    ("アイロン", "あいろん", "airon", "Setrika pakaian", "Kata Benda - Rumah & Barang", "シャツにアイロンをかけます。", "Menyetrika pakaian kemeja."),
    ("ポット", "ぽっと", "potto", "Termos pemanas air", "Kata Benda - Rumah & Barang", "電気ポットでお湯を沸かします。", "Memasak air dengan teko listrik termos."),
    ("毛布", "もうふ", "moufu", "Selimut wol hangat", "Kata Benda - Rumah & Barang", "冬に暖かい毛布を掛けます。", "Memakai selimut wol hangat di musim dingin."),
    ("枕", "まくら", "makura", "Bantal tidur", "Kata Benda - Rumah & Barang", "柔らかい枕で寝ます。", "Tidur dengan bantal empuk."),
    ("シーツ", "しーつ", "shiitsu", "Sprei kasur tempat tidur", "Kata Benda - Rumah & Barang", "シーツを洗濯して干します。", "Mencuci dan menjemur sprei kasur."),
    ("カーテン", "かーてん", "kaaten", "Gorden tirai jendela", "Kata Benda - Rumah & Barang", "朝カーテンを開けて光を入れます。", "Membuka tirai gorden di pagi hari."),
    ("ゴミ袋", "ごみぶくろ", "gomibukuro", "Kantong plastik sampah", "Kata Benda - Rumah & Barang", "指定のゴミ袋を使います。", "Menggunakan kantong sampah yang ditentukan."),

    # Kosakata Anggota Tubuh & Pakaian Tambahan
    ("首", "くび", "kubi", "Leher", "Kata Benda - Tubuh & Pakaian", "首にマフラーを巻きます。", "Melilitkan syal di leher."),
    ("肩", "かた", "kata", "Bahu / Pundak", "Kata Benda - Tubuh & Pakaian", "パソコン作業で肩が凝ります。", "Pundak terasa kaku karena bekerja di komputer."),
    ("背中", "せなか", "senaka", "Punggung badan", "Kata Benda - Tubuh & Pakaian", "背中をまっすぐに伸ばします。", "Meluruskan posisi punggung."),
    ("胸", "むね", "mune", "Dada", "Kata Benda - Tubuh & Pakaian", "深呼吸して胸を広げます。", "Menarik napas dalam-dalam membusungkan dada."),
    ("指", "ゆび", "yubi", "Jari tangan", "Kata Benda - Tubuh & Pakaian", "指に指輪をはめます。", "Mengenakan cincin di jari tangan."),
    ("爪", "つめ", "tsume", "Kuku", "Kata Benda - Tubuh & Pakaian", "爪切りで爪を切ります。", "Memotong kuku dengan gunting kuku."),
    ("腕", "うで", "ude", "Lengan tangan", "Kata Benda - Tubuh & Pakaian", "腕相撲で競い合います。", "Beradu panco lengan tangan."),
    ("膝", "ひざ", "hiza", "Lutut kaki", "Kata Benda - Tubuh & Pakaian", "転んで膝を擦りむきました。", "Lutut lecet karena terjatuh."),
    ("声", "こえ", "koe", "Suara vokal manusia", "Kata Benda - Tubuh & Pakaian", "大きな声で挨拶します。", "Menyapa dengan suara lantang."),
    ("マフラー", "まふらー", "mafuraa", "Syal leher musim dingin", "Kata Benda - Tubuh & Pakaian", "手編みのマフラーを巻きます。", "Mengenakan syal rajutan tangan."),
    ("手袋", "てぶくろ", "tebukuro", "Sarung tangan pelindung", "Kata Benda - Tubuh & Pakaian", "寒い日に革の手袋をはめます。", "Mengenakan sarung tangan kulit di hari dingin."),
    ("指輪", "ゆびわ", "yubiwa", "Cincin perhiasan", "Kata Benda - Tubuh & Pakaian", "結婚指輪を大切にします。", "Menjaga cincin pernikahan dengan baik."),
    ("ネックレス", "ねっくれす", "nekkuresu", "Kalung leher perhiasan", "Kata Benda - Tubuh & Pakaian", "真珠のネックレスをつけます。", "Mengenakan kalung mutiara."),
    ("スーツ", "すーつ", "suutsu", "Setelan jas formal", "Kata Benda - Tubuh & Pakaian", "面接に紺のスーツを着ていきます。", "Mengenakan setelan jas biru tua saat wawancara."),
    ("着物", "きもの", "kimono", "Kimono pakaian adat tradisional Jepang", "Kata Benda - Tubuh & Pakaian", "成人の日に美しい着物を着ます。", "Mengenakan kimono indah pada Hari Kedewasaan."),
    ("浴衣", "ゆかた", "yukata", "Yukata pakaian santai musim panas", "Kata Benda - Tubuh & Pakaian", "花火大会に浴衣を着て行きます。", "Pergi ke festival kembang api mengenakan yukata.")
]

print("Loaded extra additions part 2.")
