# -*- coding: utf-8 -*-
# Data Kata Benda Umum (Nama Buah, Makanan, Kendaraan, Tempat, Keluarga, Rumah, Tubuh, Pakaian, Alam)

N5_NOUNS_FOOD_FRUIT = [
    # Buah-buahan (果物)
    ("リンゴ", "りんご", "ringo", "Apel", "Kata Benda - Buah & Makanan", "毎朝新鮮なリンゴを食べます。", "Makan apel segar setiap pagi."),
    ("みかん", "みかん", "mikan", "Jeruk mandarin", "Kata Benda - Buah & Makanan", "こたつでみかんを食べます。", "Makan jeruk di bawah penghangat kotatsu."),
    ("バナナ", "ばなな", "banana", "Pisang", "Kata Benda - Buah & Makanan", "朝食にバナナを一本食べます。", "Makan satu buah pisang untuk sarapan."),
    ("ぶどう", "ぶどう", "budou", "Anggur", "Kata Benda - Buah & Makanan", "紫色のぶどうが甘いです。", "Anggur berwarna ungu ini manis rasanya."),
    ("いちご", "いちご", "ichigo", "Stroberi", "Kata Benda - Buah & Makanan", "ケーキにいちごをのせます。", "Menaruh buah stroberi di atas kue."),
    ("スイカ", "すいか", "suika", "Semangka", "Kata Benda - Buah & Makanan", "夏に冷たいスイカを食べます。", "Makan semangka dingin di musim panas."),
    ("桃", "もも", "momo", "Persik (Peach)", "Kata Benda - Buah & Makanan", "甘くてジューシーな桃です。", "Buah persik yang manis dan berair."),
    ("梨", "なし", "nashi", "Pir Jepang", "Kata Benda - Buah & Makanan", "秋に美味しい梨を食べます。", "Makan buah pir yang lezat di musim gugur."),
    ("メロン", "めろん", "meron", "Melon", "Kata Benda - Buah & Makanan", "高級なメロンをもらいました。", "Mendapatkan hadiah buah melon bermutu tinggi."),
    ("さくらんぼ", "さくらんぼ", "sakuranbo", "Ceri", "Kata Benda - Buah & Makanan", "山形県のさくらんぼは有名です。", "Buah ceri dari Prefektur Yamagata sangat terkenal."),
    ("レモン", "れもん", "remon", "Lemon", "Kata Benda - Buah & Makanan", "紅茶にレモンを入れます。", "Memasukkan lemon ke dalam teh hitam."),
    ("マンゴー", "まんごー", "mangoo", "Mangga", "Kata Benda - Buah & Makanan", "トロピカルなマンゴーが好きです。", "Suka buah mangga tropis."),
    ("パイナップル", "ぱいなっぷる", "painappuru", "Nanas", "Kata Benda - Buah & Makanan", "甘酸っぱいパイナップルです。", "Nanas dengan rasa manis dan asam segar."),
    ("柿", "かき", "kaki", "Kesemek", "Kata Benda - Buah & Makanan", "庭の柿の実が熟しました。", "Buah kesemek di kebun sudah matang."),

    # Makanan Pokok & Hidangan (料理・食べ物)
    ("ご飯", "ごはん", "gohan", "Nasi putih / Makanan", "Kata Benda - Buah & Makanan", "温かいご飯を食べます。", "Makan nasi putih hangat."),
    ("パン", "ぱん", "pan", "Roti", "Kata Benda - Buah & Makanan", "パン屋で食パンを買います。", "Membeli roti tawar di toko roti."),
    ("肉", "にく", "niku", "Daging", "Kata Benda - Buah & Makanan", "スーパーで肉を買いました。", "Membeli daging di supermarket."),
    ("牛肉", "ぎゅうにく", "gyuuniku", "Daging sapi", "Kata Benda - Buah & Makanan", "牛肉でカレーを作ります。", "Membuat kari menggunakan daging sapi."),
    ("豚肉", "ぶたにく", "butaniku", "Daging babi", "Kata Benda - Buah & Makanan", "豚肉と野菜を炒めます。", "Menumis daging babi bersama sayuran."),
    ("鶏肉", "とりにく", "toriniku", "Daging ayam", "Kata Benda - Buah & Makanan", "鶏肉の唐揚げが大好きです。", "Sangat menyukai ayam goreng tepung karaage."),
    ("魚", "さかな", "sakana", "Ikan", "Kata Benda - Buah & Makanan", "焼き魚を食べます。", "Menyantap hidangan ikan bakar."),
    ("卵", "たまご", "tamago", "Telur", "Kata Benda - Buah & Makanan", "朝ご飯に卵を食べます。", "Makan telur untuk sarapan pagi."),
    ("野菜", "やさい", "yasai", "Sayuran", "Kata Benda - Buah & Makanan", "新鮮な野菜をたくさん食べます。", "Makan banyak sayuran segar."),
    ("トマト", "とまと", "tomato", "Tomat", "Kata Benda - Buah & Makanan", "赤いトマトをサラダに入れます。", "Memasukkan tomat merah ke dalam salad."),
    ("キャベツ", "きゃべつ", "kyabetsu", "Kubis / Kol", "Kata Benda - Buah & Makanan", "キャベツを千切りにします。", "Mengiris kubis tipis-tipis."),
    ("玉ねぎ", "たまねぎ", "tamanegi", "Bawang bombay", "Kata Benda - Buah & Makanan", "玉ねぎを切ると涙が出ます。", "Mata berair saat memotong bawang bombay."),
    ("じゃがいも", "じゃがいも", "jagaimo", "Kentang", "Kata Benda - Buah & Makanan", "じゃがいもを茹でます。", "Merebus kentang."),
    ("人参", "にんじん", "ninjin", "Wortel", "Kata Benda - Buah & Makanan", "人参を角切りにします。", "Memotong wortel berbentuk dadu."),
    ("カレー", "かれー", "karee", "Kari Jepang", "Kata Benda - Buah & Makanan", "日曜日にカレーを作ります。", "Membuat masakan kari pada hari Minggu."),
    ("ラーメン", "らーめん", "raamen", "Ramen", "Kata Benda - Buah & Makanan", "熱いラーメンを食べます。", "Menyantap ramen panas yang lezat."),
    ("うどん", "うどん", "udon", "Udon (mie tebal)", "Kata Benda - Buah & Makanan", "讃岐うどんを食べました。", "Makan udon khas Sanuki."),
    ("そば", "そば", "soba", "Soba (mie gandum hitam)", "Kata Benda - Buah & Makanan", "年越しそばを食べます。", "Makan soba menjelang tahun baru."),
    ("寿司", "すし", "sushi", "Sushi", "Kata Benda - Buah & Makanan", "回転寿司に行きます。", "Pergi ke restoran sushi berjalan."),
    ("刺身", "さしみ", "sashimi", "Sashimi (irisan ikan segar mentah)", "Kata Benda - Buah & Makanan", "マグロの刺身を食べます。", "Menyantap sashimi ikan tuna."),
    ("天ぷら", "てんぷら", "tenpura", "Tempura (gorengan berbalut tepung renyah)", "Kata Benda - Buah & Makanan", "エビの天ぷらが揚がりました。", "Tempura udang telah matang digoreng."),
    ("牛丼", "ぎゅうどん", "gyuudon", "Gyudon (mangkuk nasi daging sapi)", "Kata Benda - Buah & Makanan", "お昼に牛丼を食べます。", "Makan gyudon saat jam makan siang."),
    ("弁当", "べんとう", "bentou", "Bekal makan (kotak bento)", "Kata Benda - Buah & Makanan", "手作りのお弁当を持って行きます。", "Membawa bekal bento buatan sendiri."),
    ("お菓子", "おかし", "okashi", "Kue / Cemilan / Makanan ringan", "Kata Benda - Buah & Makanan", "お茶とお菓子を楽しみます。", "Menikmati teh dan cemilan kue."),
    ("ケーキ", "けーき", "keeki", "Kue tart / Cake", "Kata Benda - Buah & Makanan", "誕生日ケーキを切り分けます。", "Memotong kue ulang tahun."),
    ("アイスクリーム", "あいすくりーむ", "aisukuriimu", "Es krim", "Kata Benda - Buah & Makanan", "暑い日にアイスクリームを食べます。", "Makan es krim di hari yang panas."),
    ("塩", "しお", "shio", "Garam", "Kata Benda - Buah & Makanan", "塩を少し振ります。", "Menaburkan sedikit garam."),
    ("砂糖", "さとう", "satou", "Gula", "Kata Benda - Buah & Makanan", "コーヒーに砂糖を入れます。", "Memasukkan gula ke dalam kopi."),
    ("醤油", "しょうゆ", "shouyu", "Kecap asin Jepang", "Kata Benda - Buah & Makanan", "刺身に醤油をつけます。", "Mencelupkan sashimi ke dalam kecap asin."),

    # Minuman (飲み物)
    ("水", "みず", "mizu", "Air putih dingin", "Kata Benda - Buah & Makanan", "冷たい水を一杯飲みます。", "Minum segelas air dingin."),
    ("お湯", "おゆ", "oyu", "Air panas", "Kata Benda - Buah & Makanan", "ポットからお湯を注ぎます。", "Menuangkan air panas dari termos."),
    ("お茶", "おちゃ", "ocha", "Teh hijau Jepang", "Kata Benda - Buah & Makanan", "食後にお茶をどうぞ。", "Silakan minum teh hijau sehabis makan."),
    ("紅茶", "こうちゃ", "koucha", "Teh hitam", "Kata Benda - Buah & Makanan", "ミルクを入れて紅茶を飲みます。", "Minum teh hitam dengan tambahan susu."),
    ("牛乳", "ぎゅうにゅう", "gyuunyuu", "Susu sapi", "Kata Benda - Buah & Makanan", "毎朝コップ一杯の牛乳を飲みます。", "Minum segelas susu sapi tiap pagi."),
    ("ミルク", "みるく", "miruku", "Susu", "Kata Benda - Buah & Makanan", "コーヒーにミルクを入れます。", "Menambahkan susu ke dalam kopi."),
    ("ジュース", "じゅーす", "juusu", "Jus buah", "Kata Benda - Buah & Makanan", "オレンジジュースを注文します。", "Memesan minuman jus jeruk."),
    ("コーヒー", "こーひー", "koohii", "Kopi", "Kata Benda - Buah & Makanan", "ブラックコーヒーを飲みます。", "Meminum kopi hitam tanpa gula."),
    ("ビール", "びーる", "biiru", "Bir", "Kata Benda - Buah & Makanan", "居酒屋で生ビールを飲みます。", "Minum bir di kedai izakaya."),
    ("お酒", "おさけ", "osake", "Minuman beralkohol / Sake Jepang", "Kata Benda - Buah & Makanan", "日本酒を味わいます。", "Menikmati cita rasa sake Jepang."),
    ("ワイン", "わいん", "wain", "Anggur (Wine)", "Kata Benda - Buah & Makanan", "赤ワインをグラスに注ぎます。", "Menuangkan anggur merah ke dalam gelas.")
]

N5_NOUNS_TRANSPORT = [
    ("電車", "でんしゃ", "densha", "Kereta listrik", "Kata Benda - Kendaraan & Transportasi", "毎朝電車で通勤します。", "Naik kereta listrik untuk bekerja tiap pagi."),
    ("地下鉄", "ちかてつ", "chikatetsu", "Kereta bawah tanah (Subway)", "Kata Benda - Kendaraan & Transportasi", "地下鉄に乗って銀座へ行きます。", "Naik subway menuju Ginza."),
    ("新幹線", "しんかんせん", "shinkansen", "Kereta cepat Shinkansen", "Kata Benda - Kendaraan & Transportasi", "新幹線で京都まで行きます。", "Pergi sampai ke Kyoto naik Shinkansen."),
    ("バス", "ばす", "basu", "Bus umum", "Kata Benda - Kendaraan & Transportasi", "駅前からバスに乗ります。", "Naik bus dari depan stasiun."),
    ("タクシー", "たくしー", "takushii", "Taksi", "Kata Benda - Kendaraan & Transportasi", "雨が降ったのでタクシーを呼びました。", "Memanggil taksi karena turun hujan."),
    ("飛行機", "ひこうき", "hikouki", "Pesawat terbang", "Kata Benda - Kendaraan & Transportasi", "飛行機で七時間飛びます。", "Terbang tujuh jam dengan pesawat."),
    ("船", "ふね", "fune", "Kapal laut / Perahu", "Kata Benda - Kendaraan & Transportasi", "大きな船で港を出航します。", "Berlayar meninggalkan pelabuhan dengan kapal besar."),
    ("自動車", "じどうしゃ", "jidousha", "Mobil bermotor", "Kata Benda - Kendaraan & Transportasi", "日本の自動車は高品質です。", "Mobil Jepang bermutu tinggi."),
    ("車", "くるま", "kuruma", "Mobil / Kendaraan roda empat", "Kata Benda - Kendaraan & Transportasi", "新しい車を運転します。", "Mengendarai mobil baru."),
    ("自転車", "じてんしゃ", "jitensha", "Sepeda pancal", "Kata Benda - Kendaraan & Transportasi", "自転車で駅まで通います。", "Pergi ke stasiun naik sepeda pancal."),
    ("バイク", "ばいく", "baiku", "Sepeda motor", "Kata Benda - Kendaraan & Transportasi", "ヘルメットを被ってバイクに乗ります。", "Mengenakan helm lalu naik sepeda motor."),
    ("駅", "えき", "eki", "Stasiun kereta", "Kata Benda - Kendaraan & Transportasi", "駅の改札口で待ち合わせます。", "Janji temu di gerbang karcis stasiun."),
    ("バス停", "ばすてい", "basutei", "Halte pemberhentian bus", "Kata Benda - Kendaraan & Transportasi", "バス停で十分待ちました。", "Menunggu sepuluh menit di halte bus."),
    ("空港", "くうこう", "kuukou", "Bandara udara", "Kata Benda - Kendaraan & Transportasi", "成田空港に到着しました。", "Tiba di Bandara Internasional Narita."),
    ("港", "みなと", "minato", "Pelabuhan laut", "Kata Benda - Kendaraan & Transportasi", "港に船が停泊しています。", "Kapal berlabuh di pelabuhan."),
    ("切符", "きっぷ", "kippu", "Tiket / Karcis perjalanan", "Kata Benda - Kendaraan & Transportasi", "券売機で切符を買います。", "Membeli tiket di mesin tiket otomatis."),
    ("定期券", "ていきけん", "teikiken", "Tiket komuter langganan berkala", "Kata Benda - Kendaraan & Transportasi", "通学定期券を更新します。", "Memperpanjang tiket langganan sekolah."),
    ("乗り場", "のりば", "noriba", "Peron tempat naik kendaraan", "Kata Benda - Kendaraan & Transportasi", "二番線の乗り場へ向かいます。", "Menuju peron jalur nomor dua."),
    ("改札口", "かいさつぐち", "kaisatsuguchi", "Gerbang pemeriksaan karcis", "Kata Benda - Kendaraan & Transportasi", "ICカードを改札口でタッチします。", "Menempelkan kartu IC di pintu karcis."),
    ("交差点", "こうさてん", "kousaten", "Persimpangan jalan / Perempatan", "Kata Benda - Kendaraan & Transportasi", "交差点を右に曲がります。", "Belok kanan di persimpangan jalan."),
    ("信号", "しんごう", "shingou", "Lampu lalu lintas", "Kata Benda - Kendaraan & Transportasi", "青信号になったら渡ります。", "Menyeberang setelah lampu hijau menyala."),
    ("道", "みち", "michi", "Jalan raya / Jalur arah", "Kata Benda - Kendaraan & Transportasi", "この道をまっすぐ歩きます。", "Berjalan lurus menyusuri jalan ini."),
    ("橋", "はし", "hashi", "Jembatan penyeberangan", "Kata Benda - Kendaraan & Transportasi", "川にかかる橋を渡ります。", "Menyeberangi jembatan di atas sungai."),
    ("角", "かど", "kado", "Sudut / Tikungan jalan", "Kata Benda - Kendaraan & Transportasi", "次の角を左に曲がってください。", "Silakan belok kiri di tikungan berikutnya.")
]

N5_NOUNS_PLACES = [
    ("学校", "がっこう", "gakkou", "Sekolah", "Kata Benda - Tempat & Fasilitas", "毎日歩いて学校へ行きます。", "Pergi ke sekolah dengan jalan kaki tiap hari."),
    ("大学", "だいがく", "daigaku", "Universitas / Perguruan tinggi", "Kata Benda - Tempat & Fasilitas", "東京の大学に入学します。", "Masuk ke universitas di Tokyo."),
    ("病院", "びょういん", "byouin", "Rumah sakit", "Kata Benda - Tempat & Fasilitas", "体調が悪いので病院へ行きます。", "Pergi ke rumah sakit karena kondisi badan kurang fit."),
    ("銀行", "ぎんこう", "ginkou", "Bank", "Kata Benda - Tempat & Fasilitas", "銀行でお金を下ろします。", "Mengambil uang di bank."),
    ("郵便局", "ゆうびんきょく", "yuubinkyoku", "Kantor pos", "Kata Benda - Tempat & Fasilitas", "郵便局で手紙を出します。", "Mengirim surat di kantor pos."),
    ("図書館", "としょかん", "toshokan", "Perpustakaan", "Kata Benda - Tempat & Fasilitas", "図書館で本を借ります。", "Meminjam buku di perpustakaan."),
    ("美術館", "びじゅつかん", "bijutsukan", "Museum seni rupa", "Kata Benda - Tempat & Fasilitas", "美術館で絵画を鑑賞します。", "Menikmati lukisan di museum seni."),
    ("映画館", "えいがかん", "eigakan", "Bioskop film", "Kata Benda - Tempat & Fasilitas", "映画館で最新の映画を見ます。", "Menonton film terbaru di bioskop."),
    ("交番", "こうばん", "kouban", "Pos polisi lingkungan (Koban)", "Kata Benda - Tempat & Fasilitas", "交番で道を尋ねます。", "Bertanya arah jalan di pos polisi."),
    ("公園", "こうえん", "kouen", "Taman rekreasi terbuka", "Kata Benda - Tempat & Fasilitas", "公園で子供たちが遊んでいます。", "Anak-anak sedang bermain di taman."),
    ("店", "みせ", "mise", "Toko / Kedai", "Kata Benda - Tempat & Fasilitas", "あのお店で美味しいパンを売っています。", "Toko itu menjual roti yang lezat."),
    ("レストラン", "れすとらん", "resutoran", "Restoran", "Kata Benda - Tempat & Fasilitas", "高級レストランで食事をします。", "Makan di restoran mewah."),
    ("デパート", "でぱーと", "depaato", "Department Store / Pusat perbelanjaan", "Kata Benda - Tempat & Fasilitas", "デパートで服を買います。", "Membeli pakaian di department store."),
    ("スーパー", "すーぱー", "suupaa", "Supermarket pasar swalayan", "Kata Benda - Tempat & Fasilitas", "近所のスーパーで買い物をします。", "Belanja di supermarket dekat rumah."),
    ("コンビニ", "こんびに", "konbini", "Minimarket 24 jam (Convenience Store)", "Kata Benda - Tempat & Fasilitas", "コンビニでおにぎりを買います。", "Membeli onigiri di minimarket."),
    ("ホテル", "ほてる", "hoteru", "Hotel penginapan", "Kata Benda - Tempat & Fasilitas", "駅前のホテルに泊まります。", "Menginap di hotel depan stasiun."),
    ("部屋", "へや", "heya", "Kamar / Ruangan", "Kata Benda - Tempat & Fasilitas", "自分の部屋を掃除します。", "Membersihkan kamar sendiri."),
    ("教室", "きょうしつ", "kyoushitsu", "Ruang kelas", "Kata Benda - Tempat & Fasilitas", "教室で日本語を勉強します。", "Belajar bahasa Jepang di ruang kelas."),
    ("食堂", "しょくどう", "shokudou", "Kantin / Ruang makan bersama", "Kata Benda - Tempat & Fasilitas", "社員食堂でお昼を食べます。", "Makan siang di kantin karyawan."),
    ("事務所", "じむしょ", "jimusho", "Kantor administrasi", "Kata Benda - Tempat & Fasilitas", "事務所で書類を整理します。", "Merapikan berkas di kantor."),
    ("会議室", "かいぎしつ", "kaigishitsu", "Ruang rapat meeting", "Kata Benda - Tempat & Fasilitas", "会議室でプロジェクトを話し合います。", "Mendiskusikan proyek di ruang rapat."),
    ("受付", "うけつけ", "uketsuke", "Meja resepsionis tamu", "Kata Benda - Tempat & Fasilitas", "受付で名前を記入してください。", "Silakan tulis nama Anda di meja resepsionis."),
    ("トイレ", "といれ", "toire", "Toilet / Kamar kecil", "Kata Benda - Tempat & Fasilitas", "トイレをお借りしてもいいですか。", "Bolehkah saya menumpang toilet?"),
    ("お手洗い", "おてあらい", "otearai", "Kamar kecil (sopan)", "Kata Benda - Tempat & Fasilitas", "お手洗いはあちらにございます。", "Kamar kecil ada di sebelah sana."),
    ("家", "いえ", "ie", "Rumah hunian", "Kata Benda - Tempat & Fasilitas", "新しい家を建てました。", "Membangun rumah baru."),
    ("うち", "うち", "uchi", "Rumah sendiri / Kediaman", "Kata Benda - Tempat & Fasilitas", "今日のうちに帰ります。", "Akan pulang ke rumah hari ini."),
    ("庭", "にわ", "niwa", "Halaman pekarangan taman rumah", "Kata Benda - Tempat & Fasilitas", "庭で綺麗な花を育てます。", "Merawat bunga indah di halaman rumah."),
    ("町", "まち", "machi", "Kota / Daerah pemukiman", "Kata Benda - Tempat & Fasilitas", "静かな町に住んでいます。", "Tinggal di kota yang tenang."),
    ("国", "くに", "kuni", "Negara", "Kata Benda - Tempat & Fasilitas", "外国へ旅行するのが好きです。", "Suka berwisata ke negara asing.")
]

N5_NOUNS_FAMILY_PEOPLE = [
    ("人", "ひと", "hito", "Orang / Manusia", "Kata Benda - Keluarga & Orang", "親切な人に助けられました。", "Ditolong oleh orang yang sangat ramah."),
    ("男の人", "おとこのひと", "otoko no hito", "Pria dewasa", "Kata Benda - Keluarga & Orang", "あの男の人は誰ですか。", "Siapakah pria itu?"),
    ("女の人", "おんなのひと", "onna no hito", "Wanita dewasa", "Kata Benda - Keluarga & Orang", "受付の女の人は親切です。", "Wanita di meja resepsionis sangat ramah."),
    ("男の子", "おとこのこ", "otoko no ko", "Anak laki-laki", "Kata Benda - Keluarga & Orang", "男の子が公園で走っています。", "Anak laki-laki sedang berlari di taman."),
    ("女の子", "おんなのこ", "onna no ko", "Anak perempuan", "Kata Benda - Keluarga & Orang", "女の子が本を読んでいます。", "Anak perempuan sedang membaca buku."),
    ("家族", "かぞく", "kazoku", "Keluarga", "Kata Benda - Keluarga & Orang", "家族と旅行に行きます。", "Pergi berlibur bersama keluarga."),
    ("両親", "りょうしん", "ryoushin", "Kedua orang tua", "Kata Benda - Keluarga & Orang", "両親に手紙を書きました。", "Menulis surat kepada kedua orang tua."),
    ("父", "ちち", "chichi", "Ayah kandung saya", "Kata Benda - Keluarga & Orang", "私の父は会社員です。", "Ayah saya adalah seorang pegawai kantor."),
    ("母", "はは", "haha", "Ibu kandung saya", "Kata Benda - Keluarga & Orang", "母の料理はとても美味しいです。", "Masakan ibu saya sangat lezat."),
    ("お父さん", "おとうさん", "otousan", "Ayah orang lain / Panggilan ayah", "Kata Benda - Keluarga & Orang", "田中さんのお父さんはお元気ですか。", "Apakah ayah saudara Tanaka sehat?"),
    ("お母さん", "おかあさん", "okaasan", "Ibu orang lain / Panggilan ibu", "Kata Benda - Keluarga & Orang", "お母さんに花をプレゼントします。", "Memberikan hadiah bunga kepada ibu."),
    ("兄", "あに", "ani", "Kakak laki-laki saya", "Kata Benda - Keluarga & Orang", "兄は大学生です。", "Kakak laki-laki saya seorang mahasiswa."),
    ("お兄さん", "おにいさん", "oniisan", "Kakak laki-laki orang lain", "Kata Benda - Keluarga & Orang", "山田さんのお兄さんは背が高いですね。", "Kakak laki-laki saudara Yamada tinggi ya."),
    ("姉", "あね", "ane", "Kakak perempuan saya", "Kata Benda - Keluarga & Orang", "姉は銀行で働いています。", "Kakak perempuan saya bekerja di bank."),
    ("お姉さん", "おねえさん", "oneesan", "Kakak perempuan orang lain", "Kata Benda - Keluarga & Orang", "綺麗なお姉さんですね。", "Kakak perempuan yang cantik ya."),
    ("弟", "おとうと", "otouto", "Adik laki-laki saya", "Kata Benda - Keluarga & Orang", "弟とサッカーをします。", "Bermain sepak bola bersama adik laki-laki."),
    ("弟さん", "おとうとさん", "otoutosan", "Adik laki-laki orang lain", "Kata Benda - Keluarga & Orang", "弟さんは何歳ですか。", "Berapakah usia adik laki-laki Anda?"),
    ("妹", "いもうと", "imouto", "Adik perempuan saya", "Kata Benda - Keluarga & Orang", "妹はピアノを習っています。", "Adik perempuan saya sedang les piano."),
    ("妹さん", "いもうとさん", "imoutosan", "Adik perempuan orang lain", "Kata Benda - Keluarga & Orang", "妹さんは可愛いですね。", "Adik perempuan Anda manis ya."),
    ("夫", "おっと", "otto", "Suami saya", "Kata Benda - Keluarga & Orang", "私の夫は医者です。", "Suami saya seorang dokter."),
    ("妻", "つま", "tsuma", "Istri saya", "Kata Benda - Keluarga & Orang", "妻と買い物へ行きます。", "Pergi berbelanja bersama istri saya."),
    ("子供", "こども", "kodomo", "Anak-anak", "Kata Benda - Keluarga & Orang", "公園で子供が遊んでいます。", "Anak-anak sedang bermain di taman."),
    ("友達", "ともだち", "tomodachi", "Teman / Sahabat", "Kata Benda - Keluarga & Orang", "週末友達とお茶をします。", "Minum teh bersama kawan saat akhir pekan."),
    ("先生", "せんせい", "sensei", "Guru / Instruktur / Dokter", "Kata Benda - Keluarga & Orang", "日本語の先生に質問します。", "Bertanya kepada guru bahasa Jepang."),
    ("学生", "がくせい", "gakusei", "Murid / Pelajar / Mahasiswa", "Kata Benda - Keluarga & Orang", "真面目な学生がたくさんいます。", "Ada banyak murid yang rajin."),
    ("留学生", "りゅうがくせい", "ryuugakusei", "Mahasiswa internasional / Pelajar asing", "Kata Benda - Keluarga & Orang", "インドネシアからの留学生です。", "Mahasiswa asing yang datang dari Indonesia."),
    ("会社員", "かいしゃいん", "kaishain", "Karyawan perusahaan", "Kata Benda - Keluarga & Orang", "父は商社の会社員です。", "Ayah saya karyawan perusahaan dagang."),
    ("社員", "しゃいん", "shain", "Karyawan (perusahaan tertentu)", "Kata Benda - Keluarga & Orang", "IMCの社員です。", "Karyawan dari perusahaan IMC."),
    ("医者", "いしゃ", "isha", "Dokter medis", "Kata Benda - Keluarga & Orang", "病院で医者に診てもらいます。", "Diperiksa oleh dokter di rumah sakit."),
    ("看護師", "かんごし", "kangoshi", "Perawat rumah sakit", "Kata Benda - Keluarga & Orang", "看護師さんが優しく世話をします。", "Perawat merawat dengan penuh kelembutan."),
    ("研究者", "けんきゅうしゃ", "kenkyuusha", "Peneliti riset", "Kata Benda - Keluarga & Orang", "研究所の研究者です。", "Seorang peneliti di laboratorium riset."),
    ("エンジニア", "えんじにあ", "enjinia", "Insinyur / Teknisi", "Kata Benda - Keluarga & Orang", "ITエンジニアとして働きます。", "Bekerja sebagai seorang software engineer IT.")
]

N5_NOUNS_HOME_ITEMS = [
    ("机", "つくえ", "tsukue", "Meja belajar / Meja tulis", "Kata Benda - Rumah & Barang", "机の上にノートを置きます。", "Meletakkan buku catatan di atas meja."),
    ("椅子", "いす", "isu", "Kursi duduk", "Kata Benda - Rumah & Barang", "椅子に座ってください。", "Silakan duduk di kursi."),
    ("ドア", "どあ", "doa", "Pintu ruangan", "Kata Benda - Rumah & Barang", "ドアを開けて入ります。", "Membuka pintu lalu masuk ke dalam."),
    ("窓", "まど", "mado", "Jendela kaca", "Kata Benda - Rumah & Barang", "窓を開けて換気します。", "Membuka jendela untuk sirkulasi udara."),
    ("テレビ", "てれび", "terebi", "Televisi (TV)", "Kata Benda - Rumah & Barang", "夜ニュースをテレビで見ます。", "Menonton berita malam hari di televisi."),
    ("ラジオ", "らじお", "rajio", "Radio siaran", "Kata Benda - Rumah & Barang", "毎朝ラジオを聞きます。", "Mendengarkan radio setiap pagi."),
    ("カメラ", "かめら", "kamera", "Kamera pemotret", "Kata Benda - Rumah & Barang", "新しいカメラで写真を撮ります。", "Mengambil foto dengan kamera baru."),
    ("パソコン", "ぱそこん", "pasokon", "Komputer laptop / PC", "Kata Benda - Rumah & Barang", "パソコンでレポートを作成します。", "Membuat laporan di komputer."),
    ("スマホ", "すまほ", "sumaho", "Ponsel pintar (Smartphone)", "Kata Benda - Rumah & Barang", "スマホで地図を調べます。", "Mencari peta lewat smartphone."),
    ("携帯電話", "けいたいでんわ", "keitaidenwa", "Ponsel genggam", "Kata Benda - Rumah & Barang", "携帯電話の番号を教えます。", "Memberitahukan nomor ponsel genggam."),
    ("電話", "でんわ", "denwa", "Telepon komunikasi", "Kata Benda - Rumah & Barang", "電話をかけます。", "Menelepon seseorang."),
    ("本", "ほん", "hon", "Buku bacaan", "Kata Benda - Rumah & Barang", "面白い本を読みました。", "Membaca buku yang sangat menarik."),
    ("辞書", "じしょ", "jisho", "Kamus bahasa", "Kata Benda - Rumah & Barang", "辞書で単語の意味を調べます。", "Mencari arti kosakata di kamus."),
    ("雑誌", "ざっし", "zasshi", "Majalah berkala", "Kata Benda - Rumah & Barang", "ファッション雑誌を読みます。", "Membaca majalah busana."),
    ("新聞", "しんぶん", "shinbun", "Surat kabar / Koran harian", "Kata Benda - Rumah & Barang", "朝刊の新聞を配達します。", "Mengantar koran edisi pagi."),
    ("テーブル", "てーぶる", "teeburu", "Meja makan", "Kata Benda - Rumah & Barang", "テーブルに料理を並べます。", "Menata makanan di atas meja makan."),
    ("ベッド", "べっど", "beddo", "Tempat tidur / Ranjang", "Kata Benda - Rumah & Barang", "ベッドでゆっくり休みます。", "Beristirahat dengan nyaman di ranjang."),
    ("冷蔵庫", "れいぞうこ", "reizouko", "Kulkas lemari pendingin", "Kata Benda - Rumah & Barang", "牛乳を冷蔵庫に入れます。", "Memasukkan susu ke dalam kulkas."),
    ("洗濯機", "せんたくき", "sentakuki", "Mesin cuci pakaian", "Kata Benda - Rumah & Barang", "洗濯機で服を洗います。", "Mencuci baju dengan mesin cuci."),
    ("エアコン", "えあこん", "eakon", "Pendingin / Penghangat udara (AC)", "Kata Benda - Rumah & Barang", "エアコンをつけて部屋を冷やします。", "Menyalakan AC untuk mendinginkan ruangan."),
    ("時計", "とけい", "tokei", "Jam dinding / Jam tangan", "Kata Benda - Rumah & Barang", "壁の時計を見ます。", "Melihat jam dinding."),
    ("鍵", "かぎ", "kagi", "Kunci pintu", "Kata Benda - Rumah & Barang", "部屋の鍵をかけます。", "Mengunci pintu kamar."),
    ("傘", "かさ", "kasa", "Payung pelindung hujan", "Kata Benda - Rumah & Barang", "雨が降るので傘を持っていきます。", "Membawa payung karena turun hujan."),
    ("財布", "さいふ", "saifu", "Dompet uang", "Kata Benda - Rumah & Barang", "財布をカバンに入れます。", "Memasukkan dompet ke dalam tas."),
    ("鞄", "かばん", "kaban", "Tas jinjing / Ransel", "Kata Benda - Rumah & Barang", "荷物を鞄に入れます。", "Memasukkan barang ke dalam tas."),
    ("手紙", "てがみ", "tegami", "Surat kiriman", "Kata Benda - Rumah & Barang", "故郷の両親に手紙を送ります。", "Mengirim surat ke orang tua di kampung."),
    ("写真", "しゃしん", "shashin", "Foto potret", "Kata Benda - Rumah & Barang", "旅行の写真をアルバムに貼ります。", "Menempelkan foto liburan di album.")
]

N5_NOUNS_SCHOOL_OFFICE = [
    ("紙", "かみ", "kami", "Kertas tulis", "Kata Benda - Sekolah & Kantor", "白い紙にメモを書きます。", "Menulis catatan pada kertas putih."),
    ("ペン", "ぺん", "pen", "Pena tinta", "Kata Benda - Sekolah & Kantor", "黒いペンでサインします。", "Menandatangani dengan pena hitam."),
    ("ボールペン", "ぼーるぺん", "boorupen", "Pulpen bolpoin", "Kata Benda - Sekolah & Kantor", "ボールペンを一本貸してください。", "Tolong pinjamkan satu buah pulpen."),
    ("シャープペンシル", "しゃーぷぺんしる", "shaapu penshiru", "Pensil mekanik", "Kata Benda - Sekolah & Kantor", "シャープペンシルでノートを取ります。", "Mencatat dengan pensil mekanik."),
    ("鉛筆", "えんぴつ", "enpitsu", "Pensil kayu", "Kata Benda - Sekolah & Kantor", "鉛筆を削ります。", "Meraut pensil kayu."),
    ("消しゴム", "けしごむ", "keshigomu", "Karet penghapus", "Kata Benda - Sekolah & Kantor", "消しゴムで間違いを消します。", "Menghapus kekeliruan dengan penghapus."),
    ("ハサミ", "はさみ", "hasami", "Gunting pemotong", "Kata Benda - Sekolah & Kantor", "ハサミで紙を切ります。", "Memotong kertas dengan gunting."),
    ("テープ", "てーぷ", "teepu", "Pita perekat (Selotip)", "Kata Benda - Sekolah & Kantor", "セロハンテープで貼ります。", "Menempelkan menggunakan selotip."),
    ("ホッチキス", "ほっちきす", "hocchikisu", "Stapler penjepit kertas", "Kata Benda - Sekolah & Kantor", "書類をホッチキスで留めます。", "Menjepit dokumen dengan stapler."),
    ("ノート", "のーと", "nooto", "Buku catatan / Notebook", "Kata Benda - Sekolah & Kantor", "ノートに大事な文法をメモします。", "Mencatat tata bahasa penting di buku catatan."),
    ("教科書", "きょうかしょ", "kyoukasho", "Buku pelajaran", "Kata Benda - Sekolah & Kantor", "教科書の二十ページを開きます。", "Membuka halaman 20 buku pelajaran."),
    ("宿題", "しゅくだい", "shukudai", "Pekerjaan rumah (PR)", "Kata Benda - Sekolah & Kantor", "今日の宿題を終わらせます。", "Menyelesaikan PR hari ini."),
    ("テスト", "てすと", "tesuto", "Ujian tes", "Kata Benda - Sekolah & Kantor", "明日のテストのために復習します。", "Mengulang materi untuk ujian besok."),
    ("質問", "しつもん", "shitsumon", "Pertanyaan", "Kata Benda - Sekolah & Kantor", "質問がある人は手を挙げてください。", "Yang punya pertanyaan silakan angkat tangan."),
    ("答え", "こたえ", "kotae", "Jawaban", "Kata Benda - Sekolah & Kantor", "正しい答えを選びます。", "Memilih jawaban yang benar.")
]

N5_NOUNS_BODY_CLOTHING = [
    ("頭", "あたま", "atama", "Kepala", "Kata Benda - Tubuh & Pakaian", "頭が痛いので薬を飲みます。", "Minum obat karena kepala terasa sakit."),
    ("目", "め", "me", "Mata penglihatan", "Kata Benda - Tubuh & Pakaian", "目を閉じて休んでください。", "Tolong pejamkan mata dan beristirahatlah."),
    ("耳", "みみ", "mimi", "Telinga pendengaran", "Kata Benda - Tubuh & Pakaian", "良い音楽に耳を傾けます。", "Memasang telinga mendengarkan musik bagus."),
    ("鼻", "はな", "hana", "Hidung", "Kata Benda - Tubuh & Pakaian", "鼻水が出ます。", "Hidung saya mengeluarkan ingus."),
    ("口", "くち", "kuchi", "Mulut", "Kata Benda - Tubuh & Pakaian", "大きく口を開けてください。", "Tolong buka mulut Anda lebar-lebar."),
    ("歯", "は", "ha", "Gigi", "Kata Benda - Tubuh & Pakaian", "食後に歯を磨きます。", "Menggosok gigi setelah makan."),
    ("顔", "かお", "kao", "Wajah", "Kata Benda - Tubuh & Pakaian", "朝起きて顔を洗います。", "Bangun pagi lalu mencuci wajah."),
    ("手", "て", "te", "Tangan", "Kata Benda - Tubuh & Pakaian", "食事の前に手を洗います。", "Mencuci tangan sebelum makan."),
    ("足", "あし", "ashi", "Kaki", "Kata Benda - Tubuh & Pakaian", "たくさん歩いて足が疲れました。", "Kaki lelah karena banyak berjalan."),
    ("お腹", "おなか", "onaka", "Perut", "Kata Benda - Tubuh & Pakaian", "お腹が空きました。", "Perut saya sudah lapar."),
    ("体", "からだ", "karada", "Tubuh / Badan", "Kata Benda - Tubuh & Pakaian", "体を大切にしてください。", "Tolong jaga kesehatan tubuh Anda."),
    ("服", "ふく", "fuku", "Pakaian / Baju", "Kata Benda - Tubuh & Pakaian", "新しい服を着ます。", "Mengenakan pakaian baru."),
    ("シャツ", "しゃつ", "shatsu", "Kemeja kancing", "Kata Benda - Tubuh & Pakaian", "白いシャツにアイロンをかけます。", "Menyetrika kemeja putih."),
    ("ズボン", "ずぼん", "zubon", "Celana panjang", "Kata Benda - Tubuh & Pakaian", "黒いズボンを履きます。", "Mengenakan celana panjang hitam."),
    ("スカート", "すかーと", "sukaato", "Rok", "Kata Benda - Tubuh & Pakaian", "可愛いスカートを買いました。", "Membeli rok yang cantik."),
    ("靴", "くつ", "kutsu", "Sepatu alas kaki", "Kata Benda - Tubuh & Pakaian", "玄関で靴を脱ぎます。", "Membuka sepatu di pintu masuk genkan."),
    ("靴下", "くつした", "kutsushita", "Kaus kaki", "Kata Benda - Tubuh & Pakaian", "暖かい靴下を履きます。", "Mengenakan kaus kaki hangat."),
    ("眼鏡", "めがね", "megane", "Kacamata lensa", "Kata Benda - Tubuh & Pakaian", "眼鏡をかけて本を読みます。", "Mengenakan kacamata membaca buku."),
    ("帽子", "ぼうし", "boushi", "Topi penutup kepala", "Kata Benda - Tubuh & Pakaian", "日差しが強いので帽子を被ります。", "Mengenakan topi karena terik matahari."),
    ("コート", "こーと", "kooto", "Mantel tebal / Jas dingin", "Kata Benda - Tubuh & Pakaian", "冬に厚いコートを着ます。", "Mengenakan mantel tebal di musim dingin."),
    ("セーター", "せーたー", "seetaa", "Baju rajut sweater wol", "Kata Benda - Tubuh & Pakaian", "手編みのセーターを着ます。", "Mengenakan sweater rajutan tangan."),
    ("ネクタイ", "ねくたい", "nekutai", "Dasi leher", "Kata Benda - Tubuh & Pakaian", "スーツにネクタイを締めます。", "Mengenakan dasi pada setelan jas."),
    ("薬", "くすり", "kusuri", "Obat medis", "Kata Benda - Tubuh & Pakaian", "食後に薬を飲みます。", "Meminum obat setelah makan."),
    ("熱", "ねつ", "netsu", "Demam suhu tubuh tinggi", "Kata Benda - Tubuh & Pakaian", "熱が三十八度あります。", "Demam tubuh mencapai 38 derajat."),
    ("風邪", "かぜ", "kaze", "Masuk angin / Flu pilek", "Kata Benda - Tubuh & Pakaian", "風邪をひいて学校を休みました。", "Tidakk masuk sekolah karena flu pilek."),
    ("病気", "びょうき", "byouki", "Penyakit / Kondisi sakit", "Kata Benda - Tubuh & Pakaian", "病気が治って安心しました。", "Lega karena penyakitnya telah sembuh.")
]

N5_NOUNS_NATURE_WEATHER = [
    ("天気", "てんき", "tenki", "Cuaca hari ini", "Kata Benda - Alam & Cuaca", "今日は素晴らしい天気です。", "Hari ini cuacanya sangat luar biasa cerah."),
    ("雨", "あめ", "ame", "Hujan curah air", "Kata Benda - Alam & Cuaca", "外は冷たい雨が降っています。", "Di luar turun hujan yang dingin."),
    ("雪", "ゆき", "yuki", "Salju putih", "Kata Benda - Alam & Cuaca", "冬の北海道に白い雪が降ります。", "Salju putih turun di Hokkaido saat musim dingin."),
    ("曇り", "くもり", "kumori", "Mendung berawan", "Kata Benda - Alam & Cuaca", "午後から曇りになりました。", "Menjadi mendung sejak siang hari."),
    ("晴れ", "はれ", "hare", "Cerah benderang", "Kata Benda - Alam & Cuaca", "明日は晴れでしょう。", "Besok kemungkinan akan cerah."),
    ("風", "かぜ", "kaze", "Angin berhembus", "Kata Benda - Alam & Cuaca", "爽やかな風が吹いています。", "Angin sejuk berhembus menyegarkan."),
    ("太陽", "たいよう", "taiyou", "Matahari surya", "Kata Benda - Alam & Cuaca", "東の空から太陽が昇ります。", "Matahari terbit dari langit timur."),
    ("月", "つき", "tsuki", "Bulan malam", "Kata Benda - Alam & Cuaca", "夜空に満月が綺麗に輝きます。", "Bulan purnama bersinar indah di langit malam."),
    ("星", "ほし", "hoshi", "Bintang gemintang", "Kata Benda - Alam & Cuaca", "夜空に無数の星が光ります。", "Bintang tak terhitung berkilau di langit malam."),
    ("海", "うみ", "umi", "Laut samudra", "Kata Benda - Alam & Cuaca", "夏休みに青い海で泳ぎます。", "Berenang di laut biru saat libur musim panas."),
    ("山", "やま", "yama", "Gunung", "Kata Benda - Alam & Cuaca", "秋に紅葉の山へ登ります。", "Mendaki gunung berdaun merah saat musim gugur."),
    ("川", "かわ", "kawa", "Sungai aliran air", "Kata Benda - Alam & Cuaca", "綺麗な川で魚が泳いでいます。", "Ikan berenang di sungai yang jernih."),
    ("木", "き", "ki", "Pohon kayu", "Kata Benda - Alam & Cuaca", "公園に大きな桜の木があります。", "Ada pohon sakura besar di taman."),
    ("花", "はな", "hana", "Bunga tanaman", "Kata Benda - Alam & Cuaca", "春に色とりどりの花が咲きます。", "Bunga beraneka warna bermekaran di musim semi."),
    ("桜", "さくら", "sakura", "Bunga Sakura khas Jepang", "Kata Benda - Alam & Cuaca", "四月に満開の桜を見に行きます。", "Pergi melihat bunga sakura mekar penuh di bulan April."),
    ("犬", "いぬ", "inu", "Anjing peliharaan", "Kata Benda - Alam & Cuaca", "毎朝可愛い犬と散歩します。", "Jalan-jalan bersama anjing lucu setiap pagi."),
    ("猫", "ねこ", "neko", "Kucing", "Kata Benda - Alam & Cuaca", "日向で猫が寝ています。", "Kucing sedang tidur di tempat yang terkena sinar matahari."),
    ("鳥", "とり", "tori", "Burung unggas", "Kata Benda - Alam & Cuaca", "木の枝で小鳥が鳴いています。", "Burung kecil berkicau di dahan pohon.")
]

print("Loaded all N5 Noun subcategories.")
