# -*- coding: utf-8 -*-
# Data Penunjuk Waktu, Angka & Uang (時間・数字・お金) - Standar N5 / Minna no Nihongo

N5_TIME_NUMBERS_MONEY = [
    # Angka Dasar 0 - 10, 100, 1000, 10000, dst.
    ("零", "れい / ゼロ", "rei / zero", "Angka Nol (0)", "Penunjuk Waktu & Angka", "気温が零度になります。", "Suhu udara menjadi nol derajat."),
    ("一", "いち", "ichi", "Angka Satu (1)", "Penunjuk Waktu & Angka", "一から始めます。", "Memulai dari angka satu."),
    ("二", "に", "ni", "Angka Dua (2)", "Penunjuk Waktu & Angka", "リンゴを二つ買います。", "Membeli dua buah apel."),
    ("三", "さん", "san", "Angka Tiga (3)", "Penunjuk Waktu & Angka", "三時に会いましょう。", "Mari bertemu pada jam tiga."),
    ("四", "よん / し", "yon / shi", "Angka Empat (4)", "Penunjuk Waktu & Angka", "四月に桜が咲きます。", "Di bulan April bunga sakura mekar."),
    ("五", "ご", "go", "Angka Lima (5)", "Penunjuk Waktu & Angka", "五人の学生がいます。", "Ada lima orang siswa."),
    ("六", "ろく", "roku", "Angka Enam (6)", "Penunjuk Waktu & Angka", "六時に起きます。", "Bangun pada jam enam."),
    ("七", "なな / しち", "nana / shichi", "Angka Tujuh (7)", "Penunjuk Waktu & Angka", "七時半に出発します。", "Berangkat pada jam setengah delapan."),
    ("八", "はち", "hachi", "Angka Delapan (8)", "Penunjuk Waktu & Angka", "八月は暑いです。", "Bulan Agustus sangat panas."),
    ("九", "きゅう / く", "kyuu / ku", "Angka Sembilan (9)", "Penunjuk Waktu & Angka", "九時五十分に始まります。", "Mulai pada jam sembilan lewat lima puluh menit."),
    ("十", "じゅう", "juu", "Angka Sepuluh (10)", "Penunjuk Waktu & Angka", "十個のパンを買いました。", "Membeli sepuluh buah roti."),
    ("百", "ひゃく", "hyaku", "Angka Ratusan (100)", "Penunjuk Waktu & Angka", "百円のお菓子です。", "Kue seharga seratus yen."),
    ("二百", "にひゃく", "nihyaku", "Dua Ratus (200)", "Penunjuk Waktu & Angka", "二百ページの本です。", "Buku setebal dua ratus halaman."),
    ("三百", "さんびゃく", "sanbyaku", "Tiga Ratus (300)", "Penunjuk Waktu & Angka", "三百円払います。", "Membayar tiga ratus yen."),
    ("四百", "よんひゃく", "yonhyaku", "Empat Ratus (400)", "Penunjuk Waktu & Angka", "四百メートル走ります。", "Berlari sejauh empat ratus meter."),
    ("五百", "ごひゃく", "gohyaku", "Lima Ratus (500)", "Penunjuk Waktu & Angka", "五百円玉を使います。", "Menggunakan koin lima ratus yen."),
    ("六百", "ろっぴゃく", "roppyaku", "Enam Ratus (600)", "Penunjuk Waktu & Angka", "六百人集まりました。", "Terkumpul sebanyak enam ratus orang."),
    ("七百", "ななひゃく", "nanahyaku", "Tujuh Ratus (700)", "Penunjuk Waktu & Angka", "七百グラムの肉です。", "Daging seberat tujuh ratus gram."),
    ("八百", "はっぴゃく", "happyaku", "Delapan Ratus (800)", "Penunjuk Waktu & Angka", "八百円でお釣りが来ます。", "Kembalian dari delapan ratus yen."),
    ("九百", "きゅうひゃく", "kyuuhyaku", "Sembilan Ratus (900)", "Penunjuk Waktu & Angka", "九百メートルの山です。", "Gunung setinggi sembilan ratus meter."),
    ("千", "せん", "sen", "Angka Seribu (1.000)", "Penunjuk Waktu & Angka", "千円札を出します。", "Mengeluarkan selembar uang seribu yen."),
    ("二千", "にせん", "nisen", "Dua Ribu (2.000)", "Penunjuk Waktu & Angka", "二千年の歴史があります。", "Memiliki sejarah dua ribu tahun."),
    ("三千", "さんぜん", "sanzen", "Tiga Ribu (3.000)", "Penunjuk Waktu & Angka", "三千円のシャツです。", "Kemeja seharga tiga ribu yen."),
    ("八千", "はっせん", "hassen", "Delapan Ribu (8.000)", "Penunjuk Waktu & Angka", "八千人の観客です。", "Delapan ribu orang penonton."),
    ("万", "まん", "man", "Puluh Ribuan (10.000)", "Penunjuk Waktu & Angka", "一万円札を両替します。", "Menukar selembar uang sepuluh ribu yen."),
    ("十万", "じゅうまん", "juuman", "Ratus Ribuan (100.000)", "Penunjuk Waktu & Angka", "十万円のパソコンです。", "Laptop seharga seratus ribu yen."),
    ("百万", "ひゃくまん", "hyakuman", "Satu Juta (1.000.000)", "Penunjuk Waktu & Angka", "百万人以上の都市です。", "Kota dengan penduduk lebih dari satu juta orang."),
    ("一億", "いちおく", "ichioku", "Seratus Juta (100.000.000)", "Penunjuk Waktu & Angka", "日本の人口は一億人以上です。", "Populasi Jepang lebih dari seratus juta orang."),

    # Bilangan Benda Umum (Hitungan Jepang: Hitotsu, Futatsu...)
    ("一つ", "ひとつ", "hitotsu", "Satu buah (satuan umum)", "Penunjuk Waktu & Angka", "リンゴを一つください。", "Tolong berikan satu buah apel."),
    ("二つ", "ふたつ", "futatsu", "Dua buah (satuan umum)", "Penunjuk Waktu & Angka", "パンを二つ買います。", "Membeli dua buah roti."),
    ("三つ", "みっつ", "mittsu", "Tiga buah (satuan umum)", "Penunjuk Waktu & Angka", "みかんを三つ食べました。", "Makan tiga buah jeruk."),
    ("四つ", "よっつ", "yottsu", "Empat buah (satuan umum)", "Penunjuk Waktu & Angka", "ケーキを四つ注文します。", "Memesan empat buah kue."),
    ("五つ", "いつつ", "itsutsu", "Lima buah (satuan umum)", "Penunjuk Waktu & Angka", "椅子を五つ並べます。", "Menata lima buah kursi."),
    ("六つ", "むっつ", "muttsu", "Enam buah (satuan umum)", "Penunjuk Waktu & Angka", "卵を六つ使います。", "Menggunakan enam butir telur."),
    ("七つ", "ななつ", "nanatsu", "Tujuh buah (satuan umum)", "Penunjuk Waktu & Angka", "星が七つ見えます。", "Tujuh buah bintang terlihat."),
    ("八つ", "やっつ", "yattsu", "Delapan buah (satuan umum)", "Penunjuk Waktu & Angka", "箱を八つ運びます。", "Mengangkat delapan buah kardus."),
    ("九つ", "ここのつ", "kokonotsu", "Sembilan buah (satuan umum)", "Penunjuk Waktu & Angka", "窓が九つあります。", "Ada sembilan buah jendela."),
    ("十", "とお", "too", "Sepuluh buah (satuan umum)", "Penunjuk Waktu & Angka", "みかんがとおあります。", "Jeruknya ada sepuluh buah."),

    # Bilangan Orang (Hitori, Futari, Sannin...)
    ("一人", "ひとり", "hitori", "Satu orang / Sendirian", "Penunjuk Waktu & Angka", "一人で映画を見に行きます。", "Pergi menonton bioskop sendirian."),
    ("二人", "ふたり", "futari", "Dua orang / Berdua", "Penunjuk Waktu & Angka", "二人で食事をします。", "Makan berdua."),
    ("三人", "さんにん", "sannin", "Tiga orang", "Penunjuk Waktu & Angka", "三人で旅行へ行きます。", "Pergi berlibur bertiga."),
    ("四人", "よにん", "yonin", "Empat orang", "Penunjuk Waktu & Angka", "家族は四人です。", "Keluarga saya berjumlah empat orang."),
    ("五人", "ごにん", "gonin", "Lima orang", "Penunjuk Waktu & Angka", "グループは五人です。", "Kelompok terdiri dari lima orang."),

    # Uang & Satuan Harga (お金)
    ("お金", "おかね", "okane", "Uang", "Penunjuk Waktu & Angka", "お金を財布に入れます。", "Memasukkan uang ke dalam dompet."),
    ("円", "えん", "en", "Mata uang Yen", "Penunjuk Waktu & Angka", "これは五百円です。", "Ini seharga lima ratus yen."),
    ("ドル", "ドル", "doru", "Mata uang Dolar", "Penunjuk Waktu & Angka", "百ドルを円に両替します。", "Menukar seratus dolar ke yen."),
    ("ルピア", "ルピア", "rupia", "Mata uang Rupiah", "Penunjuk Waktu & Angka", "インドネシアの通貨はルピアです。", "Mata uang Indonesia adalah rupiah."),
    ("現金", "げんきん", "genkin", "Uang tunai (cash)", "Penunjuk Waktu & Angka", "現金で払います。", "Membayar dengan uang tunai."),
    ("お釣り", "おつり", "otsuri", "Uang kembalian", "Penunjuk Waktu & Angka", "お釣りをお確かめください。", "Silakan periksa uang kembalian Anda."),
    ("両替", "りょうがえ", "ryougae", "Penukaran uang", "Penunjuk Waktu & Angka", "銀行で両替します。", "Melakukan penukaran uang di bank."),
    ("小銭", "こぜに", "kozeni", "Uang koin / Uang receh", "Penunjuk Waktu & Angka", "自販機で小銭を使います。", "Menggunakan uang receh di mesin penjual otomatis."),
    ("硬貨", "こうか", "kouka", "Uang logam / Koin", "Penunjuk Waktu & Angka", "百円の硬貨を入れます。", "Memasukkan uang koin seratus yen."),
    ("紙幣", "しへい", "shihei", "Uang kertas", "Penunjuk Waktu & Angka", "千円の紙幣です。", "Uang kertas pecahan seribu yen."),
    ("値段", "ねだん", "nedan", "Harga barang", "Penunjuk Waktu & Angka", "この服の値段はいくらですか。", "Berapakah harga baju ini?"),
    ("半額", "はんがく", "hangaku", "Setengah harga / Diskon 50%", "Penunjuk Waktu & Angka", "夕方パンが半額になります。", "Saat sore hari roti menjadi setengah harga."),
    ("割引", "わりびき", "waribiki", "Diskon / Potongan harga", "Penunjuk Waktu & Angka", "二割引きのセールです。", "Obral dengan diskon dua puluh persen."),
    ("無料", "むりょう", "muryou", "Gratis / Bebas biaya", "Penunjuk Waktu & Angka", "入場は無料です。", "Tiket masuk adalah gratis."),
    ("有料", "ゆうりょう", "yuuryou", "Berbayar", "Penunjuk Waktu & Angka", "この駐車場は有料です。", "Tempat parkir ini berbayar."),

    # Waktu Jam & Menit (時間・分)
    ("時", "じ", "ji", "Pukul / Jam (waktu)", "Penunjuk Waktu & Angka", "今七時です。", "Sekarang pukul tujuh."),
    ("分", "ふん / ぷん", "fun / pun", "Menit", "Penunjuk Waktu & Angka", "あと十分で着きます。", "Akan tiba dalam sepuluh menit."),
    ("半", "はん", "han", "Setengah (30 menit)", "Penunjuk Waktu & Angka", "八時半に会社へ行きます。", "Pergi ke kantor pukul delapan lewat tiga puluh menit."),
    ("時間", "じかん", "jikan", "Jam (durasi) / Waktu", "Penunjuk Waktu & Angka", "二時間勉強しました。", "Belajar selama dua jam."),
    ("午前", "ごぜん", "gozen", "A.M. (pagi / sebelum tengah hari)", "Penunjuk Waktu & Angka", "午前九時から会議です。", "Rapat mulai pukul sembilan pagi."),
    ("午後", "ごご", "gogo", "P.M. (siang-sore / sesudah tengah hari)", "Penunjuk Waktu & Angka", "午後三時にお茶を飲みます。", "Minum teh pada pukul tiga sore."),
    ("今", "いま", "ima", "Sekarang", "Penunjuk Waktu & Angka", "今何時ですか。", "Sekarang jam berapa?"),
    ("朝", "あさ", "asa", "Pagi hari", "Penunjuk Waktu & Angka", "毎朝ジョギングをします。", "Joging setiap pagi."),
    ("昼", "ひる", "hiru", "Siang hari", "Penunjuk Waktu & Angka", "昼ご飯を食べましょう。", "Mari makan siang bersama."),
    ("晩", "ばん", "ban", "Malam hari", "Penunjuk Waktu & Angka", "晩ご飯を作ります。", "Memasak makan malam."),
    ("夜", "よる", "yoru", "Malam / Larut malam", "Penunjuk Waktu & Angka", "夜十時に寝ます。", "Tidur pada jam sepuluh malam."),
    ("今朝", "けさ", "kesa", "Pagi tadi", "Penunjuk Waktu & Angka", "今朝新聞を読みました。", "Pagi tadi membaca koran."),
    ("今晩", "こんばん", "konban", "Malam ini", "Penunjuk Waktu & Angka", "今晩友達と会います。", "Malam ini bertemu dengan kawan."),
    ("今日", "きょう", "kyou", "Hari ini", "Penunjuk Waktu & Angka", "今日はいい天気です。", "Hari ini cuaca cerah."),
    ("昨日", "きのう", "kinou", "Kemarin", "Penunjuk Waktu & Angka", "昨日は雨でした。", "Kemarin turun hujan."),
    ("一昨日", "おととい", "ototoi", "Kemarin lusa", "Penunjuk Waktu & Angka", "一昨日日本に着きました。", "Tiba di Jepang pada kemarin lusa."),
    ("明日", "あした", "ashita", "Besok", "Penunjuk Waktu & Angka", "明日テストがあります。", "Besok ada ujian."),
    ("明後日", "あさって", "asatte", "Besok lusa", "Penunjuk Waktu & Angka", "明後日休みです。", "Besok lusa adalah hari libur."),
    ("毎日", "まいにち", "mainichi", "Setiap hari", "Penunjuk Waktu & Angka", "毎日日本語を話します。", "Berbicara bahasa Jepang setiap hari."),
    ("毎朝", "まいあさ", "maiasa", "Setiap pagi", "Penunjuk Waktu & Angka", "毎朝牛乳を飲みます。", "Minum susu setiap pagi."),
    ("毎晩", "まいばん", "maiban", "Setiap malam", "Penunjuk Waktu & Angka", "毎晩日記を書きます。", "Menulis buku harian setiap malam."),

    # Hari dalam Seminggu (曜日)
    ("月曜日", "げつようび", "getsuyoubi", "Hari Senin", "Penunjuk Waktu & Angka", "月曜日に仕事が始まります。", "Pekerjaan dimulai pada hari Senin."),
    ("火曜日", "かようび", "kayoubi", "Hari Selasa", "Penunjuk Waktu & Angka", "火曜日はゴミの日です。", "Hari Selasa adalah hari buang sampah."),
    ("水曜日", "すいようび", "suiyoubi", "Hari Rabu", "Penunjuk Waktu & Angka", "水曜日に買い物をします。", "Berbelanja pada hari Rabu."),
    ("木曜日", "もくようび", "mokuyoubi", "Hari Kamis", "Penunjuk Waktu & Angka", "木曜日に図書館へ行きます。", "Pergi ke perpustakaan pada hari Kamis."),
    ("金曜日", "きんようび", "kinyoubi", "Hari Jumat", "Penunjuk Waktu & Angka", "金曜日の夜は嬉しいです。", "Malam Jumat terasa menyenangkan."),
    ("土曜日", "どようび", "doyoubi", "Hari Sabtu", "Penunjuk Waktu & Angka", "土曜日に掃除をします。", "Membersihkan rumah pada hari Sabtu."),
    ("日曜日", "にちようび", "nichiyoubi", "Hari Minggu", "Penunjuk Waktu & Angka", "日曜日は休みです。", "Hari Minggu adalah hari libur."),
    ("週末", "しゅうまつ", "shuumatsu", "Akhir pekan (weekend)", "Penunjuk Waktu & Angka", "週末どこへ行きますか。", "Akhir pekan mau pergi kemana?"),
    ("今週", "こんしゅう", "konshuu", "Minggu ini", "Penunjuk Waktu & Angka", "今週はとても忙しいです。", "Minggu ini sangat sibuk."),
    ("先週", "せんしゅう", "senshuu", "Minggu lalu", "Penunjuk Waktu & Angka", "先週京都へ行きました。", "Minggu lalu pergi ke Kyoto."),
    ("来週", "らいしゅう", "raishuu", "Minggu depan", "Penunjuk Waktu & Angka", "来週レポートを出します。", "Minggu depan mengumpulkan laporan."),
    ("毎週", "まいしゅう", "maishuu", "Setiap minggu", "Penunjuk Waktu & Angka", "毎週プールで泳ぎます。", "Berenang di kolam renang setiap minggu."),

    # Bulan dalam Setahun (月) & Tanggal (日)
    ("一月", "いちがつ", "ichigatsu", "Bulan Januari", "Penunjuk Waktu & Angka", "一月一日は元日です。", "Tanggal satu Januari adalah tahun baru."),
    ("二月", "にがつ", "nigatsu", "Bulan Februari", "Penunjuk Waktu & Angka", "二月は雪が降ります。", "Bulan Februari turun salju."),
    ("三月", "さんがつ", "sangatsu", "Bulan Maret", "Penunjuk Waktu & Angka", "三月に卒業します。", "Lulus sekolah pada bulan Maret."),
    ("四月", "しがつ", "shigatsu", "Bulan April", "Penunjuk Waktu & Angka", "四月に入学します。", "Masuk sekolah pada bulan April."),
    ("五月", "ごがつ", "gogatsu", "Bulan Mei", "Penunjuk Waktu & Angka", "五月は気候が良いです。", "Bulan Mei iklimnya sangat nyaman."),
    ("六月", "ろくがつ", "rokugatsu", "Bulan Juni", "Penunjuk Waktu & Angka", "六月は雨が多いです。", "Bulan Juni banyak hujan."),
    ("七月", "しちがつ", "shichigatsu", "Bulan Juli", "Penunjuk Waktu & Angka", "七月に海へ行きます。", "Pergi ke laut pada bulan Juli."),
    ("八月", "はちがつ", "hachigatsu", "Bulan Agustus", "Penunjuk Waktu & Angka", "八月は夏休みです。", "Bulan Agustus liburan musim panas."),
    ("九月", "くがつ", "kugatsu", "Bulan September", "Penunjuk Waktu & Angka", "九月に新学期が始まります。", "Semester baru dimulai pada bulan September."),
    ("十月", "じゅうがつ", "juugatsu", "Bulan Oktober", "Penunjuk Waktu & Angka", "十月は紅葉の季節です。", "Bulan Oktober musim daun merah berguguran."),
    ("十一月", "じゅういちがつ", "juuichigatsu", "Bulan November", "Penunjuk Waktu & Angka", "十一月にコートを着ます。", "Mengenakan mantel pada bulan November."),
    ("十二月", "じゅうにがつ", "juunigatsu", "Bulan Desember", "Penunjuk Waktu & Angka", "十二月に大掃除をします。", "Pembersihan besar-besaran di bulan Desember."),

    # Tanggal Khusus 1 - 10, 14, 20, 24
    ("一日", "ついたち", "tsuitachi", "Tanggal Satu", "Penunjuk Waktu & Angka", "毎月一日に目標を立てます。", "Menyusun target pada tanggal satu setiap bulan."),
    ("二日", "ふつか", "futsuka", "Tanggal Dua / Dua Hari", "Penunjuk Waktu & Angka", "二日間に旅行します。", "Berlibur selama dua hari."),
    ("三日", "みっか", "mikka", "Tanggal Tiga / Tiga Hari", "Penunjuk Waktu & Angka", "三日待ってください。", "Tolong tunggu selama tiga hari."),
    ("四日", "よっか", "yokka", "Tanggal Empat / Empat Hari", "Penunjuk Waktu & Angka", "四日に会議があります。", "Ada rapat pada tanggal empat."),
    ("五日", "いつか", "itsuka", "Tanggal Lima / Lima Hari", "Penunjuk Waktu & Angka", "五日に帰ります。", "Pulang pada tanggal lima."),
    ("六日", "むいか", "muika", "Tanggal Enam / Enam Hari", "Penunjuk Waktu & Angka", "六日かかりました。", "Memakan waktu enam hari."),
    ("七日", "なのか", "nanoka", "Tanggal Tujuh / Tujuh Hari", "Penunjuk Waktu & Angka", "七日は七夕です。", "Tanggal tujuh adalah festival Tanabata."),
    ("八日", "ようか", "youka", "Tanggal Delapan / Delapan Hari", "Penunjuk Waktu & Angka", "八日に荷物が届きます。", "Paket tiba pada tanggal delapan."),
    ("九日", "ここのか", "kokonoka", "Tanggal Sembilan / Sembilan Hari", "Penunjuk Waktu & Angka", "九日に出発します。", "Berangkat pada tanggal sembilan."),
    ("十日", "とおか", "tooka", "Tanggal Sepuluh / Sepuluh Hari", "Penunjuk Waktu & Angka", "十日間滞在します。", "Menginap selama sepuluh hari."),
    ("十四日", "じゅうよっか", "juuyokka", "Tanggal Empat Belas", "Penunjuk Waktu & Angka", "十四日はバレンタインデーです。", "Tanggal empat belas adalah hari Valentine."),
    ("二十日", "はつか", "hatsuka", "Tanggal Dua Puluh", "Penunjuk Waktu & Angka", "二十日に給料が出ます。", "Gaji cair pada tanggal dua puluh."),
    ("二十四日", "にじゅうよっか", "nijuuyokka", "Tanggal Dua Puluh Empat", "Penunjuk Waktu & Angka", "二十四日の夜にパーティーをします。", "Mengadakan pesta pada malam tanggal 24."),

    # Tahun & Musim (年・季節)
    ("今年", "ことし", "kotoshi", "Tahun ini", "Penunjuk Waktu & Angka", "今年は日本語をマスターします。", "Tahun ini saya menguasai bahasa Jepang."),
    ("去年", "きょねん", "kyonen", "Tahun lalu", "Penunjuk Waktu & Angka", "去年高校を卒業しました。", "Tahun lalu lulus dari SMA."),
    ("来年", "らいねん", "rainen", "Tahun depan", "Penunjuk Waktu & Angka", "来年日本へ留学します。", "Tahun depan studi ke Jepang."),
    ("毎年", "まいとし / まいねん", "maitoshi / mainen", "Setiap tahun", "Penunjuk Waktu & Angka", "毎年富士山に登ります。", "Mendaki Gunung Fuji setiap tahun."),
    ("春", "はる", "haru", "Musim semi", "Penunjuk Waktu & Angka", "春は桜がとても綺麗です。", "Musim semi bunga sakura sangat indah."),
    ("夏", "なつ", "natsu", "Musim panas", "Penunjuk Waktu & Angka", "夏に海で泳ぎます。", "Berenang di laut pada musim panas."),
    ("秋", "あき", "aki", "Musim gugur", "Penunjuk Waktu & Angka", "秋は涼しくて過ごしやすいです。", "Musim gugur sejuk dan nyaman."),
    ("冬", "ふゆ", "fuyu", "Musim dingin", "Penunjuk Waktu & Angka", "冬はスキーをします。", "Bermain ski saat musim dingin.")
]

print(f"Loaded {len(N5_TIME_NUMBERS_MONEY)} Time, Numbers, and Money items.")
