# -*- coding: utf-8 -*-
# Data Kata Kerja Dasar (Golongan I, II, III) - Minna no Nihongo Bab 1 - 25+ & JLPT N5

N5_VERBS_BASIC = [
    # Bab 1 - 6 (Aktivitas Dasar Sehari-hari)
    ("行きます", "いきます", "ikimasu", "Pergi menuju tempat", "Kata Kerja Dasar", "明日東京へ行きます。", "Besok pergi ke Tokyo."),
    ("来ます", "きます", "kimasu", "Datang mendekat", "Kata Kerja Dasar", "友達が家に遊びに来ます。", "Teman datang main ke rumah."),
    ("帰ります", "かえります", "kaerimasu", "Pulang ke kediaman", "Kata Kerja Dasar", "五時にうちへ帰ります。", "Pulang ke rumah pada pukul lima."),
    ("食べます", "たべます", "tabemasu", "Makan makanan", "Kata Kerja Dasar", "朝ご飯にパンを食べます。", "Makan roti untuk sarapan pagi."),
    ("飲みます", "のみます", "nomimasu", "Minum minuman", "Kata Kerja Dasar", "冷たい水を飲みます。", "Meminum air dingin."),
    ("吸います", "すいます", "suimasu", "Menghisap / Merokok", "Kata Kerja Dasar", "タバコを吸いません。", "Saya tidak merokok."),
    ("見ます", "みます", "mimasu", "Melihat / Menonton", "Kata Kerja Dasar", "テレビで映画を見ます。", "Menonton film di televisi."),
    ("聞きます", "ききます", "kikimasu", "Mendengar / Mendengarkan / Bertanya", "Kata Kerja Dasar", "ラジオで音楽を聞きます。", "Mendengarkan musik di radio."),
    ("読みます", "よみます", "yomimasu", "Membaca buku tulisan", "Kata Kerja Dasar", "毎朝新聞を読みます。", "Membaca koran setiap pagi."),
    ("書きます", "かきます", "kakimasu", "Menulis / Menggambar", "Kata Kerja Dasar", "日本語で手紙を書きます。", "Menulis surat dalam bahasa Jepang."),
    ("買います", "かいます", "kaimasu", "Membeli barang", "Kata Kerja Dasar", "スーパーで野菜を買います。", "Membeli sayuran di supermarket."),
    ("撮ります", "とります", "torimasu", "Mengambil potret foto", "Kata Kerja Dasar", "京都で写真を撮ります。", "Mengambil foto di Kyoto."),
    ("します", "します", "shimasu", "Melakukan / Mengerjakan", "Kata Kerja Dasar", "土曜日にサッカーをします。", "Bermain sepak bola pada hari Sabtu."),
    ("会います", "あいます", "aimasu", "Bertemu dengan seseorang", "Kata Kerja Dasar", "駅で友達に会います。", "Bertemu dengan teman di stasiun."),

    # Bab 7 - 12 (Alat, Pemberian, Eksistensi, Sifat Waktu)
    ("切ります", "きります", "kirimasu", "Memotong dengan pisau/gunting", "Kata Kerja Dasar", "ハサミで紙を切ります。", "Memotong kertas dengan gunting."),
    ("送ります", "おくります", "okurimasu", "Mengirim surat/barang", "Kata Kerja Dasar", "国へ手紙を送ります。", "Mengirim surat ke kampung halaman."),
    ("あげます", "あげます", "agemasu", "Memberikan hadiah kepada orang lain", "Kata Kerja Dasar", "友達に誕生日プレゼントをあげます。", "Memberi hadiah ulang tahun ke kawan."),
    ("もらいます", "もらいます", "moraimasu", "Menerima pemberian dari orang lain", "Kata Kerja Dasar", "先生に本をもらいました。", "Menerima buku dari guru."),
    ("貸します", "かします", "kashimasu", "Meminjamkan barang kepada orang lain", "Kata Kerja Dasar", "友達に傘を貸します。", "Meminjamkan payung ke kawan."),
    ("借ります", "かります", "karimasu", "Meminjam barang dari orang lain", "Kata Kerja Dasar", "図書館で辞書を借ります。", "Meminjam kamus di perpustakaan."),
    ("教えます", "おしえます", "oshiemasu", "Mengajar / Memberitahukan informasi", "Kata Kerja Dasar", "先生が日本語を教えます。", "Guru mengajar bahasa Jepang."),
    ("習います", "ならいます", "naraimasu", "Belajar berguru dari orang lain", "Kata Kerja Dasar", "着物の着方を習います。", "Belajar cara mengenakan kimono."),
    ("かけます", "かけます", "kakemasu", "Menelepon (menghubungi)", "Kata Kerja Dasar", "家族に電話をかけます。", "Menelepon pihak keluarga."),
    ("わかります", "わかります", "wakarimasu", "Mengerti / Memahami", "Kata Kerja Dasar", "日本語の意味がよくわかります。", "Mengerti arti bahasa Jepang dengan baik."),
    ("あります", "あります", "arimasu", "Ada / Memiliki (benda mati)", "Kata Kerja Dasar", "机の上に本があります。", "Ada buku di atas meja."),
    ("います", "います", "imasu", "Ada / Tinggal (makhluk hidup: orang & hewan)", "Kata Kerja Dasar", "庭に犬がいます。", "Ada anjing di pekarangan."),
    ("かかります", "かかります", "kakarimasu", "Memakan waktu / Biaya", "Kata Kerja Dasar", "電車で一時間かかります。", "Memakan waktu satu jam naik kereta."),

    # Bab 13 - 18 (Keinginan, Permohonan, Izin, Larangan, Rutinitas)
    ("遊びます", "あそびます", "asobimasu", "Bermain / Bersenang-senang", "Kata Kerja Dasar", "休日に友達と遊びます。", "Bermain bersama teman saat hari libur."),
    ("泳ぎます", "およぎます", "oyogimasu", "Berenang di air", "Kata Kerja Dasar", "プールで気持ちよく泳ぎます。", "Berenang dengan nyaman di kolam."),
    ("迎えます", "むかえます", "mukaemasu", "Menjemput / Menyambut kedatangan", "Kata Kerja Dasar", "空港で友達を迎えます。", "Menjemput kawan di bandara."),
    ("疲れます", "つかれます", "tsukaremasu", "Menjadi lelah / Lelah bekerja", "Kata Kerja Dasar", "たくさん歩いて疲れました。", "Lelah karena banyak berjalan kaki."),
    ("出します", "だします", "dashimasu", "Mengeluarkan / Mengumpulkan tugas", "Kata Kerja Dasar", "先生に宿題を出します。", "Mengumpulkan PR kepada guru."),
    ("入ります", "はいります", "hairimasu", "Masuk ke dalam ruangan / Kafe", "Kata Kerja Dasar", "喫茶店に入ってお茶を飲みます。", "Masuk ke kedai kafe dan minum teh."),
    ("出ます", "でます", "demasu", "Keluar dari tempat / Lulus", "Kata Kerja Dasar", "七時に家を出ます。", "Keluar dari rumah pada pukul tujuh."),
    ("結婚します", "けっこんします", "kekkonshimasu", "Menikah membina rumah tangga", "Kata Kerja Dasar", "来年結婚します。", "Akan menikah tahun depan."),
    ("買い物します", "かいものします", "kaimonoshimasu", "Berbelanja membeli kebutuhan", "Kata Kerja Dasar", "デパートで買い物します。", "Berbelanja di department store."),
    ("散歩します", "さんぽします", "sanposhimasu", "Jalan-jalan santai (refreshing)", "Kata Kerja Dasar", "公園を散歩します。", "Jalan-jalan santai di taman."),
    ("見学します", "けんがくします", "kengakushimasu", "Kunjungan studi lapangan", "Kata Kerja Dasar", "自動車工場を見学します。", "Studi lapangan ke pabrik mobil."),
    ("つけます", "つけます", "tsukemasu", "Menyalakan lampu/alat elektronik", "Kata Kerja Dasar", "暗いので電気をつけます。", "Menyalakan lampu karena gelap."),
    ("消します", "けします", "keshimasu", "Mematikan lampu/alat listrik", "Kata Kerja Dasar", "エアコンを消して出かけます。", "Mematikan pendingin ruangan sebelum pergi."),
    ("開けます", "あけます", "akemasu", "Membuka pintu/jendela/kotak", "Kata Kerja Dasar", "窓を開けて涼しい風を入れます。", "Membuka jendela memasukkan angin sejuk."),
    ("閉めます", "しめます", "shimemasu", "Menutup pintu/jendela", "Kata Kerja Dasar", "寒いのでドアを閉めます。", "Menutup pintu karena dingin."),
    ("急ぎます", "いそぎます", "isogimasu", "Bergegas / Terburu-buru", "Kata Kerja Dasar", "電車に遅れそうなので急ぎます。", "Bergegas karena hampir ketinggalan kereta."),
    ("待ちます", "まちます", "machimasu", "Menunggu antrean/orang", "Kata Kerja Dasar", "ここで友達を待ちます。", "Menunggu kawan di sini."),
    ("持ちます", "もちます", "mochimasu", "Membawa / Memegang barang", "Kata Kerja Dasar", "重い荷物を持ちます。", "Membawa barang bawaan yang berat."),
    ("手伝います", "てつだいます", "tetsudaimasu", "Membantu menolong pekerjaan", "Kata Kerja Dasar", "母の料理を手伝います。", "Membantu ibu memasak di dapur."),
    ("呼びます", "よびます", "yobimasu", "Memanggil nama/taksi", "Kata Kerja Dasar", "タクシーを呼びます。", "Memanggil kendaraan taksi."),
    ("話します", "はなします", "hanashimasu", "Berbicara / Menceritakan", "Kata Kerja Dasar", "日本語で友達と話します。", "Berbicara dengan kawan dalam bahasa Jepang."),
    ("使います", "つかいます", "tsukaimasu", "Menggunakan / Memakai alat", "Kata Kerja Dasar", "パソコンを使って資料を作ります。", "Menggunakan komputer membuat materi berkas."),
    ("止めます", "とめます", "tomemasu", "Menghentikan / Memarkir kendaraan", "Kata Kerja Dasar", "駐車場に車を止めます。", "Memarkir mobil di area parkir."),
    ("見せます", "みせます", "misemasu", "Memperlihatkan / Menunjukkan", "Kata Kerja Dasar", "パスポートを見せてください。", "Tolong perlihatkan paspor Anda."),
    ("座ります", "すわります", "suwarimasu", "Duduk di kursi/lantai", "Kata Kerja Dasar", "ベンチに座って休みます。", "Duduk di bangku taman beristirahat."),
    ("立ちます", "たちます", "tachimasu", "Berdiri tegak", "Kata Kerja Dasar", "名前を呼ばれて立ちます。", "Berdiri saat nama dipanggil."),
    ("降ります", "ふります", "furimasu", "Turun (hujan / salju)", "Kata Kerja Dasar", "外で雨が降っています。", "Hujan sedang turun di luar."),
    ("コピーします", "こぴーします", "kopiishimasu", "Memfotokopi dokumen", "Kata Kerja Dasar", "会議の資料を十枚コピーします。", "Memfotokopi sepuluh lembar materi rapat."),

    # Bab 19 - 25 (Kemampuan, Pengalaman, Rangkaian Tindakan, Saran, Pengandaian)
    ("作ります", "つくります", "tsukurimasu", "Membuat / Memproduksi", "Kata Kerja Dasar", "自分で美味しい料理を作ります。", "Membuat masakan lezat sendiri."),
    ("売ります", "うります", "urimasu", "Menjual barang", "Kata Kerja Dasar", "店で新鮮な果物を売ります。", "Menjual buah-buahan segar di toko."),
    ("知ります", "しります", "shirimasu", "Mengetahui / Mengenal info", "Kata Kerja Dasar", "そのニュースを知っていますか。", "Apakah Anda mengetahui berita tersebut?"),
    ("住みます", "すみます", "sumimasu", "Tinggal / Menetap di kota", "Kata Kerja Dasar", "東京の静かなアパートに住んでいます。", "Tinggal di apartemen yang tenang di Tokyo."),
    ("研究します", "けんきゅうします", "kenkyuushimasu", "Melakukan penelitian ilmiah", "Kata Kerja Dasar", "大学で環境問題を研究します。", "Meneliti isu lingkungan hidup di universitas."),
    ("乗ります", "のります", "norimasu", "Naik kendaraan (kereta/bus/sepeda)", "Kata Kerja Dasar", "七時の電車に乗ります。", "Naik kereta jam tujuh."),
    ("降ります", "おります", "orimasu", "Turun dari kendaraan", "Kata Kerja Dasar", "次の駅で降ります。", "Turun di stasiun berikutnya."),
    ("乗り換えます", "のりかえます", "norikaemasu", "Transit pindah kendaraan", "Kata Kerja Dasar", "新宿駅で地下鉄に乗り換えます。", "Pindah ke subway di Stasiun Shinjuku."),
    ("浴びます", "あびます", "abimasu", "Mandi guyuran shower", "Kata Kerja Dasar", "毎朝シャワーを浴びます。", "Mandi dengan shower setiap pagi."),
    ("入れます", "いれます", "iremasu", "Memasukkan benda ke dalam", "Kata Kerja Dasar", "財布にお金を入れます。", "Memasukkan uang ke dalam dompet."),
    ("下ろします", "おろします", "oroshimasu", "Menarik / Mengambil uang tunai", "Kata Kerja Dasar", "ATMで現金を下ろします。", "Mengambil uang tunai di mesin ATM."),
    ("押します", "おします", "oshimasu", "Menekan tombol / Mendorong", "Kata Kerja Dasar", "エレベーターのボタンを押します。", "Menekan tombol lift."),
    ("覚えます", "おぼえます", "oboemasu", "Mengingat / Menghafal kosakata", "Kata Kerja Dasar", "毎日新しい漢字を五つ覚えます。", "Menghafal lima kanji baru setiap hari."),
    ("忘れます", "わすれます", "wasuremasu", "Lupa / Melupakan sesuatu", "Kata Kerja Dasar", "約束の時間を忘れてはいけません。", "Tidak boleh melupakan waktu janji temu."),
    ("無くします", "なくします", "nakushimasu", "Menghilangkan / Kehilangan barang", "Kata Kerja Dasar", "財布を無くして困りました。", "Kerepotan karena kehilangan dompet."),
    ("払います", "はらいます", "haraimasu", "Membayar tagihan / Belanja", "Kata Kerja Dasar", "レジで代金を払います。", "Membayar tagihan di meja kasir."),
    ("返します", "かえします", "kaeshimasu", "Mengembalikan barang pinjaman", "Kata Kerja Dasar", "借りた本を図書館に返します。", "Mengembalikan buku pinjaman ke perpustakaan."),
    ("出かけます", "でかけます", "dekakemasu", "Bepergian keluar rumah", "Kata Kerja Dasar", "休日に友達と出かけます。", "Bepergian bersama kawan saat akhir pekan."),
    ("脱ぎます", "ぬぎます", "nugimasu", "Mencopot pakaian / Sepatu", "Kata Kerja Dasar", "部屋に入る前に靴を脱ぎます。", "Mencopot sepatu sebelum masuk ruangan."),
    ("持って行きます", "もっていきます", "motte ikimasu", "Membawa pergi sesuatu", "Kata Kerja Dasar", "傘を持って行きます。", "Membawa pergi payung."),
    ("持って来ます", "もってきます", "motte kimasu", "Membawa datang kemari", "Kata Kerja Dasar", "明日教科書を持って来てください。", "Tolong bawa kemari buku pelajaran besok."),
    ("心配します", "しんぱいします", "shinpaishimasu", "Khawatir / Mencemaskan keadaan", "Kata Kerja Dasar", "一人暮らしの子供を心配します。", "Mencemaskan anak yang tinggal sendiri."),
    ("残業します", "ざんぎょうします", "zangyoushimasu", "Lembur kerja tambahan", "Kata Kerja Dasar", "忙しいので二時間残業します。", "Lembur kerja dua jam karena sedang sibuk."),
    ("出張します", "しゅっちょうします", "shucchoushimasu", "Perjalanan dinas ke luar kota", "Kata Kerja Dasar", "来週大阪へ出張します。", "Melakukan perjalanan dinas ke Osaka minggu depan."),
    ("できます", "できます", "dekimasu", "Bisa / Mampu melakukan", "Kata Kerja Dasar", "日本語で日常会話ができます。", "Mampu melakukan percakapan sehari-hari dalam bahasa Jepang."),
    ("洗います", "あらいます", "araimasu", "Mencuci benda / Tangan", "Kata Kerja Dasar", "石鹸で手を綺麗に洗います。", "Mencuci tangan hingga bersih dengan sabun."),
    ("弾きます", "ひきます", "hikimasu", "Memainkan alat musik petik/tuts (piano/gitar)", "Kata Kerja Dasar", "上手にピアノを弾きます。", "Memainkan piano dengan sangat mahir."),
    ("歌います", "うたいます", "utaimasu", "Menyanyikan lagu", "Kata Kerja Dasar", "カラオケで日本の歌を歌います。", "Menyanyikan lagu Jepang di tempat karaoke."),
    ("集めます", "あつめます", "atsumemasu", "Mengumpulkan barang koleksi", "Kata Kerja Dasar", "世界各地の切手を集めます。", "Mengumpulkan perangko dari berbagai belahan dunia."),
    ("捨てます", "すてます", "sutemasu", "Membuang sampah/barang tak terpakai", "Kata Kerja Dasar", "ゴミ箱にゴミを捨てます。", "Membuang sampah ke dalam tempat sampah."),
    ("換えます", "かえます", "kaemasu", "Menukar / Mengganti komponen", "Kata Kerja Dasar", "お金を円に換えます。", "Menukarkan uang ke dalam mata uang yen."),
    ("運転します", "うんてんします", "untenshimasu", "Mengemudi / Menyetir mobil", "Kata Kerja Dasar", "安全に車を運転します。", "Mengemudikan mobil dengan aman berkendara."),
    ("予約します", "よやくします", "yoyakushimasu", "Memesan reservasi tempat", "Kata Kerja Dasar", "レストランの席を予約します。", "Mereservasi kursi meja makan di restoran."),
    ("登ります", "のぼります", "noborimasu", "Mendaki gunung / Memanjat", "Kata Kerja Dasar", "天気のいい日に山に登ります。", "Mendaki gunung di saat cuaca cerah."),
    ("泊まります", "とまります", "tomarimasu", "Menginap di hotel/kediaman", "Kata Kerja Dasar", "温泉旅館に泊まります。", "Menginap di penginapan ryokan pemandian air panas."),
    ("掃除します", "そうじします", "soujishimasu", "Membersihkan ruangan/rumah", "Kata Kerja Dasar", "毎朝自分の部屋を掃除します。", "Membersihkan kamar sendiri setiap pagi."),
    ("洗濯します", "せんたくします", "sentakushimasu", "Mencuci pakaian cucian", "Kata Kerja Dasar", "天気がいいので服を洗濯します。", "Mencuci baju karena cuaca sangat cerah."),
    ("なります", "なります", "narimasu", "Menjadi / Berubah kondisi", "Kata Kerja Dasar", "春になって暖かくなりました。", "Menjadi hangat saat musim semi tiba."),
    ("要ります", "いります", "irimasu", "Memerlukan / Membutuhkan bantuan", "Kata Kerja Dasar", "ビザの申請に写真が要ります。", "Memerlukan pasfoto untuk pengajuan visa."),
    ("調べます", "しらべます", "shirabemasu", "Memeriksa / Mencari informasi", "Kata Kerja Dasar", "インターネットで電車の時間を調べます。", "Mencari jadwal kereta melalui internet."),
    ("直します", "なおします", "naoshimasu", "Memperbaiki kerusakan / Mengoreksi kesalahan", "Kata Kerja Dasar", "壊れたパソコンを直します。", "Memperbaiki komputer yang rusak."),
    ("思います", "おもいます", "omoimasu", "Berpikir / Mengira / Berpendapat", "Kata Kerja Dasar", "日本語は面白いと思います。", "Saya berpendapat bahasa Jepang itu sangat menarik."),
    ("言います", "いいます", "iimasu", "Mengatakan / Berkata kalimat", "Kata Kerja Dasar", "先生に「ありがとうございます」と言いました。", "Mengucapkan “terima kasih” kepada guru."),
    ("勝ちます", "かちます", "kachimasu", "Menang dalam pertandingan", "Kata Kerja Dasar", "試合に勝って喜びます。", "Bergembira karena memenangkan pertandingan."),
    ("負けます", "まけます", "makemasu", "Kalah dalam pertandingan", "Kata Kerja Dasar", "試合に負けて悔しいです。", "Merasa kecewa karena kalah dalam pertandingan."),
    ("役に立ちます", "やくにたちます", "yakunitachimasu", "Berguna / Bermanfaat bagi orang lain", "Kata Kerja Dasar", "この辞書はとても役に立ちます。", "Kamus ini sangat bermanfaat untuk belajar."),
    ("やめます", "やめます", "yamemasu", "Berhenti (bekerja / kebiasaan)", "Kata Kerja Dasar", "タバコを完全にやめます。", "Berhenti merokok sepenuhnya."),
    ("気をつけます", "きをつけます", "kiwotsukemasu", "Berhati-hati / Memperhatikan keselamatan", "Kata Kerja Dasar", "交通事故に気をつけます。", "Berhati-hati terhadap kecelakaan lalu lintas."),
    ("留学します", "りゅうがくします", "ryuugakushimasu", "Belajar studi ke luar negeri", "Kata Kerja Dasar", "日本の大学に留学します。", "Melakukan studi ke universitas di Jepang.")
]

print(f"Loaded {len(N5_VERBS_BASIC)} N5 Basic Verbs.")
